Removed `anyhow`
bevyengine/bevy pull request #10003
Opened 2023-10-03 05:45 UTC by bushrat011899

# Objective

- Fixes #8140

## Solution

- Added Explicit Error Typing for `AssetLoader` and `AssetSaver`, which were the last instances of `anyhow` in use across Bevy.

---

## Changelog

- Added an associated type `Error` to `AssetLoader` and `AssetSaver` for use with the `load` and `save` methods respectively.
- Changed `ErasedAssetLoader` and `ErasedAssetSaver` `load` and `save` methods to use `Box<dyn Error + Send + Sync + 'static>` to allow for arbitrary `Error` types from the non-erased trait variants. Note the strict requirements match the pre-existing requirements around `anyhow::Error`.

## Migration Guide

- `anyhow` is no longer exported by `bevy_asset`; Add it to your own project (if required).
- `AssetLoader` and `AssetSaver` have an associated type `Error`; Define an appropriate error type (e.g., using `thiserror`), or use a pre-made error type (e.g., `anyhow::Error`). Note that using `anyhow::Error` is a drop-in replacement.
- `AssetLoaderError` has been removed; Define a new error type, or use an alternative (e.g., `anyhow::Error`)
- All the first-party `AssetLoader`'s and `AssetSaver`'s now return relevant (and narrow) error types instead of a single ambiguous type; Match over the specific error type, or encapsulate (`Box<dyn>`, `thiserror`, `anyhow`, etc.)

## Notes

A simpler PR to resolve this issue would simply define a Bevy `Error` type defined as `Box<dyn std::error::Error + Send + Sync + 'static>`, but I think this type of error handling should be discouraged when possible. Since only 2 traits required the use of `anyhow`, it isn't a substantive body of work to solidify these error types, and remove `anyhow` entirely. End users are still encouraged to use `anyhow` if that is their preferred error handling style. Arguably, adding the `Error` associated type gives more freedom to end-users to decide whether they want more or less explicit error handling (`anyhow` vs `thiserror`).

As an aside, I didn't perform any testing on Android or WASM. CI passed locally, but there may be mistakes for those platforms I missed.

2023-10-03 06:29 UTC, JMS55 commented on crates/bevy_render/src/render_resource/shader.rs
> +    #[error("Could load shader: {0}")]
```suggestion
    #[error("Could not load shader: {0}")]
```

2023-10-03 07:02 UTC, killercup requested changes

2023-10-03 09:07 UTC, bushrat011899 commented on crates/bevy_render/src/render_resource/shader.rs
> +    #[error("Could load shader: {0}")]
Whoops! Thanks for the pickup!

2023-10-03 09:07 UTC, bushrat011899 commented on crates/bevy_asset/src/lib.rs
> +        RONSpannedError(#[from] ron::error::SpannedError),
Yeah that does look nicer, thanks!

2023-10-03 09:07 UTC, bushrat011899 commented on crates/bevy_asset/src/lib.rs
> +        IO(#[from] std::io::Error),
As before, thanks!

2023-10-03 09:08 UTC, bushrat011899 commented on crates/bevy_asset/src/lib.rs
> +    #[derive(Error, Debug)]
For the new error types I'll add `#[non_exhaustive]`, but I'll leave it off for any that already existed, unless others agree they should be changed to include that attribute.

2023-10-03 14:02 UTC, killercup approved these changes

2023-10-05 21:35 UTC, alice-i-cecile approved these changes
This is much nicer. Thank you!

2023-10-06 06:58 UTC, bushrat011899 commented
Looks like I missed one docstring in the `bevy_gltf` package (which previously didn't require documentation). I've merged `main` back into this PR and resolved that issue.

2023-10-06 07:39 UTC, merged

2023-10-13 19:20 UTC, cart commented
These AssetLoadError::CannotLoadDependency errors don't make sense to me:

1. We're dropping the actual loader error contents, making the error message effectively useless.
2. Not all asset loads are dependencies, but we're returning that error for every asset load failure.

2023-10-13 19:22 UTC, cart commented
We're also no longer including meta deserialization failures / throwing them in the generic CannotLoadDependency bucket.

2023-10-13 19:24 UTC, cart commented
I'm just going to fix this in Multiple Asset Sources as it touches this code.

2023-11-02 16:55 UTC, Roryl-c commented
> AssetLoader and AssetSaver have an associated type Error; Define an appropriate error type (e.g., using thiserror), or use a pre-made error type (e.g., anyhow::Error). Note that using anyhow::Error is a drop-in replacement.  

Not sure if a comment is the right place to put this, but this section of this PR's migration guide is incorrect. `anyhow::Error` does not implement `Error`, which is required by these associated types - so it does not work as a drop-in replacement.