Update texture_atlas example with different padding and sampling
bevyengine/bevy pull request #10073
Opened 2023-10-10 06:53 UTC by antoniacobaeus

# Objective

- Expand the texture_atlas example with padding and show how it can resolve sprite bleeding for different types of sampling. 
- Fixes #9522
## Solution
Updated the texture_atlas example by adding 4 different texture atlases:
1. linear, no padding
2. linear, padding
3. nearest neighbor, no padding
4. nearest neighbor, padding

Now renders one padded and one unpadded texture atlas, and the same upscaled sprite from each of the new texture atlases. See the screenshot below (taken on 1080p monitor).

![Screenshot from 2023-10-10 08-37-43](https://github.com/bevyengine/bevy/assets/46004494/4cef707c-e117-4835-b2c8-66503d8c275f)

**From left->right:** linear no padding, nearest no padding, linear padding, nearest no padding.

---

2023-10-10 14:49 UTC, alice-i-cecile approved these changes
Nice stuff! Good docs, simple and clean code.

2023-10-10 16:05 UTC, ickshonpe requested changes
Two requests: 
* I have to resize the window to view all of the images. Everything should fit into the default window size.
* It would be good to have a label above each of the piggy shopkeeper sprites with the details of the filtering and padding that has been applied to the sprite.

Otherwise looks good, does exactly what we wanted.

2023-10-13 18:30 UTC, antoniacobaeus commented
Added the requests mentioned above. The example should now fit in the default window size, and labels are added to display the different settings, see image below.

![Screenshot from 2023-10-13 17-29-0525](https://github.com/bevyengine/bevy/assets/46004494/b3d9b6a1-99e1-4fd6-a234-7ab4022fe62a)

*Since it seems like text2d is broken on main I had to merge with #9708 to test the labels. I manage to get the text to show, but got some artifacts which shouldn't be present when text2d works properly.*

2023-11-13 15:35 UTC, ickshonpe approved these changes
Sorry for not rereviewing earlier, the changes are exactly what I asked for. Looks great now. 
`Text2d` works again I think, so once you've merged with main this is ready to go.

2023-11-13 15:35 UTC, ickshonpe commented on examples/2d/texture_atlas.rs
> +}
The repeated `create_label` calls could be refactored using a closure or loop maybe. It's not blocking though.

2023-11-13 15:35 UTC, ickshonpe commented on examples/2d/texture_atlas.rs
> +    );
Same comment as for the labels below, this section could be refactored a bit.

2023-11-13 15:35 UTC, ickshonpe commented on examples/2d/texture_atlas.rs
> +//! In this example we generate 4 texture atlases (sprite sheets) from a folder containing
```suggestion
//! In this example we generate four texture atlases (sprite sheets) from a folder containing
```

Word number seems more readable here

2023-11-13 15:35 UTC, ickshonpe commented on examples/2d/texture_atlas.rs
> +//! An upscaled sprite from each of the 4 atlases are rendered to the screen.
```suggestion
//! An upscaled sprite from each of the four atlases are rendered to the screen.
```

2023-12-14 16:36 UTC, alice-i-cecile commented
CI is failing: fix that up and I'll merge this in for you <3

2023-12-14 19:02 UTC, merged