Enable scraping examples for docs.rs generation
bevyengine/bevy pull request #10130
Opened 2023-10-15 15:13 UTC by ShadowMitia

# Objective

- Show scraped examples in docs.rs

## Solution

- cargo doc needs the nightly channel. Local experiments showed that explicitly setting the unstable `rustdoc-scrape-examples` flag seems to work better than setting in the Cargo.toml.

2023-10-15 15:16 UTC, mockersf commented
This is not for docs.rs, this is for https://dev-docs.bevyengine.org/bevy/index.html

docs.rs issue is related to https://github.com/rust-lang/rust/issues/116690

2023-10-15 15:18 UTC, ShadowMitia commented
This is a tentative solution, I'm not familiar enough with github workflows...

I have seen some of the issues on the subject, and the PR merged (for 0.11.1 I believe), everything looks fine.
I think the issue is mainly to make sure the nightly channel needs to be set.
I am unsure why setting the flags works better, they might not be necessary.

Hope I'm not stepping on anyone's toes here. If I am feel free to close this PR.
I'm explicitly allowing reuse without attribution just in case.

2023-10-15 15:21 UTC, ShadowMitia commented
@mockersf Ah I didn't go deep enough it seems... This was already tested and didn't work...

Closing this PR.

2023-10-15 15:23 UTC, mockersf commented
In my opinion it's still interesting to enable scraping examples on the dev-docs, so this PR makes sense!

2023-10-15 15:42 UTC, ShadowMitia commented
Enabling nightly should be enough then, and whatever needs to be done as well for docs.rs.
So waiting on https://github.com/rust-lang/rust/issues/116690 to be closed?

2024-01-07 13:00 UTC, ShadowMitia commented
[#2305](https://github.com/rust-lang/docs.rs/issues/2305) was merged, so this is now mergeable!

2024-01-07 15:13 UTC, mockersf commented on .github/workflows/docs.yml
> +        run: cargo +nightly doc --all-features --no-deps -p bevy
```suggestion
        run: cargo +nightly doc --all-features --no-deps -p bevy  -Zunstable-options -Zrustdoc-scrape-examples
```
from https://doc.rust-lang.org/rustdoc/scraped-examples.html

2024-01-07 15:30 UTC, mockersf approved these changes

2024-01-16 15:39 UTC, BD103 requested changes
This line needs to be changed to `@nightly`, or the CI will fail. [See docs on action.](https://github.com/dtolnay/rust-toolchain)

https://github.com/bevyengine/bevy/blob/b6e154fc6478b11667f9c9877d1ed0c57a563f51/.github/workflows/docs.yml#L36-L37

2024-03-04 09:18 UTC, mockersf commented
done in https://github.com/bevyengine/bevy/pull/12223, sorry I forgot about this PR

2024-03-04 09:18 UTC, closed without merging