Reuse and hot reload folder handles
bevyengine/bevy pull request #10210
Opened 2023-10-21 01:41 UTC by NiklasEi

# Objective

- Folder handles are not shared. Loading the same folder multiple times will result in different handles.

## Solution

- Reuse folder handles based on their path
- Trigger a reload of a folder if a file contained in it (or a sub folder) is added or removed
    - This also covers adding/removing/moving sub folders containing files

2023-10-24 21:05 UTC, alice-i-cecile commented on crates/bevy_asset/src/server/mod.rs
>      pub fn load_folder<'a>(&self, path: impl Into<AssetPath<'a>>) -> Handle<LoadedFolder> {
Can we add some docs here explaining the behavior added in this PR?

2023-10-24 21:06 UTC, alice-i-cecile requested changes
Agreed on the changes here, but I definitely think we should document this behavior.

2023-10-25 18:13 UTC, alice-i-cecile approved these changes

2023-10-25 20:00 UTC, NiklasEi commented
I extensively tested this change together with asset processing using the `asset_processing` example. The PR is now handling more asset source events and seems to work well with processing.

2023-10-25 20:17 UTC, alice-i-cecile approved these changes

2023-10-26 22:04 UTC, cart approved these changes

2023-10-26 22:41 UTC, merged