UI Materials: don't reserve items on phase from inside the loop
bevyengine/bevy pull request #10437
Opened 2023-11-07 23:26 UTC by mockersf

# Objective

- UI Materials reserve an additional nodes length for each node, leading to (number of nodes) ^2 reserved size of array

## Solution

- Reorder the loop and reserve length outside of the loop on nodes

2023-11-07 23:28 UTC, alice-i-cecile approved these changes

2023-11-08 00:07 UTC, superdump requested changes

2023-11-08 00:07 UTC, superdump commented on crates/bevy_ui/src/render/ui_material_pipeline.rs
> +            let material = render_materials.get(&extracted_uinode.material).unwrap();
This means the material will have to be looked up once per view per entity instead of once per entity

2023-11-08 00:07 UTC, superdump commented on crates/bevy_ui/src/render/ui_material_pipeline.rs
> -            transparent_phase
Why not if items.len() < uinodes.len() { reserve diff }?

2023-11-22 18:55 UTC, alice-i-cecile commented
Removing from 0.12.1: not straightforward, and not essential.

2024-10-15 06:54 UTC, mockersf commented
updated in #15919

2024-10-15 06:54 UTC, closed without merging