Mention DirectionalLightBundle in DirectionalLight doc
bevyengine/bevy pull request #10603
Opened 2023-11-17 03:28 UTC by stepancheg

It is hard to set up `DirectionalLight` without bundle: if something is missing, `DirectionalLight` quietly does not do anything.

2023-11-17 09:52 UTC, killercup approved these changes

2023-11-28 00:56 UTC, stepancheg commented
Ping!

2024-06-25 20:45 UTC, janhohenheim approved these changes
Not entirely sure about the `Transform::IDENTITY` part, but the documentation seems very useful :)

2024-08-14 20:29 UTC, JMS55 requested changes

2024-08-14 20:29 UTC, JMS55 commented on crates/bevy_pbr/src/light.rs
> +/// # use bevy_ecs::system::Commands;
I would remove the whole example and just link to DirectionalLightBundle.

2024-08-14 20:29 UTC, JMS55 commented on crates/bevy_pbr/src/light.rs
> +/// `DirectionalLight` entity requires a few more components to work properly.
```suggestion
/// `DirectionalLight` entities require a few more components to work properly.
```

2024-10-16 19:31 UTC, JMS55 commented
No longer needed since https://github.com/bevyengine/bevy/pull/15554.

2024-10-16 19:31 UTC, closed without merging