Make Archetypes.archetype_component_count private
bevyengine/bevy pull request #10774
Opened 2023-11-28 04:40 UTC by stepancheg

Make more clear where it is used and how.

2023-11-28 16:24 UTC, alice-i-cecile commented on crates/bevy_ecs/src/archetype.rs
> +    /// (Just increment the counter and return the new value).
```suggestion
    /// This simply increment the counter and return the new value.
```

2023-12-06 20:31 UTC, james7132 requested changes
Thanks for reducing the number of stray `pub(crate)` fields in the ECS. This has been a long time coming. Just a few notes on documentation, and the one behavioral change in this PR.

2023-12-06 21:36 UTC, stepancheg commented on crates/bevy_ecs/src/archetype.rs
> +    pub(crate) fn new_archetype_component_id(&mut self) -> ArchetypeComponentId {
> branch to the hotpath

I think I should start quoting "Intel® 64 and IA-32 Architectures Optimization Reference Manual".

> 3.4.1.1 Eliminating Branches
> Conditional branches that are never taken do not consume BTB resources.

> 3.4.1.2 Static Prediction
> • Predict forward conditional branches to be NOT taken.

[Compiler explorer for `unwrap`](https://rust.godbolt.org/z/xx4ExfGWc): branch to panic is forward conditional branch, so static predictor assumes it is not taken.

This was not the case with Intel Core architecture IIRC (conditional branches occupied BTB slot), and if it wasn't, the issue was fixed long time ago.

I'm quite certain this behavior of conditional branches is implemented in other modern CPUs, although I didn't check.

2024-02-03 00:07 UTC, james7132 approved these changes

2024-02-03 00:21 UTC, merged