Add GltfLoaderSettings with load_cameras member
bevyengine/bevy pull request #10804
Opened 2023-11-29 10:37 UTC by robtfm

# Objective

when loading gltfs we may want to filter the results. in particular, i need to be able to exclude cameras. 

i can do this already by modifying the gltf after load and before spawning, but it seems like a useful general option.

## Solution

add `GltfLoaderSettings` struct, check the `load_cameras` member before processing camera nodes.

2023-11-29 14:53 UTC, alice-i-cecile requested changes
The implementation looks good, and this should definitely exist.

I'd like a bit more documentation on how to use this in practice: right now, it's quite hard to piece the usage together.

2023-11-29 14:53 UTC, alice-i-cecile commented
I think it would also make sense to add a `load_lights` field to `GltfLoaderSettings`, but that can be done in another PR :)

2023-11-29 23:37 UTC, robtfm commented
added lights, and meshes for completeness.

not sure what makes this a breaking change? anyway i added the struct comment as migration guide, let me know if you want something else.

2023-11-29 23:40 UTC, alice-i-cecile commented on crates/bevy_gltf/src/loader.rs
> +/// Example usage: to load a gltf but exclude the cameras, replace a call to `asset_server.load("my.gltf")` with
```suggestion
/// # Example
///
/// To load a gltf but exclude the cameras, replace a call to `asset_server.load("my.gltf")` with
```

2023-11-29 23:41 UTC, alice-i-cecile commented on crates/bevy_gltf/src/loader.rs
> +/// # Example
```suggestion
///
/// # Example
```

2023-11-29 23:41 UTC, alice-i-cecile approved these changes

2023-11-29 23:42 UTC, alice-i-cecile commented
Really nice, thank you!

The associated type on a public trait impl changed, which is technically semver breaking: [line 144](https://github.com/bevyengine/bevy/pull/10804/files#diff-4bad6321ea999887884bc321768f82c3bbd5aaeaf1b2ae4dca6e871b330426ebR144).

2023-11-30 00:00 UTC, alice-i-cecile commented
@robftm missing import in the example :)

2023-11-30 00:21 UTC, robtfm commented
my pc is even worse at running doctests than i am at writing them ...

2023-11-30 00:48 UTC, merged