Split `Ray` into `Ray2d` and `Ray3d` and simplify plane construction
bevyengine/bevy pull request #10856
Opened 2023-12-03 17:27 UTC by Jondolf

# Objective

A better alternative version of #10843.

Currently, Bevy has a single `Ray` struct for 3D. To allow better interoperability with Bevy's primitive shapes (#10572) as we add more functionality for them, it would be highly useful to have separate versions for 2D and 3D respectively.

## Solution

Separate `Ray` into `Ray2d` and `Ray3d`. The new structs also take advantage of the new primitives by using `Direction2d`/`Direction3d` for the direction:

```rust
pub struct Ray2d {
    pub origin: Vec2,
    pub direction: Direction2d,
}

pub struct Ray3d {
    pub origin: Vec3,
    pub direction: Direction3d,
}
```

and by allowing passing `Plane2d`/`Plane3d` to `intersect_plane`:

```rust
impl Ray2d {
    // ...
    pub fn intersect_plane(&self, plane: impl Into<Plane2d>, plane_origin: Vec2) -> Option<f32> {
        // ...
    }
}
```

To still allow passing the normal as a vector, the planes also implement `From<Vec2>`/`From<Vec3>`.

---

## Changelog

### Added

- `Ray2d` and `Ray3d`
- `Ray2d::new` and `Ray3d::new` constructors
- `Plane2d::new` and `Plane3d::new` constructors
- Implemented `From<Vec2>`/`From<Vec3>` for `Plane2d`/`Plane3d`

### Removed

- Removed `Ray` in favor of `Ray3d`

### Changed

- `direction` is now a `Direction2d`/`Direction3d` instead of a vector, which provides guaranteed normalization
- `intersect_plane` now takes an `impl Into<Plane2d>` instead of just a plane normal, so you can either pass the normal or a `Plane2d` (and similarly for 3D)

## Migration Guide

`Ray` has been renamed to `Ray3d`.

### Ray creation

Before:

```rust
Ray {
    origin: Vec3::ZERO,
    direction: Vec3::new(0.5, 0.6, 0.2).normalize(),
}
```

After:

```rust
// Option 1:
Ray3d {
    origin: Vec3::ZERO,
    // Equivalent to Direction3d::from(Vec3::new(0.5, 0.6, 0.2))
    direction: Vec3::new(0.5, 0.6, 0.2).into(),
}

// Option 2:
Ray3d::new(Vec3::ZERO, Vec3::new(0.5, 0.6, 0.2))
```

2023-12-04 16:58 UTC, alice-i-cecile requested changes
I really like the split: more consistent and efficient.

I think these `From` impls should be cut though.

2023-12-04 17:16 UTC, Jondolf commented on crates/bevy_math/src/primitives/dim2.rs
> +impl From<Vec2> for Plane2d {
Should `intersect_plane` take a `Plane2d` then? Previously it just took the plane normal as a vector, but if we have plane primitives, it'd make sense to use them. In that case, we should probably also add a `new` constructor for planes to make the API less painful:

```rust
// No constructor
let result = ray.intersect_plane(
    Vec2::X,
    Plane2d {
        normal: Direction2d::new(Vec2::Y).unwrap(),
    },
);

// Constructor (should probably panic for invalid Direction2d after #10857)
let result = ray.intersect_plane(Vec2::X, Plane2d::new(Vec2::Y));

// Current API
let result = ray.intersect_plane(Vec2::X, Vec2::Y);
```

2023-12-04 17:20 UTC, alice-i-cecile commented on crates/bevy_math/src/primitives/dim2.rs
> +impl From<Vec2> for Plane2d {
Agreed on both counts!

2023-12-04 17:58 UTC, Jondolf commented
I removed the `From` impls from the planes, added `new` constructors instead, and updated the PR description. I think #10857 could be merged first though since the constructors will have to be changed a bit

2023-12-04 18:06 UTC, alice-i-cecile approved these changes

2023-12-05 18:40 UTC, Jondolf commented
I updated the PR to match the direction constructor changes. I opted to make the `new` constructors for rays and planes panic with an `expect` if the direction is correct, since I think that's nicer for ergonomics, and you could just not use the constructor if you wanted to handle those cases manually.

If the changes look fine, everything should now be ready :)

2023-12-05 22:31 UTC, rlidwka approved these changes

2023-12-05 22:34 UTC, rlidwka commented
How common is it to convert between Ray2 to Ray3? Do we need helper methods for that like glam's `extend()` and `truncate()`?

2023-12-05 22:48 UTC, Jondolf commented
I don't think it's particularly common, but it'd probably be nice to have. But it would also make sense for other types, like directions, planes, lines, line segment and even rectangle/cuboid, so it should be done in a separate PR.

2023-12-06 14:24 UTC, merged