Make Query::new() pub
bevyengine/bevy pull request #10908
Opened 2023-12-07 21:20 UTC by JMS55

## Changelog
- Added `Query::new()` for low-level, unsafe uses of the ECS world.

2023-12-09 06:42 UTC, Nilirad commented
Should this be controversial? It makes a private API public. But it is already marked as `unsafe`, so is that enough?

2023-12-09 14:25 UTC, alice-i-cecile requested changes
I think we should add docs to the effect of "generally speaking, if you need a `Query` from ` World`, you should use `SystemState` instead."

But this is a reasonable API for `UnsafeWorldCell`, and I expect advanced users will be alright with breakage.

2023-12-11 05:57 UTC, JoJoJet reviewed
I *really* don't want to include the `force_read_only_component_access` hack in a public API. Can we rename the existing method to `new_inner`, and make `pub fn new` a thin wrapper around `new_inner`?

2023-12-11 05:57 UTC, JoJoJet commented on crates/bevy_ecs/src/system/query.rs
>      /// called in ways that ensure the queries have unique mutable access.
```suggestion
    /// `world` must have permission to access any component data specified in `state`'s [`archetype_component_access`].
    ///
    /// [`archetype_component_access`]: QueryState::archetype_component_access
    ///
    /// # Panics
    ///
    /// If `world` does not match the one used to create `state`.
```

I believe this is the most correct way you can phrase the safety requirement. Though we'd also need to add `QueryState::archetype_component_access` (it's weird that function doesn't exist already).

The `# Panics` should probably go above the `# Safety` section, although GitHub's UI won't let me format the suggestion that way.

2023-12-13 01:35 UTC, james7132 reviewed
I'll be the one to play devil's advocate and ask what the expected use case here is. `SystemState::get` and it's variants should be sufficient, and provides a list of options that can be used to create a `Query` with a gradual introduction of increasingly tighter invariants, and it ensures that `QueryState` stays in a proper state while in use. Is there any particular use case that requires `Query::new` to be public that isn't served by this flow?

2023-12-13 01:51 UTC, JMS55 commented
For reference, here's what I'm trying to achieve: https://github.com/JMS55/bevy_dioxus/blob/main/src/hooks.rs#L104-L125
```rust
fn ui_root(cx: Scope) -> Element {
    let names = use_query::<DebugName>(cx);

    render!(
        for name in names.query() {
            "{name:?}"
        }
    )
}
```

2024-01-24 18:08 UTC, JMS55 commented
Using SystemState worked, but has the unfortunate side effect of requiring things to be `mut` https://github.com/JMS55/bevy_dioxus/pull/19

2024-03-29 22:08 UTC, closed without merging