Add docs to bevy_sprite a little
bevyengine/bevy pull request #10947
Opened 2023-12-12 13:23 UTC by akimakinai

# Objective

- bevy_sprite crate is missing docs for important types. `Sprite` being undocumented was especially confusing for me even though it is one of the first types I need to learn.
 
## Solution

- Improves the situation a little by adding some documentations.
I'm unsure about my understanding of functionality and writing. I'm happy to be pointed out any mistakes.

2023-12-12 19:05 UTC, alice-i-cecile commented on crates/bevy_sprite/src/bundle.rs
> +/// A Bundle of components for drawing a single sprite from an image.
```suggestion
/// A [`Bundle`] of components for drawing a single sprite from an image.
```

2023-12-12 19:05 UTC, alice-i-cecile commented on crates/bevy_sprite/src/bundle.rs
> +    /// The transform of the sprite
```suggestion
    /// The local transform of the sprite, relative to its parent
```

2023-12-12 19:06 UTC, alice-i-cecile commented on crates/bevy_sprite/src/bundle.rs
>      pub global_transform: GlobalTransform,
```suggestion
    /// The absolute transform of the sprite. This should generally not be written to directly.
    pub global_transform: GlobalTransform,
```

2023-12-12 19:06 UTC, alice-i-cecile commented on crates/bevy_sprite/src/bundle.rs
> +    /// A handle to the image to be drawn
```suggestion
    /// A reference-counted handle to the image asset to be drawn
```

2023-12-12 19:07 UTC, alice-i-cecile commented on crates/bevy_sprite/src/collide_aabb.rs
> +/// Collision side returned by [`collide`]
```suggestion
/// The side where a collision occurred, as returned by [`collide`]
```

2023-12-12 19:08 UTC, alice-i-cecile requested changes
Great progress, some suggestions :)

2023-12-13 13:45 UTC, akimakinai commented
Thanks, applied suggestions.

2023-12-13 16:15 UTC, alice-i-cecile approved these changes

2023-12-13 16:18 UTC, Nilirad commented on crates/bevy_sprite/src/bundle.rs
> +    /// A reference-counted handle to the image asset to be drawn
```suggestion
    /// A reference-counted handle to the image asset to be drawn.
```

For consistency, I suggest to also add punctuation to the remaining fields.

2023-12-13 16:21 UTC, Nilirad commented on crates/bevy_sprite/src/bundle.rs
>  /// to as a `TextureAtlas`)
```suggestion
/// to as a `TextureAtlas`).
```

2023-12-13 16:23 UTC, Nilirad commented on crates/bevy_sprite/src/collide_aabb.rs
> +/// The side where a collision occurred, as returned by [`collide`]
```suggestion
/// The side where a collision occurred, as returned by [`collide`].
```

2023-12-13 16:30 UTC, Nilirad commented on crates/bevy_sprite/src/lib.rs
> +/// Set system for the systems relating to sprite rendering.
```suggestion
/// System labels for sprite rendering.
```

The wording is a little weird and "set system" is not a common form.

2023-12-13 16:35 UTC, Nilirad commented on crates/bevy_sprite/src/sprite.rs
> +/// [`SpriteBundle`](crate::bundle::SpriteBundle) is a bundle for common sprite rendering use cases.
```suggestion
/// This is commonly used as a component within [`SpriteBundle`](crate::bundle::SpriteBundle).
```

We're talking about `Sprite` here, not `SpriteBundle`.

2023-12-13 16:40 UTC, Nilirad commented on crates/bevy_sprite/src/lib.rs
> +/// Set system for the systems relating to sprite rendering.
```suggestion
/// System set for sprite rendering.
```

Alternative version.

2023-12-13 16:43 UTC, Nilirad commented on crates/bevy_sprite/src/texture_atlas.rs
> +/// [`SpriteSheetBundle`](crate::bundle::SpriteSheetBundle) is a bundle for common sprite rendering use cases.
```suggestion
/// This is commonly used as a component within [`SpriteSheetBundle`](crate::bundle::SpriteSheetBundle).
```

Same here.

2023-12-13 16:44 UTC, Nilirad commented on crates/bevy_sprite/src/lib.rs
> +/// Set system for the systems relating to sprite rendering.
```suggestion
/// System set for sprite rendering.
```

Alternative version.

2023-12-14 04:09 UTC, Nilirad approved these changes

2023-12-14 17:40 UTC, merged