Simplify equality assertions
bevyengine/bevy pull request #10988
Opened 2023-12-15 10:27 UTC by tygyh

# Objective

- Shorten assertions.

## Solution

- Replace '==' assertions with 'assert_eq()' and '!=' assertions with 'assert_ne()' .

2023-12-15 11:09 UTC, tygyh commented
If I am not misunderstanding the failing test, it is testing if Rust's convertions work as intended, not if the table works as intended. I do not see a reason for that test to be in the engine in that case.

2023-12-15 14:44 UTC, matiqo15 requested changes

2023-12-15 14:44 UTC, matiqo15 commented on crates/bevy_ecs/src/storage/table.rs
> +        assert_eq!(index as u32 as usize, index);
It seems like we cannot use `assert_eq!` in constant functions

2023-12-15 14:44 UTC, matiqo15 commented on crates/bevy_ecs/src/storage/table.rs
> +        assert_eq!(index as u32 as usize, index);
Same here

2023-12-15 14:46 UTC, matiqo15 commented
`assert_eq!` can't be used in constant functions, that's why CI is failing.

2023-12-15 16:25 UTC, tygyh commented
Yes, and that is why I am saying the tests are wrong. They are testing if Rust works as intended.

2023-12-15 16:48 UTC, matiqo15 commented
We check if `index` fits into `u32` and panic if it doesn't, otherwise it would be truncated to the biggest number we can fit in `u32`, and that could lead to unexpected behavior. So that `assert` is needed.

2023-12-15 17:31 UTC, tygyh commented
I think I unstand it more now. Thank you for explaining.

2023-12-15 20:16 UTC, djeedai approved these changes

2023-12-15 20:26 UTC, matiqo15 approved these changes

2023-12-15 22:30 UTC, Nilirad approved these changes

2023-12-16 23:58 UTC, mockersf approved these changes

2023-12-17 00:11 UTC, merged