Reexport winit::platform::android::activity::* in bevy_winit
bevyengine/bevy pull request #11011
Opened 2023-12-17 19:22 UTC by hecksmosis

# Objective

- Fixes #10630

## Solution

- Reexport winit::platform::android::activity::* in bevy_init

2023-12-17 19:47 UTC, alice-i-cecile approved these changes

2023-12-17 19:52 UTC, JMS55 commented
Instead of a top-level export, maybe we want to scope it under a module? I don't have a preference either way I don't think.

2023-12-17 20:32 UTC, matiqo15 commented
I agree with @JMS55, though it's fine either way.

2023-12-17 22:53 UTC, mockersf commented on crates/bevy_winit/src/lib.rs
> +pub use winit::platform::android::activity::*;
maybe
```suggestion
pub use winit::platform::android::activity as android_activity;
```

2023-12-18 19:10 UTC, matiqo15 approved these changes

2023-12-18 21:35 UTC, mockersf requested changes
you'll also have to update the places where the `AndroidApp` was used

2023-12-19 20:29 UTC, merged