Derive `Eq` and `Ord` for `Msaa`
bevyengine/bevy pull request #11042
Opened 2023-12-20 20:23 UTC by SludgePhD

# Objective

- `Msaa` already implements the partial relation traits, but there isn't much of a reason to not implement the total ones.

## Solution

- Add `Eq` and `Ord` to the derive list.

2023-12-21 14:12 UTC, mockersf commented
> * `Msaa` already implements the partial relation traits, but there isn't much of a reason to not implement the total ones.

The question shouldn't be "why not" when adding derives, it should be "why". They add to the compilation time and to the binary size.

If you have a practical use for them, no problem, but that doesn't seem the case here from your description

2023-12-21 17:25 UTC, SludgePhD commented
I'm writing an editor that allows editing enums like this with a function

```
fn edit_enum<T: fmt::Debug + Eq + Clone>(&mut self, value: &mut T, choices: &[T])
```

This does not currently work with `Msaa` because it does not implement `Eq`. I could relax the bound to `PartialEq`, but that would be semantically incorrect.

Rust's API guidelines also [recommend](https://rust-lang.github.io/api-guidelines/interoperability.html#types-eagerly-implement-common-traits-c-common-traits) eagerly implementing all applicable core traits.

2023-12-21 23:16 UTC, alice-i-cecile approved these changes

2023-12-23 17:40 UTC, james7132 requested changes
If we're choosing to explicitly derive applicable traits, I disagree with the notion that we should implement `Ord` unless there's a good reason to do so (i.e. satsifying the invariants as use as a key for a `BTreeMap`).

2024-03-02 23:13 UTC, closed without merging