Explain EventWriter limits concurrency
bevyengine/bevy pull request #11063
Opened 2023-12-22 05:21 UTC by stepancheg

2023-12-22 06:30 UTC, mockersf commented on crates/bevy_ecs/src/event.rs
> +/// # Concurrently
```suggestion
/// # Concurrency
```

2023-12-22 16:01 UTC, Nilirad requested changes

2023-12-22 16:01 UTC, Nilirad commented on crates/bevy_ecs/src/event.rs
> +/// (but not with `EventWriter<T>` systems).
```suggestion
```
This line repeats what was stated a couple of lines before.

2023-12-23 00:26 UTC, Nilirad approved these changes

2023-12-23 17:34 UTC, james7132 approved these changes

2023-12-23 17:34 UTC, james7132 commented on crates/bevy_ecs/src/event.rs
> +/// for the same `<T>` won't be executed concurrently.
```suggestion
/// for the same event type won't be executed concurrently.
```

2023-12-23 17:34 UTC, james7132 commented on crates/bevy_ecs/src/event.rs
> +/// (but not concurrently with `EventWriter<T>` systems for the same `<T>`).
```suggestion
/// (but not concurrently with `EventWriter<T>` systems for the same event type).
```

2023-12-24 17:58 UTC, merged