Take `Timer` instead of `Duration` in `on_timer` run condition
bevyengine/bevy pull request #11095
Opened 2023-12-26 18:31 UTC by TimJentzsch

# Objective

I want to run a system once after a given delay.

- First, I tried using the `on_timer` run condition, but it uses a repeating timer, causing the system to run multiple times.
- Next, I tried combining the `on_timer` with the `run_once` run condition. However, this causes the timer to *tick* only once, so the system is never executed.

## Solution

This PR changes the `on_timer` run condition to take a `Timer` instead of a `Duration` as parameter.
This allows the user to specify the `TimerMode`, so it's possible to select `TimerMode::Once` to run the system only once.

---

## Changelog

### Changed

- The `on_timer` run condition now takes a `Timer` instead of just a `Duration`, allowing you to set the `TimerMode`.

## Migration Guide

The `on_timer` run condition now takes a `Timer` instead of just a `Duration`, allowing you to set the `TimerMode`. Use `TimerMode::Repeating` for the old behavior.

### Before

```rs
app.add_systems(
    Update,
    system.run_if(on_timer(Duration::from_secs(1))))
);
```

### After

```rs
app.add_systems(
    Update,
    system.run_if(on_timer(Timer::new(
        Duration::from_secs(1),
        TimerMode::Repeating,
    ))),
);
```

2023-12-26 18:47 UTC, alice-i-cecile requested changes
I really like this change (it's flexible and intuitively matches the name), but I think it's a usability regression in most cases.

Instead, I suggest we keep this change, but also:

1. Add a `periodically` (or whatever) run condition that works the same as the old on_timer condition.
2. Doc link between the two methods, explaining why you might want the more verbose form.
3. Replicate this for the `on_real_timer` variant.

2023-12-26 18:50 UTC, TimJentzsch commented
> I really like this change (it's flexible and intuitively matches the name), but I think it's a usability regression in most cases.
> 
> Instead, I suggest we keep this change, but also:
> 
>     1. Add a `periodically` (or whatever) run condition that works the same as the old on_timer condition.
> 
>     2. Doc link between the two methods, explaining why you might want the more verbose form.
> 
>     3. Replicate this for the `on_real_timer` variant.

At this point I wonder if it's worth it to have the more verbose version, or if we have `periodically` and `after_delay` (or something similar) which both just take a `Duration` and handle the `TimerMode` internally.

2023-12-26 19:00 UTC, alice-i-cecile commented
Yeah, it might make sense just to have the two forms and don't ever expose the `Timer` form. At the same time, I think we should move away from `on_timer` as a name (use a deprecation if you do), just to avoid the same confusion you had. It's weird that it doesn't take a `Timer` argument!

2023-12-28 13:02 UTC, TimJentzsch commented
Alright, I have deprecated the `on_timer` and `on_real_timer` names and added variants with `TimerMode::Once`.

2023-12-28 18:22 UTC, alice-i-cecile approved these changes

2024-01-07 17:57 UTC, NthTensor approved these changes
Looks good to me. Nice docs.

2024-01-07 19:10 UTC, bausano approved these changes

2024-01-08 12:33 UTC, TimJentzsch commented
As per <https://discordapp.com/channels/691052431525675048/692572690833473578/1193685432442036235>, I reverted the rename of the old run condition.

2024-01-08 16:33 UTC, alice-i-cecile approved these changes

2024-01-09 00:09 UTC, merged