Add `Cursor.grab_mode` docs for X11
bevyengine/bevy pull request #11174
Opened 2024-01-01 19:46 UTC by cloud303-cholden

# Objective

- Documents workaround for bug on X11 with cursor grab on window initialization.
- Fixes #10084 

## Solution

- Add an entry to the platform-specific documentation for `bevy::window::Cursor.grab_mode` ([link](https://docs.rs/bevy/latest/bevy/window/struct.Cursor.html#structfield.grab_mode)), providing a link to the above issue where the workaround is described. I believe this is the cleanest solution.

2024-01-01 23:10 UTC, mockersf requested changes
my understanding is that it's not so much that it must be done in a startup system, but not during window creation. doing it during gameplay in a normal system should also work

2024-01-02 00:15 UTC, cloud303-cholden commented
That tracks with my understanding too, i.e. anything from startup on. Is it sufficient to rephrase it like that?

2024-01-02 00:16 UTC, mockersf commented
how would it work for a second window created after startup?

2024-01-02 04:12 UTC, cloud303-cholden commented
This particular situation might require further investigation. Below is what I have so far, and there are a couple issues.

1. I couldn't get the cursor to lock for new windows. I tried to get creative after a couple failed attempts, hence the hacky code below. But even this doesn't work.
2. It occasionally hangs when I close a window.

<details>
  <summary>Code</summary>

```rust
use bevy::{
    prelude::*,
    window::CursorGrabMode,
    winit::WinitWindows,
};

#[derive(Component)]
struct GrabCursor;

fn main() {
    App::new()
        .add_plugins(
            DefaultPlugins
                .set(WindowPlugin {
                    primary_window: Some(Window::default()),
                    ..Default::default()
                })
        )
        .add_systems(Startup, grab_cursor_startup)
        .add_systems(Update, (
            spawn_window,
            grab_cursor_update,
            bevy::window::close_on_esc,
        ))
        .run();
}

fn grab_cursor_startup(mut windows: Query<&mut Window>) {
    // X11 GrabPointer returns NotViewable error if the
    // grab mode is set on window initialization.
    let mut window = windows.single_mut();
    window.cursor.grab_mode = CursorGrabMode::Locked;
}

fn grab_cursor_update(
    mut commands: Commands,
    q_window: Query<Entity, With<GrabCursor>>,
    winit_windows: NonSend<WinitWindows>,
) {
    let Ok(entity) = q_window.get_single() else { return };
    let winit_window = winit_windows
        .get_window(entity)
        .unwrap();
    let _ = winit_window
        .set_cursor_grab(winit::window::CursorGrabMode::Locked);
    commands
        .entity(entity)
        .remove::<GrabCursor>();
}

fn spawn_window(
    mut commands: Commands,
    input: Res<Input<KeyCode>>,
    q_windows: Query<(&mut Window, Entity)>,
    winit_windows: NonSend<WinitWindows>,
) {
    if input.just_released(KeyCode::Space) {
        for (window, entity) in q_windows.iter() {
            if window.cursor.grab_mode != CursorGrabMode::None {
                let winit_window = winit_windows
                    .get_window(entity)
                    .unwrap();
                let _ = winit_window
                    .set_cursor_grab(winit::window::CursorGrabMode::None);
            }
        }
        commands.spawn((Window::default(), GrabCursor));
    }
}
```
</details>

2025-01-23 05:44 UTC, closed without merging