Addition of PopChild and PopChildren commands
bevyengine/bevy pull request #11230
Opened 2024-01-05 19:34 UTC by TirushOne

This pull request is a direct result of issue #11186

2024-01-06 15:26 UTC, alice-i-cecile commented on crates/bevy_hierarchy/src/child_builder.rs
> +///Command that removes the last Child from an entity
```suggestion
/// Command that removes the last [`Child`] from an entity
```

2024-01-06 15:30 UTC, alice-i-cecile requested changes
I'm not 100% sure this should exist: when would one want to use this command?

In terms of implementation:

1. The command structs should be directly constructable if they're pub: there's no benefit to hiding their fields.
2. Users will expect an API to use this as a method directly with Commands / EntityCommands. Check how other commands use an extension trait.
3. Because this command is centered around a single entity, should it be an `EntityCommand` instead?

2024-01-08 13:05 UTC, TirushOne commented
> I'm not 100% sure this should exist: when would one want to use this command?
> 
> In terms of implementation:
> 
> 1. The command structs should be directly constructable if they're pub: there's no benefit to hiding their fields.
> 2. Users will expect an API to use this as a method directly with Commands / EntityCommands. Check how other commands use an extension trait.
> 3. Because this command is centered around a single entity, should it be an `EntityCommand` instead?

you're going to have to run that by me again.

I would create a contructor for the command, but I can't find where the other commands have their contructors so I don't have any pattern to follow. If you would point to where I can find these command contructors and "extension traits" I could make some changes. searching through the bevy code base is like look for a niddle in a hay stack and I find what you're talking about within the hierarchy.

as far as I am awhere the point of this command is just to make removing children from parents in certain scenaros easier. rust user will already be firmila with "pop" when working with vectors so it seems like a itomatic command to have.

2024-01-08 15:52 UTC, doonv reviewed
Not bad.
By the way I recommend adding "Fixes https://github.com/bevyengine/bevy/issues/11186" to the top of your pull request's message. That tells github to automatically close that issue if this pull request gets merged.

2024-01-09 03:43 UTC, TirushOne commented on crates/bevy_hierarchy/src/child_builder.rs
> +            }
thanks for the help with the changes

2024-01-09 04:26 UTC, TirushOne commented on crates/bevy_hierarchy/src/child_builder.rs
> +            }
ok well guess I'll just wait for this pr to get merged and if something is stopping that or needs to be fixed please let me know

2024-01-09 04:57 UTC, TirushOne commented
I still don't understand though, why are some of these commands pub but there feilds are not (and I can't find any contructors) but PopChild and PopChildren have public feilds? it is becasue all of those aother commands are for internal use and not public use, why have them be pub? and if they are for public use, how are they getting contructed without public feilds and without contructors?

2024-01-09 12:32 UTC, doonv commented
It appears other commands are accessed inside the `BuildChildren` extension trait. There are functions there that create and call their respective command, like this:
```rs
fn clear_children(&mut self) -> &mut Self {
    let parent = self.id();
    self.commands().add(ClearChildren { parent });
    self
}
```
I have no idea why the commands are public while their fields are not though, might be a good idea to create another pull request to fix that.

2024-01-09 18:29 UTC, alice-i-cecile commented
I can see the argument for consistency (and I don't want to be discouraging), but I don't think this should be merged. 

Removing the last child is not an operation that users ever want to do: the operations that you want are "remove this specific entity" and "clear all other entities".

2024-01-10 03:01 UTC, TirushOne commented
> I can see the argument for consistency (and I don't want to be discouraging), but I don't think this should be merged.
> 
> Removing the last child is not an operation that users ever want to do: the operations that you want are "remove this specific entity" and "clear all other entities".

I mean I don't know if this is convincing, but I guess becasue of the funtional nature of rust, and therefore bevy, parsing commands to the ecs requires a decent bit of boiler plate, not that much, but enough that I think it's worth a small amount of back end bloat with abtractions like "pop children" that removes the need for front end boiler plate like getting the children first and then removing them. It is up to you guys though. I will say if we are closing this pull then probobley also best to go and close the issues as well if it's not acctually an issue.

2024-01-16 11:36 UTC, closed without merging