Main
bevyengine/bevy pull request #11422
Opened 2024-01-19 11:44 UTC by ArthurBrussee

# Objective

Fix weird visuals when drawing a gizmo with a non-normed normal.

Fixes #11401

## Solution
Just normalize right before we draw. Could do it when constructing the builder but that seems less consistent.

## Changelog
- Fixed gizmos.circle when normal isn't unit length.

2024-01-19 12:47 UTC, mockersf requested changes
Could you use a `Direction3d` instead of a `Vec3` so that it doesn't't have to be normalised? http://dev-docs.bevyengine.org/bevy/prelude/primitives/struct.Direction3d.html

2024-01-20 22:50 UTC, ArthurBrussee commented
Sure! Gave that a go. This does slightly conflict with @alice-i-cecile comment in #11401 though. Maybe callees using Direction3d::new(vec).unwrap_or(Direction3d::Y) isn't too bad. Maybe could be worth having a Direction3d::new_or(vec, Direction3d::Y) ? Not sure.

2024-01-21 02:47 UTC, alice-i-cecile commented
I prefer the type-safe validation to my suggestion linked :)

2024-01-21 02:47 UTC, alice-i-cecile approved these changes

2024-01-21 02:48 UTC, alice-i-cecile commented
@rodolphito review?

2024-01-21 04:54 UTC, mockersf approved these changes

2024-01-21 18:17 UTC, merged