Direction: Rename `from_normalized` to `new_unchecked` and declare unsafe
bevyengine/bevy pull request #11425
Opened 2024-01-19 20:36 UTC by doonv

# Objective

`Direction2d::from_normalized` & `Direction3d::from_normalized` allow you to create a direction that uses a vector that may not be normalized without unsafe code. This is bad because the direction vectors should guarantee that their inner vector is normalized.

## Solution

Rename `from_normalized` to `new_unchecked` and declare it as unsafe.

---

`Direction2d` and `Direction3d` were added somewhat recently in https://github.com/bevyengine/bevy/pull/10466 (after 0.12), so I don't think documenting the changelog and migration guide is necessary (Since there is no major previous version to migrate from).

But here it is anyway in case it's needed:

## Changelog

- Renamed `Direction2d::from_normalized` and `Direction3d::from_normalized` to `new_unchecked`, and marked the method as unsafe.

## Migration Guide

- Renamed `Direction2d::from_normalized` and `Direction3d::from_normalized` to `new_unchecked`, and marked the method as unsafe.

2024-01-19 23:29 UTC, tguichaoua requested changes

2024-01-19 23:29 UTC, tguichaoua commented on crates/bevy_math/src/primitives/dim2.rs
> +    /// ## Safety
```suggestion
    /// # Safety
```

2024-01-19 23:29 UTC, tguichaoua commented on crates/bevy_math/src/primitives/dim3.rs
> +    /// ## Safety
```suggestion
    /// # Safety
```

2024-01-19 23:29 UTC, tguichaoua commented on crates/bevy_math/src/primitives/dim2.rs
> +    /// release builds can allow the creation of a [`Direction2d`] that is not normalized.
```suggestion
    /// `value` must be normalized, i.e it's length must be `1.0`.
```
I think it's better to have something more straightforward for the safety section.

2024-01-19 23:29 UTC, tguichaoua commented on crates/bevy_math/src/primitives/dim3.rs
> +    /// release builds can allow the creation of a [`Direction3d`] that is not normalized.
```suggestion
    /// `value` must be normalized, i.e it's length must be `1.0`.
```
Same here

2024-01-19 23:29 UTC, tguichaoua commented on crates/bevy_math/src/bounding/bounded3d/primitive_impls.rs
> +            direction: unsafe { Direction3d::new_unchecked(rotation * Vec3::Y) },
Can `Direction(3d,2d)` implements rotation ?  (probably in another PR)
to directly use `rotation * Direction3d::Y` without unsafe.

2024-01-19 23:58 UTC, alice-i-cecile requested changes
Conventionally, `unsafe` in Rust is used *strictly* for memory safety issues. While I strongly think that there should be alternatives that work like `unsafe`, but for other forms of danger, we should stick to the conventions of the ecosystem.

That said, I love the rest of these changes and think we need to warn more aggressively here.

2024-01-20 09:23 UTC, james7132 requested changes

2024-01-20 09:23 UTC, james7132 commented on crates/bevy_math/src/primitives/dim2.rs
> +    pub unsafe fn new_unchecked(value: Vec2) -> Self {
This presents nothing that is actually undefined behavior in Rust. We should not be making APIs like these.

2024-01-20 10:46 UTC, doonv commented
> Conventionally, `unsafe` in Rust is used strictly for memory safety issues.

Yes, but it's also used in cases where there is a promise that a certain type must have some limitation (being normalized in this case).

All the `NonZero` number types in the standard library of examples of this.

Having a direction vector that is not normalized may not cause UB in the traditional sense, but it could cause unforeseen bugs.

2024-01-20 10:52 UTC, tguichaoua commented
> All the `NonZero` number types in the standard library of examples of this.

`NonZero` is used for niche optimization; if you create a zeored 'NonZero', then some code becomes unsound.
The question is: is the invariant of `Direction` (i.e., a vector is normalized) used as a guarantee in unsafe code?

2024-01-20 11:05 UTC, doonv commented
> The question is: is the invariant of Direction (i.e., a vector is normalized) used as a guarantee in unsafe code?

No, but it almost certainly cause bugs in code that expect `Direction` to be normalized.

Marking it as `unsafe` makes the user think twice on if their vector is really normalized.

2024-01-20 11:24 UTC, tguichaoua commented
From the [Book](https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html#unsafe-superpowers):
>  the intent is that as the programmer, you’ll ensure the code inside an unsafe block will access memory in a valid way.

`unsafe` in Rust is a matter of accessing valid memory. The worst that could happen with a non-normalized `Direction` is panic; which is a logic bug like dividing by `0`.

2024-01-20 11:51 UTC, doonv commented
> The worst that could happen with a non-normalized Direction is panic

Panics are arent much of a problem here (they can easily be tracked down), what is a problem is a silent bug (A bug that doesn't provide any debug information when it occurs). For example, if you have a player movement function that takes in a `Direction2d` and that `Direction2d` isnt normalized, that cause the player to move slower/faster than expected, and it'll be very hard to track down. (The user will expect `Direction2d` to be normalized)

The `unsafe` keyword isn't just for memory issues and UB, it's for places that have a "contract" that the compiler can't check.

> The `unsafe` keyword has two uses:
> 
> - to declare the existence of contracts the compiler can't check (`unsafe fn` and `unsafe trait`),
> - and to declare that a programmer has checked that these contracts have been upheld (`unsafe {}` and `unsafe impl`, but also unsafe fn -- see below).

\- The `unsafe` keyword's documentation when hovered over (rust-analyzer) 

The "contract" here is that the inner vector is normalized.

As I said earlier, making this `unsafe` makes the user think twice about if their direction is really normalized. And it makes shooting yourself in the foot harder.

2024-01-20 12:21 UTC, nicopap commented
This has been a longstanding discussion in the rust community. "What should I mark as unsafe?" For the standard library, the answer is "only methods with invariants, which, if not upheld, invoke undefined behaviors".

There is even a chapter on the rust reference about "behaviors not considered unsafe": <https://doc.rust-lang.org/stable/reference/behavior-not-considered-unsafe.html>. "Logic Errors" is in there.

This doesn't answer the question of whether we should mark the method as unsafe. The thing is, we already expose API that assumes the values passed-in represent a normal vector: [The `Quat` constructors](https://docs.rs/bevy/latest/bevy/math/struct.Quat.html#method.from_xyzw). I think we should be consistant with our API, and it makes sense to not mark the constructor as `unsafe`, the same way `glam` doesn't. We could add a runtime check though!

2024-01-20 12:42 UTC, doonv commented
Well, I guess I'll make it safe.

2024-01-20 14:12 UTC, tguichaoua requested changes

2024-01-20 14:12 UTC, tguichaoua commented on crates/bevy_math/src/primitives/dim2.rs
> +    /// ## Warning
```suggestion
    /// # Warning
```

2024-01-20 15:28 UTC, alice-i-cecile approved these changes

2024-01-20 20:14 UTC, Jondolf approved these changes
Some comment nits, but otherwise looks good

2024-01-20 20:14 UTC, Jondolf commented on crates/bevy_math/src/bounding/bounded3d/primitive_impls.rs
> +            // Multipling a normalized vector (Vec3::Y) with a rotation returns a normalized vector.
```suggestion
            // Multiplying a normalized vector (Vec3::Y) with a rotation returns a normalized vector.
```

2024-01-20 20:14 UTC, Jondolf commented on crates/bevy_math/src/primitives/dim3.rs
> +            // We are dividing by the length here, so the Vector is normalized.
```suggestion
            // We are dividing by the length here, so the vector is normalized.
```

2024-01-20 22:07 UTC, merged

2024-01-20 22:47 UTC, rlidwka commented
> The thing is, we already expose API that assumes the values passed-in represent a normal vector: [The Quat constructors](https://docs.rs/bevy/latest/bevy/math/struct.Quat.html#method.from_xyzw).

Quaternions do not need to be normalized. Only quaternions that are used for rotation do. I've used quaternions to represent angular velocity before, and those were intentionally not normalized.

In nalgebra, there's UnitQuaternion specifically for rotations, but there's nothing similar in bevy/glam.