Implement bounding volume intersections
bevyengine/bevy pull request #11439
Opened 2024-01-20 18:11 UTC by Jondolf

# Objective

#10946 added bounding volume types and an `IntersectsVolume` trait, but didn't actually implement intersections between bounding volumes.

This PR implements AABB-AABB, circle-circle / sphere-sphere, and AABB-circle / AABB-sphere intersections.

## Solution

Implement `IntersectsVolume` for bounding volume pairs. I also added `closest_point` methods to return the closest point on the surface / inside of bounding volumes. This is used for AABB-circle / AABB-sphere intersections.

2024-01-20 18:33 UTC, IQuick143 requested changes
For consistency I'd change the < to <=, but other than that I haven't noticed any problems.

2024-01-20 18:33 UTC, IQuick143 commented on crates/bevy_math/src/bounding/bounded2d/mod.rs
> +        distance_squared < radius_squared
This is nitpicking at edge cases, but I'd say this should be less than or equals, to account for the points at the surface of the ball.
```suggestion
        distance_squared <= radius_squared
```

2024-01-20 18:33 UTC, IQuick143 commented on crates/bevy_math/src/bounding/bounded3d/mod.rs
> +        distance_squared < radius_squared
Same here.
```suggestion
        distance_squared <= radius_squared
```

2024-01-20 18:47 UTC, NiseVoid reviewed
This seems correct. Didn't check the tests tho. And `closest_point` on sphere/circle appears to be unused. It might be useful, but I also feel like maybe it should be on the primitive types instead.

2024-01-20 19:20 UTC, Jondolf commented
For now, I moved the circle/sphere `closest_points` logic to the primitives (same for AABBs), but kept the methods on the bounding volumes for consistency and convenience. I can also just remove the circle/sphere version since it's unused, or split it into a different PR, but I thought it'd be nice to have if AABBs have it anyway

2024-01-20 19:34 UTC, IQuick143 approved these changes
Seems good.

Although I'm not super convinced about implementing closest point on the primitives, because closest point seems to demand transform information (translation + rotation), which is addressed here by assuming default identity transform.
It's not a huge deal, because the user can use this to implement the general case simply by inversely transforming the point and then transforming the result.

2024-01-20 20:01 UTC, Jondolf commented
FWIW, Parry has "global" and local versions of a ton of methods, like `aabb`/`local_aabb`, `project_point`/`project_local_point`, `support_point`/`local_support_point`, and so on. Both can be useful.

The `closest_point` methods on the primitives currently correspond the most to `project_local_point`, but with the shape always treated as "solid" (the returned point can be inside the shape instead of always being at the perimeter/surface). In the future we might want a trait for this and to implement it for all primitives

2024-01-20 21:10 UTC, Jondolf commented
Here's a video of the bounding volume intersections working: (gray is the bounding volume)

https://github.com/bevyengine/bevy/assets/57632562/08bfdb32-8408-43ea-a13e-c9fb650e4b54

I can add this as an example if that'd be useful. Should I do it in this PR or a follow-up?

2024-01-22 14:33 UTC, NiseVoid commented
> Should I do it in this PR or a follow-up?

I guess a follow up PR that showcases the intersection tests (including raycasting and later shapecasting) and bounding types makes sense?

2024-01-22 17:55 UTC, alice-i-cecile approved these changes
Looks good. Great docs, and thanks for including thorough tests.

2024-01-22 18:08 UTC, merged