fix link to tracy
bevyengine/bevy pull request #11521
Opened 2024-01-25 03:15 UTC by ameknite

# Objective

 #11331 move the tracy dependency, this fix the link to point to the new location

2024-01-25 03:17 UTC, alice-i-cecile reviewed
I think we should probably keep pointing to `latest` by default in our docs 🤔

2024-01-25 18:33 UTC, ameknite commented
Ok, if we keep it in latest, this should be merge after 0.13

2024-01-26 06:36 UTC, hymm commented
We probably should remove the line number rather than trying to keep it in sync.

2024-01-26 13:35 UTC, alice-i-cecile commented on docs/profiling.md
> +It has a command line capture tool that can record the execution of graphical applications, saving it as a profile file. Tracy has a GUI to inspect these profile files. The GUI app also supports live
```suggestion
It has a command line capture tool that can record the execution of graphical applications, saving it as a profile file. Tracy has a GUI to inspect these profile files. The GUI app also supports live capture, showing you in real time the trace of your app. The version of tracy must be matched to the version of tracing-tracy used in bevy. A compatibility table can be found on [crates.io](https://crates.io/crates/tracing-tracy) and the version used can be found [here](https://github.com/bevyengine/bevy/blob/latest/crates/bevy_log/Cargo.toml).
```

2024-01-26 13:35 UTC, alice-i-cecile requested changes
Agreed, let's remove the line number and merge this now.

2024-01-27 19:23 UTC, alice-i-cecile approved these changes

2024-01-27 19:36 UTC, merged