Added documentation explaining the difference between lumens and luxes
bevyengine/bevy pull request #11551
Opened 2024-01-26 23:20 UTC by NthTensor

# Objective

- Fix https://github.com/bevyengine/bevy/issues/9809

## Solution

- Describe the difference between lumens and luxes, and why some lightsources use one and some the other.

2024-01-26 23:23 UTC, alice-i-cecile approved these changes

2024-01-26 23:34 UTC, JMS55 requested changes

2024-01-26 23:34 UTC, JMS55 commented on crates/bevy_pbr/src/light.rs
> +    /// Luminous power in lumens, representing the ammount of light emited by this source in all directions.
ammount -> amount
emited -> emitted

2024-01-26 23:34 UTC, JMS55 commented on crates/bevy_pbr/src/light.rs
> +    /// light projected onto surfaces by this lightsource. Lux is used here
```suggestion
    /// light projected onto surfaces by this light source. Lux is used here
```

2024-01-27 00:08 UTC, JMS55 approved these changes

2024-01-27 00:46 UTC, merged

2024-01-27 06:35 UTC, stepancheg commented
> Lux is used here instead of lumens because a directional light illuminates all surfaces more-or-less the same way (depending on the angle of incidence). Lumens can only be specified for light sources which emit light from a specific area.

Technically more correct explanation might be something like this:

... because for infinitely far directional light source, illuminance in lumens would be infinite which is practically useless.

2024-01-27 06:41 UTC, stepancheg commented
> more-or-less the same way (depending on the angle of incidence)

This can be rephrased like:

amount of light projected onto the surface depends only on the angle between the surface and the light direction, but not on the position in space.

2024-01-27 13:03 UTC, NthTensor commented
Those would probably have been better. Do you feel they are important enough for me to open a follow-up?