Add volume cast intersection tests
bevyengine/bevy pull request #11586
Opened 2024-01-28 21:02 UTC by NiseVoid

# Objective

- Add a basic form of shapecasting for bounding volumes

## Solution

- Implement Aabb2dCast, Aabb3dCast, BoundingCircleCast, and BoundingSphereCast
- These are really just raycasts, but they modify the volumes the ray is casting against
- The tests are slightly simpler, since they just use the raycast code for the heavy lifting

2024-01-28 21:05 UTC, NiseVoid commented
https://github.com/bevyengine/bevy/assets/3254486/e4eb79b8-e09e-4271-9196-e84e556a4ad3

Here's a video of it working. The shapes are cast from the origin (purple point) in the direction of the line. The shapes (and their offset from the origin) can be seen at the origin. The casts only interact with shapes of the same type. When a collision happens it is shown as a green shape

2024-01-29 21:08 UTC, Jondolf requested changes
Looks good implementation-wise, mainly some typos/copy errors.

I feel like the names could be made closer and more consistent though... There's `RayTest2d`, with "Test" and the dimension at the end, and then there's `Aabb2dCast`, with "Cast" and the dimension in the middle.

An "AABB test" sounds a bit ambiguous, so that can probably remain as "Cast". Maybe put the dimension at the end though, like `AabbCast2d`?

2024-01-31 18:02 UTC, Jondolf commented on crates/bevy_math/src/bounding/raytest2d.rs
> +                // Hit the center a the bounding circle, but from the other side
```suggestion
                // Hit the center of the bounding circle, but from the other side
```

2024-01-31 18:05 UTC, Jondolf commented on crates/bevy_math/src/bounding/raytest3d.rs
> +    /// Construct a [`BoundingSphereCast`] from a [`BoundingSphere`], origin, [`Direction3d`] and max distance.
Very much a nit: I was told in a review once that Bevy prefers the Oxford comma

(non-blocking lol)

2024-01-31 18:08 UTC, Jondolf approved these changes
Looks pretty good to me, tests seem solid as well!

2024-01-31 20:02 UTC, alice-i-cecile approved these changes

2024-01-31 20:29 UTC, merged