Deprecating hashbrown reexports
bevyengine/bevy pull request #11721
Opened 2024-02-05 16:23 UTC by andristarr

# Objective

- The exported hashtypes are just re-exports from hashbrown, we want to drop that dependency and (in the future) let the user import their own choice.
- Fixes #11717

## Solution

- Adding a deprecated tag on the re-exports, so in future releases these can be safely removed.

2024-02-05 16:28 UTC, alice-i-cecile requested changes
Yep, we only want to deprecate the stable variants.

We should also change the note to just explain exactly what this was a type alias was for: just copy the type from the source code :)

2024-02-05 16:31 UTC, andristarr commented
Sorry, why only the stable ones: as in, the other 2 seem to only be also just a reexport without any added functionality

2024-02-05 16:36 UTC, alice-i-cecile commented
Yeah, we use the faster ones internally all over the place, and they're a good default for games.

2024-02-05 16:36 UTC, NthTensor approved these changes

2024-02-05 16:40 UTC, alice-i-cecile commented on crates/bevy_utils/src/lib.rs
> +#[deprecated(note = "Will be required to use the hash library of your choice.")]
```suggestion
```

2024-02-05 16:40 UTC, alice-i-cecile commented on crates/bevy_utils/src/lib.rs
> +#[deprecated(note = "Will be required to use the hash library of your choice.")]
```suggestion
```

2024-02-05 16:43 UTC, andristarr commented
Let me know if the wording for the deprecated note is okay.

2024-02-05 17:04 UTC, alice-i-cecile requested changes
Hmm. @SpecificProtagonist, looks like we do actually use this internally.

We should migrate off the internal code as part of this PR if we want to pursue this. But given that we *do* use it internally, I'm weakly in favor of just leaving it alone and closing this issue and PR. @andristarr thanks for your work here either way; this was good to discover.

2024-02-06 10:54 UTC, doonv requested changes

2024-02-06 10:54 UTC, doonv commented on crates/bevy_utils/src/lib.rs
>  pub type StableHashSet<K> = hashbrown::HashSet<K, FixedState>;
This note is incorrect (It's copy pasted from the `StableHashMap` one)

2024-02-06 17:17 UTC, andristarr commented
Done, should be ready to go!

2024-02-06 18:04 UTC, alice-i-cecile commented
Looks great, thanks for the prompt and friendly responses to the reviews :)

2024-02-06 18:18 UTC, merged