Fix global wireframe behaviour not being applied on new meshes
bevyengine/bevy pull request #11792
Opened 2024-02-09 11:08 UTC by Kanabenki

# Objective

- Fixes #11782.

## Solution

- Remove the run condition for `apply_global_wireframe_material`, since it prevent detecting when meshes are added or the `NoWireframe` marker component is removed from an entity. Alternatively this could be done by using a run condition like "added `Handle<Mesh>` or removed `NoWireframe` or `WireframeConfig` changed" but this seems less clear to me than directly letting the queries on `apply_global_wireframe_material` do the filtering.

2024-02-09 11:14 UTC, Kanabenki commented
Putting in draft since there is some potential edge cases with `NoWireframe` I'd like to fix.

2024-02-11 17:04 UTC, Shatur requested changes
Minor suggestion, otherwise looks good!

2024-02-11 17:04 UTC, Shatur commented on crates/bevy_pbr/src/wireframe.rs
> +                    apply_global_wireframe_material.after(apply_wireframe_material),
I would suggest to use `chain`: `(apply_wireframe_material, apply_global_wireframe_material).chain()`

2024-02-12 08:38 UTC, Shatur approved these changes

2024-02-12 08:39 UTC, Shatur commented
@alice-i-cecile may I suggest this PR for your merge train?

2024-02-12 19:48 UTC, alice-i-cecile approved these changes

2024-02-12 20:09 UTC, merged