Alpha discard
bevyengine/bevy pull request #11895
Opened 2024-02-16 08:21 UTC by bonsairobo

# Objective

I want to call the `pbr_functions::alpha_discard` shader function from my own material shader, but it only takes a `StandardMaterial` parameter.

## Solution

This PR replaces the `StandardMaterial` parameter with less restrictive ones so my shader can call it.

---

## Changelog

- The signature of `pbr_functions::alpha_discard` changed by replacing `StandardMaterial` with only the `flags` and `alpha_cutoff` fields.

## Migration Guide

Replace this:

```wgsl
pbr_functions::alpha_discard(material, ...);
```

with this:

```wgsl
pbr_functions::alpha_discard(material.flags, material.alpha_cutoff, ...);
```

2024-02-16 13:18 UTC, alice-i-cecile approved these changes

2024-02-16 18:11 UTC, janhohenheim commented
Note that this breaks all material extensions, including the example one.

2024-02-16 18:13 UTC, janhohenheim requested changes
Note that this breaks all material extensions, including the example one.
As such, `assets/shaders/extended_material.wgsl` also needs updating.

2025-02-08 02:27 UTC, andriyDev reviewed
I tested this out locally and it seems good, the code also looks fine. However, there appear to be merge conflicts. I'd approve after the conflicts are addressed.

2026-05-21 08:33 UTC, IceSentry approved these changes

2026-05-21 08:49 UTC, mockersf approved these changes

2026-05-21 10:59 UTC, merged