make gizmo groups ordering stable when rendering
bevyengine/bevy pull request #12034
Opened 2024-02-22 00:50 UTC by mockersf

# Objective

- During rendering of different gizmo groups, the ordering is random between executions

## Solution

- Make the ordering stable
- It's using a `TypeIdMap`, its iteration order depends on the insertion order. so insert when adding a group instead of when adding a gizmo
- Also changed `extract_gizmo_data` to not be group dependent. there will be only one of those systems, no matter the number of gizmo groups added

2024-02-22 00:55 UTC, alice-i-cecile commented on crates/bevy_gizmos/src/lib.rs
> +    list: TypeIdMap<Option<Handle<LineGizmo>>>,
A comment on why this is an `Option` would be helpful. I can figure it out based on the PR description, but without context a map storing an option just looks like a code quality issue.

2024-02-22 01:58 UTC, alice-i-cecile approved these changes

2024-02-25 01:38 UTC, pablo-lua requested changes
If we go about inserting the resource if this isn't already inserted, we have to remove the init_resource of this resource in `GizmosPlugin` and make this be implicit inserted by `DefaultGizmoConfigGroup`

2024-02-25 01:38 UTC, pablo-lua commented on crates/bevy_gizmos/src/lib.rs
> +        let mut handles = self.world.get_resource_mut::<LineGizmoHandles>().unwrap();
```suggestion
        let mut handles = self.world.get_resource_or_insert_with::<LineGizmoHandles>(Default::default);
```

2024-02-25 22:27 UTC, IceSentry approved these changes

2024-02-26 16:08 UTC, merged