Add basic light gizmos
bevyengine/bevy pull request #12228
Opened 2024-03-01 15:16 UTC by Kanabenki

# Objective

- Add light gizmos for `SpotLight`, `PointLight` and `DirectionalLight`.

## Solution

- Add a `ShowLightGizmo` and its related gizmo group and plugin, that shows a gizmo for all lights of an entities when inserted on it. Light display can also be toggled globally through the gizmo config in the same way it can already be done for `Aabb`s.
- Add distinct segment setters for height and base one `Cone3dBuilder`. This allow having a properly rounded base without too much edges along the height. The doc comments explain how to ensure height and base connect when setting different values.

Gizmo for the three light types without radius with the depth bias set to -1:
![without-radius](https://github.com/bevyengine/bevy/assets/18357657/699d0154-f367-4727-9b09-8b458d96a0e2)

With Radius:
![with-radius](https://github.com/bevyengine/bevy/assets/18357657/f3af003e-dbba-427a-a305-c5cc1676e340)

---

## Changelog

### Added

- The new `ShowLightGizmo`, part of the `LightGizmoPlugin` and toggle-able globally with its `LightGizmoConfigGroup`, allows drawing gizmo for `PointLight`, `SpotLight` and `DirectionalLight`.
- The cone gizmo builder (`Cone3dBuilder`) now allows setting a differing number of segments for the base and height.

2024-03-01 19:06 UTC, alice-i-cecile commented
They're pretty, but I'm not sure I see the utility of these. Can you or @nicopap say more about where users might use these?

2024-03-01 19:11 UTC, Kanabenki commented
> They're pretty, but I'm not sure I see the utility of these. Can you or @nicopap say more about where users might use these?

The common use case I've seen them in other engines is to highlight the color and boundaries of a selected light in the editor. Unity, Unreal and Godot all have some kind of wireframe display to outline a light area and/or direction when it is selected.

I'm on mobile right now but I'll update with some screenshots to show what I mean as soon as I can.

2024-03-01 19:19 UTC, alice-i-cecile commented
Ah neat, for debugging lights themselves. Okay, that makes much more sense to me :)

2024-03-01 19:55 UTC, alice-i-cecile requested changes
I'm happy with the code quality, and these should exist, but we need an example demonstrating how to use these :) Simple is totally fine: I basically just want a cube, a floor, some lights and the light gizmos being toggled.

2024-03-01 20:02 UTC, alice-i-cecile commented on crates/bevy_gizmos/src/light.rs
> +                point_light.color,
Could we add a config option to set this color? Maybe a 

```rust
enum LightGizmoColor {
    Manual(Color),
    Varied,
    #[default]
    MatchLightColor,
    ByLightType,
}
```

2024-03-01 21:04 UTC, MrGVSV commented on crates/bevy_gizmos/src/light.rs
> +) where
Nit: It might be nice from an organizational/readability perspective to split these up into a function-per-light

2024-03-01 21:04 UTC, MrGVSV commented on crates/bevy_gizmos/src/primitives/dim3.rs
> +    /// `segments` should be a divider of the value passed to [`Self::base_segments`]
Do you mean `divisor`?
```suggestion
    /// `segments` should be a divisor of the value passed to [`Self::base_segments`]
```

2024-03-03 14:34 UTC, alice-i-cecile approved these changes

2024-03-03 18:12 UTC, MrGVSV approved these changes
Just one comment. Everything else looks good to me!

2024-03-03 18:12 UTC, MrGVSV commented on crates/bevy_gizmos/src/light.rs
> +    color: Option<LightGizmoColor>,
Is this supposed to be `pub`?

```suggestion
    pub color: Option<LightGizmoColor>,
```

2024-03-03 18:42 UTC, Kanabenki commented on crates/bevy_gizmos/src/light.rs
> +    color: Option<LightGizmoColor>,
It is, thanks for catching that!

2024-03-03 19:06 UTC, merged