Fix leftover references to children when despawning audio entities
bevyengine/bevy pull request #12407
Opened 2024-03-10 13:32 UTC by rparrett

# Objective

Fixes #12402

## Solution

Use `despawn_recursive` instead of `despawn` for despawning `PlaybackMode::DESPAWN` audio.

2024-03-10 13:49 UTC, rparrett commented
Not able to test this morning. Would appreciate someone making sure this works properly.

2024-03-10 14:16 UTC, alice-i-cecile requested changes
We should document this behavior in the `PlaybackMode` variant's documentation :)

2024-03-11 00:05 UTC, alice-i-cecile approved these changes

2024-03-11 07:10 UTC, james7132 approved these changes

2024-03-11 18:16 UTC, mockersf approved these changes

2024-03-11 18:32 UTC, merged