Test for `DynamicScene` reserialization
bevyengine/bevy pull request #12464
Opened 2024-03-13 22:29 UTC by mrchantey

# Objective

- Addresses #12462
- We should be able to serialize a scene, deserialize it, then serialize it again.

## Solution

- Add a (currently failing) test to check this
---

2024-03-13 22:33 UTC, alice-i-cecile commented on crates/bevy_scene/src/serde.rs
> +    fn should_reserialize() {
Can you add a link to the issue that this is a regression test for in a comment?

2024-03-13 22:33 UTC, MrGVSV commented
I think I found the fix if you want to incorporate it in this PR:

The problem is here:

https://github.com/bevyengine/bevy/blob/0e6a171313796460b78da539b729c825f0ac6b76/crates/bevy_reflect/src/serde/de.rs#L757

We need to change it to:

```rust
let variant_name = variant_info.name();
let variant_index = self
  .enum_info
  .index_of(variant_name)
  .expect("variant should exist");
dynamic_enum.set_variant_with_index(variant_index, variant_name, value);
```

2024-03-13 22:34 UTC, alice-i-cecile requested changes
Great start! Can you add a matching test in bevy_reflect to check the serialization there? Presumably that's where the actual bug is: the scene machinery is likely redundant.

2024-03-13 23:26 UTC, mrchantey commented
Awesome I added the `bevy_reflect` test, should I remove the `bevy_scene` test?

2024-03-13 23:31 UTC, MrGVSV commented on crates/bevy_reflect/src/serde/de.rs
> +    fn enum_should_be_correct_variant_on_reserialize() {
Could you actually do this with the `MyStruct` struct? We'd then have a re-serialization test for all the major reflect kinds, including enums.

2024-03-13 23:33 UTC, MrGVSV commented
> Awesome I added the `bevy_reflect` test, should I remove the `bevy_scene` test?

Yeah I think you can remove it. It would be nice to have a re-serialization test but I think the reflection test sorta makes it redundant. Maybe if there's certain behavior we want to verify re-serializes correctly, we add the test then.

But yeah as for now, I don't think it's super necessary.

2024-03-13 23:56 UTC, mrchantey commented
Okay, refactored `enum_should_reserialize` into `should_reserialize` for `MyStruct`, now getting a new error:

```
---- serde::de::tests::should_reserialize stdout ----
thread 'serde::de::tests::should_reserialize' panicked at crates\bevy_reflect\src\serde\de.rs:1449:74:
called `Result::unwrap()` on an `Err` value: Message("Unexpected missing field `renamed` in `CustomDeserialize`")
```

btw i also deduplicated the three identical `MyStruct` instantiations instead of copy-pasting a new one, let me know if that should be reverted.

2024-03-14 03:51 UTC, MrGVSV commented
> Okay, refactored `enum_should_reserialize` into `should_reserialize` for `MyStruct`, now getting a new error:
> 
> 
> 
> ```
> 
> ---- serde::de::tests::should_reserialize stdout ----
> 
> thread 'serde::de::tests::should_reserialize' panicked at crates\bevy_reflect\src\serde\de.rs:1449:74:
> 
> called `Result::unwrap()` on an `Err` value: Message("Unexpected missing field `renamed` in `CustomDeserialize`")
> 
> ```
> 
> 
> 
> Did we catch another bug? commenting out [`#[serde(rename = "renamed")]`](https://github.com/mrchantey/bevy/blob/b93a63a6bd55aed02522107a0f8c8f95227626c6/crates/bevy_reflect/src/serde/de.rs#L1123-L1124) fixes the new test.

No I think this is expected behavior. We're serializing the Rust name but saying we expect the custom name (for a user the fix would be to register `ReflectSerialize` as well, otherwise they're declaring a one-way format).

Maybe let's try changing `rename` to [`alias`](https://serde.rs/field-attrs.html#alias)? That should allow both to be used.

2024-03-14 04:39 UTC, MrGVSV approved these changes

2024-03-14 04:51 UTC, mrchantey commented
Great yep using `alias` did the trick, I can confirm the new test fails without `set_variant_with_index`.

2024-03-14 05:14 UTC, alice-i-cecile approved these changes

2024-03-14 05:15 UTC, alice-i-cecile commented
Great stuff: thanks for the contribution!

2024-03-14 05:31 UTC, merged