Make SystemInfo a Resource
bevyengine/bevy pull request #12584
Opened 2024-03-19 23:02 UTC by IceSentry

# Objective

We already collect a lot of system information on startup when possible but we don't make this information available. With the upcoming work on a diagnostic overlay it would be useful to be able to display this information.

## Solution

Make the already existing SystemInfo a Resource

---

## Changelog

Added `SystemInfo` Resource

2024-03-19 23:45 UTC, pablo-lua reviewed
Its good to have this available all the time, I just have a comment.

2024-03-19 23:45 UTC, pablo-lua commented on crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs
> +        commands.insert_resource(info);
Can we somehow do this at app build time? This way, we can use this struct in Startup without having to worry about system ordering at all.

2024-03-19 23:55 UTC, alice-i-cecile requested changes
We should be able to just initialize and log the system info using a `FromWorld` impl + `init_resource`. Like @pablo-lua says, this will allow us to dodge system ordering issues (and reduce overhead).

2024-03-20 01:47 UTC, IceSentry commented
So, I added the FromWorld impl as suggested. I'm not sure how to handle the case where sysinfo is not supported though. right now we are kinda forced to always init the resource anyway so I created one that is just `"Unknown"` for everything. We could alternatively just not init it and hope that people querying it don't use a fallible way to access it. I think this solution reduces the chances of runtime panics at the cost of having `"Unknown"` show up in the overlay.

Another issue I'm really confused about with this is that the fps_overlay example now spawns it's UI in a different order because of my changes. It's as if it's based on timing of the startup time or something like that.

2024-03-20 02:11 UTC, alice-i-cecile approved these changes
Oh you're right, we really don't need the `World` there. We can actually just get away with a `Default` impl, sorry! I'm content with the other changes: "unknown" is a sensible fallback.

2024-03-20 02:15 UTC, IceSentry commented
Here's the fix for the UI bug in the example https://github.com/bevyengine/bevy/pull/12586

I'm not entirely sure why this PR changes the spawn order but the fps_overlay ui code was wrong anyway so I don't want to look into it too much.

2024-03-20 02:44 UTC, pablo-lua approved these changes

2024-03-20 04:13 UTC, alice-i-cecile commented
@IceSentry CI failures are real this time :)

2024-03-20 05:50 UTC, IceSentry commented
Those cfg errors are really hard to detect locally 😅 

Should be good now

2024-03-20 06:36 UTC, afonsolage commented on crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs
> +pub struct SystemInfo {
```suggestion
/// A resource that stores diagnostic information about the system.
/// This information can be useful for debugging and profiling purposes.
///
/// # See also
///
/// [`SystemInformationDiagnosticsPlugin`](crate::SystemInformationDiagnosticsPlugin) for more information.
pub struct SystemInfo {
```

2024-03-20 06:37 UTC, afonsolage reviewed
Since `SystemInfo` is in a public API now, it should have some level of doc comments.

2024-03-23 01:44 UTC, james7132 approved these changes
Please fix CI.

2024-03-23 06:31 UTC, merged