Add `Tetrahedron` primitive to `bevy_math::primitives`
bevyengine/bevy pull request #12688
Opened 2024-03-24 14:41 UTC by Chubercik

<!---
# Objective

- Describe the objective or issue this PR addresses.
- If you're fixing a specific issue, say "Fixes #X".

## Solution

- Describe the solution used to achieve the objective above.

---

## Changelog

> This section is optional. If this was a trivial fix, or has no externally-visible impact, you can delete this section.

- What changed as a result of this PR?
- If applicable, organize changes under "Added", "Changed", or "Fixed" sub-headings
- Stick to one or two sentences. If more detail is needed for a particular change, consider adding it to the "Solution" section
  - If you can't summarize the work, your change may be unreasonably large / unrelated. Consider splitting your PR to make it easier to review and merge!

## Migration Guide

> This section is optional. If there are no breaking changes, you can delete this section.

- If this PR is a breaking change (relative to the last release of Bevy), describe how a user might need to migrate their code to support these changes
- Simply adding new functionality is not a breaking change.
- Fixing behavior that was definitely a bug, rather than a questionable design choice is not a breaking change.

---!>

2024-03-24 17:07 UTC, mweatherley commented
FYI, I have also already done a substantial amount of work on this; I would recommend joining us in the math-dev channel on Discord to talk about some of the things that have come up!

2024-03-24 19:37 UTC, Chubercik commented
Aw shucks, my bad 😅

I threw this PR draft out there after checking that there isn't anything that implements it in https://github.com/bevyengine/bevy/pulls, so that there is no doubling of efforts, but I guess I was too late anyway.

Should I close this PR?

2024-03-25 01:36 UTC, mweatherley reviewed
This is fairly barebones, but I'd be happy to have this as a baseline!

2024-03-25 09:50 UTC, Chubercik commented on crates/bevy_math/src/primitives/dim3.rs
> +    }
Only for the default or an additional test?

2024-03-25 10:13 UTC, Chubercik commented on crates/bevy_math/src/primitives/dim3.rs
> +    }
Not so sure, I think it'd be pretty verbose, but I'm not against it if you think it's a better solution.

For the record, I used https://en.wikipedia.org/wiki/Tetrahedron#Volume when implementing this and, indeed, forgot the absolute value 😅

2024-03-25 14:53 UTC, mweatherley commented on crates/bevy_math/src/primitives/dim3.rs
> +    }
I was thinking an additional test on the default

2024-03-25 14:53 UTC, mweatherley commented on crates/bevy_math/src/primitives/dim3.rs
> +    }
It's not particularly verbose! The determinant is just
```rust
Mat3::from_cols(ba, ca, da).determinant()
```
I don't feel that strongly about this, I just think it's more readable than the scalar triple product.

2024-03-25 15:00 UTC, Chubercik commented on crates/bevy_math/src/primitives/dim3.rs
> +    }
Oh, when you put it like that I agree, that's much better, I wasn't familiar with the `Mat3` struct and came up with this little monster:

```rust
let matrix = [
    [a.x - d.x, a.y - d.y, a.z - d.z],
    [b.x - d.x, b.y - d.y, b.z - d.z],
    [c.x - d.x, c.y - d.y, c.z - d.z],
];

let determinant = matrix[0][0] * (matrix[1][1] * matrix[2][2] - matrix[1][2] * matrix[2][1]) -
                  matrix[0][1] * (matrix[1][0] * matrix[2][2] - matrix[1][2] * matrix[2][0]) +
                  matrix[0][2] * (matrix[1][0] * matrix[2][1] - matrix[1][1] * matrix[2][0]);
```

I'll make this change shortly.

2024-03-25 15:00 UTC, Chubercik commented on crates/bevy_math/src/primitives/dim3.rs
> +    }
Coming right up!

2024-03-26 11:05 UTC, mweatherley approved these changes
Pretty happy with this! Thanks!

2024-03-26 11:07 UTC, Jondolf approved these changes
I think this looks good for an initial implementation :) We can build on this in follow-ups

2024-03-26 11:07 UTC, Jondolf commented on crates/bevy_math/src/primitives/dim3.rs
> +pub struct Tetrahedron {
This should have a `Reflect` impl [here](https://github.com/bevyengine/bevy/blob/main/crates/bevy_reflect/src/impls/math/primitives3d.rs)

2024-03-28 05:00 UTC, rodolphito requested changes

2024-03-28 10:06 UTC, mweatherley commented on crates/bevy_math/src/primitives/dim3.rs
> +                Vec3::new(0.0, 0.0, 0.5),
I think this was chosen so that, in particular, its base is the Default `Triangle3d`. I guess it does contain the origin, but only on its boundary :)

2024-03-28 10:07 UTC, mweatherley commented on crates/bevy_math/src/primitives/dim3.rs
> +        Mat3::from_cols(ab, ac, ad).determinant().abs() / 6.0
I think a separate function for signed volume is better.

2024-03-29 09:39 UTC, Chubercik commented on crates/bevy_math/src/primitives/dim3.rs
> +        Mat3::from_cols(ab, ac, ad).determinant().abs() / 6.0
What would the naming convention be? `volume_signed`?

2024-03-29 09:42 UTC, Chubercik commented on crates/bevy_math/src/primitives/dim3.rs
> +            + (ac - ab).cross(ad - ab).length())
TBH it was just me trying to cut down the number of variables in this function to the minimum, I can change it to `bc.cross(bd).length()` if you think that's better.

2024-03-29 09:53 UTC, Chubercik commented on crates/bevy_math/src/primitives/dim3.rs
> +                Vec3::new(0.0, 0.0, 0.5),
What @mweatherley said, in practice it's just `Triangle3d` base + an extra vertex on the Z-axis.

I was thinking, if we go with your suggestion would it be possible to keep the tetrahedron upright? I think that's how people typically imagine this shape to look like.

2024-04-01 17:31 UTC, NthTensor requested changes
I think the default tet should be centered on the origin. It's going to rotate strangely when people mesh it and apply transforms. I believe all other default primitives had their center of mass more or less at the origin.

2024-04-01 18:52 UTC, mweatherley commented
> I think the default tet should be centered on the origin. It's going to rotate strangely when people mesh it and apply transforms. I believe all other default primitives have their center of mass more or less at the origin.

I agree with this

2024-04-01 22:02 UTC, Chubercik commented
> I think the default tet should be centered on the origin.

I guess that decision is being lifted off my shoulders, thanks for all the reviews!

For the record, I agree, though I still feel like having this primitive remain upright (three vertices on a plane that's parallel to the `XY` plane, one vertex above) would be desirable, but would cause icky vertex coordinates (especially if going for a regular tetrahedron), which is why I was hesitant.

2024-04-01 22:07 UTC, merged

2024-06-03 20:33 UTC, alice-i-cecile commented
Thank you to everyone involved with the authoring or reviewing of this PR! This work is relatively important and needs release notes! Head over to https://github.com/bevyengine/bevy-website/issues/1295 if you'd like to help out.