Added a `pipe_map` method to the `bevy_ecs::IntoSystem` trait (#12718)
bevyengine/bevy pull request #12723
Opened 2024-03-26 01:56 UTC by papow65

# Objective

- #12718

A composition of a system that returns an `Option` with a second system that returns an `Option`. This composition skips the second system when the output of the first system is `None`. The composition runs the second system with the unwrapped output of the first system when that output is not `None`.

## Solution

- A `pipe_map` method analogous to the `pipe` method

## Question

- `pipe_map` always returns an `Option`. Would it be more useful to simply always return `()`? Or would  variants for both `Option` and `()` be useful?
-

2024-03-26 01:59 UTC, alice-i-cecile commented on crates/bevy_ecs/src/system/combinator.rs
> +/// If the outpuf of the first system is [`None`], the seconds system is nnot executed.
```suggestion
/// If the output of the first system is [`None`], the seconds system is not executed.
```

2024-03-26 02:04 UTC, alice-i-cecile commented
Honestly I kinda like this. I wasn't convinced of the utility / elegance of this initially, but seeing the examples I can see the value.

I'd like more tests, and a demo in the system piping example.

I don't think we should / need to return `Option` out of the second system though: that seems needlessly restrictive. We should be able to mirror how the existing system pipe impl works and get arbitrary length chains still right?

2024-03-26 02:15 UTC, ItsDoot approved these changes
I like the core idea. Agreed with alice's recommendations.

2024-03-26 03:33 UTC, papow65 commented
The combined system has to have the same output as the second system. Since we skip the second system when the first returns None, we have to somehow create an instance of the return type of the second system. That is possible for all **Default** types. This allows both () and Option<T> as return type of the second system.

2024-03-26 23:45 UTC, bushrat011899 requested changes
I'm definitely in favour of good combinator methods for `System`s, but I would like this API slightly changed to remove the `Default` usage.

2024-03-26 23:45 UTC, bushrat011899 commented on crates/bevy_ecs/src/system/combinator.rs
> +        a(input).map(b).unwrap_or_default()
Why not just return `Option<B::Out>` and remove the `B::Out: Default` requirement? To replicate the current behaviour, an end user could then call `sys_a.pipe_map_some(sys_b).map(Option::unwrap_or_default)`.

2024-03-27 00:51 UTC, msvbg reviewed
Please forgive the functional programming nerdiness, but it's vaguely similar to a monadic bind if `b` returns an `Option`. We then get an `Option<B::In>` from the first system and a function `B::In -> Option<B::Out>`, producing `Option<B::Out>`, which would be equivalent to Haskell's `m a -> (a -> m b) -> m b`.

Maybe `and_then` is a good name mirroring the bind from `Option`? e.g. `parse_message_system.map(Result::ok).and_then(simple_handler_system)`. Returning an `Option` should also make it compose better with for example `a.and_then(b).and_then(c)`.

2024-03-27 01:10 UTC, bushrat011899 commented
I believe the desire is for:

- `A: fn(T) -> Option<U>`
- `B: fn(U) -> V`
- `A pipe_map_some B: fn(T) -> Option<V>`

So the `B` system is "blind" to the monad provided by `A`. I think this is the preferable API, since we already have `map` for cases where `B` can take and/or produce a monad in response to the monad provided by `A`.

Because of that, I think `and_then` isn't appropriate, since that is specifically for `B: fn(U) -> Option<V>`. `map` is the Rust name for the above operation, but we're already using it for piping, so `pipe_map_some` is an acceptable compromise.

2024-03-27 02:02 UTC, alice-i-cecile commented
> [9:48 PM]Alice 🌹: My biggest concern with this is that it won't be intuitive to users
> [9:48 PM]Alice 🌹: So it won't be reached for
> [9:48 PM]Alice 🌹: Currently leaning against merging as a result
> [10:00 PM]bushRAT: I think that might be the right call. It also just occurred to me that it feels wrong that this method will be callable on systems which don't return an Option<T>, and will just cause the whole group to fail to become a system, which is a difficult error to diagnose.

Closing out as a result: if others feel strongly that this should exist, please feel free to reopen and try and convince me. If you need anything else public to make sure this is externally implementable, let us know!

2024-03-27 02:02 UTC, closed without merging