Switch to ui_test in compile fail tests.
bevyengine/bevy pull request #12810
Opened 2024-03-31 15:55 UTC by Brezak

# Objective

Make compile fail tests less likely to break with new Rust versions. Closes #12627

## Solution

Switch from [`trybuild`](https://github.com/dtolnay/trybuild) to [`ui_test`](https://github.com/oli-obk/ui_test).

## TODO

- [x] Update `bevy_ecs_compile_fail_tests`
- [ ] Update `bevy_macros_compile_fail_tests`
- [ ] Update `bevy_reflect_compile_fail_tests`

2024-04-01 17:51 UTC, Brezak commented
The pr is smaller that it seems. I had to rename a bunch of tests because ui_test wouldn't compile them.

2024-04-01 17:53 UTC, Brezak commented
I'd suggest reviewing this commit by commit. They all touch different parts of the project.

2024-04-22 19:50 UTC, BD103 requested changes
Looks good generally, though I do have a few requests.

2024-04-22 19:50 UTC, BD103 commented on crates/bevy_reflect_compile_fail_tests/tests/reflect_derive/custom_where_fail.rs
> +//~^ ERROR: expected
```suggestion
//~^ ERROR: /expected.+:/
```

I'm not sure if that's the correct way to specify Regex, but the pattern should work in the case. [View it on regex101.](https://regex101.com/r/a4lEyx/1) It basically matches `expected` exactly, then 1 or more of any character, then the `:` colon.

2024-04-22 21:16 UTC, Brezak commented on crates/bevy_ecs_compile_fail_tests/Cargo.toml
> +bevy_ecs = { path = "../bevy_ecs", version = "0.14.0-dev" }
It won't. `cargo-release` only bumps version numbers for dependencies in the workspace.

2024-04-22 22:42 UTC, BD103 commented on crates/bevy_ecs_compile_fail_tests/Cargo.toml
> +bevy_ecs = { path = "../bevy_ecs", version = "0.14.0-dev" }
Darn, that's unfortunate. Unless you can think of an automated solution, can you add a comment here:

https://github.com/bevyengine/bevy/blob/f496d2a3c3abfa7efdfd192c44214ad7e3416bae/.github/workflows/release.yml#L48-L56

I'm thinking something like:

```yml
body: |
  Preparing next release. This PR has been auto-generated.
  UI tests will not be automatically bumped to the latest version, please manually fix it.
```

2024-04-23 10:17 UTC, Brezak commented on crates/bevy_ecs_compile_fail_tests/Cargo.toml
> +bevy_ecs = { path = "../bevy_ecs", version = "0.14.0-dev" }
Added the comment. Should we instruct the person releasing, to `git commit --amend` the UI test version bumps into the release?

2024-04-23 11:32 UTC, oli-obk commented on crates/bevy_compile_test_utils/src/lib.rs
> +}
```suggestion
pub use ui_test;
```

2024-04-23 12:08 UTC, BD103 commented on crates/bevy_ecs_compile_fail_tests/Cargo.toml
> +bevy_ecs = { path = "../bevy_ecs", version = "0.14.0-dev" }
Since all PRs get squashed when they're merged, I don't think that's necessary.

2024-04-23 12:11 UTC, BD103 approved these changes
Please fix @oli-obk's suggestion, then I'm happy with this. Thanks! :D

2024-04-23 12:11 UTC, BD103 commented on .github/workflows/release.yml
> +            UI tests have not been automatically bumped to the latest version, please fix it manually.
```suggestion
            UI tests have not been automatically bumped to the latest version, please fix them manually.
```

Non-blocking grammar fixup :)

2024-04-26 11:30 UTC, oli-obk approved these changes

2024-04-27 00:00 UTC, mockersf approved these changes

2024-04-27 00:15 UTC, merged