Fixes `get_handle_path()`
bevyengine/bevy pull request #1290
Opened 2021-01-23 10:05 UTC by TheRawMeatball

Motivated on discord: https://discord.com/channels/691052431525675048/742884593551802431/802272336774299648

2021-01-23 21:07 UTC, cart commented
This does add another atomic operation (handle_to_path.write()) to a function that will get called a lot. Probably not _terrible_ but worth calling out.

We could move it into load_async() which would ensure the op happens on a separate thread, but that has the downside of making things like this not work reliably:

```rust
let handle = server.load("path"); 
server.get_handle_path(handle);
```

2021-01-24 06:23 UTC, TheRawMeatball commented
Hmm, my first instinct is to get [dashmap](https://crates.io/crates/dashmap) as a dependency - it would probably solve the performance without such a concurrency issue. It only depends on `num_cpus` and `cfg-if`, both of which already in the build tree, so I'd say its worth considering.

2021-01-25 21:58 UTC, cart commented
Hmm I'm not familiar enough with dashmap's impl to have an immediate response. Pulling in a new dependency will always require a bit more scrutiny than normal, so it would be good to evaluate a couple of things before rolling with that approach:

1. Is it really a performance improvement and if so, by how much? Imo contention should be pretty uncommon, so a simple benchmark doing a bunch of loads in a loop would resolve most of my concerns.
2. Does it affect compile times? A couple of clean compiles with/without asset server using dashmap would resolve that question.

2021-06-06 03:07 UTC, NathanSWard commented
> We could move it into load_async() which would ensure the op happens on a separate thread, but that has the downside of making things like this not work reliably

I actually don't mind this solution of moving it into `load_async`. As I could easily see a scenario where multiple parallel systems are trying to load some assets and get blocked by `.write()` call on the internal hash map. 

It's definitely a bummer that the `get_handle_path` won't work immediately, however it's a tradeoff I'm happy to take.

2021-06-06 03:10 UTC, NathanSWard commented
I was pointed to this PR via #2306 and this is a pretty glaringly missing feature.
We definitely need to support `get_handle_path` as it has use cases, and not to mention that the `AssetServer`'s internal `handle_to_path` `HashMap` is currently just wasting memory.

2021-06-06 03:10 UTC, NathanSWard requested changes

2021-06-06 03:10 UTC, NathanSWard commented on crates/bevy_asset/src/asset_server.rs
> +        id
Just as an addition to this, could we add a test to validate this behavior?

2021-06-06 14:54 UTC, NathanSWard commented
#2268 and #2306 are both blocked by this PR. 
@TheRawMeatball let me know if you want to help finalize this PR (with the last few changes) or I'm also more than happy to open another PR like this which addresses the issues haha ☺️☺️

2021-06-06 15:20 UTC, TheRawMeatball commented
Help is always appreciated :) If you want to push this PR to completion, you can open a new PR using this as a base if you want and I can close this one. I've been fairly short on time recently, so it'd probably be better.

2021-06-06 15:25 UTC, NathanSWard commented
> Help is always appreciated :) If you want to push this PR to completion, you can open a new PR using this as a base if you want and I can close this one. I've been fairly short on time recently, so it'd probably be better.

No worries! I'll probably end up making a new PR with this as a base :)

2021-06-06 16:08 UTC, NathanSWard commented
Closed in favor of #2310

2021-06-06 16:08 UTC, closed without merging