multi_threaded feature rename
bevyengine/bevy pull request #12997
Opened 2024-04-16 16:04 UTC by andristarr

# Objective

Fixes #12966

## Solution

Renaming multi_threaded feature to match snake case

2024-04-16 16:06 UTC, andristarr commented
basis-universal and the symphonia-* features seem to be package names so I suspect having kebab case there is fine?

Do we also want to rename the internal name of the packages? Not sure the exact technical term, but do we want `bevy_internal` to export `multi_threaded` or we are content with kebab case there?

2024-04-17 03:14 UTC, james7132 requested changes
All of the cfg annotations that rely on the feature should be updated too.

2024-04-17 04:46 UTC, mockersf commented
This PR only rename the feature on the bevy crate, so any use is not impacted.

But I would prefer to rename the feature in all crates for consistency.

2024-04-19 16:34 UTC, james7132 commented on crates/bevy_tasks/README.md
> +In order to be able to optimize task execution in multi_threaded environments,
This doesn't need to be changed.

2024-04-23 00:37 UTC, james7132 approved these changes

2024-04-23 20:07 UTC, mockersf commented on crates/bevy_tasks/README.md
> +- For IO-intensive work (tasks that spend very little time in a "woken" state) we have an
those changes seems unrelated

2024-04-25 17:16 UTC, andristarr commented on crates/bevy_tasks/README.md
> +- For IO-intensive work (tasks that spend very little time in a "woken" state) we have an
This is now addressed

2024-05-06 20:45 UTC, andristarr commented
@mockersf this should be ready for re-review

2024-05-06 20:49 UTC, mockersf approved these changes

2024-05-06 21:03 UTC, merged

2024-11-17 23:16 UTC, Aronry commented
Hey! I know this is probably not Github etiquette, but nonetheless I felt compelled to comment that these sorts of changes are breaking, and they cause allot of pain and suffering for people.

I know it feels good to get a green dot on the github calendar and a "pull-shark" Github badge or whatever, but this sort of stuff hurts devs and wastes work hours. "multi-threaded" was more correct anyway.