Fixed incorrect behaviour of headless_renderer depending on image dimensions
bevyengine/bevy pull request #13388
Opened 2024-05-16 11:32 UTC by bugsweeper

# Objective

- Fixes #13384 .

## Solution

- If the image became wider when copying from the texture to the buffer, then the data is reduced to its original size when copying from the buffer to the image.

## Testing

- Ran example with 1919x1080 resolution
![000](https://github.com/bevyengine/bevy/assets/17225606/47d95ed7-1c8c-4be4-a45a-1f485a3d6aa7)

2024-05-16 11:34 UTC, alice-i-cecile commented on examples/app/headless_renderer.rs
> +                    let row_bytes = img_bytes.width() as usize
```suggestion
                    // We need to ensure that this works regardless of the image dimensions
                    let row_bytes = img_bytes.width() as usize
```

2024-05-16 11:35 UTC, alice-i-cecile reviewed
Fix seems fine, but I think it would be helpful to include the context about why we're doing this in the source itself.

2024-05-16 20:04 UTC, mockersf requested changes
It doesn't work.

If I ask for an image of 1080x1080:
```
thread '<unnamed>' panicked at examples/app/headless_renderer.rs:517:49:
range end index 4320 out of range for slice of length 2560
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `headless_renderer::update`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

2024-05-17 06:57 UTC, bugsweeper commented on examples/app/headless_renderer.rs
> +                            .flat_map(|row| &row[..row_bytes])
@mockersf Thank you for your suggestion!

2024-05-17 07:20 UTC, bugsweeper commented
Looks like problem of 1080x1080 was in last row, which somehow is reminder of division by aligned_row_bytes. I cut off remaining row, this reinsurance works well alone, but i will keep them both.

2024-05-17 07:43 UTC, bugsweeper commented
@mockersf May I ask you for review?

2024-05-19 00:14 UTC, mockersf approved these changes

2024-05-19 00:30 UTC, merged