Set ambient_intensity to 0.0 in volumetric_fog example
bevyengine/bevy pull request #13531
Opened 2024-05-27 08:42 UTC by GitGhillie

# Objective

- Fixes #13521

## Solution

Set `ambient_intensity` to 0.0 in volumetric_fog example.

I chose setting it explicitly over changing the default in order to make it clear that this needs to be set depending on whether you have an `EnvironmentMapLight`. See documentation for `ambient_intensity` and related members.

## Testing

- Run the volumetric_fog example notice how the light shown in #13521 is not there anymore, as expected.

2024-05-27 10:33 UTC, GitGhillie commented
Doc correction based on https://discord.com/channels/691052431525675048/743663924229963868/1244563147814338615

2024-05-27 13:51 UTC, alice-i-cecile commented on examples/3d/volumetric_fog.rs
> +            ambient_intensity: 0.0,
```suggestion
            // This value is explicitly set to 0 since we have no environment map light
            ambient_intensity: 0.0,
```

2024-05-27 13:51 UTC, alice-i-cecile requested changes
Left a suggestion to call this out in the example too, then this LGTM.

2024-05-27 15:18 UTC, tychedelia approved these changes

2024-05-28 05:47 UTC, JMS55 commented on crates/bevy_pbr/src/volumetric_fog/mod.rs
> +    /// If there's no environment map light, set this to 0.
Can we link to [\`EnvironmentMapLight\`] here?

2024-05-28 07:24 UTC, GitGhillie commented
Linked to [`EnvironmentMapLight`] and went ahead and fixed the preceding links to it as well. It does feel a bit verbose with the `crate::environment_map::` but I guess that's normal(?)

2024-05-28 11:11 UTC, merged