Implement motion vectors and TAA for skinned meshes and meshes with morph targets.
bevyengine/bevy pull request #13572
Opened 2024-05-30 05:04 UTC by pcwalton

This is a revamped version of #9902. Instead of adding more bind group layouts as that patch did, which created a combinatorial explosion of layouts, this patch unconditionally adds `prev_joint_matrices` and `prev_morph_weights` bindings to the shader bind groups. These add no significant overhead if unused because we simply bind dummy buffers, and the driver strips them out if unused. We already do this extensively with the various `StandardMaterial` bindings as well as the mesh view bindings, so this approach isn't anything new.

The overall technique consists of double-buffering the joint matrix and morph weights buffers, as most of the previous attempts to solve this problem did. The process is generally straightforward. Note that, to avoid regressing the ability of mesh extraction, skin extraction, and morph target extraction to run in parallel, I had to add a new system to rendering, `set_mesh_motion_vector_flags`. The comment there explains the details; it generally runs very quickly.

I've tested this with modified versions of the `animated_fox`, `morph_targets`, and `many_foxes` examples that add TAA, and the patch works. To avoid bloating those examples, I didn't add switches for TAA to them.

Addresses points (1) and (2) of #8423.

## Changelog

### Fixed

* Motion vectors, and therefore TAA, are now supported for meshes with skins and/or morph targets.

2024-05-30 05:27 UTC, aevyrie approved these changes
Closes an important gap in bevy, very little added code, this is largely documentation - the code quality here is great. The simplifying assumptions here w.r.t. the buffers seems well justified. All-in-all this should be pretty uncontroversial.

2024-05-30 06:02 UTC, JMS55 requested changes
LGTM minus some general nits, and pending tracy comparisons on a large many_foxes run.

EDIT: Please also update the doc comments in taa/mod.rs talking about skinned/morph support.

2024-05-30 06:02 UTC, JMS55 commented on crates/bevy_pbr/src/render/morph.rs
> +    // Swap buffers. We need to keep the previous frame's buffer around for the
I think your way is a bit cleaner, but this is how I did it in my PR https://github.com/JMS55/bevy/blob/3334d0bd5ff643f54a605672a70d05b6b271b455/crates/bevy_pbr/src/render/morph.rs#L93-L110. Can't remember why they look different off the top of my head.

2024-05-30 06:27 UTC, pcwalton commented
This is approximately a 3%-4% regression in CPU time of `main_opaque_pass_3d` of `many_foxes` with 10,000 foxes.

CPU 13th Gen Intel(R) Core(TM) i9-13900H
GPU NVIDIA GeForce RTX 4070 Laptop GPU
![Screenshot 2024-05-29 225937](https://github.com/bevyengine/bevy/assets/157897/165f349b-74b5-406d-84b4-76785ccaf508)

Mac mini, M2
![Screenshot 2024-05-29 231740](https://github.com/bevyengine/bevy/assets/157897/ce78b089-2682-4a68-af1b-fe3e32c278b0)

I'd argue that this small regression is worth it.

2024-05-30 06:30 UTC, pcwalton commented on crates/bevy_pbr/src/render/mesh.rs
> +        let prev_skin = skins_uniform.prev_buffer.buffer().unwrap_or(skin);
I didn't think there was any kind of rule against binding a read-only buffer twice. I can see problems with read-write buffers, but read-only seems always fine. It's extremely common for textures, so I don't see why it wouldn't be for buffers...

2024-05-30 06:38 UTC, pcwalton commented on crates/bevy_pbr/src/prepass/prepass.wgsl
> -    // Use vertex_no_morph.instance_index instead of vertex.instance_index to work around a wgpu dx12 bug.
I just tried with the Direct3D 12 backend and it works fine. I guess whatever the issue was is now fixed.

2024-05-30 13:50 UTC, alice-i-cecile commented on crates/bevy_pbr/src/prepass/prepass.wgsl
> +    // Compute the motion vector, for TAA. For this we need to know where the
```suggestion
    // Compute the motion vector, e.g. for TAA. For this we need to know where the
```

2024-05-30 19:24 UTC, pcwalton commented on crates/bevy_pbr/src/render/mesh.rs
>          /// The mesh had a transform last frame and so is eligible for TAA.
Done

2024-05-30 19:24 UTC, pcwalton commented on crates/bevy_pbr/src/render/mesh.rs
>          const HAVE_PREVIOUS_TRANSFORM = 1 << 2;
Renamed

2024-05-30 19:25 UTC, pcwalton commented on crates/bevy_pbr/src/prepass/prepass.wgsl
> +    // Compute the motion vector, for TAA. For this we need to know where the
I said "for TAA among other purposes"

2024-05-31 04:53 UTC, pcwalton commented
The regression is somewhat worse--13% or so for `main_opaque_pass_3d`--on my slower box:
CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
GPU: NVIDIA GeForce RTX 2060
![Screenshot 2024-05-30 214741](https://github.com/bevyengine/bevy/assets/157897/e879cf3a-b2ac-4f61-8807-18b0c70caa94)

Frame time is a 5.73% regression: 
![Screenshot 2024-05-30 215220](https://github.com/bevyengine/bevy/assets/157897/03435ff6-e1b9-4969-8b00-d1ff13347728)

I still think we should take this regression as this is still not very large and this is a stress test. Most games won't see this kind of regression.

2024-05-31 07:05 UTC, pcwalton commented
This version of the patch should eliminate the regression by only including the bindings for views with motion vectors.

2024-05-31 16:52 UTC, JMS55 approved these changes
I think we're technically doing a double pipeline compile here, one the first frame you add a skinned entity when it doesn't yet have a previous skin buffer entry, and then a second pipeline the next frame when it does.

I'm ok with that though, we can always improve it later.

2024-05-31 17:23 UTC, merged

2024-06-03 20:48 UTC, alice-i-cecile commented
Thank you to everyone involved with the authoring or reviewing of this PR! This work is relatively important and needs release notes! Head over to https://github.com/bevyengine/bevy-website/issues/1326 if you'd like to help out.