Implemented GizmoPrimitive2d for `Arc2d`, `CircularSegment`, `CircularSector`.
bevyengine/bevy pull request #13610
Opened 2024-05-31 17:23 UTC by Olle-Lukowski

# Objective

Fixes #13606.

## Solution

Added the missing trait impls.

## Testing

- Updated the render_primitives example, and it works.

2024-05-31 21:42 UTC, mweatherley commented
If you look at the example, you'll see that the new gizmos rotate in the opposite direction than the existing ones do. I don't think this is ultimately your fault; there is actually an orientation reversal bug in `arc_2d_inner`, which causes the `arc_2d` to behave incorrectly. I'm pretty sure this is because of [this](https://github.com/bevyengine/bevy/blob/ce46d52536d16089c91181686e6c6bdf282d4016/crates/bevy_gizmos/src/arcs.rs#L132):

```rust
fn arc_2d_inner(
    direction_angle: f32,
    arc_angle: f32,
    radius: f32,
    resolution: usize,
) -> impl Iterator<Item = Vec2> {
    (0..resolution + 1).map(move |i| {
        let start = direction_angle - arc_angle / 2.;

        let angle = start + (i as f32 * (arc_angle / resolution as f32));
        Vec2::from(angle.sin_cos()) * radius
    })
}
```

This is a quite subtle bug: it seems that the fact that the X-axis maps onto the Y-axis because of `sin_cos` was understood, but the fact that this reverses orientation actually causes the arcs to render in the wrong place. You can see this by tinkering with the `2d_gizmos` example as well.

If you like, I think you can fix this by using (cos(angle + pi/2), sin(angle + pi/2)) instead of (sin(angle), cos(angle)). This will assuredly break the `Capsule2d` gizmo, though. At any rate, the code you actually wrote seems correct to me modulo this bug that isn't your fault.

2024-05-31 21:47 UTC, mweatherley commented
Actually, upon further examination, the documentation says that the angle is clockwise, so I guess it's appropriate for you to just negate the angle you use in that case :) 

(This choice is incredibly bizarre to me.)

2024-05-31 21:56 UTC, mweatherley requested changes
(Just holding off for the angles to be negated now.)

2024-06-01 11:43 UTC, alice-i-cecile approved these changes

2024-06-01 11:59 UTC, mweatherley approved these changes

2024-06-01 12:45 UTC, merged