Adding skybox to motion_blur example
bevyengine/bevy pull request #13671
Opened 2024-06-04 15:22 UTC by andristarr

Fixes #13632

2024-06-04 15:24 UTC, alice-i-cecile commented on CREDITS.md
> -* hecs
Swapping the list style here mostly seems like noise. Can you revert this?

2024-06-04 15:25 UTC, alice-i-cecile commented on CREDITS.md
> +- SkyBox Anime Sky from [Paul](https://sketchfab.com/paul_paul_paul)
```suggestion
- [SkyBox Anime Sky](https://sketchfab.com/3d-models/free-skybox-anime-sky-56a60c1d1e8b44eabff138374f996d8f) from [Paul](https://sketchfab.com/paul_paul_paul)
```

2024-06-04 15:31 UTC, andristarr commented
> I like the choice of sky box, although AI-generation will be controversial even for test assets. CC-BY is a fine license.

I can look for some other one if its prefered. Let me know what you think.

2024-06-04 15:33 UTC, alice-i-cecile commented
Everything else being equal, let's look for a different one. Criteria for me are a) human-made b) permissively licensed c) pretty d) mostly sky

2024-06-05 06:39 UTC, aevyrie commented
Ideally we would also have an envmap, so the lighting matches the skybox. You can use https://github.com/pcwalton/gltf-ibl-sampler-egui to generate skyboxes and specular/diffuse envmaps from `hdr` skyboxes you find online.

2024-06-06 21:47 UTC, aevyrie commented
These should be compressed - see the readme on the pisa envmap in tree.
They should also be organized to match existing envmaps, there is already a directory that specifically stores envmaps.

2024-06-06 21:48 UTC, aevyrie requested changes
These should be compressed - see the readme on the pisa envmap in tree.
They should also be organized to match existing envmaps, there is already a directory that specifically stores envmaps.
Also, this should probably involve some of the rendering SMEs, quite a bit of discussion went into selecting the currently added envmaps, so it would be good to make sure it's on their radar.

Subjectively, this skybox is a bit ugly. We will be forced to keep assets small, so we may want to stick to skyboxes with low frequency detail only, e.g. no clouds, to avoid ugly pixelation.

2024-06-11 14:27 UTC, andristarr commented
@aevyrie  can you tag someone from the said experts please? It would probably be beneficial if they give their input regarding picking a skybox then.

2024-06-11 17:49 UTC, aevyrie commented
Hopefully I got this right: @superdump @pcwalton @JMS55

2024-06-12 06:45 UTC, superdump commented
Could we use existing skybox and environment map textures in the repository to avoid having to add new ones? Having large binary files in the repository should have good motivation and if we already have something then maybe we don’t need to add more.

2024-06-12 13:03 UTC, alice-i-cecile commented
The motivation for this issue is that the existing assets are kind of ugly and don't work well for this particular case. @aevyrie can say more about what's lacking. 

In general, I'd really like to move towards using nicer assets for our examples: they're the first thing people see and it's hard to disentangle "ugly/broken asset" from "ugly/broken engine".

2024-06-16 12:39 UTC, andristarr commented
To try to push this forward: with the currents assets (10 megs including all the files) it looks like the following:

https://github.com/bevyengine/bevy/assets/25829992/7e99e1df-393b-40d2-b839-d834c2973da7

I will move them to the env maps folder so they sit together.

Let me know what you think

2024-06-17 06:00 UTC, aevyrie commented
Unfortunately, 10 Mb is likely too large to be in tree, but that is not my call to make. Not sure what the limits or alternatives are.

As for the skybox itself, I would personally prefer we go with something lower detail, like other engines.

I have two issues with the skybox chosen here

1. The fidelity isn't great, and doesn't leave a good impression with me. The highlights are blown out and hue shifted, and the clouds have a sort of dirty appearance. A photoreal skybox like this is likely always going to look terrible once it has been compressed down to an acceptable size to live in tree.
2. The aesthetic doesn't seem to fit with the general feel of bevy. I'm not an authority here at all, this is my impression. Given the sort of "friendly" cartoony vibe of the logo and aesthetic elsewhere, I assume that when the org has the resources, it will be commissioning stylized assets, rather than photoreal ones? This is complete vibes-based speculation on my part though!

To give more a more concrete suggestion, if we are going to add a better default skybox, it should probably be something similar to other engines:

Fyrox
![image](https://github.com/bevyengine/bevy/assets/2632925/4bb39b91-09a5-43e1-8a8e-afd6155b98ad)
Unity
![image](https://github.com/bevyengine/bevy/assets/2632925/24356734-51c2-4427-8410-5d750dfd927b)
Godot
![](https://docs.godotengine.org/en/stable/_images/tuto_3d8.png)

2024-06-17 23:21 UTC, IceSentry commented
I agree a default sandbox like that would be better, but for the motion blur example, I'd would prefer a skybox with more stuff in it so you can actually see the blur. Otherwise we don't need to add one to that example.

2024-06-18 15:33 UTC, andristarr commented
> I agree a default skybox like that would be better, but for the motion blur example, I'd would prefer a skybox with more stuff in it so you can actually see the blur. Otherwise we don't need to add one to that example.

I agree with the the statement here. I was searching for free to use hdri skyboxes that would be potentially better in low res but I couldn't find one.

I am open for suggestions as I think it would look better with a nicer environment for this example.

2024-06-30 20:08 UTC, andristarr commented
I tried to create some skyboxes but none of them were able to jump the bare minimum of being acceptable so I am looking for input about this.

2024-07-14 01:48 UTC, pcwalton commented
If you want to save space, try:
* making the diffuse version smaller -- it's very blurry, you can safely shrink it down
* using the specular part as the skybox. I know this is not correct, but it usually looks all right and it saves a lot of space. We do this in one of our examples.

2024-07-14 01:49 UTC, pcwalton reviewed
If you want to save space, try:

* making the diffuse version smaller -- it's very blurry, you can safely shrink it down
* using the specular part as the skybox. I know this is not correct, but it usually looks all right and it saves a lot of space. We do this in one of our examples.

2026-05-21 10:45 UTC, ChristopherBiscardi commented
A number of things have changed since the introduction of this PR, including atmosphere support, and the bevy_asset_files repo. https://github.com/bevyengine/bevy_asset_files

Adding a skybox is still a possibility but would likely look different in a 0.19+ world.

2026-05-21 10:45 UTC, closed without merging