Re-name and Extend Run Conditions API
bevyengine/bevy pull request #13784
Opened 2024-06-09 21:10 UTC by CupOfTeaJay

# Objective

- My attempt at fulfilling #13629.

## Solution

Renames the `and_then` / `or_else` run condition methods to `and` / `or`, respectively.

Extends the run conditions API to include a suite of binary logical operators:
- `and`
- `or`
- `nand`
- `nor`
- `xor`
- `xnor`

## Testing

- Did you test these changes? If so, how?
    - The test **run_condition_combinators** was extended to include the added run condition combinators. A **double_counter**      system was added to test for combinators running on even count cycles.

- Are there any parts that need more testing?
    - I'm not too sure how I feel about the "counter" style of testing but I wanted to keep it consistent. If it's just a unit test I would prefer simply to just assert `true` == _combinator output_ or `false` == _combinator output_ .

- How can other people (reviewers) test your changes? Is there anything specific they need to know?
    - Nothing too specific. The added methods should be equivalent to the logical operators they are analogous to (`&&` , `||`, `^`, `!`).

- If relevant, what platforms did you test these changes on, and are there any important ones you can't test?
    - Should not be relevant, I'm using Windows.

---

## Changelog

> This section is optional. If this was a trivial fix, or has no externally-visible impact, you can delete this section.

- What changed as a result of this PR?
    - The run conditions API.

- If applicable, organize changes under "Added", "Changed", or "Fixed" sub-headings
    - Changed:
        - `and_then` run condition combinator renamed to simply `and`
        - `or_else` run condition combinator renamed to simply `or`
    - Added:
        - `nand` run condition combinator.
        - `nor` run condition combinator.
        - `xor` run condition combinator.
        - `xnor` run condition combinator.

## Migration Guide

> This section is optional. If there are no breaking changes, you can delete this section.

- If this PR is a breaking change (relative to the last release of Bevy), describe how a user might need to migrate their code to support these changes
    - Search and replace all uses of the `and_then` run condition method with the `and` run condition method.
    - Search and replace all uses of the `or_else` run condition method with the `or` run condition method.

2024-06-09 21:27 UTC, alice-i-cecile requested changes
Can you add `and_then` and `or_else` back, marking them as deprecated and calling the renamed methods in them? That will make migrations a bit easier for users and we can remove it right after it gets into a release.

I much prefer these names though, and the other logical combinations are useful enough.

2024-06-09 21:29 UTC, CupOfTeaJay commented
> Can you add `and_then` and `or_else` back, marking them as deprecated and calling the renamed methods in them? That will make migrations a bit easier for users and we can remove it right after it gets into a release.
> 
> I much prefer these names though, and the other logical combinations are useful enough.

Yes - will do

2024-06-09 22:15 UTC, alice-i-cecile approved these changes

2024-06-09 22:26 UTC, jnhyatt approved these changes

2024-06-10 08:58 UTC, andresovela commented on crates/bevy_ecs/src/schedule/condition.rs
> +        let name = format!("!({} ^ {})", a.name(), b.name());
```suggestion
        let name = format!("({} ^ {})", a.name(), b.name());
```

2024-06-10 13:57 UTC, merged

2024-06-10 17:09 UTC, JoJoJet commented
I don't think we should rename these. The `then` keyword is intentionally used here to draw attention to the fact that these combinators short-circuit, which can already lead to surprising behavior when it causes systems to skip runs and retain old change ticks

2024-06-10 17:16 UTC, alice-i-cecile commented
While that's an important fact about how these work, I don't think this naming convention was doing a good job conveying this information to users. As evidenced by the fact that users regularly asked "why is it called `and_then`", and answerers didn't point to "oh that's because it's short-circuiting".

IMO we should use clear, simple names, and explain this behavior better in documentation and other learning material.