Added peeking to EventReader
bevyengine/bevy pull request #13809
Opened 2024-06-11 18:57 UTC by BobG1983

Added peekability to EventReader for when you want to view an event but not mark it as read

# Objective

- Allow the ability to view an event without marking it as read

## Solution

- Copied the existing iterators and implemented them for peeking, ie. they no longer move the "last_read" onwards.
- I also took this opportunity to improve the documentation on EventReader given I was adding explanations for peeking.

## Testing

- Wrote a number of tests to confirm that the new peek iterators work as expected. Renamed a bunch of the existing tests to specify they test read and wrote peek equivalents. Also wrote tests for combination of reading and peeking to make sure behavior was as expected.

---

2024-06-11 19:01 UTC, BobG1983 commented
No idea why the MacOS build fails given I didn't touch those files at all?

2024-06-11 23:58 UTC, BobG1983 commented
The issue is that par_read doesn't mark events as seen like read which I assumed it did, I ended up rewriting the tests to validate that behavior. Which par_read then failed.

It looks like this has always been the behavior of par_read

2024-06-13 21:59 UTC, BobG1983 commented
Added the fix to #13821 to this pull request too given I'm going to squash the files and tests associated with it.

2024-06-14 10:52 UTC, mnmaita reviewed
Cool feature and great additions to documentation! Leaving a few nits and suggestions in doc comments.

2024-06-14 10:52 UTC, mnmaita commented on crates/bevy_ecs/src/event/reader.rs
> +    /// [`EventReader::read_with_id()`], [`EventReader::peek_with_id()`] etc. and [`EventReader::is_empty()`]
```suggestion
    /// [`EventReader::read_with_id()`], [`EventReader::peek_with_id()`], etc. and [`EventReader::is_empty()`]
```

2024-06-14 10:52 UTC, mnmaita commented on crates/bevy_ecs/src/event/reader.rs
> +    /// Returns a parallel iterator over the events this [`EventReader`] has not read.
```suggestion
    /// Returns a parallel iterator over the events this [`EventReader`] has not read yet.
```

2024-06-14 10:52 UTC, mnmaita commented on crates/bevy_ecs/src/event/peek_iterators.rs
> +    /// Iterate over only the events.
```suggestion
    /// Iterate over the events only.
```
(Unsure if this is correct though, it just sounds better to me)

2024-06-14 10:52 UTC, mnmaita commented on crates/bevy_ecs/src/event/mod.rs
> +            // Peek does not consume events put should still advance the iterator
```suggestion
            // Peek does not consume events but should still advance the iterator
```

2024-06-14 10:52 UTC, mnmaita commented on crates/bevy_ecs/src/event/read_iterators.rs
> +            // If we get to hear we're guaranteed to have seen all events
Left a suggestion for this comment [here](https://github.com/bevyengine/bevy/pull/13836#discussion_r1639621894).

2024-06-15 18:52 UTC, BD103 commented
I'm marking this as blocked by #13836. Once that gets merged and this gets enough reviews, this can be merged :)

2024-06-17 12:01 UTC, kristoff3r requested changes

2024-06-17 18:18 UTC, BobG1983 commented on crates/bevy_ecs/src/event/mod.rs
> +        // Peek iter should not remove events
I think it’s important for a test to capture the intent to catch future changes like that. I’d prefer to keep the test.

2024-06-17 18:20 UTC, BobG1983 commented on crates/bevy_ecs/src/event/reader.rs
> +    pub fn peek_with_id(&mut self) -> EventPeekIteratorWithId<'_, E> {
Removed.

2024-06-17 18:20 UTC, BobG1983 commented on crates/bevy_ecs/src/event/reader.rs
> +    pub fn par_peek(&mut self) -> EventPeekParIter<'_, E> {
Removed.

2024-06-17 18:24 UTC, BobG1983 commented
@BD103 I wouldn’t say this is blocked. In fact. This has the fix in it already so if this is merged the other PR doesn’t need to be.

2024-06-17 18:50 UTC, BobG1983 commented
Failed because of a formatting requirement that I can’t really fix on my phone. Will take a look tomorrow.

2024-06-18 06:46 UTC, kristoff3r approved these changes

2024-06-18 15:26 UTC, BD103 commented
> @BD103 I wouldn’t say this is blocked. In fact. This has the fix in it already so if this is merged the other PR doesn’t need to be.

I would prefer we split it up into two different PRs, but I'll defer to maintainers on this. :)

2024-06-18 16:07 UTC, BobG1983 commented
Only reason I included it in here is because I squash the existing iterator file anyway.

2024-06-24 17:47 UTC, BobG1983 commented
This branch is now stacked on top of https://github.com/bevyengine/bevy/pull/13818

2024-07-14 19:54 UTC, alice-i-cecile commented
Completed in https://github.com/bevyengine/bevy/pull/13820

2024-07-14 19:54 UTC, closed without merging