use Display for entity id in log_components
bevyengine/bevy pull request #14164
Opened 2024-07-05 19:58 UTC by hymm

# Objective

- Cleanup a doubled `Entity` in log components

```
// Before
2024-07-05T19:54:09.082773Z  INFO bevy_ecs::system::commands: Entity Entity { index: 2, generation: 1 }:["bevy_transform::components::transform::Transform"]

// After
2024-07-05T19:54:09.082773Z  INFO bevy_ecs::system::commands: Entity 2v1: ["bevy_transform::components::transform::Transform"]
```

2024-07-05 20:47 UTC, mnmaita approved these changes

2024-07-05 22:41 UTC, janhohenheim requested changes

2024-07-05 22:41 UTC, janhohenheim commented on crates/bevy_ecs/src/system/commands/mod.rs
> +    info!("Entity {}: {:?}", entity, debug_infos);
```suggestion
    info!("Entity {entity}: {debug_infos:?}");
```

2024-07-07 14:09 UTC, MiniaczQ approved these changes

2024-07-08 01:25 UTC, merged