Make state methods panic on missing `StatePlugin`
bevyengine/bevy pull request #14238
Opened 2024-07-09 13:55 UTC by MiniaczQ

# Objective

- Fixes: #14237

## Solution

- As described in the issue

## Testing

- Ran the example from the issue
![image](https://github.com/bevyengine/bevy/assets/13040204/9d10fa26-2d8e-42bb-b631-fe113fb01516)

2024-07-10 08:56 UTC, benfrankel requested changes
Small PR, one nit.

2024-07-10 08:56 UTC, benfrankel commented on crates/bevy_state/src/app.rs
>  /// Separate function to only warn once for all state installation methods.
```suggestion
/// Helper function to panic if [`StatesPlugin`] is not installed.
```
Or other wording that makes this comment not outdated.

2024-07-10 19:41 UTC, benfrankel approved these changes

2024-07-10 21:32 UTC, mockersf commented
Could you check the stack trace, and how easy it is to find where the issue comes from? Could `track_caller` helps?

Also, what does it mean to "install" a plugin? I prefer the error message from https://github.com/bevyengine/bevy/pull/14160

2024-07-10 21:34 UTC, mockersf commented
I would also prefer to not have a hard dependency on the plugin, but on what it's adding. If someone decides to rewrite the plugin changing a few things but still setting up all the machinery, it should still work

2024-07-12 14:03 UTC, MiniaczQ commented
> I would also prefer to not have a hard dependency on the plugin, but on what it's adding. If someone decides to rewrite the plugin changing a few things but still setting up all the machinery, it should still work. #14160 is better for that

Agree to disagree, most of the machinery is in the `app` methods. `StatePlugin` only adds `StateTransitions` to startup and main schedules and register the core state set. The only valid use case for swapping just the plugin would be to remove `StateTransitions` from startup, which doesn't sound bad, but can cause 3rd party crates to work incorrectly if they relied on this.

2024-07-12 14:31 UTC, MiniaczQ commented
> Could you check the stack trace, and how easy it is to find where the issue comes from? Could `track_caller` help?

I think it's plenty readable as is:
![image](https://github.com/user-attachments/assets/4d267eb2-5df3-4d9a-95a1-241934124902)

With `[track_caller]`:
![image](https://github.com/user-attachments/assets/7fdd59c9-a81d-4735-b9b0-3ccb210aeb37)

2024-07-12 16:05 UTC, janhohenheim approved these changes

2024-07-14 15:57 UTC, alice-i-cecile approved these changes

2024-07-14 15:58 UTC, alice-i-cecile commented
> I would also prefer to not have a hard dependency on the plugin, but on what it's adding. If someone decides to rewrite the plugin changing a few things but still setting up all the machinery, it should still work. #14160 is better for that

In addition to the feedback above; this will also be much harder to maintain. I don't think we have a clear / stable enough set of invariants to make this feasible right now.

2024-07-15 15:27 UTC, mnmaita reviewed
Is this still relevant now that https://github.com/bevyengine/bevy/pull/14160 was merged? @alice-i-cecile

2024-07-15 15:27 UTC, mnmaita commented on crates/bevy_state/src/app.rs
> +/// Helper function to panic if [`StatesPlugin`] is not installed.
This could read something like (based on the PR comments):
```rs
/// Helper function to panic if [`StatesPlugin`] is not added to the `App`.
```

2024-07-15 15:27 UTC, mnmaita commented on crates/bevy_state/src/app.rs
> +fn panic_if_no_states_plugin_installed(app: &SubApp) {
You could also rename this to `panic_if_no_states_plugin_added`

2024-07-15 15:35 UTC, closed without merging

2024-07-15 15:35 UTC, alice-i-cecile commented
I'd like to avoid panics unless absolutely essential, and I think that #14160 is an adequate solution to this problem. Closing.