Add support for environment map transformation
bevyengine/bevy pull request #14290
Opened 2024-07-12 14:18 UTC by Soulghost

# Objective

- Fixes: https://github.com/bevyengine/bevy/issues/14036

## Solution

- Add a world space transformation for the environment sample direction.

## Testing

- I have tested the newly added `transform` field using the `clearcoat` example. 
- By combining with the [Add support for skybox transformation](https://github.com/bevyengine/bevy/pull/14267), we can rotate both the skybox and the environment light map to achieve the correct rendering effect.
```rust
 /// Spawns a camera with associated skybox and environment map.
 fn spawn_camera(commands: &mut Commands, asset_server: &AssetServer) {
+    let environment_rotation = Quat::from_rotation_y(PI * 0.125);
+
     commands
         .spawn(Camera3dBundle {
             camera: Camera {
@@ -224,11 +226,13 @@ fn spawn_camera(commands: &mut Commands, asset_server: &AssetServer) {
         .insert(Skybox {
             brightness: 5000.0,
             image: asset_server.load("environment_maps/pisa_specular_rgb9e5_zstd.ktx2"),
+            rotation: environment_rotation,
         })
         .insert(EnvironmentMapLight {
             diffuse_map: asset_server.load("environment_maps/pisa_diffuse_rgb9e5_zstd.ktx2"),
             specular_map: asset_server.load("environment_maps/pisa_specular_rgb9e5_zstd.ktx2"),
             intensity: 2000.0,
+            rotation: environment_rotation,
         });
 }
```

### Original

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/83fcb6d7-9605-43cc-ab90-d5b23ac8d1f8">

### Rotate by 22.5 degrees around the Y-axis

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/0409b593-fc1a-49ea-b79a-2a77ca5d3479">

## Migration Guide

- Since we have added a new filed to the `EnvironmentMapLight` struct, users will need to include `..Default::default()` or some rotation value in their initialization code.

2024-07-14 14:59 UTC, alice-i-cecile commented on crates/bevy_pbr/src/light_probe/environment_map.rs
> +    /// The rotation of the environment light map
Nit: Documenting how this rotation is applied would be useful to reduce trial-and-error here.

2024-07-14 15:02 UTC, alice-i-cecile commented on crates/bevy_pbr/src/light_probe/environment_map.wgsl
> +        irradiance_sample_dir = (environment_map_uniform.transform * vec4(irradiance_sample_dir, 1.0)).xyz;
A comment here (and below) would be useful to make this math easier to follow.

2024-07-14 15:02 UTC, alice-i-cecile commented on crates/bevy_pbr/src/light_probe/mod.rs
> +pub struct EnvironmentMapUniform {
Documentation please: this is a public type.

2024-07-14 15:04 UTC, alice-i-cecile requested changes
Useful feature, but I'd like to see more documentation and a use of this in an example to make it easier to test.

2024-07-15 16:29 UTC, Azorlogh commented
I think the rotation is backward compared to the other skybox rotation PR:

This is what I get when the skybox & env maps share the same rotation (notice we see what's in front of us in the reflection instead of what's behind)

https://github.com/user-attachments/assets/634a2194-f327-4612-b75f-00396be6c4b4

2024-07-16 10:01 UTC, Soulghost commented
> I think the rotation is backward compared to the other skybox rotation PR:
> 
> This is what I get when the skybox & env maps share the same rotation (notice we see what's in front of us in the reflection instead of what's behind)
> 
>  1721060695.mp4

Yes, I have reproduced this bug using a debug texture, which more clearly illustrates this issue:
![panorama_image](https://github.com/user-attachments/assets/0a7ab40b-41f7-43cc-9b3d-2c5f023f76b5)

The result indicates that the skybox and the environment map are rotated in opposite directions:
<img width="1281" alt="image" src="https://github.com/user-attachments/assets/9b42ac19-2e93-4114-aa7f-135cc44bbc34">

I found some clues here: "Cube maps are left-handed so we negate the z coordinate" (https://www.khronos.org/opengl/wiki/Cubemap_Texture)
```wgsl
@fragment
fn skybox_fragment(in: VertexOutput) -> @location(0) vec4<f32> {
    let ray_direction = coords_to_ray_direction(in.position.xy, view.viewport);

    // Cube maps are left-handed so we negate the z coordinate.
    let out = textureSample(skybox, skybox_sampler, ray_direction * vec3(1.0, 1.0, -1.0));
    return vec4(out.rgb * uniforms.brightness, out.a);
}
```

For the skybox cubemap, we rotate the ray in a right-handed view space coordinate, while for the environment map, we rotate it in a right-handed world space coordinate. However, there appears to be a difference between these two types of cubemaps. I will do some research to figure it out.

2024-07-16 10:34 UTC, Soulghost commented
I've identified the issue: In the environment map, I initially inverted the z before transforming, which placed the transformation in a left-handed coordinate system. I should transform first, like with the skybox, and then invert the z. 😄

2024-07-16 12:26 UTC, Hexorg commented
Great catch!

2024-07-17 13:04 UTC, alice-i-cecile approved these changes

2024-07-17 18:19 UTC, Azorlogh approved these changes

2024-07-18 02:14 UTC, Soulghost commented
There appears to be some binding errors for the `alien_cake_addict` example, let me check where the problem is.

2024-07-18 10:19 UTC, Soulghost commented on crates/bevy_pbr/src/render/mesh_view_bindings.rs
> +        Some(environment_map_binding),
Will exit if no `EnvironmentMapLight ` is present in the scene, need to implement a fallback uniform for the `environment_map_binding`

2024-07-19 08:51 UTC, Soulghost commented
@alice-i-cecile @Azorlogh I apologize for the mistake that led to the mismatch of the mesh view bindings. I should have conducted more thorough testing before submiting these changes. I have now resolved all the issues and tested numerous examples. Below is a summary of the code changes.

1. The `EnvironmentMapUniform` should be configured as a per-view buffer, therefore I have modified the uniform to use a dynamic offset. We also need to include the `ViewEnvironmentMapUniformOffset` in all the associated `ViewNode`s and `RenderCommand`s.
    ```rust
    uniform_buffer::<EnvironmentMapUniform>(true).visibility(ShaderStages::FRAGMENT)
    ```

2. Some of the camera may not contain a `EnvironmentMapLight`, so we need to fallback to a default binding for the `EnvironmentMapUniform`
    ```rust
    fn gather_environment_map_uniform(
        view_query: Extract<Query<(Entity, Option<&EnvironmentMapLight>), With<Camera3d>>>,
        mut commands: Commands,
    ) {
        for (view_entity, environment_map_light) in view_query.iter() {
            let environment_map_uniform = if let Some(environment_map_light) = environment_map_light {
                EnvironmentMapUniform {
                    transform: Transform::from_rotation(environment_map_light.rotation)
                        .compute_matrix()
                        .inverse(),
                }
            } else {
                EnvironmentMapUniform::default()
            };
            commands
                .get_or_spawn(view_entity)
                .insert(environment_map_uniform);
        }
    }
    ```

3. Changing the binding number in `mesh_view_bindings.wgsl` and `mesh_view_bindings.rs` is insufficient; the tone mapping LUT bindings also required adjustment. Since these numbers are injected through shader definitions, they are easily overloooked. **This is the root cause of this issue**.
    ```rust
    #define_import_path bevy_core_pipeline::tonemapping_lut_bindings
    
    @group(0) @binding(#TONEMAPPING_LUT_TEXTURE_BINDING_INDEX) var dt_lut_texture: texture_3d<f32>;
    @group(0) @binding(#TONEMAPPING_LUT_SAMPLER_BINDING_INDEX) var dt_lut_sampler: sampler;
    ```
    
    ```
    diff --git a/crates/bevy_pbr/src/render/mesh.rs b/crates/bevy_pbr/src/render/mesh.rs
    index 8432cbd97..282b116e9 100644
    --- a/crates/bevy_pbr/src/render/mesh.rs
    +++ b/crates/bevy_pbr/src/render/mesh.rs
    @@ -1765,11 +1765,11 @@ impl SpecializedMeshPipeline for MeshPipeline {
                 shader_defs.push("TONEMAP_IN_SHADER".into());
                 shader_defs.push(ShaderDefVal::UInt(
                     "TONEMAPPING_LUT_TEXTURE_BINDING_INDEX".into(),
    -                20,
    +                21,
                 ));
                 shader_defs.push(ShaderDefVal::UInt(
                     "TONEMAPPING_LUT_SAMPLER_BINDING_INDEX".into(),
    -                21,
    +                22,
                 ));
    ```

2024-07-19 15:00 UTC, alice-i-cecile approved these changes

2024-07-19 15:18 UTC, merged