Using Cas instead of CAS #14341
bevyengine/bevy pull request #14357
Opened 2024-07-17 06:08 UTC by Cioraz

# Objective

- Replacing CAS with Cas in CASPlugin

## Solution

- Simple replace

2024-07-17 06:50 UTC, mockersf approved these changes

2024-07-17 06:52 UTC, mockersf commented
this doesn't close #14341, there are other types using `CAS` instead of `Cas`: found `DenoiseCAS`, `CASUniform`, `CASNode`, `CASPipeline`, `CASPipelineKey`, `ViewCASPipeline` with a quick search.

Could you also change those?

2024-07-17 09:46 UTC, mockersf commented on crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/mod.rs
> +/// Applies a contrast adaptive sharpening (Cas) filter to the camera.
in doc it should stay CAS

2024-07-17 11:45 UTC, janhohenheim requested changes

2024-07-17 11:45 UTC, janhohenheim commented on crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/mod.rs
> +                    // Cas Settings
```suggestion
                    // CAS Settings
```

2024-07-20 18:02 UTC, mockersf approved these changes

2024-07-20 18:28 UTC, merged