`Trigger::entity()` only returns valid entities
bevyengine/bevy pull request #14558
Opened 2024-07-31 16:28 UTC by SarthakSingh31

# Objective

Fixes #14236 

## Solution

Made `Trigger::entity()` panic on `Entity::PLACEHOLDER` and added a `Trigger::get_entity()`

---

## Migration Guide

Anyone using `Trigger::entity()` should switch to `Trigger::get_entity()` unless they know that the event will always be triggered on an entity.

2024-07-31 16:50 UTC, DasLixou commented
This has itched me when reading the release docs. But isn't `Entity::PLACEHOLDER` allowed to exist? The docs don't deny it.
What about a real `Option<Entity>` from the beginning?

2024-08-05 23:56 UTC, alice-i-cecile requested changes
I'm nervous about all of our options here. Panicking is Very Bad, returning dummy entities is a silly footgun, and returning an option that always has to be unwrapped is frustrating.

In the spirit of #14275 / #12660, I'd prefer to store / return an `Option` here over adding a panic, but I'm interested in @janhohenheim / @benfrankel / @james7132's opinions too.

2024-08-06 00:01 UTC, janhohenheim commented
Ping @MiniaczQ who I know has thoughts about this

2024-08-06 00:07 UTC, janhohenheim requested changes

2024-08-06 00:07 UTC, janhohenheim commented on crates/bevy_ecs/src/observer/mod.rs
> +                "called `Trigger::entity()` when the target entity was a `Entity::PLACEHOLDER`."
This message does not help a user, as they will mostly not interact with `Entity::PLACEHOLDER` and probably got this panic while trying to get the entity of a globally triggered observer. Add a hint to this like "Did you try [...]? There is no associated entity in that case."

This comment is also valid for the `# Panics` documentation, which should mention under which circumstances an underlying `Entity` would be a placeholder.

2024-08-06 00:07 UTC, janhohenheim commented on crates/bevy_ecs/src/observer/mod.rs
> +    /// Returns the entity that triggered the observer, if it's not a placeholder entity.
```suggestion
    /// Returns the entity that triggered the observer, if it's not [`Entity::PLACEHOLDER`].
```

2024-08-06 00:07 UTC, janhohenheim commented on crates/bevy_ecs/src/observer/mod.rs
> +                    .unwrap_or_default()
```suggestion
                    .get_entity()
                    .is_some_and(|entity| query.get(entity).is_ok())
```

2024-08-06 00:07 UTC, janhohenheim commented on examples/ecs/observer_propagation.rs
> +            info!("Attack hit {}", name);
```suggestion
            info!("Attack hit {name}");
```

2024-08-06 00:14 UTC, janhohenheim commented
@alice-i-cecile my own preference in a vacuum would be to make `entity()` return an `Option` and force unwraps.

The general consensus there is that we should not break pre-established naming conventions, so respecting that, the recommendation becomes to only add `get_entity`. 
The general consensus *then* is that forcing `Option`s is bad because we do not have good error handling built in. Good error handling is possible, but it currently requires the user to use `anyhow` and create their own `error` logging function that works with `anyhow::Error`.
As such, respecting the general vibe from the discussion in https://github.com/bevyengine/bevy/issues/14275, my recommendation ultimately becomes allowing both APIs and changing `get_entity` to return a `Result` instead of an `Option`.

2024-08-06 00:22 UTC, benfrankel commented
Agreed with @janhohenheim, in that `entity() -> Result` would be ideal, but `entity() -> Entity` vs. `get_entity() -> Result` is the consistent option for now. I have an extension trait in my own code that provides `get_entity()` and I unwrap it with `r!(trigger.get_entity())` from `tiny_bail`, and I'm happy with this personally.

2024-08-06 00:22 UTC, MiniaczQ commented
No strong opinion here.
Definitely need a method that returns `Option<Entity>`, whether it's `entity()` or `get_entity()` depends solely on decision in https://github.com/bevyengine/bevy/issues/14275 / https://github.com/bevyengine/bevy/issues/12660

2024-08-06 06:46 UTC, DasLixou commented
I wonder if we could always show `get_entity` returning an `Option<Entity>` but then having a generic thing on the observer which indicates that this should only run when an entity was targeted and then enable an `entity()` function.

2024-09-03 02:28 UTC, NthTensor commented
My 2C here is that this is a silly problem that we have created for ourselves, and which we can solve by changing the problem.

Why can't we have a `Trigger<T>` and `TriggerEntity<T>`, and let the user statically indicate whether they need an entity or not. Then `trigger()` will only be dispatched to the former, and `trigger_targets()` will be dispatched to both. I suggest this because, in my experience so far, there do not seem to be many cases where the entity is really optional; either you want the entity, or you don't.

A slightly less controversial option might be to make `Trigger::entity()` return `Option<Entity>` and `TriggerEntity::entity()` return `Entity`.

2024-09-03 02:42 UTC, benfrankel commented
Related: https://github.com/bevyengine/bevy/issues/14272 and https://github.com/bevyengine/bevy/issues/14843.

2024-10-08 15:11 UTC, alice-i-cecile commented
@SarthakSingh31 are you planning on completing this PR?

2024-10-08 19:58 UTC, NthTensor commented
Should be re-evaluated in the context of https://github.com/bevyengine/bevy/pull/15698. This could just be `Trigger<Event, (), Entity>`.

I will also say, the use-case for target-less observers seems small.

2024-10-08 21:03 UTC, MiniaczQ commented
> I will also say, the use-case for target-less observers seems small.

I use "targetless" observers for state transition events.
Targetless cost us nothing as it's just targeted at `Entity::PLACEHOLDER`, the point is just to have a slightly better API than comparing to this entity.

2025-05-03 11:00 UTC, closed without merging