issue #14569 - added example in the crate docs
bevyengine/bevy pull request #14741
Opened 2024-08-14 10:52 UTC by Nihilistas

# Objective

fixes #14569

## Solution

added an .md file with the code example and included it inside the top-level bevy_diagnostic crate doc.

## Testing

I tested locally on my laptop in a web browser. Looked fine. You are able to collapse the whole "intro" part of the doc to get to the links sooner (for those who may think that including the example code here is annoying to scroll through)

I would like people to run ```cargo doc```  and go the bevy_diagnostic page to see if they have any issues or suggestions.

---

## Showcase

<img width="1067" alt="Screenshot 2024-08-14 at 12 52 16" src="https://github.com/user-attachments/assets/70b6c18a-0bb9-4656-ba53-c416f62c6116">

2024-08-14 20:06 UTC, BD103 commented
Is there a specific reason you created a separate markdown file for the example, instead of just including it directly into `lib.rs`?

2024-08-14 20:39 UTC, Nihilistas commented
I assumed there may be further examples of usage in the future, so I made
it file-per-example to not bloat the lib.rs

On Wed 14. Aug 2024 at 22:07, BD103 ***@***.***> wrote:

> Is there a specific reason you created a separate markdown file for the
> example, instead of just including it directly into lib.rs?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bevyengine/bevy/pull/14741#issuecomment-2289775485>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQUIR2EEJRAL5JOPP5MHOYTZRO2GRAVCNFSM6AAAAABMQCTNLSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOBZG43TKNBYGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-08-15 14:12 UTC, alice-i-cecile requested changes
I prefer the simpler, more local organization. We can split it out later if we run into problems. Docs look good though, so once this is moved into lib.rs this has my approval.

2024-08-15 16:11 UTC, alice-i-cecile commented on Cargo.toml
> +# Copy this file to `config.toml` to speed up your builds.
This shouldn't be here :)

2024-08-15 16:11 UTC, alice-i-cecile commented
Sure, an example works well too 👍🏽

2024-08-15 16:15 UTC, Nihilistas commented on Cargo.toml
> +# Copy this file to `config.toml` to speed up your builds.
my bad

2024-08-15 18:42 UTC, alice-i-cecile commented on crates/bevy_diagnostic/src/lib.rs
> +//!This crate provides a straightforward solution for integrating diagnostics in the [Bevy game engine](https://bevyengine.org/).
IMO we should leave this file unchanged: the example is enough.

2024-08-15 18:42 UTC, alice-i-cecile requested changes
Sorry for nitpicking on organization 😅

2024-08-15 20:08 UTC, Nihilistas commented
> Sorry for nitpicking on organization 😅

all good.

2024-08-15 20:31 UTC, alice-i-cecile approved these changes

2024-08-15 20:40 UTC, BD103 approved these changes
Looks good, thanks!

2024-08-15 21:11 UTC, merged