SystemParamBuilder - Allow deriving a SystemParamBuilder struct when deriving SytemParam.
bevyengine/bevy pull request #14818
Opened 2024-08-19 18:39 UTC by chescock

# Objective

Allow `SystemParamBuilder` implementations for custom system parameters created using `#[derive(SystemParam)]`.  

## Solution

Extend the derive macro to accept a `#[system_param(builder)]` attribute.  When present, emit a builder type with a field corresponding to each field of the param.  

## Example

```rust
#[derive(SystemParam)]
#[system_param(builder)]
struct CustomParam<'w, 's> {
    query: Query<'w, 's, ()>,
    local: Local<'s, usize>,
}

let system = (CustomParamBuilder {
    local: LocalBuilder(100),
    query: QueryParamBuilder::new(|builder| {
        builder.with::<A>();
    }),
},)
    .build_state(&mut world)
    .build_system(|param: CustomParam| *param.local + param.query.iter().count());
```

2024-08-24 13:44 UTC, alice-i-cecile requested changes
Looks reasonable, but needs to be documented in a user facing way :) Probably in the `SystemParam` and system param builder docs?

2024-08-24 15:38 UTC, cBournhonesque approved these changes
awesome

2024-08-28 17:51 UTC, chescock commented
> Looks reasonable, but needs to be documented in a user facing way :) Probably in the `SystemParam` and system param builder docs?

I added docs to the `SystemParam` trait near the rest of the `#[derive(SystemParam)]` docs.  

I think the `SystemParamBuilder` docs need a larger rewrite to mention the new features from this and the other PRs, so I'd like to try to do that as a separate PR.  I should also update the [list of system params](https://docs.rs/bevy/latest/bevy/ecs/system/index.html#system-parameter-list) in the module level docs with a section for params that only make sense when building a system.

2024-08-28 18:24 UTC, alice-i-cecile approved these changes

2024-08-28 18:41 UTC, merged