Change parameter type of `InitTriInfo` to prevent underflow panic
bevyengine/bevy pull request #14893
Opened 2024-08-23 14:30 UTC by kumikaya

# Objective

- Fix #14874

## Solution

- Changed the type of `iNrTrianglesIn` in the `bevy_mikktspace::generated::InitTriInfo` function signature from `usize` to `i32`.
- This change was made because other functions like `DegenPrologue` and `Build4RuleGroups` also use i32 for triangle counts.
- This ensures that negative values are handled gracefully, avoiding `panic` due to underflow when `iNrTrianglesIn` is zero.

## Testing

- After the fix, the following code runs successfully without any panic.

```rust
use bevy::prelude::Mesh;
use bevy_render::{
    mesh::{Indices, PrimitiveTopology},
    render_asset::RenderAssetUsages,
};

const POSITIONS: &[[f32; 3]] = &[[0.0, 1.0, 0.0], [0.0, 0.0, 0.0], [0.0, 1.0, 0.0]];

const NORMALS: &[[f32; 3]] = &[[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]];

const INDICES: &[u32] = &[0, 1, 2];

const UVS: &[[f32; 2]] = &[[0.0, 1.0], [0.0, 0.0], [0.0, 1.0]];

fn main() {
    let mut mesh = Mesh::new(
        PrimitiveTopology::TriangleList,
        RenderAssetUsages::default(),
    );

    mesh.insert_attribute(Mesh::ATTRIBUTE_POSITION, POSITIONS.to_vec());
    mesh.insert_attribute(Mesh::ATTRIBUTE_UV_0, UVS.to_vec());
    mesh.insert_attribute(Mesh::ATTRIBUTE_NORMAL, NORMALS.to_vec());
    mesh.insert_indices(Indices::U32(INDICES.to_vec()));
    mesh.generate_tangents().unwrap();

}

```

## Migration Guide

- No breaking changes introduced.

2024-08-23 14:39 UTC, janhohenheim commented
Note that this will add a merge conflict to https://github.com/bevyengine/bevy/pull/9050

2024-08-23 15:07 UTC, alice-i-cecile approved these changes

2024-08-23 16:49 UTC, janhohenheim reviewed
I'm honestly not convinced that the code in question *should* run smoothly. That mesh seems whacky and bound to cause problems down the line. @ethereumdegen's offending mesh was similarly malformed. Do we at learn print a `warn!` in this case?

2024-08-23 16:53 UTC, janhohenheim commented on crates/bevy_mikktspace/src/generated.rs
> +        iNrTrianglesIn as i32,
Isn't the data type inferred to be `i32` already? If not, what is the data type and why does the line number 255 exactly do when going below 0?

2024-08-23 16:53 UTC, janhohenheim commented on crates/bevy_mikktspace/src/generated.rs
> +    let mut pEdges = vec![SEdge::zero(); (iNrTrianglesIn as usize) * 3];
I assume safety checks happened before this line?

2024-08-23 16:54 UTC, ethereumdegen commented
> I'm honestly not convinced that the code in question *should* run smoothly. That mesh seems whacky and bound to cause problems down the line. @ethereumdegen's offending mesh was similarly malformed. Do we at least print a `warn!` in this case?


It doesnt have to run smoothly it can throw an error from the result 

But it shouldnt crash the entire program

2024-08-23 16:58 UTC, ethereumdegen commented
Yeah my pr is about generate_tangents not mesh new
On Fri, Aug 23, 2024 at 12:57 PM Jan Hohenheim ***@***.***>
wrote:

> Mesh::new doesn't return a result. Am I missing something?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bevyengine/bevy/pull/14893#issuecomment-2307468229>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABPVWL5TC4ZJQW3TZYDS7OTZS5SXXAVCNFSM6AAAAABNAJSJFSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMBXGQ3DQMRSHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-08-23 16:59 UTC, janhohenheim commented
@ethereumdegen Ooooooh I see, I didn't scroll down enough on the example code, haha. That makes sense then :)

2024-08-23 17:10 UTC, kumikaya commented
Maybe it would be more appropriate to change the place where a panic occurs from `t < iNrTrianglesIn - 1` to `t + 1 < iNrTrianglesIn`.

2024-08-23 17:20 UTC, janhohenheim requested changes
@kumikaya I would prefer it if there was no panic at all, and instead `generate_tangents` returned an error in this case.
Also, no need to force push your commits to clean the history; the PR get squashed anyways and by leaving the history intact you make it easier for future readers :)

2024-08-23 17:32 UTC, kumikaya commented
@janhohenheim Yeah, it would be better to check if `iNrTrianglesIn` is zero and return false after `iNrTrianglesIn = iTotTris - iDegenTriangles`, but I'm not quite sure at which point it would be best to return; thanks for your advice.

2024-08-23 17:55 UTC, janhohenheim commented
@kumikaya feel free to ping me when the code you posted in the PR description results in `generate_tangents` returning an `Err` variant :)

2024-08-24 04:29 UTC, kumikaya commented
@janhohenheim I've updated the code in the PR

2024-08-24 06:50 UTC, janhohenheim approved these changes
Looks good to me then :)
Thanks for fixing the crash!

2024-08-25 14:28 UTC, merged