Add helper methods on `Visibility`
bevyengine/bevy pull request #14898
Opened 2024-08-23 21:14 UTC by ThomasAlban

Add various helper methods on `Visibility`, such as conversions between `Visibility` and `bool`, and toggling `Visibility`. 

The methods are:

- `from_bool_inherited(value: bool) -> Self`
    - Returns `Visibility::Inherited` if true, else returns `Visibility::Hidden`.
- `to_bool_inherited(self) -> bool`
    - Returns `true` if `self` is `Visibility::Visible` or `Visibility::Inherited`, else returns `false`.
- `toggle_inherited(&mut self)`
    - If `self` is `Visibility::Hidden`, sets it to `Visibility::Inherited`. Otherwise, sets it to `Visibility::Hidden`.
- `from_bool_unconditional(value: bool) -> Self`
    - Returns `Visibility::Visible` if true, else returns `Visibility::Hidden`.
- `to_bool_unconditional(self) -> bool`
    - Returns `true` if `self` is `Visibility::Visible`, else returns `false`.
- `toggle_unconditional(&mut self)`
    - If self is `Visibility::Visible`, sets it to `Visibility::Hidden`. Otherwise, sets it to `Visibility::Visible`.
 

There was a previous PR (which got merged and reverted) to address the issue of converting between `Visibility` and `bool`, however this was confusing because it did it by implementing `From` and `TryFrom` which introduces many footguns. 

With this approach, I believe the methods are clear in their naming of how exactly the conversion/toggle will work. 

Since toggling visibility and converting between `Visibility` and `bool` are common operations in bevy, I believe it's important to supply methods to make code conciser - saving people from having to write if statements everywhere!

2024-08-23 21:26 UTC, ThomasAlban commented
I don't know why my commits from a previous PR which was merged are also included here, but they don't affect the files changed as it was merged anyway 🙄 github fail

2024-08-23 21:28 UTC, ickshonpe commented
> I don't know why my commits from a previous PR which was merged are also included here, but they don't affect the files changed as it was merged anyway 🙄 github fail

yeah happens to me all the time 😅

2024-08-23 21:57 UTC, ickshonpe reviewed
`to_bool_` and `from_bool_` don't seem very idiomatic, `is_` and `if_` would make more sense I think.

2024-08-23 21:57 UTC, ickshonpe commented on crates/bevy_render/src/view/visibility/mod.rs
> +    pub fn to_bool_inherited(self) -> bool {
I'm not sure about the naming scheme. `to_bool_inherited` doesn't feel very intuitive, `visibility != Visibility::Hidden` seems much clearer.

2024-08-23 21:57 UTC, ickshonpe commented on crates/bevy_render/src/view/visibility/mod.rs
> +    pub fn to_bool_unconditional(self) -> bool {
I don't think i'd ever be able to remember with confidence what `to_bool_unconditional` did without looking at the docs.
```pub fn is_unconditionally_visible(self) -> bool {``` would be better maybe? 
But neither seems as readable `visibility == Visibility::Visible` really.

2024-08-23 22:36 UTC, ThomasAlban commented
Converted to draft as I feel like there is room for improvement here

2024-08-23 22:42 UTC, janhohenheim commented
Imo these methods do not have clear naming for an outsider and are nonetheless on the verge of being verbose enough that I would probably personally prefer a manual `matches!`.

2024-08-23 22:43 UTC, ThomasAlban commented
from discussion on bevy discord, how about this instead:
```rust
toggle_inherited_visible()
toggle_inherited_hidden()
toggle_visible_hidden()
```
these methods toggle between the 2 states in the name

2024-08-23 22:49 UTC, ThomasAlban commented
Yeah this problem is quite hard to solve but I'm determined to find a solution which covers at least some common use cases. I initially thought my wording was quite clear but from what you guys have said it seems to need work! Let me know what you think of the above suggestion (suggested by bestRanar on bevy discord)

2024-08-23 22:59 UTC, janhohenheim commented
@ThomasAlban assuming that these functions simply ignore the variant that is not being toggled, I think those are good :) I can see myself using them!
Btw, that would be @rparrett on GitHub

2024-08-23 23:06 UTC, ThomasAlban commented
The Perhaps to bool methods should be removed in favour of simply doing a `matches!` statement or something, but Methods to convert from bool to visibility in some way would be particularly useful to me in my codebase. Does anyone have any alternate ideas on naming for these methods?

2024-08-23 23:14 UTC, janhohenheim commented
@ThomasAlban agreed that those two would be the most useful ones. Maybe `Visibility::inherited_if` and `Visibility::visible_if`?

2024-08-24 11:26 UTC, janhohenheim approved these changes
I think this is alright now. Good job gradually improving the PR :)

2024-08-24 11:32 UTC, alice-i-cecile requested changes
I like the toggle methods, but the `if` family of methods seems both very niche and challenging to read. If you cut those from here I'll approve and merge this.

2024-08-24 11:41 UTC, ThomasAlban commented
@alice-i-cecile In my codebase there are loads of places where I have to do
```rust
if value {
    Visibility::Visible
} else {
    Visibility::Hidden
}
```
And it would be so nice if it could be cut down to a single function call such as what I proposed.
Are there any changes that could be made to the naming etc that would improve them for you?
If it's a definite no, I'll remove them :)

2024-08-24 12:11 UTC, janhohenheim commented
Can confirm that I have also seen that pattern crop up a few times. I personally don't use it much because I tend to make my `UiNode` explicitly visible or invisible through events, but I think this is a valid use-case.

2024-08-24 13:35 UTC, alice-i-cecile commented
IMO the `if` pattern is much more readable, sorry!

2024-08-24 13:42 UTC, alice-i-cecile approved these changes
Great, thank you <3

2024-08-24 14:06 UTC, merged