Updated `LogPlugin::filter` Documentation wtih Performance Warning
bevyengine/bevy pull request #14984
Opened 2024-08-30 02:20 UTC by bushrat011899

# Objective

- Fixes #14966

## Solution

- Added a _Performance_ section to the documentation for `LogPlugin::filter` explaining that long filter strings can degrade performance and to instead rely on `LogPlugin::level` when possible.

## Testing

- CI passed locally.

2024-08-30 02:26 UTC, lewiszlw approved these changes

2024-08-30 06:27 UTC, Elabajaba approved these changes

2024-08-30 19:10 UTC, mockersf requested changes
the linked issue doesn't say anything about long filter string, and the way to fix this is by enabling the features to set the max log level

2024-08-30 22:05 UTC, bushrat011899 commented
> the linked issue doesn't say anything about long filter string, and the way to fix this is by enabling the features to set the max log level

Apologies for the misunderstanding and thanks for the clarification! I've moved the performance section of the documentation to the `LogPlugin` itself with a link to the [compile time filters](https://docs.rs/log/#compile-time-filters) section of `log`'s documentation, and included an example line for an end-user's `cargo.toml`.

2024-08-31 03:25 UTC, BD103 approved these changes

2024-09-03 00:48 UTC, alice-i-cecile approved these changes

2024-09-03 01:03 UTC, merged