Split OrthographicProjection::default into 2d & 3d (Adopted)
bevyengine/bevy pull request #15073
Opened 2024-09-07 00:08 UTC by Azorlogh

Adopted PR from dmlary, all credit to them! https://github.com/bevyengine/bevy/pull/9915

Original description:

# Objective

The default value for `near` in `OrthographicProjection` should be different for 2d & 3d.

For 2d using `near = -1000` allows bevy users to build up scenes using background `z = 0`, and foreground elements `z > 0` similar to css. However in 3d `near = -1000` results in objects behind the camera being rendered. Using `near = 0` works for 3d, but forces 2d users to assign `z <= 0` for rendered elements, putting the background at some arbitrary negative value.

There is no common value for `near` that doesn't result in a footgun or usability issue for either 2d or 3d, so they should have separate values.

There was discussion about other options in the discord [0](https://discord.com/channels/691052431525675048/1154114310042292325), but splitting `default()` into `default_2d()` and `default_3d()` seemed like the lowest cost approach.

Related/past work https://github.com/bevyengine/bevy/issues/9138, https://github.com/bevyengine/bevy/pull/9214, https://github.com/bevyengine/bevy/pull/9310, https://github.com/bevyengine/bevy/pull/9537 (thanks to @Selene-Amanita for the list)

## Solution

This commit splits `OrthographicProjection::default` into `default_2d` and `default_3d`.

## Migration Guide

- In initialization of `OrthographicProjection`, change `..default()` to `..OrthographicProjection::default_2d()` or `..OrthographicProjection::default_3d()`

Example:
```diff
--- a/examples/3d/orthographic.rs
+++ b/examples/3d/orthographic.rs
@@ -20,7 +20,7 @@ fn setup(
         projection: OrthographicProjection {
             scale: 3.0,
             scaling_mode: ScalingMode::FixedVertical(2.0),
-            ..default()
+            ..OrthographicProjection::default_3d()
         }
         .into(),
         transform: Transform::from_xyz(5.0, 5.0, 5.0).looking_at(Vec3::ZERO, Vec3::Y),
```

2024-09-07 10:33 UTC, janhohenheim requested changes
Makes sense to me :) I would like to not add API without documentation, otherwise this looks good.

2024-09-07 10:33 UTC, janhohenheim commented on crates/bevy_core_pipeline/src/core_2d/camera_2d.rs
>  impl Default for Camera2dBundle {
There's an outdated comment a few lines above this:
```rust
    /// Note: default value for `OrthographicProjection.near` is `0.0`
    /// which makes objects on the screen plane invisible to 2D camera.
    /// `Camera2dBundle::default()` sets `near` to negative value,
    /// so be careful when initializing this field manually.
```

2024-09-07 10:33 UTC, janhohenheim commented on crates/bevy_render/src/camera/projection.rs
> +    pub fn default_2d() -> Self {
Could you add your PR motivation to this function as a description?

2024-09-07 10:33 UTC, janhohenheim commented on crates/bevy_render/src/camera/projection.rs
> +    pub fn default_3d() -> Self {
Could you add your PR motivation to this function as a description?

2024-09-07 10:33 UTC, janhohenheim commented on crates/bevy_render/src/camera/projection.rs
> +            area: Rect::new(-1.0, -1.0, 1.0, 1.0),
```suggestion
            near: -1000.0,
            ..OrthographicProjection::default_3d()
```
to reduce duplication

2024-09-07 13:33 UTC, Azorlogh commented
@janhohenheim Thanks for the review! I removed the outdated comment & added docs to `default_2d` & `default_3d`. Let me know if they're clear enough

2024-09-07 15:14 UTC, janhohenheim approved these changes
Looks good now, thanks! Left some minor documentation suggestions, but nothing blocking :)

2024-09-07 15:14 UTC, janhohenheim commented on crates/bevy_render/src/camera/projection.rs
> +    /// Returns the default orthographic projection in a 2d context.
```suggestion
    /// Returns the default orthographic projection for a 2D context.
```

2024-09-07 15:14 UTC, janhohenheim commented on crates/bevy_render/src/camera/projection.rs
> +    /// render the scene when using positive z coordinates for foreground elements.
```suggestion
    /// render the scene when using positive z coordinates to order foreground elements.
```

2024-09-07 15:14 UTC, janhohenheim commented on crates/bevy_render/src/camera/projection.rs
> +    /// Returns the default orthographic projection in a 3d context.
```suggestion
    /// Returns the default orthographic projection for a 3D context.
```

2024-09-08 09:38 UTC, IQuick143 approved these changes
Would it make sense for Default to default to default_3d (like FromWorld does)?

2024-09-08 13:05 UTC, Azorlogh commented
> Would it make sense for Default to default to default_3d (like FromWorld does)?

It would defeat the point, since beginners would keep writing
```
OrthographicProjection {
    scaling_mode: ScalongMode::FixedVertical(2.0),
    ..default()
}
```
on their 2d cameras, ending up with a black screen.
With this PR they're forced to make the choice

2024-09-09 16:07 UTC, merged