Fix screenshot example
bevyengine/bevy pull request #15094
Opened 2024-09-08 08:52 UTC by akimakinai

# Objective

I noticed some issues in `screenshot` example:
1. Cursor icon won't return from `SystemCursorIcon::Progress` to default icon, even though screen shot saving is done.
2. Panics when exiting window: ``called `Result::unwrap()` on an `Err` value: NoEntities("bevy_ecs::query::state::QueryState<bevy_ecs::entity::Entity, bevy_ecs::query::filter::With<bevy_window::window::Window>>")``

## Solution

1. Caused by cursor updating system not responding to [`CursorIcon` component removal](https://github.com/bevyengine/bevy/blob/5cfcbf47ed386515adefe80f99f8e8f7e7f3ce5a/examples/window/screenshot.rs#L38). I believe it should, so change it to react to `RemovedComponents<CursorIcon>`. (a suggestion)
2. Use `get_single` for window.

## Testing

- run screenshot example

2024-09-08 16:58 UTC, alice-i-cecile approved these changes
Good fixes, thank you!

2024-09-08 17:58 UTC, janhohenheim requested changes
Looks nearly ready, thanks! I'd appreciate if you could use an observer here, so we don't have to fix this usage of `RemovedComponents` when we deprecate it :)

2024-09-08 17:58 UTC, janhohenheim commented on crates/bevy_render/src/view/window/cursor.rs
> +    mut icon_removed: RemovedComponents<CursorIcon>,
'RemovedComponents` is on the chopping block. Could you replace this with an `OnRemove` observer?

2024-09-08 19:34 UTC, eero-lehtinen approved these changes

2024-09-09 11:32 UTC, janhohenheim approved these changes

2024-09-09 16:24 UTC, alice-i-cecile commented
@akimakinai it looks like I didn't resolve merge conflicts fully correctly in the web UI: there's an unused import. When you get a chance can you fix this locally and push the changes? Once that's done I'll merge this in.

2024-09-09 17:12 UTC, merged