The Cooler 'Retain Rendering World'
bevyengine/bevy pull request #15320
Opened 2024-09-19 23:24 UTC by Trashtalk217

- Adopted from #14449
- Still fixes #12144.

2024-09-20 01:26 UTC, ecoskey requested changes
tiny nitpick, otherwise lgtm unless there's significant changes since the last pr

2024-09-20 01:26 UTC, ecoskey commented on crates/bevy_render/src/extract_component.rs
> +/// data, but won't remove the corresponding entity in the render world.
```suggestion
/// data, but won't remove the corresponding component in the render world.
```

2024-09-20 04:32 UTC, JMS55 commented
It's kinda unfortunate that all my previous comments can't be easily viewed with this new PR. What wasn't implemented/changed that I suggested?

2024-09-20 22:54 UTC, Trashtalk217 commented
@JMS55 The things I didn't adress are:
- "Should'nt we modify the clusterizer system to store RenderEntity on Clusters directly, instead of using another query here?"
- Mystery two lines in crates/bevy_pbr/src/lib at line 423 and 424
- What happened with crates/bevy_sprite/src/mesh2d/mesh.rs ?
- Footgun regarding adding SyncRenderWorld to spatial entities.
- Shrinking the size of `pending` in world_sync.rs
- Is recursive despawn appropriate for despawning unsynced entities? (again in world_sync)

The files you didn't review were:
- crates/bevy_pbr/src/render/light.rs
- crates/bevy_ui/src/render/mod.rs

2024-09-21 12:50 UTC, Trashtalk217 commented
> Mystery two lines in crates/bevy_pbr/src/lib at line 423 and **424**
```rust
        render_app.world_mut().observe(add_light_view_entities);
        render_app.world_mut().observe(remove_light_view_entities);
```
The first observer adds `LightViewEntities` to an extracted light, while the second observer despawns the entity if its `LightViewEntities` is removed. This plays into the `crates/bevy_pbr/src/render/light.rs` machinery, which in all honesty I also haven't found the time to fully understand it.

2024-09-21 18:49 UTC, Trashtalk217 commented
I've looked at the code again to write the migration guide and I've noticed two things:
1. The reverse `MainEntity` mapping is not used currently. It could be removed, but it might be usefull for users. Unsure of what to do.
2. I'm worried about the `SyncToRenderWorld` having to be added to everything you want to extract using the `ExtractComponentPlugin`. This might affect the general user base (not just the people messing around with rendering internals), so I'm thinking about using an observer to add `SyncToRenderWorld` automatically every time an extracted component is added.

2024-09-22 04:07 UTC, hymm approved these changes
Mostly just nits. I did make some comments for some things that should be investigated for perf, but those can be done in followup prs.

2024-09-22 04:29 UTC, hymm commented
It's probably worth it to remove `MainEntity` unless there's a better reason to keep it. There probably a measurable cost to it, since the temp render entities now need to move that data every frame, rather than just moving from the empty archetype.

2024-09-22 16:25 UTC, Trashtalk217 commented on crates/bevy_render/src/pipelined_rendering.rs
> +/// |---------------------------------------------------------------------------|
I feel like it does since it is a distinct phase that's relevant for extraction.

2024-09-22 16:30 UTC, Trashtalk217 commented on crates/bevy_render/src/world_sync.rs
> +    records: Vec<EntityRecord>,
This seems like a minor improvement at best and it would have to be benchmarked. Punting this to a potential follow-up PR.

2024-09-22 16:35 UTC, Trashtalk217 commented on crates/bevy_render/src/world_sync.rs
> +pub struct SyncToRenderWorld;
Similar thing to what I said before, it's a perf improvement I don't have time for right now. Maybe a follow-up PR, but not now.

2024-09-22 16:47 UTC, Trashtalk217 commented on crates/bevy_pbr/src/render/light.rs
> +            while light_entities.len() < 6 * (offset + 1) {
crates/bevy_pbr/src/render/light.rs is an enigma that I need to take a closer look at. Thanks for the discord archaeology. I'll try to make sense of it.

2024-09-22 17:11 UTC, Trashtalk217 commented
I've thought about it some more and I've decided to keep the `MainWorld(id)` component even when it's not currently used. The primary reason is that this component helps distinguish between synced entities and non-synced entities in the render world. Without it, there's no easy way of doing that.
Secondly, it's exceptionally cheap to work with: When you are spawning an entity in the render world during sync, you might as well spawn it with something.

2024-09-22 18:01 UTC, alice-i-cecile commented
It's much appreciated; and I'm happy with how you're handling the review feedback. It's good to clearly discuss the feedback and split out what can be split into follow-up.

2024-09-23 12:31 UTC, Trashtalk217 commented
I've decided to use an observer to add `SyncToRenderWorld` automatically to every component that should be extracted. This has the obvious upside that users don't need to change how they use `ExtractComponentPlugin`, it will work identically as it did before the change. The downside, however, is a little subtle.

If you remove the component `ExtractComponent` from the entity, it will not automatically remove the `SyncToRenderWorld` component, making it so that entities are left synced when they shouldn't be. This means that the render world entity remains there, with the old data, which is potentially quite bad. If the entire entity with the `ExtractComponent` is removed, this is not a problem, because `SyncToRenderWorld` is also removed and the render world entity is despawned correctly.

> Why don't you just add another observer that removed `SyncToRenderWorld` if the relevant `ExtractComponent` is removed?

This becomes a problem with an entity that has two extract components, say `Foo` and `Bar`. If we remove `Bar`, `SyncToRenderWorld` is removed and the corresponding render world entity is despawned. But wait a minute, we still care about `Foo`! Yup, that becomes an annoying problem, doesn't it?

> Is there no way to fix this?

Yes there is, we could give `SyncToRenderWorld` a field that keeps track of the number of 'synced' components. So an entity with `Foo` and `Bar` would have a `SyncToRenderWorld(2)`, because it has two reasons to be synced. With some appropriate accounting with observers, this would all work.

> Why are you not doing it then?

Because this whole system is so *so* **so** complicated and annoying. The sync system to begin with is a cludge built on a hack built on an etc etc. This is all to catch a very minor edge-case and I'm wondering if there is a better way. Or if we can just write a stern warning somewhere in the docs, maybe that's enough.

2024-09-23 12:45 UTC, alice-i-cecile commented
> Or if we can just write a stern warning somewhere in the docs, maybe that's enough.

IMO removing `ExtractComponent` from an entity should be *vanishingly* rare: this is enough for me here.

As a note, trait queries would be a really clean fix to your problem of "have we removed all of the relevant components of a generic type", but those aren't upstreamed.

2024-09-23 20:51 UTC, Trashtalk217 commented on crates/bevy_pbr/src/render/light.rs
> +            while light_entities.len() < 6 * (offset + 1) {
6 is the number of sides a cube has, I figured it out, you're welcome

2024-09-26 22:51 UTC, alice-i-cecile commented on crates/bevy_render/src/extract_component.rs
> +/// Therefore it sets up the [`ExtractSchedule`] step for the specified [`ExtractComponent`].
```suggestion
/// To do so, it sets up the [`ExtractSchedule`] step for the specified [`ExtractComponent`].
```

2024-09-26 22:52 UTC, alice-i-cecile commented on crates/bevy_render/src/extract_component.rs
> +/// # Warning
```suggestion
/// # Warning
///
```

2024-09-26 22:52 UTC, alice-i-cecile commented on crates/bevy_render/src/extract_component.rs
> +/// We recommend removing the entity at once, instead of only removing [`ExtractComponent`].
```suggestion
/// We recommend despawning the entire entity, instead of only removing [`ExtractComponent`].
```

2024-09-26 22:53 UTC, alice-i-cecile commented on crates/bevy_render/src/world_sync.rs
> +/// A Plugin that synchronizes entities with [`SyncToRenderWorld`] between the main world and the render world.
```suggestion
/// A plugin that synchronizes entities with [`SyncToRenderWorld`] between the main world and the render world.
```

2024-09-26 22:57 UTC, alice-i-cecile requested changes
A few small doc changes, but I'm sold on the core design and implementation. Thanks for shepherding this across the finish line!

2024-09-26 22:57 UTC, alice-i-cecile commented on crates/bevy_render/src/world_sync.rs
> +pub struct WorldSyncPlugin;
IMO we should cover `RenderEntity` and `MainEntity` here as well, since those are important parts of the puzzle.

2024-09-26 22:57 UTC, alice-i-cecile commented on crates/bevy_render/src/world_sync.rs
> +#[derive(Component, Deref, Clone, Debug)]
Nit: move this below the doc comments.

2024-09-26 22:57 UTC, alice-i-cecile commented on crates/bevy_render/src/world_sync.rs
> +/// This is currently used for gizmos and UI nodes, which are redrawn / recalculated every frame.
```suggestion
```

2024-09-26 22:57 UTC, alice-i-cecile commented on crates/bevy_render/src/world_sync.rs
> +/// This is currently used for gizmos and UI nodes, which are redrawn / recalculated every frame.
We should remove this: it's *way* too easy for this info to go out of date because of how far it is from the other code.

2024-09-26 22:57 UTC, alice-i-cecile commented on crates/bevy_render/src/world_sync.rs
> +pub(crate) enum EntityRecord {
Tiny doc strings please.

2024-09-26 23:29 UTC, alice-i-cecile approved these changes

2024-09-30 19:15 UTC, merged

2024-10-20 15:42 UTC, alice-i-cecile commented
I'll tackle the release notes for this. I think that getting something in place for this ASAP is important to help communicate these changes to the rendering devs and ease initial migration during the release candidate.