Change ReflectMapEntities to operate on components before insertion
bevyengine/bevy pull request #15422
Opened 2024-09-25 10:59 UTC by jrobsonchase

Previous PR https://github.com/bevyengine/bevy/pull/14549 was closed in error and couldn't be reopened since I had updated the branch :crying_cat_face: 

# Objective

Fixes #14465

## Solution

Alters `ReflectMapEntities` to operate more like `MapEntities` by making it operate on the component itself rather than the `World` post-insertion. As a result, `Observers` never see the in-between state where the scene component has been added, but hasn't yet had its entities mapped.

Also brings it more in-line with `MapEntities` by accepting a generic `DynEntityMapper` rather than relying on the `EntityHashMap` and `SceneEntityMapper` implementation.

## Testing

* New unit test for `Observer`s + `DynamicScene`s
* New unit test for `Observer`s + `Scene`s
* Open to suggestions for other tests!

---

## Migration Guide

- The existing `map_entities` and `map_all_entities` methods have been renamed to `map_world_entities` and `map_all_world_entities` respectively and marked as deprecated.
  - Figured I'd leave these in some form since the new method isn't exactly a drop-in replacement.
  - ~This is in a separate commit so that they'll be easy to fully remove later.~ Edit: Oops, I forgot I did this and squashed it away. Oh well, should still be easy to remove them if/when desired.

2024-09-26 21:01 UTC, jrobsonchase commented
I've rebased this on #15425 since it's gaining traction and I like its approach way better than what I had here previously.

2024-09-28 17:18 UTC, jrobsonchase commented
Welp, this has now been un-rebased on #15425 after realizing the approach there wouldn't work for `HashSet`s. So now we're back to the original plan.

2024-09-28 17:18 UTC, jrobsonchase commented
@alice-i-cecile This is ready for review once more!

2024-10-01 14:14 UTC, alice-i-cecile approved these changes

2024-10-01 17:07 UTC, Shatur requested changes
Looks good!
Left a small suggestion.

2024-10-01 17:07 UTC, Shatur commented on crates/bevy_ecs/src/reflect/map_entities.rs
> +                let mut concrete = C::from_reflect(reflected).expect("mismatched reflected type");
Let's use the [recommended](https://doc.rust-lang.org/std/result/enum.Result.html#recommended-message-style) message style.
```suggestion
                let mut concrete = C::from_reflect(reflected).expect("reflected type should match");
```

2024-10-01 17:20 UTC, Shatur approved these changes

2024-10-01 18:50 UTC, merged