Streaming `bevy/get` and `bevy/list` with HTTP SSE
bevyengine/bevy pull request #15608
Opened 2024-10-03 01:49 UTC by LiamGallagher737

## Objective

Add a way to stream BRP requests when the data changes.

## Solution

#### BRP Side (reusable for other transports)

Add a new "update checker" handler alongside a normal method handler that works a lot like a run condition. Streaming requests are stored in a resource, every request in it is checked every frame for updates and the main handler is run if the update condition returns true. The new response is sent over the same channel as normal. Transports decide how to decide if requests should be streamed or not as some like web sockets will always want to stream and others may want to be a hybrid (like I did with HTTP).

#### HTTP Side

If a request comes in with `+stream` in the method, the transport will invoke the method with streaming enabled. It will then reply with `text/event-stream` content-type (Server sent events) and keep the connection open for more responses.

## Testing

I tested with the podman HTTP client. This client has good support for SSE's if you want to test it too.

## Future work

- Currently the full response is resent, it would be nice to only send whats changed but for now I want to keep things as simple as I can keep them.
- The `bevy/query` method would also benefit from this but that condition will be quite complex so I will leave that to later.

2024-10-03 01:56 UTC, JMS55 commented
Really not sure how I feel about SSE vs a proper streaming protocal like QUIC or WebTransport...

2024-10-03 02:05 UTC, LiamGallagher737 commented
> Really not sure how I feel about SSE vs a proper streaming protocol like QUIC or WebTransport...

I chose it just due to being easy to implement with the existing HTTP transport. I am happy to swap it for something else as it's the BRP part I care about, the SSE is just to have something to show it works.

2024-10-03 02:26 UTC, LiamGallagher737 commented
After a quick look at the [wtransport](https://github.com/BiagioFesta/wtransport) crate, it is defiantly something I'd like to have a go at integrating. Until then I think the SSE serves as a good example of how to use the streaming.

2024-10-03 04:57 UTC, LiamGallagher737 commented
@notmd I'd also appreciate a review from you since you have been working on streaming stuff.

2024-10-03 15:37 UTC, notmd commented
I'm not sure about mixing streaming and one-time request into 1 handler is a good I idea. Also, letting the transport control weather to stream seems bad. The `RemoteMethods` should act as contracts for what a method does, either streaming or one-time. And the transport should return err if it not support streaming.

2024-10-03 19:17 UTC, LiamGallagher737 commented
Currently re-working it to separate the streaming handlers and only stream changed data, not entire responses.

2024-10-04 05:15 UTC, LiamGallagher737 commented
One issue with this is some components such as `bevy_render::view::visibility::ViewVisibility` are "changed" every frame and a response is sent even though the value of `true` stays the same. I am guessing this is because it is being accessed mutably even though the value isn't changed. Does anyone know a solution to this?

2024-10-04 06:02 UTC, djeedai commented
If a component gets flagged by the change detection system without an actual change, this is a bug in that component management, and likely breaks other uses of it. I'd log a bug. Otherwise we can't rely on change detection.

2024-10-04 06:09 UTC, djeedai approved these changes

2024-10-04 06:33 UTC, LiamGallagher737 commented
As a note on bandwidth usage, requesting `bevy/get+watch` with `Transform` as the only component on the cube result in roughly 6KB per second with the app running at 60fps.

2024-10-04 06:43 UTC, LiamGallagher737 commented on examples/remote/server.rs
> +        .add_systems(Update, move_cube.run_if(on_timer(Duration::from_secs(1))))
I made the movement continuous. 

As for what to do if the volume of data gets to much for the transport, no clue. Currently due to using `force_send` on the senders I believe un-received messages are overridden by shifting the queue down (removing the oldest one) and adding the new message to the end. Not the best way of handling it but it should work for now until someone thinks of something better.

2024-10-04 06:51 UTC, notmd commented
> One issue with this is some components such as `bevy_render::view::visibility::ViewVisibility` are "changed" every frame and a response is sent even though the value of `true` stays the same. I am guessing this is because it is being accessed mutably even though the value isn't changed. Does anyone know a solution to this?

I have the same issue in my impl. There is `track_change_detection` feature, but I haven't dig into yet. Searching `mut ViewVisibility` in the repo have few systems use it, probably one of them

2024-10-04 20:50 UTC, pablo-lua commented
> One issue with this is some components such as `bevy_render::view::visibility::ViewVisibility` are "changed" every frame and a response is sent even though the value of `true` stays the same. I am guessing this is because it is being accessed mutably even though the value isn't changed. Does anyone know a solution to this?

ViewVisibility is a Component used for calculations and therefore, is set every frame to false, and after that, other components do they thing and will se this to True after. 
Would probably be better to bypass this when setting, but I'm not sure if this is the best approach. For that kind of component, I think the client side should probably be responsible for storing an cache and seeing if the value was in fact changed. We could do this kind of cache in the backend, but I think this would be much more tricky for this PR

2024-10-04 21:39 UTC, LiamGallagher737 commented
Found an issue with missing removal events so I'll rework that. Please don't merge until then.

2024-10-04 22:06 UTC, LiamGallagher737 commented
Good to go now

2024-10-08 04:04 UTC, bushrat011899 requested changes
Don't have time just yet to do a test locally, but I have some suggestions already mostly around avoid performance regression.

2024-10-08 04:16 UTC, LiamGallagher737 commented on crates/bevy_remote/src/lib.rs
> +        .run_system_with_input(*system_id, message.params.clone())
Good to know! I'll make this PR once this one is merged

2024-10-08 05:14 UTC, bushrat011899 approved these changes
Can confirm this works as expected. Sending `bevy/query` to find the cube `Entity` and then using:

```json
{
    "jsonrpc": "2.0",
    "method": "bevy/get+watch",
    "params": {
        "entity": 4294967333,
        "components": [
            "bevy_transform::components::transform::Transform"
        ]
    }
}
```

does start an HTTP stream sending results continuously (since in the `server` example the cube's transform is changing continuously). I think this is a solid piece of infrastructure to include, even if it isn't based on something more feature rich like web sockets.

2024-10-08 16:39 UTC, merged