Upgrade to Taffy 0.6
bevyengine/bevy pull request #15844
Opened 2024-10-10 23:34 UTC by nicoburns

# Objective

- Keep Taffy version up to date

Taffy 0.6 doesn't include a huge amount relevant to Bevy. But it does:

- Add the `box_sizing` style
- Expose the computed `margin` in layout
- Have a few bug fixes in the layout algorithms

## Solution

- Upgrade Taffy to `0.6.0`

## Testing

- I've run the `grid` example. All looks good.
- More testing is probably warranted. We have had regressions from Taffy upgrades before
- Having said that, most of the algorithm changes this cycle were driven by fixing WPT tests run through the new Servo integration. So they're possibly less likely than usual to cause regressions.

## Breaking changes

The only "breaking" change is adding a field to `Style`. Probably doesn't bear mentioning?

2024-10-11 05:20 UTC, rparrett requested changes

2024-10-11 05:20 UTC, rparrett commented on crates/bevy_ui/src/ui_node.rs
> +/// Whether to show or hide overflowing items
Stray comments from another `Overflow`

2024-10-11 05:20 UTC, rparrett commented on crates/bevy_ui/src/ui_node.rs
> +    ///
Stray comments from `Display`

2024-10-11 05:20 UTC, rparrett commented on crates/bevy_ui/src/ui_node.rs
> +/// Which part of a Node's box length styles like width and height control
nit: I think we're generally placing doc comments above attributes, and not including new lines between

2024-10-12 14:58 UTC, ickshonpe approved these changes
Looks good besides the comments nits.

Adding the computed margin values is something I've wanted for a while and means I can add support for `margin-box` to #15561.

2024-10-12 15:12 UTC, nicoburns commented
Nits addressed

2024-10-12 15:14 UTC, rparrett approved these changes

2024-10-28 12:51 UTC, mnmaita approved these changes

2024-10-28 13:43 UTC, BenjaminBrienen approved these changes

2024-11-16 11:50 UTC, robtfm commented
fixes #16304

2024-12-02 16:47 UTC, alice-i-cecile commented
Yep! I'll grab this in my next merge train.

2024-12-03 17:39 UTC, merged