Fix AVIF image decoding
bevyengine/bevy pull request #15959
Opened 2024-10-16 18:05 UTC by brianreavis

# Objective / Solution

This expands upon:

- https://github.com/bevyengine/bevy/pull/15586

The image crate requires `avif-native` feature for decoding AVIF images ([documented here](https://github.com/image-rs/image?tab=readme-ov-file#supported-image-formats)). The `avif` flag only allows for the encoding of AVIFs.

## Testing

- Tested on a local project

2024-10-16 18:07 UTC, alice-i-cecile commented on crates/bevy_internal/Cargo.toml
> +avif = ["bevy_image/avif-native"]
```suggestion
avif = ["bevy_image/avif"]
```
We need to enable the `bevy_image` feature flag here, which is still just called `avif`.

2024-10-16 18:07 UTC, alice-i-cecile requested changes
The feature flag for `bevy_image` is wrong :)

2024-10-16 18:07 UTC, alice-i-cecile commented
@clarfonthey can I get your review here?

2024-10-16 18:08 UTC, brianreavis commented
@alice-i-cecile You're quick! Just noticed that too and fixed it.

2024-10-16 18:22 UTC, brianreavis commented
One thing that needs to be figured out: the `ci` clippy job fails because it runs with `--all-features`:
https://github.com/bevyengine/bevy/actions/runs/11371344253/job/31633201423?pr=15959#step:6:876

We could install `dav1d`, but that seems overkill to make that particular job work.

2024-10-16 18:51 UTC, mockersf commented
AVIF seems to be mostly a format for animated images, which Bevy doesn't support built in.
I think the fix is to not expose it in Bevy, it will still be possible for a third party plugin to enable it.

2024-10-16 19:00 UTC, brianreavis commented
>  AVIF seems to be mostly a format for animated images, which Bevy doesn't support built in.

Though AVIF supports animation, it's great for compressing single images: https://jakearchibald.com/2020/avif-has-landed/

2024-10-16 19:52 UTC, clarfonthey approved these changes
I'm fine with this; it does look like the decoder is only gated on this feature, not the `avif` feature.

2024-10-16 20:46 UTC, mockersf commented
> the `ci` clippy job fails because it runs with `--all-features`

You can either remove built-in support for `AVIF`, which is what I would recommend, or add the `dav1d` library to the linux dependencies ([for ci](https://github.com/bevyengine/bevy/blob/main/.github/actions/install-linux-deps/action.yml) and [in documentation](https://github.com/bevyengine/bevy-website/blob/main/content/learn/book/getting-started/installation.md)).

Both options are possible, it depends how much you want built-in support for `AVIF`

2024-10-17 01:32 UTC, clarfonthey commented
I feel like it'd be best as a third option, opt for an embedded AVIF implementation, but in the absence of that, removing it feels better.

2024-10-17 01:34 UTC, alice-i-cecile commented
> I feel like it'd be best as a third option, opt for an embedded AVIF implementation, but in the absence of that, removing it feels better.

I don't think this is an important enough feature for that. I'd prefer to remove it and let third-party solutions cover this.

2024-10-17 05:54 UTC, brianreavis commented
I’m going to go ahead and close this PR and leave removal to another PR. If I get time I’ll take a stab at it.

2024-10-17 05:54 UTC, closed without merging