Double MAX_JOINTS and MAX_MORPH_WEIGHTS
bevyengine/bevy pull request #15972
Opened 2024-10-17 17:36 UTC by victorb

# Objective

- Describe the objective or issue this PR addresses.
- If you're fixing a specific issue, say "Fixes #X".

I tried to import a 3D model that were slightly above the existing limits, got this error:

```
Failed to load asset 'models/humanoid.glb' with asset loader 'bevy_gltf::loader::GltfLoader': failed to generate morph targets: Bevy only supports up to 64 morph targets (individual poses), tried to create a model with 77 morph targets
```

## Solution

So tried the simplest solution possible, doubling the limits I hit when trying to load the model. It seems to work without any issues, everything still works exactly the same as far as I can tell. @alice-i-cecile asked me to PR the changes, so here we are :)

Ideally, I'd would have liked the comments for these two values to describe why those exact limits have been chosen, but I don't know the answer to that, maybe someone else could help me explain why the limits are there in the first place, and how the specific numbers were chosen.

2024-10-17 18:04 UTC, alice-i-cecile commented
Do you have a convenient link to a model that previously failed but now works that we can use to test this?

2024-10-17 18:08 UTC, alice-i-cecile commented
This has been moved several times, and I'm trying to piece together the history. It was moved to `bevy_mesh`, and before that split off of `mesh.rs` in https://github.com/bevyengine/bevy/commit/db1e3d36bc8ebdcdf85b17eecca2ecf022dabd78

2024-10-17 18:42 UTC, victorb commented
@alice-i-cecile 
> Do you have a convenient link to a model that previously failed but now works that we can use to test this?

Unfortunately not, it's a purchased & proprietary model and license doesn't allow me to redistribute it like that.

I'm wondering if maybe just the weight/joint data however could be extracted and used for a test case, would just be data and should be fine in theory. If this could work for you/Bevy and be beneficial, I can reach out to the original model author and ask if it's OK with them.

2024-10-17 19:38 UTC, mockersf requested changes
This values are used to allocate buffers. Their maximum sizes depend on the GPU/platform, the current values are the ones guaranteed to work everywhere.

To allow bigger values, you would have to check against the limits of the GPU at runtime, which would mean not using consts anymore.

2024-10-18 17:23 UTC, victorb commented
> To allow bigger values, you would have to check against the limits of the GPU at runtime, which would mean not using consts anymore.

How would that realistically work like? I'm guessing we can't dynamically figure that out, as that would have to take into consideration other things that go into the GPU, or not? Or would it just be a question of reading a value then setting the limits based on that?

Alternatively, would it make sense to have the default values as they were before this patch, and then allow users to set the limit themselves via passed in values? Would be a workaround at best I suppose.

2025-01-03 19:12 UTC, victorb commented
Closing this in favor of https://github.com/bevyengine/bevy/issues/17128

2025-01-03 19:12 UTC, closed without merging