Refactor `GltfLoader::load_gltf`
bevyengine/bevy pull request #15994
Opened 2024-10-18 22:06 UTC by hukasu

# Objective

Refactor the `load_gltf` method in `bevy_gltf/loader.rs`, the criteria for the split is kind of arbitrary but at least it is not a 2.6k line file.

## Solution

Move methods and structs found in `bevy_gltf/loader.rs` into 12 new modules.

## Testing

Ran `cargo test --package bevy_gltf` and verified with some of the examples.

2024-12-16 16:46 UTC, suprohub commented
any updates?

2024-12-16 20:19 UTC, hukasu commented
The team is focused on 0.15.1, i'm in wait until 0.16 becames the target, then i will merge and do the comments

2025-02-18 23:51 UTC, hukasu commented
@alice-i-cecile can we get this moving now? who would be SME on this topic to do the reviews?

2025-02-20 01:08 UTC, thepackett reviewed
Overall this seems like a good PR. Having read through the GltfLoader code before, this is a significant improvement. I ran CI locally successfully and was able to confirm that examples using Gltf assets were working as expected. The only question I have is whether or not the extension traits should be public or not.

2025-02-20 01:29 UTC, hukasu commented on crates/bevy_gltf/src/ext/document.rs
> +pub trait DocumentExt {
they are visible only inside the crate because the modules are not public

2025-02-20 01:37 UTC, hukasu commented on crates/bevy_gltf/src/ext/document.rs
> +pub trait DocumentExt {
if you go to `lib.rs` you will see that all modules are private, and a bit below it there is the re-exports of what should be visible by users of the crate

2025-02-20 01:38 UTC, hukasu commented on crates/bevy_gltf/src/ext/document.rs
> +pub trait DocumentExt {
what is visible by users remains the same as before the refactor

2025-02-20 01:53 UTC, thepackett commented on crates/bevy_gltf/src/ext/document.rs
> +pub trait DocumentExt {
Yep, you are correct. In that case I can't see any issues with this PR as written.

2025-02-20 01:53 UTC, thepackett approved these changes

2025-02-20 07:06 UTC, andriyDev requested changes
I am not a fan of how many extension traits there are. This doesn't seem necessary, and results in a bunch of tiny files which I hurts readability IMO. For example `crates/bevy_gltf/src/ext/scene.rs` is a whopping 14 lines. Jumping to this file just to see "oh this is just an extension trait" is quite underwhelming.

I would prefer just free functions for most of these (like the original implementation), just organized into modules more. For example, rather than `node.node_name()`, we just have `node_name(&node)` and `node_transform(&node)` and so on. But with the important part being that `node_name` and `node_transform` should be in a `mod node`.

One case where "extension traits" is likely desirable is labels - these could all be a single `trait ToLabel` which Scene, Skin, Texture, etc can implement. Now all these disparate label stuffs can be brought under one roof and we can see how all of these are really the same thing over and over again. Of course whether this really is the way we want to go I'm not sure (for example Skin already breaks this pattern since it wants a `inverse_bind_matrics_label` version - though this could just sit next to the trait implementations as `inverse_bind_matrics_label_for_skin` to again keep the similar implementations together.

2025-02-20 10:12 UTC, hukasu commented
@andriyDev see if this solution is satisfactory

2025-02-20 13:15 UTC, rparrett reviewed
I added some specific suggestions about the `ext` module, though I think I generally agree that this is feeling excessively "enterprise-grade."

I don't really agree with the way the changeset is presented. The current arrangement of "the loader stuff is in loader.rs" is logical and not inherently worse than an "arbitrary" split.

2025-02-21 07:03 UTC, andriyDev requested changes

2025-02-21 07:03 UTC, andriyDev commented on crates/bevy_gltf/src/label.rs
> +}
Ah I didn't realize how some of these need an "inverse" flag. Sorry about that. I don't think we should go with this. Seeing something like `(material, true).into()` would be very confusing. It's not clear what's going on, what `true` corresponds to, etc. I think just making these regular free functions like `material_to_label(material: &gltf::Material, is_scale_inverted: bool)` is straight forward and clear.

2025-02-21 07:03 UTC, andriyDev commented on crates/bevy_gltf/src/loader/gltf_ext/mesh.rs
> +pub trait MeshExt {
As I said before, I think we should just avoid these extension traits. I'd much prefer just free functions, like `primitive_name_for_mesh(mesh: &gltf::Mesh, primitive: &Primitive)`. (Similar for the other extension traits)

2025-02-22 02:59 UTC, andriyDev requested changes
This is looking great!

2025-02-22 02:59 UTC, andriyDev commented on crates/bevy_gltf/src/loader/gltf_ext/extras.rs
> +pub fn as_gltf_extras(extras: &Extras) -> Option<GltfExtras> {
Can we make basically everything in `crates/bevy_gltf/src/loader/gltf_ext` and `crates/bevy_gltf/src/loader/extensions` `pub(crate)` instead (where it makes sense of course)? I know these aren't leaking out right now, but I'd rather make it clear that we want these to only be implementation details.

2025-02-22 10:26 UTC, hukasu commented on crates/bevy_gltf/src/loader/gltf_ext/extras.rs
> +pub fn as_gltf_extras(extras: &Extras) -> Option<GltfExtras> {
sure

2025-02-22 10:36 UTC, mockersf commented
This feels to me as too many small files, not sure that's better than the current state.

2025-02-22 10:38 UTC, hukasu commented on crates/bevy_gltf/src/loader/gltf_ext/extras.rs
> +pub fn as_gltf_extras(extras: &Extras) -> Option<GltfExtras> {
is it enough like this?
```rust
pub(super) mod extras;
pub(super) mod material;
pub(super) mod mesh;
pub(super) mod scene;
pub(super) mod skin;
pub(super) mod texture;
```
or is it better on each individual struct?

2025-02-22 19:09 UTC, andriyDev commented on crates/bevy_gltf/src/loader/gltf_ext/extras.rs
> +pub fn as_gltf_extras(extras: &Extras) -> Option<GltfExtras> {
It's better on each individual struct. Making it clear that these are not our public API to readers of the code is useful IMO. Plus it prevents us from accidentally exposing these symbols even if we make a mod public for some reason.

2025-02-22 19:15 UTC, hukasu commented on crates/bevy_gltf/src/loader/gltf_ext/extras.rs
> +pub fn as_gltf_extras(extras: &Extras) -> Option<GltfExtras> {
understood

2025-02-22 19:26 UTC, hukasu commented on crates/bevy_gltf/src/loader/gltf_ext/extras.rs
> +pub fn as_gltf_extras(extras: &Extras) -> Option<GltfExtras> {
or would it be ok to have a module doc (i.e. `//!`) that says that all items on that file are internal to `loader.rs`?

2025-02-22 20:09 UTC, andriyDev commented on crates/bevy_gltf/src/loader/gltf_ext/extras.rs
> +pub fn as_gltf_extras(extras: &Extras) -> Option<GltfExtras> {
Doc comments can go stale. Visibility keywords can't. So I'd prefer we make it explicit and just say `pub(crate)`.

2025-02-22 20:15 UTC, hukasu commented on crates/bevy_gltf/src/loader/gltf_ext/extras.rs
> +pub fn as_gltf_extras(extras: &Extras) -> Option<GltfExtras> {
ok, coming up in a few seconds

2025-02-23 00:48 UTC, andriyDev approved these changes

2025-02-23 00:48 UTC, andriyDev commented on crates/bevy_gltf/src/loader/extensions/khr_materials_anisotropy.rs
> +    pub fn parse(
Parsing here should also be `pub(crate)` unless I'm missing something?

2025-02-23 00:48 UTC, andriyDev commented on crates/bevy_gltf/src/loader/extensions/khr_materials_clearcoat.rs
> +    pub fn parse(
Same here.

2025-02-23 00:48 UTC, andriyDev commented on crates/bevy_gltf/src/loader/extensions/khr_materials_specular.rs
> +    pub fn parse(
Same here.

2025-02-25 00:54 UTC, andriyDev requested changes

2025-02-25 00:54 UTC, andriyDev commented on crates/bevy_gltf/src/loader/extensions/khr_materials_anisotropy.rs
> +}
All these pub things should also be `pub(crate)`. Please repeat that for all these extensions. AFAICT, these types weren't public before, so we should mark them as such.

2025-02-25 01:30 UTC, hukasu commented
after merge, tested with `many_foxes`, `anisotropy`, and `deferred_rendered` examples, which are some examples that i know use distinct gltfs

2025-02-25 01:50 UTC, andriyDev approved these changes

2025-02-25 09:10 UTC, pcwalton commented
@mockersf This PR makes more small files than I personally would, but it's definitely better than the current monster `load_gltf` function.

2025-02-25 10:11 UTC, hukasu commented
I see following code by jumping between different files easier that jumping between different locations on the same file

2025-02-25 11:50 UTC, mockersf commented
> I see following code by jumping between different files easier that jumping between different locations on the same file

There's a balance to reach, and this PR takes it too far in the other direction in my opinion

2025-02-25 12:55 UTC, greeble-dev commented on crates/bevy_gltf/src/loader/mod.rs
> +                        .add_labeled_asset(skin_label(&skin).to_string(), gltf_skin)
I think this can use GltfSkin's method? See related comment on `gltf_ext/skin.rs`.

```suggestion
                        .add_labeled_asset(skin.asset_label(&skin).to_string(), gltf_skin)
```

2025-02-25 12:55 UTC, greeble-dev commented on crates/bevy_gltf/src/loader/gltf_ext/skin.rs
> +pub(crate) fn skin_label(skin: &Skin<'_>) -> GltfAssetLabel {
If `loader/mod.rs` is changed to use `GltfSkin::asset_label` then I think this becomes redundant?

2025-02-25 12:58 UTC, hukasu commented
> E.g. gltf_ext/mesh.rs is small now, but there's still 100+ lines in the loader that could move there in a follow up PR.
my first go into this at the tail end of 0.14 was a lot more aggressive with the changes, including breaking the contents of `load_gltf`, `load_material`, etc, methods into smaller methods, but there is already pushback with the current changes, so my idea was to leave to a different PR

2025-02-25 18:59 UTC, alice-i-cecile commented
I've finally taken a proper look at this, and I'm broadly on board with this. It's *much* better than the status quo, so I'm going to merge this now.

2025-02-25 19:20 UTC, alice-i-cecile requested changes
Sorry, I changed my mind. I *do* think this is better than the status quo, but I'm uncomfortable with the single item files, especially since these files feel mostly complete.

Is there another splitting strategy that we can use?

2025-02-25 19:52 UTC, hukasu commented
1. I'm ok with merging the types on `assets/` into a single file
2. I could also merge the types on `extensions/` into a single file, but for this one I would vote against, as to have a clearer view of which extensions we already have
3. I could also merge the methods on `gltf_ext/` into a single file, but I would prefer not to, my reasoning for the split was, if the main type of the method is present in `gltf::N` or `gltf::json::N`, I put the method in `gltf_ext/N`, so methods that use `gltf::Gltf` or `gltf::Document` would go on the root, and `gltf::texture::Texture` and `gltf::json::texture::Info` would go into `gltf_ext/texture.rs`, etc
4.  `gltf_ext/extras.rs` I can merge with the module root or implement as `From` for the components

2025-02-25 20:05 UTC, hukasu commented
5. `ImageOrPath` and `DataUri` are in separate modules because I couldn't think of a name for the module that would work

2025-02-25 20:12 UTC, alice-i-cecile commented
Let's go with 1 and 4,  and then resolve 5 by moving them back into lib.rs for now?

2025-02-25 20:17 UTC, hukasu commented
4 by moving to `mod.rs` or `impl From`?

2025-02-25 22:15 UTC, alice-i-cecile commented
Let's go with the `From` route. Although if I understand correctly, the conversion is fallible, in which case it should be `TryFrom`.

2025-02-26 00:20 UTC, hukasu commented
is my solution for 4 satisfactory?

2025-02-26 00:58 UTC, alice-i-cecile approved these changes

2025-02-26 01:00 UTC, alice-i-cecile commented
I quite like your final solution for 4. I think this is a nicer balance now; thanks for your patience. These sorts of reorganization PRs are quite painful due to merge conflicts and bikeshedding, but it's important to do them every now and then.

2025-02-26 01:18 UTC, merged