Remove custom rounding
bevyengine/bevy pull request #16097
Opened 2024-10-25 09:12 UTC by ickshonpe

# Objective

Taffy added layout rounding a while ago but it had a couple of bugs and caused some problems with the fussy `ab_glyph` text implementation. So I disabled Taffy's builtin rounding and added some hacks ad hoc that fixed (some) of the issues. Since then though Taffy rounding algorithm has improved while we've changed layout a lot and migrated to `cosmic-text` so those hacks don't help any more and in some cases cause significant problems.

Also our rounding implementation only rounds to the nearest logical pixel, whereas Taffy rounds to the nearest physical pixel meaning it's much more accurate with high dpi displays.

## Some examples of layout rounding errors visible in the UI examples

These errors are much more obvious at high scale factor, you might not see any problems at a scale factor of 1.

`cargo run --example text_wrap_debug`

<img width="1000" alt="text_debug_gaps" src="https://github.com/user-attachments/assets/5a584016-b8e2-487b-8842-f0f359077391">

All the narrow horizontal and vertical lines are gaps in the layout caused by errors in the coordinate rounding.

`cargo run --example text_debug`

<img width="1000" alt="text_debug" src="https://github.com/user-attachments/assets/a4b37c02-a2fd-441c-a7bd-cd7a1a72e7dd">

The two text blocks here are aligned right to the same boundary but in this screen shot you can see that the bottom one reporting the frame rate is one pixel off to the left. Because the size of this text node changes between frames the rounding errors cause it to vibrate left and right.

## Solution

Remove all our custom rounding hacks and reenable Taffy's layout rounding.

This doesn't fix some of the gaps that occur between borders and content but they seem to be a rendering problem as they disappear with `UiAntiAlias::Off`.

## Testing

Run the examples as described above in the `Objective` section. With this PR the problems mentioned shouldn't appear.

Also just added a new example in a separate PR #16096 `layout_rounding_debug`, which shows significant improvements with this PR.

2024-10-25 09:43 UTC, nicoburns approved these changes
Makes sense to me

2024-10-25 10:37 UTC, ickshonpe commented
`ui_rounding_test` was failing after the layout rounding changes but only fails at extremely low scale factors (below ~0.14). At that scale factor with 7 logical pixels to 1 physical pixel not much is going to visable anyway, so I don't think it's worth worrying about. I set the test to start at `1 - 1/n` instead of `1/n` scale factor and now it passes.

2024-10-25 13:07 UTC, rparrett commented on crates/bevy_ui/src/layout/mod.rs
> +            let mut s = 1. - r;
```suggestion
            // This fails with very small / unrealistic scale values
            let mut s = 0.2 + r;
```

Tiny suggestion for the test.

2024-10-27 19:09 UTC, alice-i-cecile commented
@ickshonpe CI is failing on a related test: can you take a look? I *suspect* the test itself is wrong.

2024-10-27 19:10 UTC, ickshonpe commented
Yep I'll fix it now

2024-10-27 19:10 UTC, alice-i-cecile approved these changes

2024-10-27 19:30 UTC, BenjaminBrienen approved these changes

2024-10-27 19:30 UTC, BenjaminBrienen commented on crates/bevy_ui/src/layout/mod.rs
> +            let rounded_size = (absolute_location + layout_size) - (absolute_location);
Parentheses are redundant

2024-10-27 19:45 UTC, alice-i-cecile approved these changes

2024-10-27 19:46 UTC, alice-i-cecile commented
Removing the unrounded size is a breaking change, but I'm okay if the migration guide is just "please tell us why you wanted this".

2024-10-27 20:14 UTC, BenjaminBrienen approved these changes

2024-10-27 20:24 UTC, alice-i-cecile commented
@ickshonpe CI failure is pointing out a real, if minor issue :) Ping me once it's resolved!

2024-10-27 21:02 UTC, ickshonpe commented
> Removing the unrounded size is a breaking change, but I'm okay if the migration guide is just "please tell us why you wanted this".

Couldn't decide what to say in the migration guide, so went back and worked out a really wretched way to retrieve the unrounded size from Taffy. I guess it's better this way though, there don't seem to be any problems anymore but it feels safer to stick with using the unrounded size for text.

2024-10-27 21:02 UTC, ickshonpe commented
> @ickshonpe CI failure is pointing out a real, if minor issue :) Ping me once it's resolved!

Fixed

2024-10-27 21:18 UTC, alice-i-cecile commented on crates/bevy_ui/src/layout/ui_surface.rs
> +    pub fn get_layout(&mut self, entity: Entity) -> Result<(taffy::Layout, Vec2), LayoutError> {
Can you document the meaning of the new `Vec2` here? Or replace the returned tuple with a real type.

2024-10-27 21:20 UTC, alice-i-cecile requested changes
Small docs and/or quality request, then this LGTM :)

2024-10-28 18:15 UTC, alice-i-cecile approved these changes

2024-10-28 19:48 UTC, BenjaminBrienen approved these changes
I noticed a small inconsistency with unwrap vs expect in the tests, but other than that, still good.

2024-10-28 19:48 UTC, BenjaminBrienen commented on crates/bevy_ui/src/layout/mod.rs
> +                .expect("failed to get layout")
`expect()` here

2024-10-28 19:48 UTC, BenjaminBrienen commented on crates/bevy_ui/src/layout/mod.rs
> +        let layout = ui_surface.get_layout(ui_entity).unwrap().0;
`unwrap()` here

2024-10-28 22:41 UTC, merged