Remove unnecessary lifetimes from impl
bevyengine/bevy pull request #16141
Opened 2024-10-28 19:52 UTC by BenjaminBrienen

# Objective

Fixes https://github.com/bevyengine/bevy/issues/15116#issuecomment-2441422838

## Solution

Removed lifetime generic

## Testing

Clippy lint no longer triggers locally

2024-10-28 19:56 UTC, alice-i-cecile approved these changes

2024-10-28 19:58 UTC, BenjaminBrienen commented
Hold on, I made a mistake

2024-10-28 20:05 UTC, BenjaminBrienen commented
![image](https://github.com/user-attachments/assets/348b1a4b-1dd3-4cf5-937e-cd07793caf79)
I just want you to know that this is all coming from clippy

2024-10-28 20:17 UTC, BenjaminBrienen commented
@alice-i-cecile No longer 2 lines :(

2024-10-28 20:27 UTC, BenjaminBrienen commented
Ok, clippy isn't requiring anything more.

2024-10-28 20:32 UTC, alice-i-cecile commented on crates/bevy_audio/src/audio_output.rs
> +impl EarPositions<'_, '_> {
This is a regression.

2024-10-28 20:32 UTC, alice-i-cecile commented on crates/bevy_ecs/src/change_detection.rs
> +impl<'a, T: Resource> IntoIterator for &'a Res<'_, T>
These are regressions.

2024-10-28 20:32 UTC, Victoronz commented
All the `'a` lifetimes that are hidden away are a nice cleanup, but this change also hides away a lot of named lifetimes, mostly `'w` and `'s`. 
There are cases when only one of the two is present, and now when hidden, is no longer discernible from just any elided `'a` lifetime. In other places now only one of these two is hidden, which is no longer be discernible from `<'w, 'a>`, which also exists.

2024-10-28 20:32 UTC, alice-i-cecile commented on crates/bevy_ecs/src/event/mutator.rs
> +impl<E: Event> EventMutator<'_, '_, E> {
This is a regression.

2024-10-28 20:35 UTC, alice-i-cecile requested changes
Rescinding my approval: we shouldn't do this systematically. The 'a lifetimes are fine, but as @Victoronz points out, the loss of named lifetimes is a net downgrade for readability.

2024-10-28 20:35 UTC, Victoronz commented
> Yeah, I don't like these changes as a whole, and would prefer to allow this lint.

I agree. My opinion generally is:
Unnamed lifetime -> elide when possible
Named lifetime -> never elide

2024-11-01 00:16 UTC, alice-i-cecile commented on crates/bevy_core/src/serde.rs
> +impl Visitor<'_> for EntityVisitor {
These ones should be reverted; the 'de convention is helpful.

2024-11-01 00:18 UTC, alice-i-cecile commented on crates/bevy_ecs/src/system/query.rs
> +    pub fn par_iter<'world, 'state>(&self) -> QueryParIter<'world, 'state, D::ReadOnly, F>
Rest of this file uses 'w and 's.

2024-11-01 00:19 UTC, alice-i-cecile commented on crates/bevy_render/src/texture/fallback_image.rs
> +impl FallbackImageMsaa<'_> {
This one should be reverted.

2024-11-01 00:20 UTC, alice-i-cecile requested changes
Only a couple more fixes left! I'm in favor of these changes now, and I'm glad to see the lint allowed.

2024-11-01 00:44 UTC, Victoronz commented
I would be careful about keeping the scope of this PR down. I see it now also specifies some named lifetimes, which is fine for impls, but there are also some function (and trait function?) definitions in there now. 

Caution should be taken with other locations, because specifying lifetimes in function definitions (i.e. adding generics) can be a breaking change. It also means no longer systematically following/allowing a lint, so that should be a separate decision/PR imo.

2024-11-01 02:06 UTC, BenjaminBrienen commented
I totally understand if we aren't interested in tackling "lifetime style consistency" right now. The problems I noticed are:

- Many `'a` should be `'w`, so it's not obvious which changes should be reverted.
- Existing inconsistencies in the way lifetimes are written that go against feedback I've received in the PR, which makes me want to fix those, too.
- Other inconsistencies that are easy fixes, like `Formatter<'_>`.

2024-11-01 19:57 UTC, BenjaminBrienen commented
I also prefer to just follow the lints, for similar reasons. I'm just doing my best given the feedback since I think pretty much every member has been against that strategy. I'm trying to find a balance between "We don't want to have to write all the lifetimes" in #15916 (for example, writing `Mut<'w, T>` everywhere and "We don't want to ellide `'w`.

2024-11-01 20:37 UTC, chescock commented
> I'm just doing my best given the feedback since I think pretty much every member has been against that strategy.

Just in case it wasn't clear: I think you're doing a great job with this PR!  My comment was for the folks who were against that strategy.  There are definitely tradeoffs to be made here, but I wanted to highlight some of the benefits of your original proposal in case they hadn't been considered.

2025-01-01 20:43 UTC, bushrat011899 reviewed
In general I like the changes here. My only broad concern is there are a few instances of switching to anonymous `'_` lifetimes where I think `'w` is more appropriate.

2025-01-01 20:43 UTC, bushrat011899 commented on crates/bevy_asset/src/reflect.rs
> +    len: for<'w> fn(&World) -> usize,
I think either the `for<...>` needs to be removed here, or the lifetime for `World` should be `'w`.

2025-01-01 20:43 UTC, bushrat011899 commented on crates/bevy_ecs/src/query/fetch.rs
> +unsafe impl<'world> WorldQuery for EntityRef<'world> {
I've seen some of these changes use `'w` and others use `'world`. Is there a particular reason for one over the other? I think it's fine if it's just an inconsistency as both are clear IMO

2025-01-01 20:43 UTC, bushrat011899 commented on crates/bevy_ecs/src/query/fetch.rs
> +unsafe impl<B> QueryData for EntityRefExcept<'_, B>
Shouldn't this be `'w`?

2025-01-01 20:55 UTC, BenjaminBrienen commented on crates/bevy_ecs/src/query/fetch.rs
> +unsafe impl<'world> WorldQuery for EntityRef<'world> {
Sometimes there is a conflicting, existing lifetime declared in an overlapping scope

2025-01-01 20:59 UTC, BenjaminBrienen commented on crates/bevy_asset/src/reflect.rs
> +    len: for<'w> fn(&World) -> usize,
The fact that this isn't caught by a lint (among other things) makes me wish that we just went by the normal clippy lint and elided all lifetimes when possible.

2025-01-01 21:24 UTC, BenjaminBrienen commented on crates/bevy_ecs/src/query/fetch.rs
> +unsafe impl<B> QueryData for EntityRefExcept<'_, B>
Yeah, I'll fix all of those now

2025-01-01 21:50 UTC, bushrat011899 approved these changes

2025-01-02 00:58 UTC, chescock commented
> The fact that this isn't caught by a lint (among other things) makes me wish that we just went by the normal clippy lint and elided all lifetimes when possible.

I also wish that!  I don't entirely understand the objection to following the lint, and had been hoping [my comment above](https://github.com/bevyengine/bevy/pull/16141#issuecomment-2452043891) would spur a little more debate.  

> Sometimes there is a conflicting, existing lifetime declared in an overlapping scope

I think this is guaranteed to happen on every `SystemParam` and `WorldQuery` impl that uses those lifetimes.  The lifetime parameters on `Self` are never used in the impls.  They only exist to support the magic where ordinary functions can be converted to systems.  Everything gets the actual lifetimes re-applied in `type Item<'w>` and `type Item<'w, 's>`.  

Those traits are some of the cases where I think using `'_` to make it clear that the lifetime is never used is really valuable!

2025-01-02 01:47 UTC, Victoronz commented
Revisiting this, I think this is definitely a more intricate issue than it at first seems. This is my current understanding of the lifetimes here:

The `'w` lifetime doesn't semantically mean what it sounds like:
As far as I understand, it is supposed to represent a "borrow from world", which conceptually means that there is a `&'w World` that `'w` refers to. However, that isn't really the case. Semantically, a `'w` lifetime is simply a named lifetime like any other, i.e. `'a`. Its scope must match any other mention of `'w` in the item it is defined in, and satisfy any specified bounds on top of that. Because there is not just one "world borrow lifetime", we are lead to confusing situations where we have both `'world` and `'w`, which are both supposed to be the same, yet are semantically not.

Furthermore, `&'w mut Query<'w, ...>` doesn't mean we have a borrow of `Query` that lives as long as world, but that `'w` is now constrained to match the scope of that query borrow.
If we obtain an `EntityMut<'_>` from that query, what is originally written as `'w` in the struct definition instead becomes scoped on our query borrow (we could call this `'q`). If we now fetch an item from `EntityMut`, we rely on a borrow of that struct, not directly of `Query`, or `World`.
In these constrained cases, switching `'_` to `'w` is actually unsound! See: https://github.com/bevyengine/bevy/pull/17035
(Similar to this are `transmute`s, where the `'s` in `Query` now borrows from a `QueryLens`).

I do like `'_` when it can remove noise, and say "it is inferred, don't worry about this", and I like `'w` when it can clarify noise, and say "it is a world borrow, don't worry about this". 

When either applies is heavily case dependent, and I don't think I can broadly say.

2025-01-02 04:28 UTC, BenjaminBrienen commented
I wouldn't be surprised. Manually annotating the lifetimes correctly is nontrivial in sneaky ways. I think what this shows is that it is easier and more maintainable to elide lifetimes when possible. Currently, we do it one way half the time and another way half the time. Choosing to be consistent this way seems really hard.

2025-05-16 13:34 UTC, closed without merging