Picking out order
bevyengine/bevy pull request #16231
Opened 2024-11-04 15:48 UTC by NthTensor

Tweaks picking docs slightly for formatting and to add additional context about the ordering of `Over` and `Out` events. Also shifts `Out` to trigger before `Over` in the global event ordering.

Because of how focus is tracked, we must send all `Over` and `Out` events at the same time, in a block. Originally I had `Over` precede `Out` in the global event order, because this seemed natural. However, the effect of this, when a pointer moves between entities, is to have the new entity receive `Over` before the old entity received `Out`, which several users found confusing.

The new ordering (out before over globally, over before out locally per entity) should make it much easier to write hover state cleanup code.

2024-11-04 15:53 UTC, alice-i-cecile approved these changes
Really excellent docs. I'd *love* to have some tests to verify that order, but that's a ton of extra work and I won't block on it.

2024-11-04 15:55 UTC, NthTensor commented
> I'd love to have some tests to verify that order, but that's a ton of extra work and I won't block on it.

ooh good idea. I think this will make sense to do as part of the next winit upgrade, because the way this pointer stuff interacts with their pointer stuff will be complex and not entirely owned by us.

2024-11-06 17:24 UTC, doup requested changes
The comment on pointer presses might be wrong? I think it should say `down/click/up`. Apart from that the ordering explained at the beginning looks consistent with the code.

Btw, great docs 👍

2024-11-06 17:27 UTC, NthTensor commented on crates/bevy_picking/src/events.rs
> +///   [`Down`], [`Up`], [`Click`].
Good catch. I'll fix that, ty.

2024-11-11 22:57 UTC, mockersf commented
@NthTensor could you look into the conflict and fixing the order in the comment?

2024-11-12 04:04 UTC, NthTensor commented
Yep, thanks for the poke.

2024-11-15 11:07 UTC, doup approved these changes

2024-11-15 15:59 UTC, merged