Fix panic in UiSurface if Node is removed and re-added
bevyengine/bevy pull request #16288
Opened 2024-11-08 01:47 UTC by UkoeHB

# Objective

- Fix bug where `UiSurface::set_camera_children` will panic if you remove and add a `Node` component in a single tick.

## Solution

- Filter out entities with `Node` when cleaning up entities from `RemovedComponents<Node>`.

## Testing

- Not tested, correct by inspection.

2024-11-08 21:49 UTC, mockersf approved these changes

2024-11-09 20:33 UTC, richchurcher approved these changes

2024-11-09 21:33 UTC, BenjaminBrienen commented
This should have a test to prove that it works and prevent regressions. Can you add one?

2024-11-10 00:00 UTC, BenjaminBrienen requested changes

2024-11-10 00:00 UTC, BenjaminBrienen commented on crates/bevy_ui/src/layout/mod.rs
> +    /// bugfix test, see https://github.com/bevyengine/bevy/pull/16288
```
    /// bugfix test, see [#16288](https://github.com/bevyengine/bevy/pull/16288)
```

2024-11-10 00:01 UTC, BenjaminBrienen approved these changes

2024-11-11 22:21 UTC, merged