Rename `AnimationGraph`
bevyengine/bevy pull request #16280
Opened 2024-11-07 18:49 UTC by BenjaminBrienen

# Objective

Fixes #15604

## Solution

Replace "AnimationGraph" with "BlendGraph".

TODO: Update the comments. I see a lot of "`// animation graph`". I'll do this once this is blessed and the scope has been determined.

## Testing

Simple refactor can be evaluated by CI

## Migration Guide

I'll create this once this has been blessed.

2024-11-07 18:50 UTC, BenjaminBrienen commented
The scope of this task needs to be precisely defined. What other types should be renamed for clarity? Should the term "blend" be used in documentation as well?

2024-12-07 16:25 UTC, hukasu commented
Shouldn't the name of the file also be renamed from `animatable.rs` to `blendable.rs`?

And what about the extension of the `AnimationGraphAssetLoader` from `.animgraph` to `.blendgraph`?

2024-12-07 18:29 UTC, BenjaminBrienen commented
Good ideas, thanks.

2025-01-05 04:42 UTC, pcwalton approved these changes
I don't have any problem with this.

2025-01-10 15:11 UTC, mweatherley requested changes
I'm fine with this, but there are still a bunch of places in `animatable.rs` and `animation_curves.rs` where "animatable" should be changed to "blendable" (including the name of the former module, probably).

2025-03-09 19:30 UTC, alice-i-cecile commented
Marking as Adopt-Me: I still think this is a good change (and there's support from animation experts), but there's more work to do here and a boatload of merge conflicts.

2026-05-22 10:59 UTC, ChristopherBiscardi commented
adoption attempt in https://github.com/bevyengine/bevy/pull/22782 so closing this one

2026-05-22 10:59 UTC, closed without merging