Fix markdownlint warnings and improve consistency with config (reduced)
bevyengine/bevy pull request #16308
Opened 2024-11-09 03:42 UTC by BenjaminBrienen

# Objective

Markdown files should have a consistent style which promotes readability for development purposes.

## Solution

Use #16306 and remove the line length changes.

Add configuration for extensions with all settings explicitly configured. Extend the base config for a couple scenarios.
Fix the inconsistent `ul` style in all markdown files. Fix the inconsistent table style in the templated README.
Make the language on code fences consistent.
Other minor improvements.

I'm not sure if changing `rust,no_run` to `rust no_run` is okay. It fixes markdownlint thinking that `rust,no_run` is all part of the language.

## Testing

Manual testing of that one caveat is to-do.

2024-11-09 10:14 UTC, BenjaminBrienen commented on .github/pull_request_template.md
> -  <summary>Click to view showcase</summary>
I didn't even see the closing tag. I'll add it back.

2024-11-09 10:15 UTC, BenjaminBrienen commented on CONTRIBUTING.md
> +Go give it a read, and thanks for contributing!
That's unfortunate and makes it impossibly to deal with line length if we choose to turn that on.

2024-11-09 16:05 UTC, alice-i-cecile commented on .github/pull_request_template.md
> +> If this PR does not include a visual change or does not add a new feature, you can delete this section.
This is a good example of why I think that the line length linting is undesirable.

2024-11-09 16:06 UTC, alice-i-cecile commented on CONTRIBUTING.md
> +Go give it a read, and thanks for contributing!
Yep, that's why I think we shouldn't turn on line length linting.

2024-11-10 00:35 UTC, BenjaminBrienen commented on .github/.markdownlint.jsonc
This file is for the extension, whereas the CI uses the `.yml` file.

2025-01-02 21:10 UTC, BenjaminBrienen commented on docs-template/EXAMPLE_README.md.tpl
> +|Example | Description |
```suggestion
| Example | Description |
```

2025-01-02 21:10 UTC, BenjaminBrienen commented on docs-template/EXAMPLE_README.md.tpl
> +[crates.io](https://crates.io/crates/bevy) release and the development version of Bevy in the git main branch!
```suggestion
There are often large differences and incompatible API changes between the latest [crates.io](https://crates.io/crates/bevy) release and the development version of Bevy in the git main branch!
```

2025-01-02 21:10 UTC, BenjaminBrienen commented on docs-template/EXAMPLE_README.md.tpl
> +option `--features x11` or `--features wayland` to force the example to run on a specific window compositor, e.g.
```suggestion
To run an example, use the command `cargo run --example <Example>`, and add the option `--features x11` or `--features wayland` to force the example to run on a specific window compositor, e.g.
```

2025-01-02 21:10 UTC, BenjaminBrienen commented on Cargo.toml
> +The GPU executes these programs in a highly parallel way.
```suggestion
A shader in its most common usage is a small program that is run by the GPU per-vertex in a mesh (a vertex shader) or per-affected-screen-fragment (a fragment shader.) The GPU executes these programs in a highly parallel way.
```

2025-01-02 21:10 UTC, BenjaminBrienen commented on docs-template/EXAMPLE_README.md.tpl
> +This page also describes a JS workaround to resume audio as soon as the user interact with your game.
```suggestion
In browsers, audio is not authorized to start without being triggered by a user interaction. This is to avoid multiple tabs all starting to auto play some sounds. You can find more context and explanation for this on [Google Chrome blog](https://developer.chrome.com/blog/web-audio-autoplay/). This page also describes a JS workaround to resume audio as soon as the user interacts with your game.
```

2025-01-02 21:10 UTC, BenjaminBrienen commented on docs-template/EXAMPLE_README.md.tpl
> +Not all browsers react the same way for all games, you will have to experiment for your game.
```suggestion
For the moment, everything is single threaded. This can lead to stuttering when playing audio in browsers. Not all browsers react the same way for all games. You will have to experiment with your game.
```

2025-01-02 21:10 UTC, BenjaminBrienen commented on docs-template/EXAMPLE_README.md.tpl
> +feature enabled won't be able to run on browsers that don't support WebGPU.
```suggestion
To build for WebGPU, you'll need to enable the `webgpu` feature. This will override the `webgl2` feature, and builds with the `webgpu` feature enabled won't be able to run on browsers that don't support WebGPU.
```

2025-01-02 21:10 UTC, BenjaminBrienen commented on docs-template/EXAMPLE_README.md.tpl
> +|`ios` | [`mobile/src/lib.rs`](./mobile/src/lib.rs) | A 3d Scene with a button and playing sound|
```suggestion
| Example | File | Description |
| --- | --- | --- |
| `ios` | [`mobile/src/lib.rs`](./mobile/src/lib.rs) | A 3d Scene with a button and playing sound |
```

2025-01-02 21:10 UTC, BenjaminBrienen commented on docs-template/EXAMPLE_README.md.tpl
> +|`android` | [`mobile/src/lib.rs`](./mobile/src/lib.rs) | A 3d Scene with a button and playing sound|
```suggestion
| Example | File | Description |
| --- | --- | --- |
|`android` | [`mobile/src/lib.rs`](./mobile/src/lib.rs) | A 3d Scene with a button and playing sound |
```

2025-01-02 21:10 UTC, BenjaminBrienen commented on docs-template/EXAMPLE_README.md.tpl
> +instructions(`app/CMakeList.txt`, `app/build.gradle`, `app/src/main/cpp/dummy.cpp`).
```suggestion
Alternatively, you can modify project files to include it when building an APK. To understand the specific steps taken in this project, please refer to the comments within the project files for detailed instructions(`app/CMakeList.txt`, `app/build.gradle`, `app/src/main/cpp/dummy.cpp`).
```

2025-01-02 21:10 UTC, BenjaminBrienen commented on docs-template/EXAMPLE_README.md.tpl
> +automation, as described in the `cargo-ndk` [README](https://github.com/bbqsrc/cargo-ndk?tab=readme-ov-file#linking-against-and-copying-libc_sharedso-into-the-relevant-places-in-the-output-directory)
```suggestion
To include it, you can manually obtain it from NDK source or use a `build.rs` script for automation, as described in the `cargo-ndk` [README](https://github.com/bbqsrc/cargo-ndk?tab=readme-ov-file#linking-against-and-copying-libc_sharedso-into-the-relevant-places-in-the-output-directory).
```

2025-01-02 21:10 UTC, BenjaminBrienen commented on docs-template/EXAMPLE_README.md.tpl
> +but typically `cargo-ndk` does not copy this file automatically.
```suggestion
Bevy may require `libc++_shared.so` to run on Android, as it is needed by the `oboe` crate, but typically `cargo-ndk` does not copy this file automatically.
```

2025-01-02 21:10 UTC, BenjaminBrienen commented on docs-template/EXAMPLE_README.md.tpl
> +directories under `jniLibs` where the JNI can find them.
```suggestion
Setting the output path ensures the shared object files can be found in target-specific directories under `jniLibs` where the JNI can find them.
```

2025-01-02 21:10 UTC, BenjaminBrienen commented on docs-template/EXAMPLE_README.md.tpl
> +must also be set to one of the NDKs in `sdk\ndk\[NDK number]`.
```suggestion
When using `NDK (Side by side)`, the environment variable `ANDROID_NDK_ROOT` must also be set to one of the NDKs in `sdk\ndk\[NDK number]`.
```

2025-01-02 21:27 UTC, BenjaminBrienen commented on examples/README.md
> +option `--features x11` or `--features wayland` to force the example to run on a specific window compositor, e.g.
```suggestion
To run an example, use the command `cargo run --example <Example>`, and add the option `--features x11` or `--features wayland` to force the example to run on a specific window compositor, e.g.
```

2025-01-02 21:27 UTC, BenjaminBrienen commented on examples/README.md
> +This page also describes a JS workaround to resume audio as soon as the user interact with your game.
```suggestion
In browsers, audio is not authorized to start without being triggered by a user interaction. This is to avoid multiple tabs all starting to auto play some sounds. You can find more context and explanation for this on [Google Chrome blog](https://developer.chrome.com/blog/web-audio-autoplay/). This page also describes a JS workaround to resume audio as soon as the user interacts with your game.
```

2025-01-02 21:27 UTC, BenjaminBrienen commented on examples/README.md
> +Not all browsers react the same way for all games, you will have to experiment for your game.
```suggestion
For the moment, everything is single threaded. This can lead to stuttering when playing audio in browsers. Not all browsers react the same way for all games. You will have to experiment with your game.
```

2025-01-02 21:27 UTC, BenjaminBrienen commented on examples/README.md
> +feature enabled won't be able to run on browsers that don't support WebGPU.
```suggestion
To build for WebGPU, you'll need to enable the `webgpu` feature. This will override the `webgl2` feature, and builds with the `webgpu` feature enabled won't be able to run on browsers that don't support WebGPU.
```

2025-01-02 21:27 UTC, BenjaminBrienen commented on examples/README.md
> +which can be loaded using this [example HTML file](./wasm/index.html).
```suggestion
javascript bindings to this wasm file in the output file `examples/wasm/target/wasm_example.js`, which can be loaded using this 
 [example HTML file](./wasm/index.html).
```

2025-01-03 22:31 UTC, alice-i-cecile approved these changes

2025-05-16 14:07 UTC, Trashtalk217 approved these changes

2025-05-19 20:00 UTC, mockersf requested changes

2025-05-19 20:00 UTC, mockersf commented on .markdownlint.jsonc
please don't add files at the root of the repo

2025-05-19 20:03 UTC, BenjaminBrienen commented on .markdownlint.jsonc
Then it won't affect MD files in the repo root. What do you suggest?

2025-05-19 20:10 UTC, mockersf commented on .markdownlint.jsonc
sticking to the default config

2026-05-05 03:44 UTC, closed without merging

2026-05-05 19:46 UTC, cart commented
Hey @BenjaminBrienen! I'm not sure what the current state of this PR is, but just as a heads up the closing and re-opening was something I did in an automated fashion to fix the PR after changing the history on `main`. This wasn't intended to be a signal that we want to shut this down. Feel free to re-open if you want!

2026-05-05 22:16 UTC, BenjaminBrienen commented
I'm closing it because I lost interest 👍