Only use physical coords internally in `bevy_ui`
bevyengine/bevy pull request #16375
Opened 2024-11-13 13:43 UTC by ickshonpe

# Objective

Use physical coords everwhere internally in the UI.

## Solution

Store physical coords in `Node` and tear out all the unneeded scale factor calculations and queries.

2024-11-16 11:17 UTC, doup approved these changes

2024-11-16 13:15 UTC, BenjaminBrienen approved these changes

2024-11-19 22:19 UTC, atlv24 approved these changes
This needs a migration guide. Its a particularly sneaky type of breaking change, because it causes almost no compile errors, but underlying semantics change. @BenjaminBrienen @doup have you tested these changes/run any examples? I haven't yet.

2024-11-19 22:19 UTC, atlv24 commented on crates/bevy_ui/src/render/mod.rs
> +        if let (Some(physical_viewport_rect),) = (camera.physical_viewport_rect(),) {
whats the point of the tuple on either side of this let?
```suggestion
        if let Some(physical_viewport_rect) = camera.physical_viewport_rect() {
```

2024-11-19 22:19 UTC, atlv24 commented on crates/bevy_ui/src/render/mod.rs
> +                            atlas_scaling: Vec2::splat(1.),
I think there's `Vec2::ONE`

2024-11-21 10:38 UTC, doup requested changes
@atlv24 I ran the UI testbed and a couple more examples. But, now I checked some other random example and there are indeed issues. 😬

So… I've run all the examples and these are the issues I've found:

- border width are different (example: `borders`, `ui_texture_atlas`)
- texture atlas slice border width (example: `ui_texture_atlas_slice`, `ui_texture_slice_flip_and_tile`, `ui_texture_slice`)
- border radius are different (example: `box_shadow`)
- text wrapping (examples: `grid` sidebar text, `scroll`, `text_debug`, `text_wrap_debug`)
- wrong text/box (?) alignment, could be because of the wrapping issue (examples: `display_and_visibility`, `text`, `size_constraints`)
- overflow clip margin (example: `overflow_clip_margin`)
- a panic! (example: `overflow_debug`)

2024-11-21 13:23 UTC, ickshonpe commented
> @atlv24 I ran the UI testbed and a couple more examples. But, now I checked some other random example and there are indeed issues. 😬
> 
> So… I've run all the UI examples and this is what I've found:
> 
> * border width are different (example: `borders`, `ui_texture_atlas`)
> * texture atlas slice border width (example: `ui_texture_atlas_slice`, `ui_texture_slice_flip_and_tile`, `ui_texture_slice`)
> * border radius are different (example: `box_shadow`)
> * text wrapping (examples: `grid` sidebar text, `scroll`, `text_debug`, `text_wrap_debug`)
> * wrong text/box (?) alignment, could be because of the wrapping issue (examples: `display_and_visibility`, `text`, `size_constraints`)
> * overflow clip margin (example: `overflow_clip_margin`)
> * a panic! (example: `overflow_debug`)

I think all of these are fixed now.

2024-11-21 20:50 UTC, doup approved these changes
Everything is fine now! 🎉

2024-11-21 21:42 UTC, atlv24 approved these changes
ran the ui examples, all looks good, and migration guide is good!

2024-11-22 00:30 UTC, cart approved these changes

2024-11-22 01:02 UTC, merged