bevy_picking UI example
bevyengine/bevy pull request #16412
Opened 2024-11-17 04:25 UTC by richchurcher

# Objective

This example demonstrates responding to picking events within the UI context.

## Solution

It's been fun playing with this, but I'm also open to changing it dramatically if it doesn't quite meet our needs. I was trying to think of a way to demonstrate without making the example too complex. With one-shot systems, I may not have succeeded there... but they do reduce the overall masses of nested UI code, which helps with readability.

I'm also aware other examples partially cover this territory, like `sprite_picking`.

I did have some hover highlighting in there, but took it out to reduce length/complexity.

2024-11-17 04:29 UTC, richchurcher commented
Heh. It kinda broke with some of the latest changes... :eyes: :construction:

2024-11-17 20:22 UTC, richchurcher commented on examples/picking/ui_picking.rs
> +                    ZIndex(99),
Note to self: `GlobalZIndex` is a thing.

2024-11-23 06:35 UTC, richchurcher commented on examples/picking/ui_picking.rs
> +        transform.scale *= 4.;
Maybe `ComputedNode::size()`? Something to investigate.

2025-02-26 00:35 UTC, alice-i-cecile commented on Cargo.toml
> +description = "Demonstrates picking in a UI context"
```suggestion
description = "Demonstrates using picking to build a drag-and-drop UI"
```

2025-02-26 00:38 UTC, alice-i-cecile requested changes
Generally like this, but I don't understand why we're returning `impl Fn` closures here. They're much more complex to reason about, and I don't think they're needed.

2026-05-22 12:26 UTC, ChristopherBiscardi commented
no answer to previous change requests, plus with bsn it definitely doesn't make sense to run_system_cached here.

2026-05-22 12:26 UTC, closed without merging