Add `Commands::run_schedule`
bevyengine/bevy pull request #16537
Opened 2024-11-28 03:31 UTC by bushrat011899

# Objective

- Fixes #16495

## Solution

- Added `Commands::run_schedule`, which internally calls `World::try_run_schedule`, logging any issues.

## Testing

- Added doctest
- Ran CI

2024-11-28 04:00 UTC, alice-i-cecile approved these changes
Not just unwrapping I see :P I think this is good default behavior, but we'll need to come back and change this when we tackle command error handling.

2024-11-28 04:04 UTC, bushrat011899 commented
> Not just unwrapping I see :P I think this is good default behavior, but we'll need to come back and change this when we tackle command error handling.

I was half tempted to do `// TODO: commands need a coherent error handling policy` but I thought I'd just sneak in my preferred solution!

2024-11-28 08:53 UTC, BenjaminBrienen approved these changes

2024-12-01 16:15 UTC, mockersf requested changes
I would prefer this to panic until there's a way to react in code to errors

Running a schedule that doesn't exist doesn't seem like something that should be ignored and you would still expect everything working

2024-12-01 16:24 UTC, BenjaminBrienen commented
Does `error!` not set the right expectation?

2024-12-01 17:01 UTC, mockersf commented
no, you can't react to it in code

2024-12-02 22:16 UTC, mockersf approved these changes

2024-12-02 22:32 UTC, merged