Forward decals (port of bevy_contact_projective_decals)
bevyengine/bevy pull request #16600
Opened 2024-12-02 04:58 UTC by JMS55

# Objective

- Describe the objective or issue this PR addresses.
- If you're fixing a specific issue, say "Fixes #X".

## Solution

- Describe the solution used to achieve the objective above.

## Testing

- Did you test these changes? If so, how?
- Are there any parts that need more testing?
- How can other people (reviewers) test your changes? Is there anything specific they need to know?
- If relevant, what platforms did you test these changes on, and are there any important ones you can't test?

---

## Showcase

> This section is optional. If this PR does not include a visual change or does not add a new feature, you can delete this section.

- Help others understand the result of this PR by showcasing your awesome work!
- If this PR adds a new feature or public API, consider adding a brief pseudo-code snippet of it in action
- If this PR includes a visual change, consider adding a screenshot, GIF, or video
  - If you want, you could even include a before/after comparison!
- If the Migration Guide adequately covers the changes, you can delete this section

While a showcase should aim to be brief and digestible, you can use a toggleable section to save space on longer showcases:

<details>
  <summary>Click to view showcase</summary>

```rust
println!("My super cool code.");
```

</details>

## Migration Guide

> This section is optional. If there are no breaking changes, you can delete this section.

- If this PR is a breaking change (relative to the last release of Bevy), describe how a user might need to migrate their code to support these changes
- Simply adding new functionality is not a breaking change.
- Fixing behavior that was definitely a bug, rather than a questionable design choice is not a breaking change.

2025-01-11 18:45 UTC, JMS55 commented on crates/bevy_pbr/src/decal/forward.rs
> +    /// Units are in meters.
> Units are in meters.
I think?

2025-01-12 01:12 UTC, pcwalton requested changes
I got:

```
2025-01-12T01:11:09.471156Z ERROR bevy_render::render_resource::pipeline_cache: failed to process shader:
error: failed to build a valid final module: Function [74] 'bevy_pbr::decal::forward::get_forward_decal_info' is invalid
   ┌─ crates\bevy_pbr\src\decal\forward_decal.wgsl:22:1
   │
22 │ ╭   fn get_forward_decal_info(in: bevy_pbr::forward_io::VertexOutput) -> ForwardDecalInformation {
23 │ │       let world_from_local = bevy_pbr::mesh_functions::get_world_from_local(in.instance_index);
24 │ │       let scale = (world_from_local * vec4(1.0, 1.0, 1.0, 0.0)).xyz;
25 │ │       let scaled_tangent = vec4(in.world_tangent.xyz / scale, in.world_tangent.w);
   · │
44 │ │       let uv = bevy_pbr::parallax_mapping::parallaxed_uv(
   │ │ ╭──────────────^
45 │ │ │         normal_depth,
46 │ │ │         1.0,
47 │ │ │         0u,
48 │ │ │         in.uv,
49 │ │ │         Vt,
   │ │ ╰──────────^ invalid function call
   · │ │
54 │ │
55 │ │       return ForwardDecalInformation(world_position, uv, alpha);
   │ ╰────────────────────────────────────────────────────────────────^ naga::Function [74]
   │
   = Call to [72] is invalid
   = Requires 6 arguments, but 5 are provided
```

2025-01-12 01:12 UTC, pcwalton commented on crates/bevy_pbr/src/extended_material.rs
> +    fn alpha_mode(&self) -> AlphaMode {
This is technically a breaking change and should be documented as such.

2025-01-12 21:26 UTC, JMS55 commented on crates/bevy_pbr/src/extended_material.rs
> +    fn alpha_mode(&self) -> AlphaMode {
It's not a breaking change, because E::alpha_mode() did not exist until now.

2025-01-12 21:26 UTC, JMS55 commented on crates/bevy_pbr/src/decal/forward_decal.wgsl
> +fn project_onto(lhs: vec3<f32>, rhs: vec3<f32>) -> vec3<f32> {
Ehh I don't really know how the math works, so I'd rather leave it there. If someone else wants to move it and add some docs they can.

2025-01-12 21:29 UTC, pcwalton commented on crates/bevy_pbr/src/decal/forward_decal.wgsl
> +fn project_onto(lhs: vec3<f32>, rhs: vec3<f32>) -> vec3<f32> {
FYI the math is described here https://en.wikipedia.org/wiki/Vector_projection#Vector_projection_2

2025-01-12 21:41 UTC, JMS55 commented on crates/bevy_pbr/src/decal/forward_decal.wgsl
> +fn project_onto(lhs: vec3<f32>, rhs: vec3<f32>) -> vec3<f32> {
Moved

2025-01-12 21:47 UTC, JMS55 commented
Updated the PR, but I don't know why bevy_contact_projective_decals is calling parallaxed_uv() which samples the material's depth map, which for custom materials won't exist, and for standard material will probably be a placeholder.

2025-01-13 00:47 UTC, JMS55 commented
Fixed it, removed parallaxed_uv().

2025-01-13 01:59 UTC, pcwalton approved these changes

2025-01-14 02:22 UTC, IceSentry approved these changes

2025-01-14 02:24 UTC, IceSentry commented on examples/3d/decal.rs
> +    let num_obs = 10;
```suggestion
	// Spawn a few cube with random rotations to showcase how the decals behave with non-flat geometry
    let num_obs = 10;
```

2025-01-14 02:24 UTC, IceSentry commented on examples/3d/decal.rs
> +    commands.spawn((
```suggestion
	// Spawn the forward decal
    commands.spawn((
```

2025-01-14 02:26 UTC, IceSentry commented on examples/3d/decal.rs
> +            extension: ForwardDecalMaterialExt {
```suggestion
			// The decal material is implemented as an extended material
			// The default implementation extends the StandardMaterial so decals are rendered using PBR
            extension: ForwardDecalMaterialExt {
```

2025-01-14 02:26 UTC, IceSentry commented on examples/3d/decal.rs
> +        EnvironmentMapLight {
For the purpose of keeping the example short, I would remove the env light. I don't think it adds anything.

2025-01-14 02:27 UTC, IceSentry commented
I suggested a few comments for the example. They don't need to be used verbatim, but a few comments like those would be nice.

2025-01-14 04:06 UTC, IceSentry commented
Not sure if it's related to this PR, but a few examples are broken when running this PR https://pixel-eagle.com/project/B25A040A-A980-4602-B90C-D480AB84076D?filter=PR-16600

2025-01-14 04:13 UTC, JMS55 commented
I doubt it's related, probably just non-deterministic examples.

2025-01-15 01:38 UTC, JMS55 commented on examples/3d/decal.rs
> +        EnvironmentMapLight {
My lighting 😭. I'll remove it though.

2025-01-15 02:50 UTC, merged

2025-03-25 20:07 UTC, alice-i-cecile commented
Thank you to everyone involved with the authoring or reviewing of this PR! This work is relatively important and needs release notes! Head over to https://github.com/bevyengine/bevy-website/issues/1980 if you'd like to help out.