Expose `SystemMeta`'s access field as part of public API
bevyengine/bevy pull request #16625
Opened 2024-12-03 11:24 UTC by vil-mo

# Objective

Outside of the `bevy_ecs` crate it's hard to implement `SystemParam` trait on params that require access to the `World`, because `init_state` expects user to extend access in `SystemMeta` and access-related fields of `SystemMeta` are private.

## Solution

Expose those fields as a functions

2024-12-03 11:26 UTC, BenjaminBrienen approved these changes
^_^

2024-12-03 16:21 UTC, alice-i-cecile requested changes
Great docs, and I think we should expose this. That said, the mutable accessors need to be unsafe. If you lie about the access you can get UB by allowing aliased mutability at both the schedule and system levels.

2024-12-03 20:05 UTC, alice-i-cecile approved these changes

2024-12-04 00:38 UTC, chescock approved these changes

2024-12-05 18:28 UTC, merged