Rename `EntityCommands::clone` to `spawn_clone`
bevyengine/bevy pull request #16696
Opened 2024-12-06 22:48 UTC by JaySpruce

## Objective

Follow-up to #16672.

`EntityCommands::clone` looks the same as the `Clone` trait, which could be confusing. A discord discussion has made me realize that's probably a bigger problem than I thought. Oops :P

## Solution

Renamed `EntityCommands::clone` to `EntityCommands::spawn_clone`, renamed `EntityCommands::clone_with` to `EntityCommands::spawn_clone_with`. Also added some docs explaining the commands' relation to `Clone` (components need to implement it (or `Reflect`)).

## Showcase

```
// Create a new entity and keep its EntityCommands
let mut entity = commands.spawn((ComponentA(10), ComponentB(20)));

// Create a clone of the first entity
let mut entity_clone = entity.spawn_clone();
```

2024-12-06 22:50 UTC, rparrett commented
Here's a link to the referenced conversation.

https://discord.com/channels/691052431525675048/749335865876021248/1314635145650638960

2024-12-06 22:55 UTC, JaySpruce commented
Credit to @eugineerd for the neat feature, sorry for repeatedly nitpicking it :P

2024-12-08 15:34 UTC, alice-i-cecile requested changes
I definitely think we should rename this, but I find `spawn_clone` quite awkward and unclear. Are you okay with `clone_and_spawn` instead?

2024-12-08 15:49 UTC, rparrett commented
What about `spawn_cloned`?

Also cc @benfrankel who suggested `spawn_clone`.

2024-12-08 16:38 UTC, alice-i-cecile commented
That's also an improvement, but I think that the order of operations (spawn, then clone) is clearest with my suggestion :)

2024-12-09 18:52 UTC, alice-i-cecile approved these changes

2024-12-10 03:43 UTC, merged