Cache systems by `S` instead of `S::System`
bevyengine/bevy pull request #16694
Opened 2024-12-06 20:33 UTC by benfrankel

# Objective

- Fixes the issue described in this comment: https://github.com/bevyengine/bevy/issues/16680#issuecomment-2522764239.

## Solution

- Cache one-shot systems by `S: IntoSystem` (which is const-asserted to be a ZST) rather than `S::System: System`.

## Testing

Not tested besides CI.

---

## Migration Guide

The struct `CachedSystemId` has been changed:

```rust
// Old:
struct CachedSystemId<S: System>(SystemId<S::In, S::Out>);

// New:
struct CachedSystemId<S> { id: Entity, .. }
```

2024-12-06 21:35 UTC, chescock approved these changes

2024-12-07 00:17 UTC, alice-i-cecile requested changes
I like this change, but it needs a test :)

2025-03-04 04:26 UTC, benfrankel commented
Added a unit test for this.

2025-03-04 04:32 UTC, alice-i-cecile approved these changes

2025-03-04 04:37 UTC, alice-i-cecile commented
Ping me when CI is green please?

2025-03-04 05:21 UTC, benfrankel commented
@alice-i-cecile CI passes now.

2025-03-04 08:35 UTC, merged