Formatting cleanup
bevyengine/bevy pull request #1670
Opened 2021-03-16 19:43 UTC by alice-i-cecile

Fixes trivial (but noisy) formatting changes; caused by running unstable `cargo fmt` features from rustfmt.toml.

2021-03-17 16:28 UTC, Ratysz requested changes

2021-03-17 16:28 UTC, Ratysz commented on crates/bevy_ecs/src/schedule/state.rs
> +    /// current state
```suggestion
    /// current state.
```

2021-03-17 16:28 UTC, Ratysz commented on crates/bevy_ecs/src/schedule/state.rs
> +    /// instead of failing
```suggestion
    /// instead of failing.
```

2021-03-17 16:28 UTC, Ratysz commented on crates/bevy_ecs/src/schedule/state.rs
> +    /// instead of failing
```suggestion
    /// instead of failing.
```

2021-03-17 16:28 UTC, Ratysz commented on crates/bevy_ecs/src/schedule/state.rs
> +    /// instead of failing
```suggestion
    /// instead of failing.
```

2021-03-17 17:31 UTC, Ratysz approved these changes

2021-04-12 21:54 UTC, cart commented
Can you either re-run this on `main` or resolve merge conflicts?

2021-04-13 01:37 UTC, alice-i-cecile commented
Fixing this will be more work than redoing it. Opening a new PR quick.

2021-04-13 01:37 UTC, closed without merging