Use explicitly added `ApplyDeferred` stages when computing automatically inserted sync points.
bevyengine/bevy pull request #16782
Opened 2024-12-12 09:01 UTC by andriyDev

# Objective

- The previous implementation of automatically inserting sync points did not consider explicitly added sync points. This created additional sync points. For example:

```
A-B
C-D-E
```

If `A` and `B` needed a sync point, and `D` was an `ApplyDeferred`, an additional sync point would be generated between `A` and `B`.

```
A-D2-B
C-D -E
```

This can result in the following system ordering:
```
A-D2-(B-C)-D-E
```
Where only `B` and `C` run in parallel. If we could reuse `D` as the sync point, we would get the following ordering:
```
(A-C)-D-(B-E)
```
Now we have two more opportunities for parallelism!

## Solution

- In the first pass, we:
    - Compute the number of sync points before each node
        - This was already happening but now we consider `ApplyDeferred` nodes as creating a sync point.
    - Pick an arbitrary explicit `ApplyDeferred` node for each "sync point index" that we can (some required sync points may be missing!)
- In the second pass, we:
    - For each edge, if two nodes have a different number of sync points before them then there must be a sync point between them.
    - Look for an explicit `ApplyDeferred`. If one exists, use it as the sync point.
    - Otherwise, generate a new sync point.

## Testing

- Added a test to test the feature.
-  The existing tests from all our crates still pass.

## Showcase

- Automatically inserted sync points can now reuse explicitly inserted `ApplyDeferred` systems! Previously, Bevy would add new sync points between systems, ignoring the explicitly added sync points. This would reduce parallelism of systems in some situations. Now, the parallelism has been improved!

2024-12-12 10:08 UTC, andriyDev commented
One thing I'm not fully certain of is whether this unlocks more parallelism. The naive answer is fewer sync points = more parallelism. However this depends on how the multi-threaded executor works. AFAIK, the systems are topologically sorted, and then when a system finishes, an executor thread wakes up, iterates through the list of unfinished systems, finds the first one whose dependencies are satisfied (before systems), and runs that.

I'm not certain how system accesses relate to this. Perhaps a systems dependencies just be satisfied AND its accesses must be satisfied, otherwise it is skipped. This would imply that ApplyDeferred systems would always be "pushed back" as far as they can be since it obviously requires full world access. So even if we have two sync points, the prior systems would end up "pushing them" next to each other in many cases. This could lead to "starvation" though, so maybe that's not how it works? I need to dig in to how the executor works!

2024-12-12 19:32 UTC, alice-i-cecile commented
Good: this was part of the future work that we put off when merging the initial PR.

2024-12-13 00:21 UTC, hymm commented
ran the build_schedule benches and seems about the same. The extra pass doesn't seem too expensive. I guess it was probably the extra topo sort that was expensive in the original pr.

```text
group                                         apply_deferred                         main_for_apply_deferred
-----                                         --------------                         -----------------------
build_schedule/1000_schedule                  1.00       2.1±0.15s        ? ?/sec    1.00       2.1±0.15s        ? ?/sec
build_schedule/1000_schedule_noconstraints    1.00     27.1±2.29ms        ? ?/sec    1.00     27.2±2.33ms        ? ?/sec
build_schedule/100_schedule                   1.00      8.6±1.01ms        ? ?/sec    1.00      8.6±0.83ms        ? ?/sec
build_schedule/100_schedule_noconstraints     1.00   437.9±40.73µs        ? ?/sec    1.08   473.8±41.74µs        ? ?/sec
build_schedule/500_schedule                   1.00   387.5±35.70ms        ? ?/sec    1.01   390.5±37.29ms        ? ?/sec
build_schedule/500_schedule_noconstraints     1.00      7.1±0.65ms        ? ?/sec    1.00      7.1±0.61ms        ? ?/sec
```

2024-12-13 01:59 UTC, andriyDev commented
@hymm How are you generating that benchmark? I tried running the benchmark locally, once with main and once with this PR and got the following:
```
~/bevy/benches (deferred) $ cargo bench build_schedule
   Compiling benches v0.0.0 (E:\Content\bevy\benches)
    Finished `bench` profile [optimized] target(s) in 4m 15s
     Running benches/bevy_ecs/main.rs (target\release\deps\ecs-d2da3142124a85f3.exe)
Gnuplot not found or not usable, using plotters backend
`gnuplot --version` returned an unparseable version string: gnuplot 6.0 patchlevel 1

build_schedule/100_schedule_noconstraints
                        time:   [726.73 µs 729.60 µs 732.60 µs]
                        change: [+1.5341% +2.0926% +2.6640%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 2 outliers among 100 measurements (2.00%)
  2 (2.00%) high mild
build_schedule/100_schedule
                        time:   [10.889 ms 11.275 ms 11.697 ms]
                        change: [+11.464% +15.498% +20.594%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 6 outliers among 100 measurements (6.00%)
  5 (5.00%) high mild
  1 (1.00%) high severe
build_schedule/500_schedule_noconstraints
                        time:   [12.233 ms 12.428 ms 12.626 ms]
                        change: [+22.118% +24.134% +26.229%] (p = 0.00 < 0.05)
                        Performance has regressed.
Benchmarking build_schedule/500_schedule: Warming up for 500.00 ms
Warning: Unable to complete 100 samples in 15.0s. You may wish to increase target time to 53.4s, or reduce sample count to 20.
build_schedule/500_schedule
                        time:   [468.93 ms 477.26 ms 485.64 ms]
                        change: [+19.192% +21.547% +24.130%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild
build_schedule/1000_schedule_noconstraints
                        time:   [45.864 ms 46.657 ms 47.519 ms]
                        change: [+25.115% +27.296% +29.666%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 5 outliers among 100 measurements (5.00%)
  3 (3.00%) high mild
  2 (2.00%) high severe
Benchmarking build_schedule/1000_schedule: Warming up for 500.00 ms
Warning: Unable to complete 100 samples in 15.0s. You may wish to increase target time to 277.9s, or reduce sample count to 10.
build_schedule/1000_schedule
                        time:   [2.4158 s 2.4411 s 2.4681 s]
                        change: [+6.4100% +7.6148% +8.8132%] (p = 0.00 < 0.05)
                        Performance has regressed.
```

Our delta seems to be about +7%. I'm on Windows, but I'm surprised if there's such a substantial difference between OSes (that's my guess).

2024-12-13 03:41 UTC, hymm commented
pretty much what you're doing except using `critcmp` to make a nice table. https://github.com/BurntSushi/critcmp

I do run a few times to make sure I'm getting consistent result and making sure the diffs aren't in the noise of my cpu perf. For these result I ran on my laptop I changed to silent mode, since the normal mode was too noisy.

2024-12-13 08:21 UTC, andriyDev commented
Ah after using critcmp I got similar results:
```
group                                         deferred                               main
-----                                         --------                               ----
build_schedule/1000_schedule                  1.00       2.3±0.06s        ? ?/sec    1.05       2.4±0.11s        ? ?/sec
build_schedule/1000_schedule_noconstraints    1.07     41.5±3.04ms        ? ?/sec    1.00     39.0±1.29ms        ? ?/sec
build_schedule/100_schedule                   1.00      9.6±0.34ms        ? ?/sec    1.03     10.0±0.33ms        ? ?/sec
build_schedule/100_schedule_noconstraints     1.01   723.7±15.73µs        ? ?/sec    1.00   713.1±22.68µs        ? ?/sec
build_schedule/500_schedule                   1.01   403.0±43.40ms        ? ?/sec    1.00   399.9±12.32ms        ? ?/sec
build_schedule/500_schedule_noconstraints     1.00     10.5±0.61ms        ? ?/sec    1.03     10.8±0.69ms        ? ?/sec
```

That's very surprising that there's such a big difference between the measuring techniques. I wonder why. Based on this chart though it seems like the runtime is basically unchanged and more importantly within variance (sometimes main wins and sometimes this PR wins). This PR technically should be slower, but I don't imagine by much at all.

2025-02-20 01:56 UTC, andriyDev commented
I rebased. It was not entirely trivial due to #11094 being merged, so many of the changes had to be moved to `auto_insert_apply_deferred.rs`, but for the most part it was just a move.

2025-02-20 02:54 UTC, hymm approved these changes
whoops. Thought I had approved this already.

2025-02-20 08:11 UTC, urben1680 requested changes

2025-02-21 08:03 UTC, andriyDev commented on crates/bevy_ecs/src/schedule/schedule.rs
> +
This was a very good catch! I hadn't considered conditions on `ApplyDeferred`. I think we can still do this, as long as we only use `ApplyDeferred` stages without conditions. I would be surprised if there was an intentional use of a run condition on an `ApplyDeferred`, so I think we can still get benefits here.

I'll write up my solution soon hopefully.

2025-02-21 08:57 UTC, urben1680 commented on crates/bevy_ecs/src/schedule/schedule.rs
> +
>  I would be surprised if there was an intentional use of a run condition on an `ApplyDeferred`

What may happen more likely is that it is part of a set that has a condition I guess.

I noticed that we maybe should also check for conditions when we merely check if the target is `ApplyDeferred` in the existing logic for that same reason.

2025-02-21 22:59 UTC, alice-i-cecile commented on crates/bevy_ecs/src/schedule/schedule.rs
> +
I would be in favor of panicking if `ApplyDeferred` has a condition. That's extremely cursed.

2025-02-21 23:33 UTC, urben1680 commented on crates/bevy_ecs/src/schedule/schedule.rs
> +
On it directly? Yes, but I am still sure that you can make a set with lots of `ignore_deferred`, an `ApplyDeferred` here and there and the set gets a condition. That should not panic.

2025-02-22 05:56 UTC, andriyDev commented on crates/bevy_ecs/src/schedule/schedule.rs
> +
Alright I've implemented my solution. I only consider `ApplyDeferred` without conditions for explicit sync points.

We could prevent `ApplyDeferred` from having conditions, but we still have to deal with transitive conditions, so I'd rather just support them having conditions (even though it **is** cursed).

2025-02-23 00:27 UTC, urben1680 approved these changes
Just smaller nits but I like the state of it now.

2025-02-23 00:27 UTC, urben1680 commented on crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs
> +            assert!(node.is_system());
What is the concern here for this assert? Since the other function has no inverse assert?

2025-02-23 00:27 UTC, urben1680 commented on crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs
> +        for node in &topo {
You need to do this in a second iteration because until then you don't necessarily have all explicit sync points collected before adding new ones, right?

2025-02-23 00:27 UTC, urben1680 commented on crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs
> +        fn set_has_conditions(graph: &ScheduleGraph, node: NodeId) -> bool {
This and the other two functions kinda bloat this up. It might be worth it making them methods of `ScheduleGraph` since that is the first argument for all of them. Though the third and it's HashMap parameter make it probably even less useful in any other (future) context.

2025-02-23 01:04 UTC, andriyDev commented on crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs
> +            assert!(node.is_system());
The other one does this implicitly. `set_conditions_at` panics if the node is not a set.

For the systems, there's no corresponding function, but we can implement it ourselves pretty simply. But we need to make sure this only happens for systems. In practice, we will never call this with a set, but better to be safe than sorry.

2025-02-23 01:04 UTC, andriyDev commented on crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs
> +        fn set_has_conditions(graph: &ScheduleGraph, node: NodeId) -> bool {
I kinda don't want to do this. If in the future this is a desirable thing to know for other cases, then we should probably use some dynamic programming to figure out which sets/systems overall have conditions. This is only "efficient" because we expect few `ApplyDeferred` stages in the first place, so querying for those in particular is probably cheaper.

2025-02-24 21:10 UTC, merged