Add dasehd lines
bevyengine/bevy pull request #16884
Opened 2024-12-18 17:28 UTC by lynn-lumen

# Objective

- Fixes #16873

## Solution

- Added  `GizmoLineStyle::Dashed {gap_scale, line_scale}`
  - The `gap_scale` and `line_scale` describe the lengths of the gaps and visible line-segments in terms of line-widths. For example, if `gap_scale == 1.0` and `line_scale == 3.0` the gaps are square and the the visible segments are three line-widths long.
- The new `GizmoLineStyle` can be used both in 3D and 2D and with both perspective and orthographic cameras.
- Updated the `2d_gizmos` and `3d_gizmos` examples to include the new line-style.
- Display a warning, when using negative `gap_scale` or `line_scale`.

## Testing

- The results can be verified visually

---

## Showcase

![linestyle-dashed-2d](https://github.com/user-attachments/assets/3541cc55-63c2-4600-882b-3da61f9472bd)
![linestyle-dashed-3d](https://github.com/user-attachments/assets/6b106352-8e74-44a0-b481-46510d4f9148)

2024-12-18 20:07 UTC, alice-i-cecile approved these changes
Very pretty, and very easy. Thanks!

2024-12-18 20:16 UTC, Shatur approved these changes
Awesome! Left a few minor nitpicks:

2024-12-18 20:16 UTC, Shatur commented on crates/bevy_gizmos/src/config.rs
> +impl Hash for GizmoLineStyle {
Let's add newlines for consistency:
```suggestion

impl Eq for GizmoLineStyle {}

impl Hash for GizmoLineStyle {
```

2024-12-18 20:16 UTC, Shatur commented on crates/bevy_gizmos/src/retained.rs
> +                warn_once!("When using gizmos with the line style `GizmoLineStyle::Dashed{{..}}` the gap scale should be greater than zero.");
```suggestion
                warn_once!("when using gizmos with the line style `GizmoLineStyle::Dashed{{..}}` the gap scale should be greater than zero");
```

2024-12-18 20:16 UTC, Shatur commented on crates/bevy_gizmos/src/retained.rs
> +                warn_once!("When using gizmos with the line style `GizmoLineStyle::Dashed{{..}}` the line scale should be greater than zero.");
Warnings usually starts without capital letter and dot at the end:
```suggestion
                warn_once!("when using gizmos with the line style `GizmoLineStyle::Dashed{{..}}` the line scale should be greater than zero");
```

2024-12-18 20:16 UTC, Shatur commented on crates/bevy_gizmos/src/lib.rs
> +    use config::GizmoLineStyle;
Maybe import globally?

2024-12-18 20:18 UTC, Shatur requested changes

2024-12-18 20:18 UTC, Shatur commented on crates/bevy_gizmos/src/lines.wgsl
> +@fragment
A newline between functions:
```suggestion

@fragment
```

2024-12-18 20:38 UTC, Shatur approved these changes

2024-12-18 20:59 UTC, merged

2024-12-27 21:54 UTC, globin commented
Would it be possible to extend this to not only allow `(line, gap)`, but rater `Vec<(line, gap)>` in order to produce a dash-dot/dash-dot-dot pattern etc?

2024-12-27 22:01 UTC, lynn-lumen commented
> Would it be possible to extend this to not only allow `(line, gap)`, but rater `Vec<(line, gap)>` in order to produce a dash-dot/dash-dot-dot pattern etc?
> 

I'm not sure if it's sensible, as it would require a pretty big adjustment to the current system, which is primarily meant to aid development. 

Currently, the `(line, gap)` pair is part of the gizmos-uniform whisch _should_ not hold large amounts of data and cannot hold dynamic amounts of data. As such, we would need smth. like an extra buffer for that, which seems fairly excessive for a development tool.

2024-12-28 00:08 UTC, globin commented
I am aware that gizmos were originally intended for debugging, but with retained mode and other improvements they have moved more toward a polyline implementation, which bevy currently is lacking. I am currently using bevy_prototype_lyon for it, but could imagine moving to retained Gizmos for that.