Key render phases off the main world view entity, not the render world view entity.
bevyengine/bevy pull request #16942
Opened 2024-12-23 05:19 UTC by pcwalton

We won't be able to retain render phases from frame to frame if the keys are unstable. It's not as simple as simply keying off the main world entity, however, because some main world entities extract to multiple render world entities. For example, directional lights extract to multiple shadow cascades, and point lights extract to one view per cubemap face. Therefore, we key off a new type, `RetainedViewEntity`, which contains the main entity plus a *subview ID*.

This is part of the preparation for retained bins.

2024-12-26 21:00 UTC, ickshonpe reviewed
Nothing gets rendered for the UI, but I'm not very familiar with the camera extraction internals and I couldn't quite unravel the problem. 

Very loosely, from what I can tell: 
`extract_default_ui_camera_view` spawns a default camera view entity for each camera which has an `ExtractedView` with `subview_index: 1` and then creates a corresponding `TransparentUi` render phase. 

But the extracted uinodes are given the entity id of the non-ui camera `ExtractedView` entity so that in `queue_uinodes` the non-ui view with `subview_index: 0` is retrieved and then no `TransparentUi` phases are found because they were all keyed to `subview_index: 1`.

2024-12-31 20:36 UTC, pcwalton commented
This should fix the issue with the UI. The proper fix was a bit tricky and involved creating a new subgraph runner to make sure to run the UI rendering subgraph on the right render world entity.

2025-01-02 16:59 UTC, ickshonpe requested changes
Multi-window UI isn't working, I think I found the problem though.

Otherwise everything looks good now, the different shaders etc all seem to be working correctly.

2025-01-02 16:59 UTC, ickshonpe commented on crates/bevy_ui/src/render/mod.rs
> +        let Some(default_camera_view) = render_views.iter(world).next() else {
The `multiple_windows` example doesn't render the label for the second window. It looks like this just needs to look up the correct view using the `graph.view_entity()`.
```suggestion
        let Ok(default_camera_view) = render_views.get(world, graph.view_entity()) else {
```

2025-01-04 03:06 UTC, IceSentry commented
It looks like there's still some issues with UI based on the example runner https://pixel-eagle.com/project/B25A040A-A980-4602-B90C-D480AB84076D?filter=PR-16942

2025-01-04 10:00 UTC, ickshonpe commented
> It looks like there's still some issues with UI based on the example runner https://pixel-eagle.com/project/B25A040A-A980-4602-B90C-D480AB84076D?filter=PR-16942

Ah yeah you're right. Shadows and texture slices still don't work, I must have ran those examples on the wrong branch by mistake.

2025-01-04 10:45 UTC, ickshonpe commented
The extraction and queue functions just needed to be updated. I put in a pr on this pr with the needed changes.

2025-01-05 05:27 UTC, pcwalton commented
Cherry picked over, thanks!

2025-01-07 12:40 UTC, ickshonpe approved these changes
The UI rendering is all fixed now. There is a slight performance regression from the extra indirection but I don't think it's a problem with this PR really, more of a sign that we need to rethink how the UI handle its camera views.

2025-01-07 17:55 UTC, IceSentry commented on crates/bevy_ui/src/render/mod.rs
> +/// subview, 1.
Why does this comment only mentions 3d cameras? Isn't this also true for 2d?

2025-01-07 17:57 UTC, IceSentry approved these changes

2025-01-07 18:21 UTC, ickshonpe commented on crates/bevy_ui/src/render/mod.rs
> +/// subview, 1.
Yes every active 2d or 3d camera gets an extracted UI view. Doesn't matter if there are any UI entities present, only that the UI rendering plugin is enabled.

2025-01-07 18:51 UTC, pcwalton commented on crates/bevy_ui/src/render/mod.rs
> +/// subview, 1.
Updated the comment.

2025-01-09 06:28 UTC, alice-i-cecile commented
Let me know when this has passed an example check run and merge conflicts are resolved please :)

2025-01-12 19:47 UTC, pcwalton commented
@alice-i-cecile I kicked off a run. https://pixel-eagle.com/project/B25A040A-A980-4602-B90C-D480AB84076D?filter=PR-16942 Looks like the failures are known intermittents, so we should be good to go.

2025-01-12 20:39 UTC, merged