wip: example to show these 'fully qualified paths' you're somehow sup…
bevyengine/bevy pull request #16944
Opened 2024-12-23 10:45 UTC by alphastrata

# Objective

It is not obvious that one would know these:
```json
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": [
    "bevy_animation::AnimationPlayer",
    "bevy_animation::AnimationTarget",
    "bevy_animation::graph::AnimationGraphHandle",
    "bevy_animation::transition::AnimationTransitions",
    "bevy_audio::audio::PlaybackSettings",
    "bevy_audio::audio::SpatialListener",
    "bevy_core_pipeline::bloom::settings::Bloom",
    "bevy_core_pipeline::contrast_adaptive_sharpening::ContrastAdaptiveSharpening",
   **... snipping for brevity ...**
    "bevy_ui::ui_node::Node",
    "bevy_ui::ui_node::Outline",
    "bevy_ui::ui_node::ScrollPosition",
    "bevy_ui::ui_node::TargetCamera",
    "bevy_ui::ui_node::UiAntiAlias",
    "bevy_ui::ui_node::ZIndex",
    "bevy_ui::widget::button::Button",
    "bevy_window::monitor::Monitor",
    "bevy_window::window::PrimaryWindow",
    "bevy_window::window::Window",
    "bevy_winit::cursor::CursorIcon",
    "server::Cube"
  ]
}
```
Especially if you for example, are reading the GH examples because:
![image](https://github.com/user-attachments/assets/46c9c983-4bf9-4e70-9d6e-8de936505fbb)
If you for example expand these things, due to the number of places bevy re-exports things you'll find it difficult to find the true path of something.
i.e you'd probably be forgiven for writing a query (using the `client.rs` example):
```sh
$ cargo run --example client --  bevy_pbr::mesh_material::MeshMaterial3d | jq
{
  "error": {
    "code": -23402,
    "message": "Unknown component type: `bevy_pbr::mesh_material::MeshMaterial3d`"
  },
  "id": 1,
  "jsonrpc": "2.0"
}
```
which is where https://github.com/bevyengine/bevy/blob/8d9a00f5483b2ba28f40081759bd3d6f8b8a686d/crates/bevy_pbr/src/mesh_material.rs#L41 would lead you to believe it is...

I've worked with bevy a lot, so it's no issue for me, but for others... ?

However, running this new example:
```sh
$ cargo run --example list_all_paths --features="bevy_remote" | jq | rg MeshMaterial3d
...
 "bevy_pbr::mesh_material::MeshMaterial3d<bevy_pbr::pbr_material::StandardMaterial>",
```

## Solution

- another example.

## Testing

Yes, I ran them. and have been using the output from for the last hour or two.

---

## Showcase

Instead of encouraging this:
![image](https://github.com/user-attachments/assets/0b6b0428-5605-41f1-9b57-423b326da9f3)
> `cargo run --example client --features="bevy_remote" --  bevy_pbr::mesh_material::MeshMaterial3d`

We could suggest something like this:
![image](https://github.com/user-attachments/assets/be3b0abe-4963-46c1-8fdb-59b88cc59344)
> `cargo run --example list_all_paths --features="bevy_remote" | jq '.result[] | select(contains("Material"))'`

NOTE: ReflectSerialize isn't a thing on MeshMaterial3d, nor indeed on many of the paths that one might explore on the list of returned 'things', but the point should still stand...

2024-12-24 01:40 UTC, BenjaminBrienen requested changes

2024-12-24 01:40 UTC, BenjaminBrienen commented on examples/remote/list_all_paths.rs
> +    // If you pass no params, you'll be able to see all the optinos for arguments you can pass to the `./client.rs` remote example.
```suggestion
    // If you pass no params, you'll be able to see all the options for arguments you can pass to the `./client.rs` remote example.
```

2024-12-24 02:32 UTC, BenjaminBrienen approved these changes

2024-12-24 06:26 UTC, alphastrata commented
👍🏽

2024-12-24 18:07 UTC, alice-i-cecile reviewed
Hmm. I can see why this would be useful, but I think it's probably better suited as a doc test in the module docs.

2024-12-24 20:52 UTC, alphastrata commented
> Hmm. I can see why this would be useful, but I think it's probably better suited as a doc test in the module docs.

Am I correct in thinking that if they are here [in examples] they're scraped for the docs, but not the other way around?

Happy to move them though. @alice-i-cecile whatever you want to do is fine with me.

2024-12-26 22:15 UTC, alice-i-cecile commented
Examples getting scraped is a good argument, but Bevy's examples are already rather numerous. I'd like to reserve them for teaching things that *must* be interactive, so let's move this information into the docs.

2024-12-26 22:40 UTC, BenjaminBrienen commented
Examples being visual examples only will help delineate that and it makes sense, since examples are shown on the website as a "look at this".

2024-12-26 23:44 UTC, alice-i-cecile commented
> Although, many crates don't have anything to do with visuals and might benefit from bigger examples that aren't well suited to a doc test.

Yeah, things that demonstrate end-to-end usage patterns can be valuable to teach in examples too! But small snippets / notes like this should just go in the docs.

2024-12-27 01:09 UTC, alphastrata commented
> > Although, many crates don't have anything to do with visuals and might benefit from bigger examples that aren't well suited to a doc test.
> 
> Yeah, things that demonstrate end-to-end usage patterns can be valuable to teach in examples too! But small snippets / notes like this should just go in the docs.

I will move them over the weekend. --standby

2024-12-27 04:52 UTC, alphastrata commented
We thinking something like this:
![image](https://github.com/user-attachments/assets/9dd61f2a-6e14-4df9-8785-38284082bb49)
i.e have them on the BrpRequest docs? or something more... prominent?

2024-12-30 19:47 UTC, alice-i-cecile commented
On the BrpRequest docs makes sense to me :)

2024-12-31 00:29 UTC, alice-i-cecile approved these changes

2024-12-31 00:45 UTC, merged