Add mutate_component BRP method
bevyengine/bevy pull request #16940
Opened 2024-12-23 00:54 UTC by purplg

# Objective

Add a method to mutate components with BRP.

Currently the only way to modify a component on an entity with BRP is to insert a new one with the new values. This isn't ideal for several reasons, one reason being that the client has to know what all the fields are of the component and stay in sync with the server.

## Solution

Add a new BRP method called `bevy/mutate_component` to mutate a single field in a component on an entity.

## Testing

- Tested on a simple scene on all `Transform` and `Name` fields.

---

## Showcase

Example JSON-RPC request to change the `Name` of an entity to "New name!"

```json
{
    "jsonrpc": "2.0",
    "id": 0,
    "method": "bevy/mutate_component",
    "params": {
        "entity": 4294967308,
        "component": "bevy_ecs::name::Name",
        "path": ".name",
        "value": "New name!"
    }
}
```

2024-12-23 00:56 UTC, purplg commented on crates/bevy_remote/src/builtin_methods.rs
> +pub const BRP_MUTATE_COMPONENT_METHOD: &str = "bevy/mutate_component";
I'm not sure what the convention is for multiple words in a method name is. Should the method be named differently? I'm trying to consider future methods for modifying other things like Resource's. 

I had a few other ideas for methods:

- `bevy/modify/component`
- `bevy/mutate/component`
- `bevy/component_mut` *this feels too Rusty in this context*

2024-12-23 00:57 UTC, purplg commented on crates/bevy_remote/src/builtin_methods.rs
> +) -> BrpResult {
I feel like the method handler could probably be done better. Any pointers here would be appreciated.

2025-01-05 23:57 UTC, cBournhonesque approved these changes
This generally LGTM.
It's a shame that we don't have unit tests for BRP

2025-01-06 14:41 UTC, purplg commented
> It's a shame that we don't have unit tests for BRP

I agree. I did look at writing tests for this, but I didn't see an existing way to do this.

2025-01-09 06:48 UTC, LiamGallagher737 requested changes
It would be useful to link to the following docs in the crate level docs for this method to show how the path field should be structured.

https://docs.rs/bevy/latest/bevy/prelude/trait.GetPath.html#syntax

2025-01-10 00:40 UTC, purplg commented
Good point on that doc link. Added.

2025-01-10 09:01 UTC, LiamGallagher737 approved these changes

2025-01-11 15:06 UTC, BenjaminBrienen commented
CI still failing

2025-01-12 00:16 UTC, purplg commented
I think the msrv one just needed a rebase.

Not sure why the CI check required me to backtick `bevy/mutate_component`. None of the other ones required it, heh.

Anyway, it looks like it all passes now. Thanks

2025-01-14 07:41 UTC, mockersf approved these changes

2025-01-14 08:13 UTC, merged