fix visibility propogate
bevyengine/bevy pull request #17025
Opened 2024-12-29 18:55 UTC by ethereumdegen

# Objective
Fixes #17024 

## Solution
 

## Testing
 By adding 

```
if let Some(mut cmd) = commands.get_entity( *equipment_link_node ){
                         cmd.insert(Visibility::Inherited); // a hack for now 
                     }

```
in my build, this fixes the issue.  This is why i think that this change will fix the issue.  Unfortunately i was not able to test the Changed (parent )  , this actual code change, because no matter how i 'patch', it breaks my project.  I got super close but still had 23 errors due to Reflect being angry.  

---

2024-12-29 19:07 UTC, alice-i-cecile approved these changes

2024-12-29 19:08 UTC, alice-i-cecile requested changes
Can you please add a regression test for this?

2024-12-30 02:40 UTC, ethereumdegen commented
Alright @alice-i-cecile  i have added your test and it indeed fails when i use the original code and passes when i put my fix in .  !

2024-12-30 05:52 UTC, alice-i-cecile approved these changes

2024-12-30 07:20 UTC, BenjaminBrienen approved these changes
I'm fairly confident that this will work recursively, although the test doesn't check for that.

2024-12-30 21:12 UTC, merged