chore: enhanced decoder error messages to include more meaningful hints.
bevyengine/bevy pull request #17056
Opened 2024-12-31 00:34 UTC by 0xb-s

2024-12-31 01:11 UTC, BenjaminBrienen approved these changes

2024-12-31 01:14 UTC, 0xb-s commented
need fmt and one err not related to this pr

2024-12-31 03:57 UTC, BenjaminBrienen commented
> need fmt and one err not related to this pr

Run `cargo fmt --all` and commit the formatted files. Then, once #17060 is merged, you can update your branch and that should fix the wasm check.

2025-01-01 11:02 UTC, Olle-Lukowski approved these changes

2025-01-01 11:04 UTC, Olle-Lukowski commented
This justs needs formatting and CI, then it's good to merge!

2025-01-01 18:44 UTC, alice-i-cecile commented
Once CI is passing I'll merge this in :) Looks like it just needs the old `cargo fmt --all`.

2025-01-01 20:27 UTC, mockersf requested changes
This function returns a `DecoderError` https://docs.rs/rodio/latest/rodio/decoder/enum.DecoderError.html

It seems the message you added is not the only possible issue. Could you give more details in why it's better than logging that error which is already done?

2025-01-02 15:49 UTC, closed without merging