expose texture/image conversions as From/TryFrom
bevyengine/bevy pull request #2175
Opened 2021-05-15 20:04 UTC by mockersf

fixes #2169 

Instead of having custom methods with reduced visibility, implement `From<image::DynamicImage> for Texture` and `TryFrom<Texture> for image::DynamicImage`

2021-05-16 00:52 UTC, NathanSWard commented on crates/bevy_render/src/texture/image_texture_conversion.rs
> +pub enum TextureConversionError {
```suggestion
#[derive(Clone, Copy, Debug)] // also maybe Eq/PartialEq
pub enum TextureConversionError {
```

Also is it worth implementing `std::error::Error` for this?

2021-05-16 00:54 UTC, NathanSWard commented on crates/bevy_render/src/texture/image_texture_conversion.rs
> +                    let a = u16::max_value();
```suggestion
                    let a = u16::MAX;
```
`max_value()` is deprecated in favor of `::MAX`

2021-05-16 17:48 UTC, NathanSWard requested changes

2021-05-16 17:48 UTC, NathanSWard commented on crates/bevy_render/src/texture/image_texture_conversion.rs
> +#[derive(Clone, Copy, Debug, Eq, Error, PartialEq)]
```suggestion
}

#[derive(Clone, Copy, Debug, Eq, Error, PartialEq)]
```

2021-05-16 17:48 UTC, NathanSWard commented on crates/bevy_render/src/texture/image_texture_conversion.rs
> +#[derive(Clone, Copy, Debug, Eq, Error, PartialEq)]
Missing a newline here ;)

2021-05-16 20:24 UTC, NathanSWard approved these changes

2021-05-19 02:14 UTC, alice-i-cecile approved these changes

2021-06-08 02:26 UTC, cart commented
Love it!

2021-06-08 02:26 UTC, cart commented
bors r+

2021-06-08 02:46 UTC, closed without merging