Update hexasphere to 4.0.0.
bevyengine/bevy pull request #2390
Opened 2021-06-24 20:14 UTC by OptimisticPeach

# Objective

- Update `hexasphere` to 4.0.0, which is now licensed with dual MIT/Apache-2.0.

2021-06-24 20:16 UTC, DJMcNab requested changes
Please also remove the exception from `deny.toml`.

2021-06-24 20:48 UTC, DJMcNab approved these changes
🎉

2021-06-24 21:47 UTC, mockersf approved these changes

2021-06-25 00:35 UTC, cart commented
bors r+

2021-06-25 00:55 UTC, closed without merging