Add the Inside version to the Collision enum
bevyengine/bevy pull request #2489
Opened 2021-07-16 14:03 UTC by horvbalint

# Objective
I think the 'collide' function inside the 'bevy/crates/bevy_sprite/src/collide_aabb.rs' file should return 'Some' if the two rectangles are fully overlapping or one is inside the other. This can happen on low-end machines when a lot of time passes between two frames because of a stutter, so a bullet for example gets inside its target. I can also think of situations where this is a valid use case even without stutters. 

## Solution
I added an 'Inside' version to the Collision enum declared in the file. And I use it, when the two rectangles are overlapping, but we can't say from which direction it happened. I gave a 'penetration depth' of minus Infinity to these cases, so that this variant only appears, when the two rectangles overlap from each side fully. I am not sure if this is the right thing to do.

2021-07-16 14:16 UTC, mockersf commented
Thank you for looking into this! It may be related to #1980 and #1982

2021-07-16 14:36 UTC, horvbalint commented
Yes! Thanks, I couldn't find these, even though I tried.
But I don't think that 'Intersecting' is the right name for the new variant as all of the variants describe some kind of intersection and this can cause some confusion I think.

2021-07-16 16:42 UTC, NathanSWard requested changes

2021-07-16 16:42 UTC, NathanSWard commented on crates/bevy_sprite/src/collide_aabb.rs
> +            (Some(Collision::Inside), -f32::INFINITY)
Since all of these branch are now a `Collision` enum variant, I think we can remove the `Some` around all of them.

2021-07-16 16:42 UTC, NathanSWard commented on crates/bevy_sprite/src/collide_aabb.rs
> +            (Some(Collision::Inside), -f32::INFINITY)
same here as well

2021-07-16 18:29 UTC, horvbalint commented
@NathanSWard You are right, I updated the pull request. Removing the Option also made the code less complex.

2021-07-22 23:44 UTC, alice-i-cecile approved these changes

2021-07-26 18:49 UTC, alice-i-cecile commented
bors try

2022-01-15 22:06 UTC, alice-i-cecile commented
@horvbalint Can you comment on https://github.com/bevyengine/bevy/issues/2373? :) I'd like to see if we can merge this in.

2022-01-16 07:35 UTC, horvbalint commented
@alice-i-cecile I commented :) Please check if my changes are logically correct, I don't want to mess things up for others :)

2022-02-01 22:01 UTC, cart commented
bors r+

2022-02-01 22:40 UTC, cart commented
bors r+

2022-02-01 22:58 UTC, closed without merging