Add get_change_ticks method to EntityRef and EntityMut
bevyengine/bevy pull request #2539
Opened 2021-07-25 07:56 UTC by TheRawMeatball

Direct access to the change ticks is useful for integrating the reliable change detection with external stuff.

2021-07-25 16:57 UTC, mockersf commented
As this is a little advanced, some doc comments would be nice 😃

2021-08-10 01:27 UTC, cart commented on crates/bevy_ecs/src/world/entity_ref.rs
> +            get_component_and_ticks_with_type(
I know you're trying to reuse code here, but we don't need to retrieve the component for this operation. This seems like the sort of small inefficiency that we'd merge and then forget about. A theoretical `get_ticks` and the existing `get_component` and `get_component_with_ticks` methods probably have some refactoring potential to share code. They all need to "get the entity's offset in each storage". This seems like a relatively trivial refactor for Table storage, but Sparse Set storage would probably need some new get_with_dense_index_unchecked() apis.

2021-12-15 14:06 UTC, TheRawMeatball commented
Closing as I no longer need this, might reopen if I do.

2022-01-02 08:22 UTC, TheRawMeatball commented
Reopening because I need this

2022-05-02 16:48 UTC, alice-i-cecile commented on crates/bevy_ecs/src/world/entity_ref.rs
> +) -> Option<*mut ComponentTicks> {
This should use the new pointer types that you added in #3001 now.

2022-05-02 16:48 UTC, alice-i-cecile commented on crates/bevy_ecs/src/storage/sparse_set.rs
> +    pub fn get_ticks_ptr(&self, entity: Entity) -> Option<*mut ComponentTicks> {
This should use the new pointer types that you added in #3001 now.

2022-05-02 16:49 UTC, alice-i-cecile requested changes
I'm having a hard time seeing what users would do with this, but I'm open to being convinced.

In any case, now that #3001 is merged, we can use lifetimed pointers!

2022-05-02 18:16 UTC, mockersf approved these changes

2022-05-02 18:39 UTC, alice-i-cecile commented
bors r+

2022-05-02 19:06 UTC, closed without merging