Make the `iter_combinators` examples more pretty
bevyengine/bevy pull request #3075
Opened 2021-11-05 23:29 UTC by DJMcNab

# Objective

- More colours

## Solution

- Various changes
- Would have a video here, but don't have an easy way to record one before I go to sleep
- I intend to additionally change the distribution of the satellites, to be more uniform in space.

2021-11-05 23:39 UTC, mockersf commented
https://user-images.githubusercontent.com/8672791/140589595-d7562887-70be-48d8-86f7-32e6f00760f3.mov

2022-01-06 00:03 UTC, mockersf approved these changes

2022-01-06 04:26 UTC, cart commented
bors r+

2022-01-06 05:54 UTC, alice-i-cecile commented
bors try

2022-01-06 05:56 UTC, alice-i-cecile commented on examples/ecs/iter_combinations.rs
> +            radius: star_radius,
```suggestion
            radius: star_radius,
            ..Default::default(),
```
This should fix the compile failure the CI caught.

2022-01-06 08:18 UTC, mockersf commented on examples/ecs/iter_combinations.rs
> +            ..Default::default(),
```suggestion
            ..Default::default()
```

2022-01-06 09:18 UTC, mockersf commented
I tried running on rebased main, the light doesn't work anymore as it needs other components from the `PointLightBundle` 

Could you apply this change to your PR branch?
```diff
--- a/examples/ecs/iter_combinations.rs
+++ b/examples/ecs/iter_combinations.rs
@@ -127,14 +127,19 @@ fn generate_bodies(
             mass: Mass(500.0),
             ..Default::default()
         })
-        .insert(PointLight {
-            color: Color::WHITE,
-            intensity: 400.,
-            range: 100.,
-            radius: star_radius,
-            ..Default::default()
-        })
-        .insert(Star);
+        .insert(Star)
+        .with_children(|p| {
+            p.spawn_bundle(PointLightBundle {
+                point_light: PointLight {
+                    color: Color::WHITE,
+                    intensity: 400.0,
+                    range: 100.0,
+                    radius: star_radius,
+                    ..Default::default()
+                },
+                ..Default::default()
+            });
+        });
     commands.spawn_bundle(PerspectiveCameraBundle {
         transform: Transform::from_xyz(0.0, 10.5, -30.0).looking_at(Vec3::ZERO, Vec3::Y),
         ..Default::default()
```

2022-01-06 09:18 UTC, mockersf requested changes
I tried running on rebased main, the light doesn't work anymore as it needs other components from the `PointLightBundle` 

Could you apply this change to your PR branch?
```diff
--- a/examples/ecs/iter_combinations.rs
+++ b/examples/ecs/iter_combinations.rs
@@ -127,14 +127,19 @@ fn generate_bodies(
             mass: Mass(500.0),
             ..Default::default()
         })
-        .insert(PointLight {
-            color: Color::WHITE,
-            intensity: 400.,
-            range: 100.,
-            radius: star_radius,
-            ..Default::default()
-        })
-        .insert(Star);
+        .insert(Star)
+        .with_children(|p| {
+            p.spawn_bundle(PointLightBundle {
+                point_light: PointLight {
+                    color: Color::WHITE,
+                    intensity: 400.0,
+                    range: 100.0,
+                    radius: star_radius,
+                    ..Default::default()
+                },
+                ..Default::default()
+            });
+        });
     commands.spawn_bundle(PerspectiveCameraBundle {
         transform: Transform::from_xyz(0.0, 10.5, -30.0).looking_at(Vec3::ZERO, Vec3::Y),
         ..Default::default()
```

2022-01-06 09:53 UTC, mockersf approved these changes

2022-01-06 19:13 UTC, alice-i-cecile commented
bors r+

2022-01-06 19:28 UTC, closed without merging