Added documentation to WindowMode to better document what 'use_size' …
bevyengine/bevy pull request #3216
Opened 2021-11-28 22:08 UTC by dimitribobkov

This pull request aims to solve the issue of a lack of documentation in the enum WindowMode

# Objective

- Fixes #3136

## Solution

- Added a few lines of documentation that should document what the enum does better

2021-11-28 22:30 UTC, alice-i-cecile approved these changes
Looks great! Thanks for your first PR :)

2021-11-28 22:54 UTC, Weibye approved these changes
👍

2021-11-28 23:12 UTC, mockersf requested changes
With this change, the field is documented on the enum and on the variant.

I think it would be best to keep the documentation on only one place, and that would be on the field itself. This would be better presented on docs.rs, and will also be the doc that will show up in an IDE. Could you move it there? 

Also, "best" is not very explicit on how it is chosen. Could you expand the explanation? It seems "best" is from https://github.com/bevyengine/bevy/blob/3de391be21666c90661066ca395c63813352b4bb/crates/bevy_winit/src/winit_windows.rs#L213-L227
so it's picking the one with the bigger height / refresh rate I think?
Or better, add the explanation as doc to this comment, then link to it from the field doc.

And from CI, it seems you could run `cargo fmt` 😃

2021-11-28 23:30 UTC, mockersf commented on crates/bevy_window/src/window.rs
> +    /// When set to true, the window uses the given size.
This is not true, it will pick the resolution supported by the monitor that is closer to the given resolution, not the given one

2021-11-30 11:59 UTC, dimitribobkov commented
I've updated the documentation and ensured the new changes are compatible with bevy. I've tested it on a few examples and it seems to have run pretty well, but a review would be appreciated!

2021-11-30 23:45 UTC, mockersf approved these changes

2021-11-30 23:50 UTC, cart commented
bors r+

2021-11-30 23:51 UTC, cart commented
Nice improvements!

2021-12-01 00:12 UTC, closed without merging