SceneSpawner: add unload() and unload_sync()
bevyengine/bevy pull request #339
Opened 2020-08-25 01:35 UTC by Fishrock123

This allows you to unload scenes.

Refs: https://github.com/bevyengine/bevy/issues/255

I've been struggling to get an example up that isn't just rewriting the breakout game to use scenes, maybe someone can help me make something simpler to properly verify this.

2020-09-01 08:22 UTC, memoryruins commented on crates/bevy_scene/src/scene_spawner.rs
> +        std::mem::swap(&mut self.scenes_to_unload, &mut scenes_to_unload);
```suggestion
        let scenes_to_unload = std::mem::take(&mut self.scenes_to_unload);
```

2020-09-01 08:26 UTC, memoryruins commented on crates/bevy_scene/src/scene_spawner.rs
> +            }
```suggestion
            self.unload_sync(world, scene_handle)?;
```

2020-09-01 08:27 UTC, memoryruins commented on crates/bevy_scene/src/scene_spawner.rs
> +        std::mem::swap(&mut self.scenes_to_spawn, &mut scenes_to_spawn);
```suggestion
        let scenes_to_spawn = std::mem::take(&mut self.scenes_to_spawn);
```

2020-09-01 16:58 UTC, Fishrock123 commented on crates/bevy_scene/src/scene_spawner.rs
> +        std::mem::swap(&mut self.scenes_to_unload, &mut scenes_to_unload);
Ah, that's handy. Good to know.

2020-09-04 21:32 UTC, cart requested changes
Looks good. A lot of people want this feature :smile: 

Just a couple of small changes needed. I'd say its fine to not add an example in this pr. Its worth spending some time to come up with an interesting spawn / despawn example.

2020-09-04 21:32 UTC, cart commented on crates/bevy_scene/src/scene_spawner.rs
> +            self.loaded_scenes
lets replace these retain() calls with
```rust
self.loaded_scenes.remove(&scene_handle);
```

These are hashsets/hashmaps, which means we don't need to iterate over the whole collection to find a key.

2020-09-04 21:32 UTC, cart commented on crates/bevy_scene/src/scene_spawner.rs
> +                    self.scenes_to_spawn.push(scene_handle)
this should be `self.scenes_to_load`

2020-09-06 19:49 UTC, Fishrock123 commented
@cart Addressed and updated.

2020-09-06 19:58 UTC, cart approved these changes

2020-09-06 20:06 UTC, merged