Nightly clippy fixes
bevyengine/bevy pull request #3491
Opened 2021-12-29 20:42 UTC by SarthakSingh31

Fixes the following nightly clippy lints:
- [map_flatten](https://rust-lang.github.io/rust-clippy/master/index.html#map_flatten)
- [needless_borrow](https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow)
- [return_self_not_must_use](https://rust-lang.github.io/rust-clippy/master/index.html#return_self_not_must_use) (Added in 1.59.0)
- [unnecessary_lazy_evaluations](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_lazy_evaluations)

2021-12-30 11:45 UTC, mockersf approved these changes
Thank you!

The fixes make sense, though it should be noted that some of those lints are not stable and have been in nightly for some time

2022-05-16 18:29 UTC, alice-i-cecile commented
@SarthakSingh31 can you rebase this?

2022-05-16 18:29 UTC, alice-i-cecile requested changes
@SarthakSingh31 can you rebase this?

2022-05-17 04:20 UTC, alice-i-cecile approved these changes
bors r+

2022-05-17 04:21 UTC, alice-i-cecile commented
I particularly love the reduction in lifetime parameters here :D Thanks!

2022-05-17 04:55 UTC, closed without merging