create font atlas that can contains fonts of any size
bevyengine/bevy pull request #3592
Opened 2022-01-08 14:45 UTC by mockersf

# Objective

- Bevy currently panics when displaying text with a *very* big font size  (with font size greater than 400, the glyph would have a width or height greater than 512)
```
thread 'main' panicked at 'Fatal error when processing text: failed to add glyph to newly-created atlas GlyphId(514).', crates/bevy_ui/src/widget/text.rs:118:21
```

## Solution

- Create font atlas that scales up with the size of the glyphs

2022-05-16 18:30 UTC, alice-i-cecile approved these changes

2022-05-17 03:24 UTC, devil-ira approved these changes
Looks good.
I would like a comment on the calculation for `containing` though.

2022-05-30 15:02 UTC, alice-i-cecile requested changes

2022-05-30 15:02 UTC, alice-i-cecile commented on crates/bevy_text/src/font_atlas_set.rs
> +            let containing = (1u32 << (32 - glyph_max_size.leading_zeros())).max(512) as f32;
This needs a comment explaining what's being done in this line before I'm comfortable merging it.

2022-06-01 20:44 UTC, alice-i-cecile commented
bors r+

2022-06-01 21:05 UTC, closed without merging