showcasing the Material2d abtraction with a new example: 2d/mesh2d_material.rs
bevyengine/bevy pull request #3610
Opened 2022-01-09 16:50 UTC by eliotbo

# Objective

- There are currently no resources to learn how to use the Material2d trait, and this PR fixes this issue by adding a related example to the examples/2d folder.

## Solution

The new 2d/mesh2d_material example is a modified version of the shader/shader_material example, where the Material trait is replaced by the Material2d trait. In the new example, users will be able to add fields to the Custom2dMaterial struct without having to change the Material2d and RenderAsset implementations, provided that bevy_crevice supports the type of said fields. This is achieved by 1) deriving AsStd140 on Custom2dMaterial, 2) setting the binding size with Custom2dMaterial::std140_size_static(), and 3) converting the entirety of the Custom2dMaterial data into std140 format with  the derived as_std140() method. Of course, as users modify the Custom2dMaterial struct, they must also change the corresponding struct inside the shader script, but this exercise is left to them.

2022-01-09 16:56 UTC, jakobhellermann requested changes

2022-01-09 16:56 UTC, jakobhellermann commented on examples/2d/mesh2d_material.rs
> +/// set up a simple 3D scene
```suggestion
/// set up a simple 2D scene
```

2022-01-09 16:56 UTC, jakobhellermann commented on examples/2d/mesh2d_material.rs
> +#[uuid = "4ee9c363-1124-4113-890e-199d81b00281"]
Use a different UUID than the 3d example please, it's okay here since they are never in the same program but the should be different nonetheless

2022-01-22 17:37 UTC, jakobhellermann reviewed
Looks good to me!

2022-01-22 17:37 UTC, jakobhellermann commented on examples/2d/mesh2d_material.rs
> +    commands.spawn().insert_bundle(MaterialMesh2dBundle {
```suggestion
    commands.spawn_bundle(MaterialMesh2dBundle {
```

2023-10-01 21:10 UTC, IceSentry commented
@eliotbo would you be interested in updating this PR to the newer Material api using AsBindGroup. We do get people asking about 2d materials from time to time so having an example could be useful instead of just telling them to copy the 3d version.

2024-01-10 08:22 UTC, mockersf commented
done in https://github.com/bevyengine/bevy/pull/10542

2024-01-10 08:22 UTC, closed without merging