`winit_wasm` requires `render` feature
bevyengine/bevy pull request #3637
Opened 2022-01-11 06:28 UTC by dpc

Otherwise it will throw an exception on start.

2022-01-11 07:49 UTC, bjorn3 commented
Can you please also update https://github.com/bevyengine/bevy/blob/bc499591c2d090e17c95d2c59bc6e16ba60a023d/Cargo.toml#L516?

2022-01-11 08:26 UTC, mockersf approved these changes

2022-01-11 08:28 UTC, mockersf requested changes
this

2022-01-11 08:28 UTC, mockersf commented on Cargo.toml
> +required-features = ["bevy_winit","render"]
This line is not for the `winit_wasm` example, it's for `assets_wasm`

Could you update the one ten lines down?

2022-01-11 20:34 UTC, mockersf approved these changes

2022-01-15 21:29 UTC, cart commented
`bevy_winit` and `render` are both default features. I'd like us to move away from specifying default features for examples, unless they are meant to be run without default features. I think what really needs to change is our `examples/README.md` telling people to run wasm examples without default features.

2022-01-20 00:13 UTC, mockersf commented
the wasm examples have been removed as they are no longer relevant, most examples should work in wasm with default features now 👍

2022-01-20 01:07 UTC, dpc commented
I guess no longer needed then

2022-01-20 01:07 UTC, closed without merging