Clippy fixes
bevyengine/bevy pull request #3718
Opened 2022-01-18 14:43 UTC by ManevilleF

# Objective

Fixes some `nursery` clippy warnings like
- `clippy::missing_const_fn`
- `clippy::option_if_let_else`
- `clippy::use_self`

## Solution

I applied many small changes accross all crates.

2022-01-18 15:51 UTC, MinerSebas requested changes
There were several places where an `fn` was made const, that can't be actually called in a const context as the Type they are implemented for can only be constructed at runtime.
Please revert those functions or try to get a const-constructor.

Also please when change as many Files/Places as here, make 1. Commit for every clippy Lint. this makes it much easier to review each individual Lint.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_ecs/src/storage/blob_vec.rs
> +    pub const fn capacity(&self) -> usize {
`BlobVec` has no const constructor.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_ecs/src/storage/blob_vec.rs
> +    pub const unsafe fn get_ptr(&self) -> NonNull<u8> {
Same as above.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_ecs/src/storage/sparse_set.rs
> +    pub const fn is_empty(&self) -> bool {
`ComponentSparseSet` has no const constructor.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_ecs/src/storage/table.rs
> +    pub const fn is_empty(&self) -> bool {
`Column` has no const constructor.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_ecs/src/storage/table.rs
> +    pub const unsafe fn get_data_ptr(&self) -> NonNull<u8> {
Same as above.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_ecs/src/system/commands/mod.rs
> +    pub const fn id(&self) -> Entity {
`EntityCommands` get created in the `entity()` call of `Commands` which is not const.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_ecs/src/system/function_system.rs
>      }
`SystemMeta` has no const constructor.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_ecs/src/world/entity_ref.rs
> +    pub const fn location(&self) -> EntityLocation {
`EntityMut` has no const constructor.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_ecs/src/world/mod.rs
> +    pub const fn entities(&self) -> &Entities {
`World` has no const constructor.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_ecs/src/world/mod.rs
> +    pub const fn components(&self) -> &Components {
Same as above.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_ecs/src/world/mod.rs
> +    pub const fn bundles(&self) -> &Bundles {
Same as above.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_ecs/src/world/mod.rs
>      }
Same as above.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_input/src/touch.rs
> +    pub const fn force(&self) -> Option<ForceTouch> {
`Touch` has no const constructor.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_reflect/src/type_registry.rs
> +    pub const fn type_id(&self) -> TypeId {
`TypeRegistration` has no const constructor.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_reflect/src/type_registry.rs
> +    pub const fn name(&self) -> &'static str {
Same as above.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_render/src/mesh/mesh/mod.rs
> +    pub const fn primitive_topology(&self) -> PrimitiveTopology {
`Mesh` does not have a const constructor.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_render/src/mesh/mesh/mod.rs
> +    pub const fn indices(&self) -> Option<&Indices> {
Same as above.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_render/src/render_graph/context.rs
> +    pub const fn output_info(&self) -> &SlotInfos {
`RenderGraphContext` has no const constructors.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_render/src/render_graph/node.rs
> +    pub const fn uuid(&self) -> &Uuid {
`NodeId` has no const constructor.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_render/src/render_resource/bind_group.rs
> +    pub const fn id(&self) -> BindGroupId {
`BindGroup` has no const constructor.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_render/src/render_resource/bind_group_layout.rs
> +    pub const fn id(&self) -> BindGroupLayoutId {
`BindGroupLayout` has no const constructor.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_render/src/render_resource/buffer.rs
> +    pub const fn id(&self) -> BufferId {
`Buffer` has no const constructor.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_render/src/render_resource/buffer.rs
> +    pub const fn offset(&self) -> wgpu::BufferAddress {
`BufferSlice` has no const constructor.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_render/src/render_resource/pipeline.rs
> +    pub const fn id(&self) -> RenderPipelineId {
`RenderPipeline` has no const Constructor.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_render/src/render_resource/shader.rs
> +    pub const fn import_path(&self) -> Option<&ShaderImport> {
`Shader` has no const cosntructor.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_render/src/render_resource/texture.rs
> +    pub const fn id(&self) -> TextureId {
`Texture` has not a const constructor.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_tasks/src/task_pool.rs
> +    pub const fn stack_size(mut self, stack_size: usize) -> Self {
`TaskPoolBuilder` does not have a const-constructor, but the `new` method could be made trivially const.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_window/src/window.rs
> +    pub const fn resizable(&self) -> bool {
Same as above.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_window/src/window.rs
> +    pub const fn decorations(&self) -> bool {
Same as above.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_window/src/window.rs
> +    pub const fn cursor_locked(&self) -> bool {
Same as above.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_window/src/window.rs
> +    pub const fn cursor_visible(&self) -> bool {
Same as above.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_window/src/window.rs
> +    pub const fn cursor_icon(&self) -> CursorIcon {
Same as above.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_window/src/window.rs
> +    pub const fn physical_cursor_position(&self) -> Option<DVec2> {
Same as above.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_window/src/window.rs
> +    pub const fn mode(&self) -> WindowMode {
Same as above.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_window/src/window.rs
> +    pub const fn is_focused(&self) -> bool {
Same as above.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_core/src/time/stopwatch.rs
> +    pub const fn elapsed(&self) -> Duration {
`Stopwatch` has no const constructor.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_core/src/time/stopwatch.rs
> +    pub const fn paused(&self) -> bool {
Same as above.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_core/src/time/time.rs
> +    pub const fn time_since_startup(&self) -> Duration {
`Time` has no const constructor.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_core/src/time/timer.rs
> +    pub const fn finished(&self) -> bool {
`Timer` has no non-const constructor.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_core/src/time/timer.rs
> +    pub const fn just_finished(&self) -> bool {
Same as above.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_core/src/time/timer.rs
> +    pub const fn elapsed(&self) -> Duration {
Same as above.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_core/src/time/timer.rs
> +    pub const fn duration(&self) -> Duration {
Same as above.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_core/src/time/timer.rs
> +    pub const fn repeating(&self) -> bool {
Same as above.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_core/src/time/timer.rs
> +    pub const fn paused(&self) -> bool {
Same as above.

2022-01-18 15:51 UTC, MinerSebas commented on crates/bevy_core/src/time/timer.rs
> +    pub const fn times_finished(&self) -> u32 {
Same as above.

2022-01-18 16:02 UTC, ManevilleF commented
@MinerSebas `const` functions don't require a `const` context, there is no need for `const` constructors as it just allows the evaluation of the function at compile time. 
Is there maybe a convention regarding `const` functions that I'm not aware of?

2022-01-18 17:03 UTC, mockersf commented
A `const` function can be evaluated at compile time, and will if all its parameters are `const`. In the cases raised by MinerSebas, there will never be a `self` that is `const`, so even if the functions are marked, they will never be evaluated at compile time.

Adding `const` here won't change anything for now, but it's an extra constraint on how Bevy may evolve as they may need to not be `const` later on and the person may be hesitant to remove it.

2022-01-18 18:01 UTC, alice-i-cecile commented
Some of this work was duplicated in #2934. I think I prefer the clarity and freshness of this PR, if we're picking one to merge.

2022-01-19 09:18 UTC, ManevilleF commented
Thanks @mockersf (Merci François !)  I'll apply the suggestions of @MinerSebas and remove the extra `const` I added

@alice-i-cecile I added two more clippy fixes: `clippy::semicolon_if_nothing_is_returned` and `clippy::explicit_iter_loop` which are in the similar PR.

Should I add to the CI config or the `lib.rs` files the now fixed clippy warnings to avoid them in the future?

2022-01-19 09:40 UTC, ManevilleF commented on crates/bevy_ecs/src/world/mod.rs
> +    // TODO: return `std::iter::Copied` instead
I think we should return a `std::iter::Copied` here but I don't know if it would be a breaking change or not

2022-01-19 09:40 UTC, ManevilleF commented on crates/bevy_ecs/src/world/mod.rs
> +    // TODO: return `std::iter::Copied` instead
I think we should return a `std::iter::Copied` here but I don't know if it would be a breaking change or not

2022-01-19 17:23 UTC, alice-i-cecile commented
Yeah, if we're going to fix pedantic / nursery lints we should toggle them on in CI so they stay fixed.

2022-01-19 19:02 UTC, mockersf commented
> Yeah, if we're going to fix pedantic / nursery lints we should toggle them on in CI so they stay fixed.

To be transparent, this is exactly why I think most of those lints should not be fixed. adding more things to control while slow down development. Some add enough values to be worth it, but that's not the case of most of the pedantic lints.

2022-01-20 08:40 UTC, ManevilleF commented
@mockersf I agree, many pedantic lints are not worth it.
I only fixed a few that I think are good practice or useful and ignored the others.

2022-04-22 06:24 UTC, alice-i-cecile commented
@ManevilleF do you want to rebase this? If so we can merge it in ASAP after rebasing; otherwise I think we should just close it out to reduce merge conflicts.

2022-04-22 07:35 UTC, ManevilleF commented
As discussed I will close this and open it again from the `main` branch with the warnings enabled on the CI.

@mockersf @cart I think the current list of warnings is a good start:

```
    clippy::option_if_let_else
    clippy::use_self
    clippy::redundant_else
    clippy::match_same_arms
    clippy::semicolon_if_returned
    clippy::explicit_iter_loop
    clippy::cloned_instead_of_copied
    clippy::map_flatten
```

Do you have more warnings you wish to add or some to remove?

2022-04-22 07:35 UTC, closed without merging

2022-04-22 08:45 UTC, alice-i-cecile commented
[List of lints](https://rust-lang.github.io/rust-clippy/v0.0.212/index.html), for easy reference.

2022-04-22 08:54 UTC, alice-i-cecile commented
Personal opinions:

1. [option_if_let_else](https://rust-lang.github.io/rust-clippy/master/#option_if_let_else): genuinely clearer.
2. [use_self](https://rust-lang.github.io/rust-clippy/master/#use_self): actively dislike this. See #4152.
3. [redundant_else](https://rust-lang.github.io/rust-clippy/master/#redundant_else): seems nice
4. [match_same_arms](https://rust-lang.github.io/rust-clippy/master/#match_same_arms): nice clarity win
5. [semicolon_if_nothing_returned](https://rust-lang.github.io/rust-clippy/master/#semicolon_if_nothing_returned): presuming this is what you meant? Seems like a minor improvement.
6. [explicit_iter_loop](https://rust-lang.github.io/rust-clippy/master/#explicit_iter_loop): no strong feelings
7. [cloned_instead_of_copied](https://rust-lang.github.io/rust-clippy/master/#cloned_instead_of_copied): eh sure why not
8. [map_flatten](https://rust-lang.github.io/rust-clippy/master/#map_flatten): I like it! Much clearer.