Add `gamepad_stick_input` example
bevyengine/bevy pull request #3721
Opened 2022-01-19 05:55 UTC by mfdorst

# Objective

In pursuit of #3691 I felt that it would be handy to have a way to visualize the gamepad stick input.

## Solution

Add an example that shows gamepad stick input.

![gamepad_stick_input](https://user-images.githubusercontent.com/2002883/150072256-8f6ebec1-c1c5-4bf0-a59c-8127497ec5d4.png)

2022-01-19 06:36 UTC, mfdorst commented
Still adding some stuff. I want to mark the deadzone regions with boxes.

2022-01-19 08:11 UTC, alice-i-cecile requested changes

2022-01-19 08:39 UTC, mfdorst commented on examples/input/gamepad_stick_input.rs
> +    commands.spawn_bundle(OrthographicCameraBundle::new_2d());
Lol mistakes were made.

2022-01-19 14:48 UTC, rparrett reviewed
This seems like a good addition to me. We don't expose gamepad settings anywhere else and it looks nice!

2022-01-19 14:48 UTC, rparrett commented on examples/input/gamepad_stick_input.rs
> +    mut xform_query: Query<&mut Transform, With<Crosshair>>,
For consistency with other examples, I think `crosshair_query` would be better here.

2022-01-19 14:48 UTC, rparrett commented on examples/input/gamepad_stick_input.rs
> +    let mut xform = xform_query.single_mut();
For consistency with other examples, I think `let mut transform` would be better here.

2022-01-19 14:48 UTC, rparrett commented on examples/input/gamepad_stick_input.rs
> +                custom_size: Some(Vec2::new(CROSSHAIR_SIZE, CROSSHAIR_SIZE)),
When specifying the size of something that's explicitly square, `Vec2::splat(CROSSHAIR_SIZE)` is nice.

2022-01-19 14:48 UTC, rparrett commented on examples/input/gamepad_stick_input.rs
> +            custom_size: Some(Vec2::new(livezone_box_size, livezone_box_size)),
Same as above

2022-01-19 14:48 UTC, rparrett commented on examples/input/gamepad_stick_input.rs
> +            custom_size: Some(Vec2::new(deadzone_box_size, deadzone_box_size)),
Same as above

2022-01-19 19:00 UTC, alice-i-cecile commented
Can we add a circle with radius 1 to verify that the joystick never leaves it?

2022-01-19 23:42 UTC, mfdorst commented on examples/input/gamepad_stick_input.rs
> +            custom_size: Some(Vec2::new(deadzone_box_size, deadzone_box_size)),
Oh cool I wasn't aware of that. Thanks

2022-01-19 23:46 UTC, mfdorst commented
Not sure how to render a circle but I'll try and figure it out.

2022-01-20 00:05 UTC, mockersf commented
you can't currently without adding a lot of unrelated complexity (or using a picture of a circle)

2022-01-20 00:47 UTC, alice-i-cecile commented
I think either "picture of a circle" or just leaving it would be fine for this initial example.

2022-01-20 03:07 UTC, mfdorst commented
The circle thing adds a bit of complexity because the way the outside deadzone is currently shown is that the clear color is the deadzone color and the livezone is shown with a lighter gray sprite. If I want to show the circle I'd probably to have the livezone be a light gray circle and then render four sprites around the edges for the outside deadzone. I can do that but I think it might be better not to in the interest of simplicity. Let me know what you think.

2022-01-20 03:11 UTC, mfdorst commented
Also, all of this will need to change when #3464 lands, because it will no longer be possible to visualize the deadzone areas  unless we add a way to get the raw unscaled input (incidentally I think that would be handy because then I could show two crosshairs, one for scaled and one for unscaled, but admittedly I can't see a use-case for an actual game).

2022-01-20 07:05 UTC, ickk commented
> Can we add a circle with radius 1 to verify that the joystick never leaves it?

I don't think this is something that controllers generally guarantee. In hardware joysticks are usually a pair of linear variable resistors for each of the x & y axes, with the radius only being constrained physically by the cutout in the plastic form, not electrically. You can verify this by testing your own controllers with something like [gamepad-tester.com](https://gamepad-tester.com/). 

Here's an xbox controllers which has an interesting rounded-square shape because the variable resistors actually max out before being restricted when positioned at the extremes directly along the x/y axes, though it does become constrained by the circular cutout elsewhere: 
![image](https://user-images.githubusercontent.com/17050131/150287022-2161f283-a7c5-4f7b-9fc7-80534113a2a5.png)

Many controllers have differently shaped cutouts, some circular and some octagonal, and there may be some that happen to not limit the radius of the stick at all beyond the extremes of each axis (so x: 1.0, y: 1.0 may be valid/attainable).

2022-01-20 23:26 UTC, mfdorst commented
@rparrett oh I'm sorry, I wasn't aware of the spam issue. I will fix that.

2022-01-20 23:30 UTC, alice-i-cecile approved these changes

2022-05-03 12:59 UTC, Nilirad commented
This PR adds a new example. Adding module and item level doc comments, as described in:

- #3951 and
- #4438,

would be really useful to those who will browse examples.

2022-05-04 22:30 UTC, alice-i-cecile commented
@rparrett could I get your approval on this? This is a super cool example that I'd like to include.

2022-05-05 00:49 UTC, rparrett commented
This PR needs to be updated due to #4519 being merged.

```diff
index 8f9e2cfed..bf8bb4f01 100644
--- a/examples/input/gamepad_stick_input.rs
+++ b/examples/input/gamepad_stick_input.rs
@@ -39,10 +39,10 @@ fn update_position(
     for gamepad in gamepads.iter() {
         // We only use input from the left stick.
         let x = axes
-            .get(GamepadAxis(*gamepad, GamepadAxisType::LeftStickX))
+            .get(GamepadAxis::new(*gamepad, GamepadAxisType::LeftStickX))
             .unwrap();
         let y = axes
-            .get(GamepadAxis(*gamepad, GamepadAxisType::LeftStickY))
+            .get(GamepadAxis::new(*gamepad, GamepadAxisType::LeftStickY))
             .unwrap();
         transform.translation.x = x * WINDOW_SIZE / 2.0;
         transform.translation.y = y * WINDOW_SIZE / 2.0;
```

2022-05-05 15:03 UTC, alice-i-cecile commented
Oh and we also merged #3730, so we can add a unit circle indicator :D

2022-05-05 15:29 UTC, rparrett commented
I do think it would be a good idea to rework this so that it's window-size-agnostic / just displays the thing in the center of the screen. (Thinking about https://bevyengine.org/examples/)

> If I want to show the circle I'd probably to have the livezone be a light gray circle and then render four sprites around the edges for the outside deadzone.

Drawing the edges that way shouldn't be necessary. In order of increasing Z you can spawn

- Big dead zone square
- Live zone square
- Circle
- Little dead zone square

2022-09-21 20:32 UTC, alice-i-cecile commented
Closing in favor of the rebased https://github.com/bevyengine/bevy/pull/6052 <3 Excellent work with the prototyping here though; thanks!

2022-09-21 20:32 UTC, closed without merging