[Merged by Bors] - SystemState usage docs
bevyengine/bevy pull request #3783
Opened 2022-01-27 20:09 UTC by alice-i-cecile

# Objective

- `SystemStates` rock for dealing with exclusive world access, but are hard to figure out how to use.
- Fixes #3341.

## Solution

- Clearly document how to use `SystemState`, and why they're useful as an end-user.

2022-01-27 20:12 UTC, TheRawMeatball commented on crates/bevy_ecs/src/system/function_system.rs
> +/// // This can be cached and reused for improved performance.
This doesn't highlight how caching is necessary for correctness sometimes, such as with event readers and changed filters.

2022-01-27 20:18 UTC, speakk requested changes
Overall looks great, few typos and suggestions and after that I'll send approval!

2022-01-27 20:18 UTC, speakk commented on crates/bevy_ecs/src/system/function_system.rs
> +/// Borrow-checking is handled for you, allowing you to mutably acccess multiple compatible system parameters at once,
acccess -> access

2022-01-27 20:18 UTC, speakk commented on crates/bevy_ecs/src/system/function_system.rs
> +/// // You can use system_state.get(&world) instead for read-only versions of your system parameters
These two lines could possibly be combined into one:
Use system_state.get_mut(&mut world) or system_state.get(&world) for mutable or ready-only versions of your system parameters.

2022-01-27 20:18 UTC, speakk commented on crates/bevy_ecs/src/world/mod.rs
> +/// For split mutable access to the [`World`], use [`World::resource_scope`] or
Is this supposed to be: For splitting mutable access

2022-01-27 20:18 UTC, speakk commented on crates/bevy_ecs/src/world/mod.rs
> +    /// For more complex access patterns, consider using [`SystemState`](crate::system::SystemState).
Very happy you added a reference in the world docs for discoverability!

2022-01-27 21:26 UTC, alice-i-cecile commented
@TheRawMeatball, the caching example is rather involved (relevant to discussion in #3774).

I think I can get it working with a resource scope, but this pattern is clearly suboptimal.

2022-01-28 09:48 UTC, TheRawMeatball commented
Hm, resource_scope is how I do the caching usually, but given the boilerplate associated I agree we could make it better. I'd use resource_scope for now, and we can make a better API for this later.

2022-01-29 00:21 UTC, speakk approved these changes

2022-02-14 20:37 UTC, TheRawMeatball commented on crates/bevy_ecs/src/system/function_system.rs
> +/// This API has more performance overhead than more direct methods: prefer them when possible.
Is this warning really necessary? I can't think of a case where someone would use this api over more direct ones unless they need the extra flexibility.

2022-02-15 05:52 UTC, TheRawMeatball approved these changes

2022-02-15 21:40 UTC, speakk approved these changes
This looks excellent and I will already Approve, but positing one question: Should there be a quick passage on why resource scope might be desirable in certain situations?

Maybe not necessary, just thought I would bring it up anyway.

2022-02-15 21:44 UTC, alice-i-cecile commented
>  Should there be a quick passage on why resource scope might be desirable in certain situations?

It's probably slightly faster in general, and can be clearer / less verbose. I don't think it's worth including without benchmarks that are outside of the scope of this PR.

2022-02-15 21:53 UTC, djeedai approved these changes
That helped quite a lot, thanks for the docs @alice-i-cecile!

2022-02-15 21:53 UTC, alice-i-cecile commented
bors r+

2022-02-15 22:14 UTC, closed without merging