Update ClearColor Resource docs
bevyengine/bevy pull request #3842
Opened 2022-02-01 15:06 UTC by TheAndrewJackson

# Objective
- Update the `ClearColor` resource docs as described in #3837  so new users (like me) understand it better

## Solution
- Update the docs to use what @alice-i-cecile described in #3837 

I took this one up because I got confused by it this weekend. I didn't understand why the  "background" was being set by a `ClearColor` resource.

2022-02-01 15:29 UTC, alice-i-cecile commented on crates/bevy_core_pipeline/src/lib.rs
> +/// The color that is used to clear the screen between frames.
```suggestion
/// When used as a resource, sets the color that is used to clear the screen between frames.

```
The extra line between the "basic description" and "details" is a helpful Rust convention that makes doc strings easier to use in IDEs.

2022-02-01 15:29 UTC, alice-i-cecile requested changes
Thanks for the contribution! <3

2022-02-01 16:16 UTC, TheAndrewJackson commented
You're welcome <3! I think I got all of the PR feedback added correctly

2022-02-01 16:36 UTC, TheAndrewJackson commented on crates/bevy_core_pipeline/src/lib.rs
> +/// there are portions of the screen with nothing rendered over top.
Does only saying "nothing rendered" at the end make sense?

2022-02-01 16:48 UTC, alice-i-cecile commented on crates/bevy_core_pipeline/src/lib.rs
> +/// there are portions of the screen with nothing rendered over top.
> Does only saying "nothing rendered" at the end make sense?

Yeah, I think that makes sense.

2022-02-01 19:35 UTC, alice-i-cecile commented
Can you fix up the comment from `@mockersf`? That's the last nit that I think we'll need for this PR :)

2022-02-01 20:04 UTC, alice-i-cecile approved these changes

2022-02-01 20:05 UTC, TheAndrewJackson commented
It's updated now :)

2022-02-01 22:37 UTC, mockersf approved these changes

2022-02-02 21:29 UTC, alice-i-cecile commented
bors r+

2022-02-02 21:47 UTC, closed without merging