[Merged by Bors] - improve error messages for render graph runner
bevyengine/bevy pull request #3930
Opened 2022-02-13 05:10 UTC by dataphract

# Objective

Currently, errors in the render graph runner are exposed via a `Result::unwrap()` panic message, which dumps the debug representation of the error.

## Solution

This PR updates `render_system` to log the chain of errors, followed by an explicit panic:

```
ERROR bevy_render::renderer: Error running render graph:
ERROR bevy_render::renderer: > encountered an error when running a sub-graph
ERROR bevy_render::renderer: > tried to pass inputs to sub-graph "outline_graph", which has no input slots
thread 'main' panicked at 'Error running render graph: encountered an error when running a sub-graph', /[redacted]/bevy/crates/bevy_render/src/renderer/mod.rs:44:9
```

Some errors' `Display` impls (via `thiserror`) have also been updated to provide more detail about the cause of the error.

2022-02-13 17:07 UTC, alice-i-cecile requested changes
This is a good change. Just a consistency nit to clean up.

2022-02-13 17:07 UTC, alice-i-cecile commented on crates/bevy_render/src/render_graph/context.rs
> +    #[error("attempted to pass inputs to sub-graph \"{0}\", which has no input slots")]
These are sometimes \`, sometimes " and sometimes nothing at all. I would prefer \` everywhere, but would like consistency regardless.

2022-02-13 19:38 UTC, alice-i-cecile approved these changes

2022-02-14 00:04 UTC, mockersf approved these changes

2022-03-05 21:22 UTC, mockersf commented
@dataphract could you update this on current main?

2022-03-07 09:09 UTC, mockersf commented
bors r+

2022-03-07 09:27 UTC, closed without merging