Remove WorldCell
bevyengine/bevy pull request #3939
Opened 2022-02-13 23:08 UTC by alice-i-cecile

# Objective

- `WorldCell` is not fully featured: see #1555.
- As a result, it does not fully behave like a `Cell` (a runtime borrow-checked API to split borrows arbitrarily).
- Making it fully-featured is a questionable idea: see discussion in https://github.com/bevyengine/rfcs/pull/42 on how this promotes very panic-prone, fragile and hard-to-reason about code that is easy to write.

## Solution

- Remove `WorldCell` completely, rather than keeping a half-working implementation around.
- Users should use `resource_scope` and `SystemState` instead (for now).
- As clear use cases arise that cannot be comfortably tackled with the existing API, add additional, less error-prone methods on `World`.

2022-02-13 23:11 UTC, alice-i-cecile commented
@bevyengine/ecs-team; this is fundamentally a design decision. RFC #42 seems fairly doomed (a decision I support), but if it's doomed we should close it and remove the half-working `WorldCell` API.

As a point in favor of this removal, this API was *never* used internally.

2022-02-13 23:15 UTC, cart commented
> As a point in favor of this removal, this API was never used internally.

This isn't true :)

![image](https://user-images.githubusercontent.com/2694663/153779537-08f3514a-c942-4598-a5ff-57cfef2dfea9.png)

2022-02-13 23:19 UTC, alice-i-cecile commented
Ah, my search missed it. Let me try fixing those...

2022-02-13 23:22 UTC, cart commented
Pretty sure they can all be replaced with SystemState or resource_scope.
What WorldCell really enables is "arbitrary nesting of non-conflicting contexts with arbitrary ad-hoc borrows". Bevy doesn't use that pattern internally except for the RenderGraph resource_scope, but I can see why some users might want it. _We_ might want it if we want to support Entitas-style event handlers.

2022-02-13 23:27 UTC, alice-i-cecile commented
> What WorldCell really enables is "arbitrary nesting of non-conflicting contexts with arbitrary ad-hoc borrows"

I agree.

This is a *very* risky pattern, and non-trivial uses of this are likely to lead to complex runtime panics whenever surrounding code is changed. IMO the ideas discussed in #2192 are a much better way to accomplish the same goals.

2022-02-14 00:32 UTC, alice-i-cecile commented
It's a bit frustrating not to have a better solution for #2192 yet; the extremely complex system state constructed in `winit_runner` would particularly benefit from the caching and complexity management. Looking at the code, I actually think it may be cleanest to just create / store / run a little schedule on the App to push the information from `winit` into the various event resources. This would also make `winit_runner` much more reusable / hackable.

Overall, that refactor was quite painless, even for extremely complex uses of `WorldCell`. And now the system state can be cached and the borrow checker rules are upheld at compile time.

2022-02-14 15:52 UTC, TheRawMeatball commented
> We might want it if we want to support Entitas-style event handlers.

I personally think requiring &mut World and adding hooks would be a better way to support this.

2022-02-14 18:19 UTC, TheRawMeatball reviewed
I agree with the idea, but the winit runner can be done better imo.

2022-02-14 18:19 UTC, TheRawMeatball commented on crates/bevy_winit/src/lib.rs
> +                let mut system_state: SystemState<(
I think i agree with clippy on this one, this type is horrendeous. I'd recommend making a custom struct and using `#[derive(SystemParam)]` so it's neater.

2022-02-14 19:12 UTC, TheRawMeatball approved these changes

2022-03-04 19:17 UTC, aevyrie commented
Please ping me when this is ready to merge, assuming it happens after #3974. I want to double check that everything still behaves as expected. 🙂

2022-03-04 19:30 UTC, aevyrie requested changes

2022-03-04 19:30 UTC, aevyrie commented on crates/bevy_pbr/src/render/light.rs
> +            let mesh_pipeline = world.get_resource::<MeshPipeline>().unwrap();
```suggestion
            let mesh_pipeline = world.resource::<MeshPipeline>();
```

2022-03-04 19:30 UTC, aevyrie commented on crates/bevy_render/src/lib.rs
> +                    .unwrap();
```suggestion
                    .resource_mut::<bevy_window::Windows>();
```

2022-03-05 18:58 UTC, aevyrie commented
Got it! We'll just have to be mindful if/when this and #3974 are merged that we don't accidentally break anything in the merging process. We don't have an effective way to automatically test the window updating just yet.

2022-06-26 23:22 UTC, alice-i-cecile commented
Closing in favor of the dramatically less controversial #5109. I still think this should be done, but the code-quality changes should be ported over ASAP anyways.

2022-06-26 23:22 UTC, closed without merging

2024-03-17 22:56 UTC, james7132 commented
Our internal uses of `World::cell` outside of tests is now at 0. It might be a good time to revisit this now that we have `UnsafeWorldCell` and `DeferredWorld`.