Fix mesh2d_manual example
bevyengine/bevy pull request #4037
Opened 2022-02-25 18:04 UTC by rparrett

# Objective

Fixes #4036 

## Solution

- Use `VertexBufferLayout::from_vertex_formats`
- Actually put a u32 into `ATTRIBUTE_COLOR` and convert it in the shader

2022-02-25 18:15 UTC, alice-i-cecile commented on examples/2d/mesh2d_manual.rs
> +        let vertex_layout =
Much more robust!

2022-02-25 19:46 UTC, alice-i-cecile approved these changes
Much more robust and clear than before, and confirmed to fix the issue. I'm unsure about the color question, but otherwise this LGTM.

2022-02-25 20:50 UTC, rparrett commented
I updated the description with slightly more info about the color situation.

2022-02-26 23:37 UTC, superdump requested changes
It feels clunky that `ATTRIBUTE_COLOR` is a `u32` but that's not your fault.

That said, it feels like it would be nicer to have `Color::as_rgba_u32(self: Color) -> u32` and `Color::as_linear_rgba_u32(self: Color) -> u32` to support use of `ATTRIBUTE_COLOR`.

2022-03-03 22:45 UTC, superdump commented
* #4088 now exists so I think this should use that.

2022-03-08 11:55 UTC, james7132 approved these changes
We definitely need shader utilities for handling conversion back to vec4<f32>, but that's for another time. This works well as an example.

2022-03-08 17:35 UTC, rparrett commented on examples/2d/mesh2d_manual.rs
> +    out.color = vec4<f32>((vec4<u32>(vertex.color) >> vec4<u32>(0u, 8u, 16u, 24u)) & vec4<u32>(255u)) / 255.0;
I'm not sure that I can adequately explain the process, but I added a command that hopefully communicates the intent of the code.

2022-03-08 17:50 UTC, alice-i-cecile commented
bors r+

2022-03-08 18:04 UTC, mockersf commented on examples/2d/mesh2d_manual.rs
> +    out.color = vec4<f32>((vec4<u32>(vertex.color) >> vec4<u32>(0u, 8u, 16u, 24u)) & vec4<u32>(255u)) / 255.0;
good enough for me, thanks!

2022-03-08 18:04 UTC, mockersf approved these changes

2022-03-08 18:07 UTC, closed without merging