Expose draw indirect
bevyengine/bevy pull request #4056
Opened 2022-02-27 17:03 UTC by Ku95

# Objective

- Currently there is now way of making an indirect draw call from a tracked render pass.
- This is a very useful feature for GPU based rendering.

## Solution

- Expose the `draw_indirect` and `draw_indexed_indirect` methods from the wgpu `RenderPass` in the `TrackedRenderPass`.

## Alternative

- #3595: Expose the underlying `RenderPass` directly

2022-02-27 17:28 UTC, superdump reviewed
This looks good to me though I’d need to double-check that the documentation is correct.

2022-02-27 18:30 UTC, Ku95 commented
The documentation is copied over from the wgpu equivalent.

2022-02-27 19:55 UTC, superdump approved these changes

2022-02-27 20:47 UTC, cart commented
bors r+

2022-02-27 20:57 UTC, superdump commented
> bors r+

I meant to respond "approved but fix the CI errors first" :)

2022-02-28 07:54 UTC, superdump requested changes
Suggestions that should fix the CI errors.

2022-02-28 07:54 UTC, superdump commented on crates/bevy_render/src/render_phase/draw_state.rs
> +        self.pass.draw_indirect(&indirect_buffer, indirect_offset);
```suggestion
        self.pass.draw_indirect(indirect_buffer, indirect_offset);
```

2022-02-28 07:54 UTC, superdump commented on crates/bevy_render/src/render_phase/draw_state.rs
> +            .draw_indexed_indirect(&indirect_buffer, indirect_offset);
```suggestion
            .draw_indexed_indirect(indirect_buffer, indirect_offset);
```

2022-02-28 10:10 UTC, Ku95 commented
Sorry my bad, was in a hurry yesterday.

2022-02-28 10:26 UTC, mockersf approved these changes

2022-02-28 10:26 UTC, mockersf commented
bors r+

2022-02-28 10:42 UTC, closed without merging