Add `#[reflect(default)]` attribute for `FromReflect`
bevyengine/bevy pull request #4140
Opened 2022-03-07 10:26 UTC by MrGVSV

# Objective

Currently, `FromReflect` makes a couple assumptions:

* Ignored fields must implement `Default`
* Active fields must implement `FromReflect`

However, one or both of these requirements might be unachievable, such as for external types. In these cases, it might be nice to tell `FromReflect` to use a custom default.

## Solution

Added the `#[reflect(default)]` derive helper attribute. This attribute can be applied to any field and will allow a default to be specified in place of the regular `from_reflect()` call. 

It takes two forms: `#[reflect(default)]` and `#[reflect(default = "some_func")]`. The former specifies that `Default::default()` should be used while the latter specifies that `some_func()` should be used. This is pretty much [how serde does it](https://serde.rs/field-attrs.html#default).

### Example

```rust
#[derive(Reflect, FromReflect)]
struct MyStruct {
  // Use `Default::default()`
  #[reflect(default)]
  custom: CustomStruct

  // Use `get_foo_default()`
  #[reflect(default = "get_foo_default")]
  #[reflect(ignore)]
  foo: usize,
}

fn get_foo_default() -> usize {
  123
}
```

### Reflect Attributes

Most of the attribute handling was moved to a new `attributes` module. The idea was to _hopefully_ make adding more `#[reflect(...)]` attributes easier and cleaner. 

### Additional Changes

To reduce code duplication, I also cleaned up some of the files. However, if this is too much to put into a single PR, I can split it into separate ones. The minimal code for the feature itself is in 48b1e470d8bbb5a7f2ef4c2d6ad62fbe9550bd3e, everything after is cleanup stuff so it shouldn't be hard to separate if desired.

### Related

* #3733 
* #2377

2022-05-08 01:28 UTC, MrGVSV commented
With #3733 merged, I'm wondering: would also be good to make it so we use the struct's `Default` impl for unmarked ignored fields (if `#[reflect(Default)]` is defined)?

So for example, `value` would default to `123` instead of its usual `0` here:

```rust
#[reflect(Default)]
struct Foo {
  value: i32
}

impl Default for Foo {
  fn default() -> Self {
    Self {
      value: 123
    }
  }
}

let foo: Foo = FromReflect::from_reflect(dyn_foo_struct);
assert_eq!(123, foo.value);
```

This could be convenient for when defining custom `Default` impls. However, it could also be counter-intuitive and possibly footgunny since it would only be applicable for when `#[reflect(Default)]` is used.

Alternatively, we could define a sister attribute for the struct itself, like [serde does](https://serde.rs/container-attrs.html#default). This might result in more macro clutter, though...

2022-05-09 18:13 UTC, PROMETHIA-27 requested changes
Tests for correct behavior would probably also be a good idea. 

I like the changes overall, but mixing all of the cleanup changes with the actual feature additions does make it harder to review.

2022-05-09 18:18 UTC, MrGVSV commented
> Tests for correct behavior would probably also be a good idea.

Lol was just adding some since I noticed that too.

> I like the changes overall, but mixing all of the cleanup changes with the actual feature additions does make it harder to review.

Would it be better if I split it up then? I like the changes because they make the end product a lot nicer to read/maintain. But if it's too difficult to review, then I can try to turn the cleanup changes into a followup PR.

2022-05-09 21:41 UTC, PROMETHIA-27 commented
I think it makes sense that if you reflect Default on a type, then creating an instance of that type from e.g. an empty dynamic struct should have all default values. So yeah, I think it's a good idea. I'm somewhat hesitant but I think it makes more sense than each value defaulting to its own default value. But also, it might cause a niche backwards incompatibility issue if that's done- I'm not sure if it's worth worrying about (or worth intentionally causing anyway) but good to keep in mind I think.
E.g. if I have the type
```
#[derive(Reflect)]
#[reflect(Default)]
struct Foo {
    x: i32
}
```
where x defaults to 12, this would suddenly change behavior from a 0'd x to 12 without changing the code. But reflect(Default) was also *just* added and hasn't been released in a version yet, so chances are no one is going to run into this.

2022-05-09 23:56 UTC, MrGVSV commented
> where x defaults to 12, this would suddenly change behavior from a 0'd x to 12 without changing the code.

Yeah that was one of the concerns. Although, I think it makes sense that using `#[reflect(Default)]` would act much like serde's container `#[serde(default)]`. And thinking on it more, using an alternative mechanism (like our own container `#[reflect(default)]`) could result in weird/unexpected behavior.

So I think if a user lets the reflection system know it implements `Default`, then we should use it.

2022-05-10 07:29 UTC, MrGVSV commented
Going to put this in draft form until #4712 is merged. We could just revert to the first commit of this PR and rebase from there, but I think it would just be easier to wait and see if the cleanup PR gets accepted/merged first so I can use some of the niceties added there.

If it's rejected or gets blocked for a long time, I'll go ahead and do the revert and rebase.

2022-05-17 06:43 UTC, MrGVSV commented
Rebased and reopened!

2022-05-17 07:36 UTC, MrGVSV commented
> Although, I think it makes sense that using `#[reflect(Default)]` would act much like serde's container `#[serde(default)]`

Added this behavior!

2022-05-30 16:12 UTC, alice-i-cecile commented on crates/bevy_reflect/bevy_reflect_derive/src/container_attributes.rs
> +// Traits not considered "special" (i.e. use the `ReflectMyTrait` syntax)
```suggestion
// The traits listed below are not considered "special" (i.e. they use the `ReflectMyTrait` syntax)
```

2022-05-30 16:17 UTC, alice-i-cecile commented on crates/bevy_reflect/src/lib.rs
> +            // Use `get_foo_default()`
```suggestion
            // Use `get_bar_default()`
```

2022-05-30 16:18 UTC, alice-i-cecile requested changes
Some small nits to clean up, then this LGTM. We'll need a second reviewer (@PROMETHIA-27?) before I can merge this though; it's not trivial and more eyes will help.

2022-05-30 17:07 UTC, PROMETHIA-27 approved these changes
LGTM!

2022-05-30 18:16 UTC, alice-i-cecile commented
bors r+

2022-05-30 19:21 UTC, closed without merging