[Merged by Bors] - fix cluster tiling calculations
bevyengine/bevy pull request #4148
Opened 2022-03-08 09:33 UTC by robtfm

# Objective

fix cluster tilesize and tilecount calculations.
Fixes https://github.com/bevyengine/bevy/issues/4127 & https://github.com/bevyengine/bevy/issues/3596

## Solution

- calculate tilesize as smallest integers such that dimensions.xy() tiles will cover the screen
- calculate final dimensions as smallest integers such that final dimensions * tilesize will cover the screen

there is more cleanup that could be done in these functions. a future PR will likely remove the tilesize completely, so this is just a minimal change set to fix the current bug at small screen sizes

2022-03-08 12:56 UTC, superdump requested changes
I think we should probably be using `debug_assert` for situations that could happen due to programming errors within bevy that would cause runtime problems, but that if we wrote our code properly, should never happen. And then use `assert` for things that could happen at runtime in release builds due to a user error, though proper error handling would be nicer than panicking... so I'm trying to think of a situation where assert should really be used... I realise I've used `assert` elsewhere in this code but the thought came up now. @cart @mockersf do you have any opinion / clear thoughts and guidelines on this?

2022-03-08 12:56 UTC, superdump commented on crates/bevy_pbr/src/light.rs
> +                );
This catches a developer error so I think it should be a debug_assert so it gets compiled out for release builds.
```suggestion
                debug_assert!(
                    *total >= *z_slices,
                    "ClusterConfig has more z-slices than total clusters!"
                );
                let per_layer = *total as f32 / *z_slices as f32;
```

2022-03-08 12:56 UTC, superdump commented on crates/bevy_pbr/src/light.rs
> +                let mut y = y.floor() as u32;
Now I think about it, the `.floor()` should be unnecessary as casting to `u32` to should truncate.
```suggestion
                let mut x = (y * aspect_ratio) as u32;
                let mut y = y as u32;
```

2022-03-08 12:56 UTC, superdump commented on crates/bevy_pbr/src/light.rs
> +        assert!(dimensions.x > 0 && dimensions.y > 0 && dimensions.z > 0);
This is a private method and I think if these are 0, it is our fault, so I think these should be debug_assert too.
```suggestion
        debug_assert!(screen_size.x > 0 && screen_size.y > 0);
        debug_assert!(dimensions.x > 0 && dimensions.y > 0 && dimensions.z > 0);
```

2022-03-08 19:09 UTC, superdump approved these changes

2022-03-10 00:54 UTC, cart commented
> I think we should probably be using debug_assert for situations that could happen due to programming errors within bevy that would cause runtime problems

The rule of thumb I've been using:
1. When possible, use tests instead of asserts. The more expensive an assertion is, the more you should try to make it a test. We shouldn't meaningfully compromise dev performance because we aren't confident in our code. For expensive checks, we should achieve confidence through other forms of testing.
2. For cheap assertions that can't be tests, use debug_assert.

2022-03-10 01:01 UTC, cart commented
This particular case doesn't feel like a debug_assert. This is a user-facing type that has constraints on the values it supports. These constraints should either be enforced here (panic if unrecoverable, or warn + auto-constrain to avoid crashing) or they should be enforced via a constructor. I'm inclined to auto-constrain and warn here.

2022-03-10 01:14 UTC, cart commented
bors r+

2022-03-10 01:26 UTC, closed without merging