Split bevy_hierarchy out from bevy_transform
bevyengine/bevy pull request #4168
Opened 2022-03-10 04:15 UTC by alice-i-cecile

# Objective

- Hierarchy tools are not just used for `Transform`: they are also used for scenes.
- In the future there's interest in using them for other features, such as visiibility inheritance.
- The fact that these tools are found in `bevy_transform` causes a great deal of user and developer confusion
- Fixes #2758.

## Solution

- Split `bevy_transform` into two!
- Make everything work again.

Note that this is a very tightly scoped PR: I *know* there are code quality and docs issues that existed in bevy_transform that I've just moved around. We should fix those in a seperate PR and try to merge this ASAP to reduce the bitrot involved in splitting an entire crate.

## Additional context

- double-blessed by @cart in https://github.com/bevyengine/bevy/issues/4141#issuecomment-1063592414 and https://github.com/bevyengine/bevy/issues/2758#issuecomment-913810963
- preparation for more advanced / cleaner hierarchy tools: go read https://github.com/bevyengine/rfcs/pull/53 !
- originally attempted by @finegeometer in #2789. It was a great idea, just needed more discussion!

2022-03-10 04:16 UTC, alice-i-cecile commented
@cart as part of this PR's merge process, can we get a `A - Hierarchy` label?

2022-03-10 21:52 UTC, mockersf requested changes

2022-03-10 21:52 UTC, mockersf commented on crates/bevy_hierarchy/.gitignore
> +**/*.rs.bk
this file shouldn't be here

2022-03-11 02:51 UTC, james7132 requested changes

2022-03-11 02:51 UTC, james7132 commented on crates/bevy_hierarchy/src/hierarchy/hierarchy_maintenance_system.rs
> +    use bevy_transform::components::Transform;
I feel like this should be rectified. `bevy_hierarchy` should be a dependency of `bevy_transform` not the other way around, even for test dependencies.

2022-03-11 02:51 UTC, james7132 commented on crates/bevy_ui/src/lib.rs
> +                    .before(HierarchySystem::TransformPropagate),
Mirroring my coments from another file. This seems backwards. TransformPropagate should remain a TransformSystem, and HierarchySystems for maintaining the hierarchy should be separate. Hopefully in the near future, we won't need any HierarchySystems.

2022-03-12 03:39 UTC, alice-i-cecile commented
bors try

2022-03-12 20:45 UTC, IceSentry commented
btw, bevy_hierarchy is not reserved on crates.io. Even if this PR doesn't get merged, we should probably reserve it. 

https://crates.io/crates/bevy_hierarchy

2022-03-13 06:44 UTC, james7132 approved these changes

2022-03-14 15:35 UTC, mockersf approved these changes

2022-03-15 01:39 UTC, cart commented
> The API around GlobalTransform is a mess: we have massive code and docs duplication, no link between the two types and no clear way to extend this to other forms of inheritance. In the medium-term, I feel pretty strongly that GlobalTransform should be replaced by something like Inherited<Transform>, which lives in bevy_hierarchy

I object to the framing that a fully separate GlobalTransform component is a "mess". I personally think a named (and fully separate) GlobalTransform type is preferable to a more abstracted "component inheritance system". GlobalTransform having a separate type (and name) makes the context and "space" (as in "world space") of the component clear. It also leaves the door open to things like "adding a `GlobalTransform::ignore_parent` field".

On the other hand, `Inherited<Transform>` could literally mean anything (and _would_ mean different things, depending on the context of `Inherited + ComponentType`). Of course, the value of this design is up for debate (and should be discussed in a different place), but by including "highly opinionated and negatively weighted" thoughts on what we already have, I feel compelled to reply here.

2022-03-15 01:41 UTC, cart commented
(but I do agree that it would be nice to cut down on code duplication ... impl macros or Deref are also options)

2022-03-15 01:53 UTC, cart approved these changes
Looks good to me. Just one baby nit.

2022-03-15 01:53 UTC, cart commented on crates/bevy_transform/src/lib.rs
> +/// Label enum for the systems relating to transform propagaion
```suggestion
/// Label enum for the systems relating to transform propagation
```

2022-03-15 01:53 UTC, cart commented
bors r+

2022-03-15 02:15 UTC, alice-i-cecile commented
>  but by including "highly opinionated and negatively weighted" thoughts on what we already have, I feel compelled to reply here.

Fair; this wasn't really the place or tone for it. I'm sorry for that @cart. I was frustrated about the code duplication, but we can debate the relative merits of that design somewhere else.

2022-03-15 02:16 UTC, closed without merging

2022-03-15 02:28 UTC, cart commented
> Fair; this wasn't really the place or tone for it. I'm sorry for that @cart. I was frustrated about the code duplication, but we can debate the relative merits of that design somewhere else.

No worries. I almost didn't say anything because its definitely ok to think something is a mess (although I try to avoid using that language to avoid hurting peoples' feelings ... and to account for the fact that I might find out I'm wrong about that assessment. When trying to get that point across, I think its better to just outline the specific facts of the situation rather than ascribe generic negative labels to things). I mainly brought it up because I'd rather leave "opinionated discussions and pronouncements about the value of a thing" to issues scoped to that topic. I selfishly don't want to defend my design choices in 10 different places :)