Improve the `set_active_camera` system
bevyengine/bevy pull request #4251
Opened 2022-03-19 08:00 UTC by kirusfg

# Objective

- Make `set_active_camera` system correctly respond to camera deletion, while preserving its correct behavior on first ever frame and any consequent frame, and with multiple cameras of the same type available in the world.
- Fixes #4227

## Solution

- Add a check that the entity referred to by `ActiveCamera` still exists in the world.

2022-03-19 08:23 UTC, alice-i-cecile commented on crates/bevy_render/src/camera/camera.rs
> +    // If the previous active camera ceised to exist -
```suggestion
    // If the previous active camera ceased to exist
```

2022-03-19 08:26 UTC, alice-i-cecile requested changes
IMO we should tighten the query in the system you tweaked to add a With filter for Camera. It'll catch a few really weird edge cases when using the fallback you added.

2022-03-19 16:22 UTC, kirusfg commented
Yep, you could definitely slap a `Camera3d` or `Camera2d` on anything and it would cause problems, but I hope Bevy users won't do that :)

I've included your suggestions, and I hope correctly.

2022-03-19 16:31 UTC, alice-i-cecile approved these changes
Perfect, that was exactly what I had in mind.

2022-03-19 21:54 UTC, mockersf approved these changes

2022-03-28 06:38 UTC, superdump approved these changes

2022-04-07 23:30 UTC, cart commented
bors r+

2022-04-07 23:46 UTC, closed without merging