Improve docs and naming for RawWindowHandle functionality
bevyengine/bevy pull request #4335
Opened 2022-03-26 00:58 UTC by alice-i-cecile

# Objective

- As noticed in #4333 by @x-52, the exact purpose and logic of `HasRawWIndowHandleWrapper` is unclear
- Unfortunately, there are rather good reasons why this design is needed (and why we can't just `impl HasRawWindowHandle for RawWindowHandleWrapper` 

## Solution

- Rename `HasRawWindowHandleWrapper` to `ThreadLockedRawWindowHandleWrapper`, reflecting the primary distinction
- Document how this design is intended to be used
- Leave comments explaining why this design must exist

---

## Changelog

> This section is optional. If this was a trivial fix, or has no externally-visible impact, feel free to skip this section.

- What changed as a result of this PR?
- If applicable, organize changes under "Added", "Changed", or "Fixed" sub-headings
- Stick to one or two sentences. If more detail is needed for a particular change, consider adding it to the "Solution" section
  - If you can't summarize the work, your change may be unreasonably large / unrelated. Consider splitting your PR to make it easier to review and merge!

## Migration Guide

> This section is optional

- If this PR is a breaking change (relative to the last release of Bevy), describe how a user might need to migrate their code to support these changes
- Simply adding new functionality is not a breaking change.
- Fixing behavior that was definitely a bug, rather than a questionable design choice is not a breaking change.

2022-03-26 01:05 UTC, alice-i-cecile commented
Pulling in @cart directly for a review here as the original author of the code. I'm reasonably confident that I understand the logic behind the design now, but this is tricksy unsafe logic.

2022-04-25 17:59 UTC, nicopap requested changes

2022-04-25 17:59 UTC, nicopap commented on crates/bevy_window/src/raw_window_handle.rs
> +/// A [`RawWindowHandleWrapper`] that cannot be sent across threads
```suggestion
/// A [`RawWindowHandleWrapper`] that cannot be sent across threads.
```

2022-04-25 17:59 UTC, nicopap commented on crates/bevy_window/src/raw_window_handle.rs
> +    /// Returns a [`HasRawWindowHandle`] impl, which exposes [`RawWindowHandle`]
```suggestion
    /// Returns a [`HasRawWindowHandle`] impl, which exposes [`RawWindowHandle`].
```

2022-04-25 17:59 UTC, nicopap commented on crates/bevy_window/src/raw_window_handle.rs
> +/// and so we cannot simply make it (or any type that has a safe opration to get a [`RawWindowHandle`])
```suggestion
/// and so we cannot simply make it (or any type that has a safe operation to get a [`RawWindowHandle`])
```

2022-04-25 18:49 UTC, nicopap approved these changes

2022-05-25 00:19 UTC, cart commented
bors r+

2022-05-26 00:09 UTC, cart commented
bors r+

2022-05-26 00:27 UTC, closed without merging