example on how to create an animation in code
bevyengine/bevy pull request #4399
Opened 2022-04-03 12:44 UTC by mockersf

# Objective

- Animation can be used outside of glTF, but are not obvious on how to create them

## Solution

- Add an example creating an animation

2022-04-03 17:18 UTC, devil-ira commented on examples/animation/animated_transform.rs
> +    let satellite = Name::new("satellite".to_string());
```suggestion
    let planet = Name::new("planet");
    let orbit_controller = Name::new("orbit_controller");
    let satellite = Name::new("satellite");
```
Minor nit. Looking good!

2022-04-03 18:46 UTC, alice-i-cecile commented on examples/README.md
> +`animated_transform` | [`animation/animated_transform.rs`](./animation/animated_transform.rs) | Create an animation in code on transforms, and play it.
```suggestion
`animated_transform` | [`animation/animated_transform.rs`](./animation/animated_transform.rs) | Create and play an animation defined by code that operates on the `Transform` component.
```

2022-04-03 18:47 UTC, alice-i-cecile commented on examples/animation/animated_transform.rs
> +    // Animation use name to target entities.
```suggestion
    // The animation API uses the `Name` component to target entities
```

2022-04-03 18:47 UTC, alice-i-cecile commented on examples/animation/animated_transform.rs
> +    // Or the rotation of the transform. To find the entity to modify, the hierarchy
```suggestion
    // Or it can modify the rotation of the transform.
    // To find the entity to modify, the hierarchy
```

2022-04-03 18:48 UTC, alice-i-cecile requested changes
Left some wording nits, once those are resolved this LGTM.

2022-04-03 19:58 UTC, alice-i-cecile approved these changes

2022-04-07 23:53 UTC, cart commented
bors r+

2022-04-08 00:20 UTC, closed without merging