Switch from &str to String in ReflectPathError
bevyengine/bevy pull request #4763
Opened 2022-05-16 10:16 UTC by makspll

# Objective

- ReflectPathError uses non-owned strings, meaning that often when returning errors lifetime issues are encountered.
- Things like the `?` operator need to often be used with `map_err` and a `to_owned` call to work 

## Solution

- Let the error type own the string, this increases ergonomics at negligible cost.
- I don't think these errors are thrown a lot (at least in my use case)

---

## Migration Guide

- Change type from &str to String in `InvalidField`, `UnexpectedToken` and `ExpectedToken` variants of `bevy_reflect::ReflectPathError`

2022-05-16 20:46 UTC, alice-i-cecile approved these changes
The code changes look good, and the ergonomics are better. Because this only happens on the unhappy path, I'm 100% okay with prioritizing ergonomics over performance.

2022-05-16 20:49 UTC, james7132 requested changes
If we're using this for Reflect-based animation, this puts copies and allocation on the hotpath for something driven from an asset. Could we use `Cow<'static, str>`  or `&'static str` instead where we have `&'static str` literals? It seems like a good number of these are indeed coming from literals.

2022-05-17 00:03 UTC, makspll commented
I've changed this to `Cow<'a,str>` now, that seems like the perfect compromise.

How does this end up on the hotpath exactly?

2022-05-17 01:21 UTC, james7132 commented
> I've changed this to `Cow<'a,str>` now, that seems like the perfect compromise.

You can probably replace `'a` with `'static` and remove the lifetime parameter from it. This was mostly to avoid allocating when we have literals.

> How does this end up on the hotpath exactly?

We read the field path from an animation clip alongside values of the appropriate type, then use `GetPath` to use `Reflect` to write the animated value to it. This can happen 10+ times per animated entity per frame. You might see a few hundred to a few thousand of these used per frame. And because it's coming from a saved asset and not code, if it fails, it'll fail repeatedly and quickly.

2022-05-17 03:00 UTC, alice-i-cecile commented
Thanks James; that context is super helpful here. I like the use of Cow here, and like you said, I think we may be able to get rid of the lifetime.

2022-05-17 11:26 UTC, makspll commented
Alrighty, Done.

Now I didn't want to touch the external API much so there are two `to_owned()` calls:
- https://github.com/makspll/bevy/blob/e8db50d9572e5f2e0b78ac96aaceb17f68667756/crates/bevy_reflect/src/path.rs#L242-L269
- https://github.com/makspll/bevy/blob/e8db50d9572e5f2e0b78ac96aaceb17f68667756/crates/bevy_reflect/src/path.rs#L271-L298

Both only happen for the `ReflectPathError::InvalidField` error variant,  could maybe be avoided if `Cow`'s are passed around instead of `&str`s

2022-05-17 15:42 UTC, MrGVSV approved these changes
Looks good to me. I think the `field.to_owned().into()` you mentioned is unavoidable due to how `read_field[_mut]` is used.

2022-05-17 16:17 UTC, PROMETHIA-27 requested changes
Looks good, but I think we probably want to benchmark this on a real scenario before we come to a final decision. If it's causing excessive allocations it could be the difference between usable and unusable animation, especially since it is entirely possible that people will want to leverage the ECS and end up with thousands of animating models at the same time.

2022-05-17 16:17 UTC, PROMETHIA-27 commented on crates/bevy_reflect/src/path.rs
> +                    field: field.to_owned().into(), // possibly removable to_owned() ?
.to_owned() is not removable here, so long as we're going with 'static `Cow`s, right?
```suggestion
                    field: field.to_owned().into(),
```

2022-05-17 16:17 UTC, PROMETHIA-27 commented on crates/bevy_reflect/src/path.rs
> +                    field: field.to_owned().into(), // possibly removable to_owned() ?
```suggestion
                    field: field.to_owned().into(),
```

2022-05-17 17:28 UTC, alice-i-cecile commented on crates/bevy_reflect/src/path.rs
> +                    field: field.to_owned().into(), // possibly removable to_owned() ?
```suggestion
                    field: field.to_owned().into(),
```

2022-12-03 07:21 UTC, MrGVSV commented
Hi @makspll! Are you planning to add benchmarks for this change? If you need help, maybe reach out to the community on Discord (I'm sure someone there has a good idea of how to go about this well)? Or we could also move this over to `S-Adopt-Me` for someone else to just pick up and finish the benchmarking. Up to you!

2022-12-06 19:44 UTC, makspll commented
Hi @MrGVSV Apologies, I completely forgot about this PR, at this point yeah it's probably better adopted :)

2024-10-13 07:19 UTC, richchurcher commented
Backlog cleanup: closing due to inactivity, could still be adopted but `ReflectPathError` has changed shape quite a bit since then.

2024-10-13 07:19 UTC, closed without merging