Yeet fetch state
bevyengine/bevy pull request #4802
Opened 2022-05-19 01:58 UTC by james7132

# Objective
`FetchState` adds a bit of additional type/trait impl bloat. Slim down ECS's compilation by moving the implementation to `Fetch` instead.

## Solution
Move the implementations onto their associated `Fetch` instead, remove the old implementations.

I tried putting this on `WorldQuery` instead, but it snagged on some of the `Fetch` impls for some of the filters.

---

## Changelog
TODO

## Migration Guide
TODO

2022-05-22 09:13 UTC, james7132 commented
This is basically ready, but #4807 should probably be merged first.

2022-05-31 07:32 UTC, james7132 commented
#4807 has been checked in. Taking this out of draft.

2022-05-31 16:22 UTC, BoxyUwU requested changes

2022-05-31 23:04 UTC, james7132 commented on crates/bevy_ecs/src/query/fetch.rs
> +    ) {
Done.

2022-05-31 23:04 UTC, james7132 commented on crates/bevy_ecs/src/query/fetch.rs
>  pub trait Fetch<'world>: Sized {
Done.

2022-05-31 23:04 UTC, james7132 commented on crates/bevy_ecs/src/query/fetch.rs
> +    fn update_component_access(state: &Self::State, access: &mut FilteredAccess<ComponentId>) {}
Done.

2022-07-06 18:20 UTC, james7132 commented
This has been superceded by #5205, which does this and further collapses the WorldQuery trait hierarchy.

2022-07-06 18:20 UTC, closed without merging