add `Commands::send_event` fn
bevyengine/bevy pull request #4840
Opened 2022-05-25 19:27 UTC by JoJoJet

# Objective

Make it possible to send events of any kind, by using commands to perform type erasure.

## Solution

Use commands to perform type erasure on to-be-sent events.

## Notes

This is currently already possible, using something like this:

```rust
let event = todo!();
commands.add(move |w: &mut World| {
    w.resource_mut::<Events<_>>().send(event);
});
```

However, this is very cumbersome, and it's quite unclear that it's even possible to do this. It almost feels like getting away with something you shouldn't be allowed to do.

Adding this API not only makes it easier to send events of any type, it makes it abundantly clear to users that doing so is even *possible*.

2022-05-25 19:42 UTC, DJMcNab reviewed
Implementation is fine. I'm not sure I want us to encourage this though.

If users want to do this themselves, they should. I guess you could add this as an example to the docs of `impl Command for F where F: FnMut(&mut World)` - that way we can still show people it's possible, but make it clear that it's not idiomatic.

2022-05-30 17:13 UTC, alice-i-cecile requested changes
I agree with @DJMcNab above; can you adapt this PR to show the untyped event pattern as a doc example on either `Events` or `EventWriter`?

2022-07-10 12:34 UTC, MinerSebas requested changes
Please update the PR Title and Description to reflect that this is now a doc change.

2022-07-10 16:31 UTC, alice-i-cecile commented on crates/bevy_ecs/src/event.rs
> +/// # Limitations
```suggestion
/// # Limitations
///
```

2022-07-10 16:31 UTC, alice-i-cecile approved these changes
Changes LGTM now :)

2022-07-10 20:20 UTC, IceSentry approved these changes

2022-07-10 20:20 UTC, IceSentry commented on crates/bevy_ecs/src/event.rs
> +/// Sends events of type `T` to [`EventReader`]s of type `T`.
I know this makes sense from a high level perspective, but technically the events are sent to `Events<T>` and `EventReader` is just a nicer abstraction around that.

Personally I would simply not mention it at all

```suggestion
/// Sends events of type `T`.
```

2022-07-10 20:21 UTC, alice-i-cecile commented
@JoJoJet I'm ready to merge this, but the PR title should really be updated to ensure that our commit history makes sense.

2022-07-10 21:50 UTC, JoJoJet commented
I believe that addresses everything.

2022-07-11 13:57 UTC, alice-i-cecile reviewed
bors r+

2022-07-13 14:40 UTC, alice-i-cecile commented
bors retry

2022-07-13 14:57 UTC, closed without merging