#4123: example state allow for continue and restart
bevyengine/bevy pull request #4894
Opened 2022-06-01 21:53 UTC by Vrixyz

# Objective

Fixes #4123.

## Solution

- menu state is now more dynamic, with 2 scenario:
  - first load: displaying **Play**, and setting up camera 🤷 
  - subsesquent loads: **Restart** and **Continue**
- It might be cleaner to use more states (Loading and/or first menu VS PauseMenu) ?

States are now:
- (first)Menu
- Game
- Game -> (**pushed** subsequent) Menu
  - `Restart` leads to a replace of the whole State stack to Game (calling `on_exit` and `on_enter`)
  - `Continue`simply pops the last menu state.

We could make this example better by avoiding the blue changing color to quickly change (use delta_time rather than time), to add to the feeling of real "pause" and start from previous state.

2022-06-01 21:57 UTC, alice-i-cecile commented on examples/ecs/state.rs
> +fn create_button(commands: &mut Commands, asset_server: &AssetServer, title: &str) -> Entity {
I like this; users often struggle to figure out how to write simple abstractions like this for manipulating entities.

2022-06-01 21:59 UTC, Vrixyz commented on examples/ecs/state.rs
> +    let is_first_load = !state.inactives().contains(&AppState::InGame);
I hesitated to modify Menu state into Menu(bool) or inner clearer enum to carry this information.

2022-06-01 22:00 UTC, alice-i-cecile commented on examples/ecs/state.rs
> +fn cleanup_game(mut commands: Commands, query_to_remove: Query<Entity, With<RemoveWhenGameDone>>) {
```suggestion

fn cleanup_game(mut commands: Commands, query_to_remove: Query<Entity, With<RemoveWhenGameDone>>) {
```

2022-06-01 22:00 UTC, alice-i-cecile commented on examples/ecs/state.rs
> +fn back_to_menu(time: Res<Time>, mut state: ResMut<State<AppState>>, input: Res<Input<KeyCode>>) {
```suggestion

fn back_to_menu(time: Res<Time>, mut state: ResMut<State<AppState>>, input: Res<Input<KeyCode>>) {
```

2022-06-01 22:01 UTC, alice-i-cecile requested changes
I like this! I think that once we've removed the state stack stuff this will make a nice improvement.

2022-06-02 14:01 UTC, alice-i-cecile commented on examples/ecs/state.rs
> +    let is_first_load = !state.inactives().contains(&AppState::InGame);
I was actually just thinking a resource that we flip that encodes *why* we care about this information.

2022-06-02 19:57 UTC, alice-i-cecile approved these changes
This LGTM; is this ready to come out of draft mode?

2024-09-24 09:24 UTC, Vrixyz commented
I'm closing this as it's way outdated now

2024-09-24 09:24 UTC, closed without merging