Remove redundant table and sparse set component IDs from Archetype
bevyengine/bevy pull request #4927
Opened 2022-06-04 21:05 UTC by james7132

# Objective
Archetype is a deceptively large type in memory. It stores metadata about which components are in which storage in multiple locations, which is only used when creating new Archetypes while moving entities.

## Solution
Remove the redundant `Box<[ComponentId]>`s and iterate over the sparse set of component metadata instead. Reduces Archetype's size by 4 usizes (32 bytes on 64-bit systems).

It'd seem like there's a downside that the origin archetype has it's component metadata iterated over twice when creating a new archetype, but this change also removes the extra `Vec<ComponentId>` allocations when creating a new archetype. This change likely negatively impacts creating new archetypes with a large number of components, but that's a cost mitigated by the fact that these archetypal relationships are cached in Edges and is incurred only once for each edge created.

## Additional Context
There are several other in-flight PRs that shrink Archetype:

 - #4800 removes merges the entities and rows Vecs together (shaves off 24 bytes per archetype) 
 - #4809 removes unique_components and moves it to it's own dedicated storage (shaves off 72 bytes per archetype)

---

## Changelog
Changed: `Archetype::table_components` and `Archetype::sparse_set_components` return iterators instead of slices. `Archetype::new` requires iterators instead of parallel slices/vecs.

## Migration Guide
Do I still need to do this? I really hope people were not relying on the public facing APIs changed here.

2022-06-04 21:11 UTC, alice-i-cecile commented
I'm fine without a migration guide here. Anyone attempting to rely on this is experienced enough to piece it together.

2022-06-04 21:12 UTC, alice-i-cecile commented on crates/bevy_ecs/src/archetype.rs
> +        let (min_sparse, _) = table_components.size_hint();
```suggestion
        let (min_sparse, _) = sparse_set_components.size_hint();
```

2022-06-04 21:14 UTC, alice-i-cecile requested changes
There's a critical little typo in your code. Once that's fixed this LGTM.

2022-06-04 22:41 UTC, alice-i-cecile approved these changes

2022-11-01 03:55 UTC, Diddykonga approved these changes
Besides for the suggested change from @alice-i-cecile LGTM
A good simplification for sure :)

2022-11-15 21:27 UTC, cart commented on crates/bevy_ecs/src/archetype.rs
>              .entry(archetype_identity)
Not something that needs to be done here, but I think we can completely eliminate the redundant clones / allocations here related to ArchetypeIdentity:

1. Use Hashbrown's raw_entry API to remove the need for an "owning" ArchetypeIdentity when the archetype already exists
2. When the archetype does not exist, create the Archetype first using a non-owning iterator over sparse_set_components and table_components, then use the same allocated lists to construct the final owning ArchetypeIdentity.

2022-11-15 21:35 UTC, cart commented
bors r+

2022-11-15 21:39 UTC, cart commented
bors retry

2022-11-15 21:55 UTC, closed without merging