Implement methods to list all components and all resources (Rebase of PR #3012)
bevyengine/bevy pull request #4955
Opened 2022-06-07 04:14 UTC by KevinKeyser

# Objective

- Take over and Rebase Pull Request https://github.com/bevyengine/bevy/pull/3012
    - Fixes https://github.com/bevyengine/bevy/issues/3007
    - Simplify debugging by allowing iteration over all Components and Resources registered in a World.

## Solution

- [x] Rename Components into WorldData to reflect that it stores metadata both on Components and Resources. Also rename ComponentId to DataId, ComponentInfo to DataInfo and ComponentDescriptor to DataDescriptor
- [x] implement IntoIterator for WorldData to iterate over all components and resources
- [x] create a new Components system descriptor and implement IntoIterator to iterate over all components
- [x] create a new Resources system descriptor and implement IntoIterator to iterate over all resources

---

## Changelog

- `struct ComponentId` -> `struct DataId`
- `struct Components` -> `struct WorldData`
   - `Components::components` -> `WorldData::data`
- `struct ComponentInfo` -> `struct DataInfo`
- `struct ComponentDescriptor` -> `struct DataDescriptor`

2022-06-07 04:19 UTC, alice-i-cecile commented
My instinct is that we should merge #4809 first, which should simplify the implementation here significantly. @james7132, are you in agreement?

2022-10-08 16:16 UTC, targrub commented
@KevinKeyser Is this a dead PR at this point?

2022-10-10 18:27 UTC, alice-i-cecile requested changes
I like the `ComponentId` -> `DataId` change: I think it's genuinely correct and clearer. However it makes this PR much harder to review, and should be its own PR.

2023-01-08 21:26 UTC, alice-i-cecile commented on crates/bevy_ecs/src/system/mod.rs
> +        world.insert_resource(42usize);
These will have to be redone to account for the opt-in `Resource` trait.

2023-01-08 21:27 UTC, alice-i-cecile commented on crates/bevy_ecs/src/system/mod.rs
> +    fn remove_tracking() {
```suggestion
    fn removal_tracking() {
```

Just to reduce diff noise.

2023-01-08 21:28 UTC, alice-i-cecile approved these changes
This is quite nice: I really like how much clearer `DataId` and `WorldData` are. If you rebase this and get CI passing I'd be happy to see this merged basically as is.

2023-09-11 15:58 UTC, alice-i-cecile commented
@KevinKeyser I still really like this work, but at this point it's going to be easier to remake this PR than to solve merge conflicts. I'm going to `Adopt-Me` to this PR, but feel free to adopt it yourself if you'd like!

2024-02-06 20:39 UTC, Adamkob12 commented
I'd like to pick this up soon.

2024-03-30 22:38 UTC, AustinHellerRepo commented on crates/bevy_ecs/src/system/system_param.rs
> +unsafe impl<'a> SystemParamState for ComponentsState {
Probably trivial, but is this explicit lifetime required?

2024-03-30 22:43 UTC, AustinHellerRepo commented on crates/bevy_ecs/src/world/mod.rs
> +            component_id
Should this be `resource_id`?

2024-03-30 22:54 UTC, AustinHellerRepo commented
I'm hoping that this PR will help permit me to more easily serialize specific components (when I only have the name) of an entity as well as overwrite the state of a component by deserializing a previous state's `String` into the component.
If this is now possible with these changes, would it be possible to get a unit test or example included in this PR?
If that is out of scope for these changes, any help with this task would be greatly appreciated. Thank you.

2024-03-31 12:46 UTC, alice-i-cecile commented
@matiqo15, this seems really useful for https://github.com/bevyengine/rfcs/pull/77. Perhaps we should re-adopt it and get the basic form merged?

2024-03-31 13:44 UTC, matiqo15 commented
> @matiqo15, this seems really useful for https://github.com/bevyengine/rfcs/pull/77. Perhaps we should re-adopt it and get the basic form merged?

Agree, this could help a lot

2024-09-20 09:24 UTC, VitalyAnkh commented
@alice-i-cecile Now that #12829  has been merged, is this PR still necessary?

2024-09-20 14:57 UTC, closed without merging

2024-09-20 14:57 UTC, alice-i-cecile commented
It would still be nice to have something like this for components, but I'm going to close this out regardless.