Add error when extract resource build fails
bevyengine/bevy pull request #4964
Opened 2022-06-07 22:14 UTC by aevyrie

# Objective

- Provide feedback when an extraction plugin fails to add its system.

I had some troubleshooting pain when this happened to me, as the panic only tells you a resource is missing. This PR adds an error when the ExtractResource plugin is added before the render world exists, instead of silently failing.

![image](https://user-images.githubusercontent.com/2632925/172491993-673d9351-215a-4f30-96f7-af239c44686a.png)

2022-06-07 22:52 UTC, alice-i-cecile commented
Another one for #1255...

2022-06-07 22:52 UTC, alice-i-cecile approved these changes

2022-06-08 01:56 UTC, superdump requested changes
I feel like a .expect() is appropriate here. It should be a fatal error imo as the code is wrong. Also, why did the render app not exist yet? This is a plugin. Did you add it before DefaultPlugins or something? @alice-i-cecile @cart  what do you think? Fatal or not?

2022-06-08 03:06 UTC, alice-i-cecile commented
Definitely fatal; I don't think there's any way to recover from this.

The fix is always just "order your plugins better", as much as I hate that.

2022-06-08 04:11 UTC, aevyrie commented
Good point. `expect` is more appropriate.

2022-06-11 02:55 UTC, cart commented
Iirc we adopted the `if let Ok(render_app)` pattern to ensure we dont panic when "headless" mode is enabled. We should make sure that switching to expect doesn't break headless.

2024-04-28 02:28 UTC, pcwalton approved these changes
LGTM

2024-04-28 05:20 UTC, superdump approved these changes

2024-04-28 05:34 UTC, merged