Implement Reflect for TypeId
bevyengine/bevy pull request #4976
Opened 2022-06-09 16:23 UTC by PROMETHIA-27

# Objective

Allows reflection and serialization of TypeIds. This is helpful for serializing and deserializing certain types that use TypeIds and are otherwise reflectable/serializable. 

## Solution

- Implement TypeIds as reflect values with Hash and PartialEq
- Hardcode TypeId serialization as an alternative to Value serialization, since TypeIds need access to the TypeRegistry to be serialized/deserialized and otherwise cannot access it. TypeIds are de/serialized as their corresponding type's name.

## Issues:

- Hardcoding a new serialization method for one type is gross, especially when it's entirely possible other types might end up also needing a TypeRegistry for serialization.
- Serialization format can be simplified to `TypeId("{type name here}")` once [4561](https://github.com/bevyengine/bevy/pull/4561) hits

## Alternative solutions:

- Don't implement reflect for TypeIds
   - Would entirely prevent behavior which is probably logically sound and useful
- Implement reflect without serialization
   - It should be sound to allow TypeIds to be serialized to a type name and back, so this doesn't seem like a good approach
- Allow any serialized types to access the TypeRegistry during de/serialization
   - Add it to thread local storage?
   - Pass it as a parameter?

2022-06-09 16:40 UTC, PROMETHIA-27 commented on crates/bevy_reflect/src/serde/ser.rs
> +pub struct TypeIdSerializer<'a> {
Yes, I wouldn't serialize TypeIds directly. I'm also aware type names are unstable, but if that instability manifests then all of bevy's reflection serialization has problems. I believe #4561 mentioned above will mitigate this somewhat but it'll still be an issue. Hopefully rust gets stable type names at some point?

2022-06-09 16:52 UTC, MrGVSV approved these changes
Looks good to me!

2022-06-09 16:55 UTC, MrGVSV commented
> Allow any serialized types to access the TypeRegistry during de/serialization
> * Add it to thread local storage?
> * Pass it as a parameter?

Reflecting on this more, I think you're right. It's probably best to allow the serialization method to access the registry (even if #4782 lands) as this gives the best control and flexibility for types going forward.

We could probably add that functionality to #4782 itself or create a new PR for it (I don't think it should be included as part of this one).

2022-06-09 17:02 UTC, PROMETHIA-27 commented
Agreed, that's a big change beyond the scope of this PR. I think it probably belongs in a new PR. I'm also not certain on how it should be done.

2022-06-09 17:14 UTC, MrGVSV commented
> I'm also not certain on how it should be done.

I’m in favor of the parameter method. The TLS solution will probably be a lot more controversial and a bigger change. 

So just adding it as a parameter is probably simplest and most likely to be approved for now

2022-06-09 17:52 UTC, PROMETHIA-27 commented
I'll investigate that and open a PR if I can get it working

2022-10-10 18:39 UTC, alice-i-cecile requested changes
@PROMETHIA-27, once this is rebased and the serialization fixed (remember to fix the PR description) I'm happy to merge this.

Other code LGTM.

2022-10-11 02:18 UTC, closed without merging

2022-10-11 02:30 UTC, PROMETHIA-27 commented
Making a new PR for this soon:tm: