Add `Input::reset_all`
bevyengine/bevy pull request #5015
Opened 2022-06-14 21:01 UTC by Hoidigan

Adds a `reset_all` method to reset `pressed`, `just_pressed`, and `just_released` on the `Input`.

Fixes #3383

2022-06-15 04:06 UTC, alice-i-cecile commented
Note for reviewers: this was previously attempted in #4410. That PR caused a serious regression because it modified the behavior of a method used internally in critical ways.

2022-06-15 04:10 UTC, alice-i-cecile requested changes
I'd like a link to and from clear / reset_all in each of those methods docs. `clear` is more useful for simulating elapsed time steps, but `reset_all` is a proper reset.

(I wouldn't mind renaming `clear` to `tick`, but that can be a different PR)

2022-06-15 16:52 UTC, Hoidigan commented
Each of those methods docs being which ones, sorry?

2022-06-15 19:21 UTC, alice-i-cecile commented
> Each of those methods docs being which ones?

Link to `Input::clear` from `Input::reset_all` and vice versa :) Sorry for the confusion.

2022-06-16 10:12 UTC, Sheepyhead approved these changes

2022-06-20 01:28 UTC, alice-i-cecile approved these changes

2022-06-20 01:29 UTC, alice-i-cecile commented
Once this is formatted I'm happy to merge this!

2022-06-20 11:12 UTC, LoipesMas commented
> (I wouldn't mind renaming clear to tick, but that can be a different PR)

I agree that the names are confusing (`clear` and `reset_all` sound like they would do the same thing) and `clear` should probably the one to get renamed, but it's probably best left for a separate PR.

2022-06-20 17:18 UTC, alice-i-cecile commented
bors r+

2022-06-20 18:49 UTC, closed without merging