Default image sampler doc fix
bevyengine/bevy pull request #5047
Opened 2022-06-18 17:25 UTC by sarkahn

# Objective

Attempt to more clearly document `ImageSettings` and setting a default sampler for new images, as per #5046

## Changelog

- Moved ImageSettings into image.rs, image::* is already exported. Makes it simpler for linking docs. 
- Renamed "DefaultImageSampler" to "RenderDefaultImageSampler". Not a great name, but more consistent with other render resources.
- Added/updated related docs

2022-06-20 19:09 UTC, alice-i-cecile requested changes
This is clearer, and I like the reorganization. Can you revert the rename? I don't think the improvement is worth the breaking change.

2022-06-20 19:09 UTC, alice-i-cecile commented on crates/bevy_render/src/texture/image.rs
> +pub struct RenderDefaultImageSampler(pub(crate) Sampler);
Not convinced on this rename; it makes this a breaking change and I don't think it's appreciably clearer.

2022-06-20 20:17 UTC, alice-i-cecile approved these changes

2022-06-20 20:31 UTC, mockersf commented on crates/bevy_render/src/texture/image.rs
> +    /// Creates image settings with default linear sampling.
```suggestion
    /// Creates image settings with linear sampling by default.
```

2022-06-20 20:32 UTC, mockersf commented on crates/bevy_render/src/texture/image.rs
> +    /// Creates image settings with default nearest sampling.
```suggestion
    /// Creates image settings with nearest sampling by default.
```

2022-06-26 00:04 UTC, superdump approved these changes
LGTM.

2022-06-26 02:26 UTC, alice-i-cecile commented
bors r+

2022-06-26 02:37 UTC, closed without merging