Add `bevy_core::Name` doc examples
bevyengine/bevy pull request #5093
Opened 2022-06-24 22:25 UTC by TimJentzsch

# Objective

- Make it clear how `Name` and its functions are used.
- Add unit tests to make sure that everything works as expected.

## Solution

- Add examples to `Name`s docs, which serve both as documentation and as tests.

2022-06-24 22:32 UTC, TimJentzsch commented
# Preview

- `Name`:
    ![Name docs](https://user-images.githubusercontent.com/13908946/175714028-65d5dc40-4613-45f1-a26a-8cde9b48095e.png)

- `Name::new()`:
    ![Name::new() docs](https://user-images.githubusercontent.com/13908946/175714849-04e746c8-0211-4449-a8eb-14c4f35ffb7e.png)

- `Name::set()`:
    ![Name::set() docs](https://user-images.githubusercontent.com/13908946/175715565-9d00d454-9987-4bbf-b0fd-226d1635c102.png)

- `Name::mutate()`:
    ![Name::mutate() docs](https://user-images.githubusercontent.com/13908946/175716534-d6275b67-f5ba-4e75-b52a-4338e06931d3.png)

- `Name::as_str()`:
    ![Name::as_str() docs](https://user-images.githubusercontent.com/13908946/175717189-0f452fba-5913-4051-a031-4d85021fb31d.png)

2022-06-24 23:16 UTC, mockersf commented
I would rather the docs don't show the usage of `as_str()` for a comparison with another string, one of the main point of `Name` is to have a faster `PartialEq` implementation that is using its hash

2022-06-25 00:27 UTC, alice-i-cecile commented on crates/bevy_core/src/name.rs
> +/// Component used to identify an entity. Stores a hash for faster comparisons.
Line break after the first line of docs please :)

2022-06-25 00:29 UTC, alice-i-cecile requested changes
Two larger requests:

1. Discuss how `Name` is used with scenes, and the gltf file format.
2. Demonstrate how to look up an entity by its name instead of showing `query_system`. For now, this is just a linear time search, but it's useful to show this still (to demonstrate that nothing better exists).

2022-06-25 09:11 UTC, TimJentzsch commented
@alice-i-cecile 

> Discuss how Name is used with scenes, and the gltf file format.

Do you have any resources for me to look up here? I'm not really familiar with Bevy's scenes or the gltf format yet.

> Demonstrate how to look up an entity by its name instead of showing query_system. For now, this is just a linear time search, but it's useful to show this still (to demonstrate that nothing better exists).

I changed it to something similar as @mockersf suggested, please let me know if that works :)

2022-06-25 11:30 UTC, alice-i-cecile commented
> Do you have any resources for me to look up here? I'm not really familiar with Bevy's scenes or the gltf format yet.

Ha, if we had good docs I wouldn't be asking you to write them! However, [here's](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#indices-and-names) a writeup of how they're used in `gltF`. When `gltF` files are loaded into Bevy as a scene, each gltF entity becomes one Bevy entity, and that property is translated into the `Name` component for the corresponding entity. You can see this in the `load_gltf` and associated `load_node` functions.

These are also apparently used in the `EntityPath` struct for animation, which is probably worth calling out as part of the section on gltF.

> I changed it to something similar as `@mockersf` suggested, please let me know if that works :)

I'm happy with those changes.

2022-06-25 11:44 UTC, mockersf commented
Inside Bevy, names are very used for animations. You can see it in https://github.com/bevyengine/bevy/blob/main/examples/animation/animated_transform.rs where an animation is built in code. For glTF, every node is given a name, either the one from glTF file or a generated one so that it can be targeted by an animation.

2022-08-31 10:45 UTC, TimJentzsch commented
I still don't really know how scenes/gltf work and currently don't have enough time to study them in detail.

I would propose to either factor that part out in a new issue or to put an Adopt Me tag on this PR :)

2023-04-08 11:11 UTC, closed without merging