Migrated to f32::total_cmp() function.
bevyengine/bevy pull request #5208
Opened 2022-07-05 07:52 UTC by nhunds

# Objective

Fixes #5152

## Solution

Use total_cmp() function from f32 in cmp() function on FloatOrd

2022-07-05 11:31 UTC, alice-i-cecile commented
Code change looks good to me. @DJMcNab, advice on the hash concern you raised?

2022-07-05 11:34 UTC, mockersf commented
This should be benchmarked too 👍

2022-07-05 11:34 UTC, DJMcNab commented
I don't think the hash concern is relevant here, since the only thing that matters is hash in relation to PartialEq

However, I think the clippy lint we ignore is making a good point - we should also implement PartialOrd in terms of this Ord impl.

2022-07-05 11:35 UTC, DJMcNab commented
Saying that, I'm not convinced PartialEq doesn't have requirements related to the PartialOrd implementation

Basically, we need to check the documentation for all four traits, which I can't right at this moment.

2022-07-06 20:10 UTC, james7132 reviewed
Going to second the `PartialOrd` implementation. The `Ord` documentation explicitly states the two must be in sync.

2022-07-10 16:43 UTC, DJMcNab requested changes
I wish we could remove the `Hash` implementation entirely.

At the moment, we either:
- need a test which loops through all f32 values, and checks that the implementations agree. I expect that they won't, unfortunately.
- convert the only usage of this impl (in `FontAtlasSet`) to use `BTreeMap`. I suspect for this workload, that would even be faster. This is the path I'd recommend taking

2022-07-10 16:43 UTC, DJMcNab commented on crates/bevy_utils/src/float_ord.rs
> +        self.0 == other.0
```suggestion
        self.cmp(other) == Ordering::Equal
```
This ensures that our `PartialEq` and `PartialOrd` implementations match

2022-07-13 09:31 UTC, superdump commented
>     * convert the only usage of this impl (in `FontAtlasSet`) to use `BTreeMap`. I suspect for this workload, that would even be faster. This is the path I'd recommend taking

Why would `BTreeMap` be faster? It would still be a binary search versus a hash and direct lookup, right?

2022-07-13 12:20 UTC, DJMcNab commented
Based on the using `with_capacity(1)`, I assume that the majority of the cases have very few items.

Additionally, the keys are small, so a binary search should be very fast.

2024-01-23 03:15 UTC, rodolphito commented
The same approach taken in #10558 should be used here

2024-08-22 02:23 UTC, NthTensor commented
I'm going to close this out. Looks like this is wanted, but work has stalled out and the approach needs to be changed. Feel free to re-open.

2024-08-22 02:23 UTC, closed without merging