Add stress test for many ui elements
bevyengine/bevy pull request #5253
Opened 2022-07-08 18:18 UTC by nicopap

# Objective

Bevy need a way to benchmark UI rendering code,
this PR adds a stress test that spawns a lot of buttons.

## Solution

- Add the `many_buttons` stress test.

---

## Changelog

- Add the `many_buttons` stress test.

2022-07-08 20:12 UTC, mockersf commented
This is not testing much of the UI, just spawning buttons:
* Should it add more hierarchies? This impact layout a lot
* Should layout change each frame? Without that it's pretty much static once spawned
* Should the mouse position change automatically during the test? Otherwise the interaction part is not stress test, unless the user randomly moves the mouse, which is not really reproducible twice in the same way

2022-07-09 05:26 UTC, nicopap commented
@mockersf

I want to keep this test focused. The original version of this test in [ui-navigation] did indeed only exist to test the focus system (well, my own). However, the ui rendering code is just too slow for even the slowest and most naive mouse picking algorithm to contribute in any meaningful way to the global run time of the app. You are indeed right. There is no hierarchy or change to layout, yet the test is still _staggeringly slow_ I get 2FPS in release mode. Given the layout is static, this should be smooth as butter. Why is it so slow? Well, now we have a test to help us answer that question!

Here are the most prominent tracing spans in tracy:
- `system{name="bevy_ui::flex::flex_node_system"}`
- `system{name="bevy_ui::render::prepare_uinodes"}`
- `node{name="bevy_ui::render::render_pass::UiPassNode"}`

This stress test was already helpful, it helped me test if #5252 made the base case slower.

[ui-navigation]: https://github.com/nicopap/ui-navigation/blob/30c828a465f9d4c440d0ce6e97051a5f7fafa425/examples/too_many_focusables.rs

2022-07-09 18:07 UTC, mockersf commented
Ha I didn't expect just buttons to be that slow...
But then, it's displaying 62500 buttons. for reference, many_sprites is around 10000, many_cubes around 11000

for reference:
|example|fps on my laptop|
|--|--|
|many_buttons|5|
|many_buttons (just 10000 buttons)|41|
|many_cubes|90|
|many_sprites|73|

So even for similar number of elements, UI is slower

2022-07-09 18:30 UTC, mockersf requested changes
Could you add the `FrameTimeDiagnosticsPlugin` and `LogDiagnosticsPlugin` plugins like in other stress tests?
In this example I don't think it's needed to display the ui element count as there isn't culling

2022-07-09 18:33 UTC, mockersf commented
Most of the improvements that were made to the sprite systems were not made for the ui, so it should be "easy" to improve. This example will help for that.

After that, we could add complexity to test other things

2022-07-11 13:50 UTC, alice-i-cecile approved these changes
I'm on board. We should add a deeply nested layout stress test later, but that can wait.

2022-07-21 12:44 UTC, mockersf approved these changes

2022-07-21 14:38 UTC, alice-i-cecile commented
bors r+

2022-07-21 14:57 UTC, closed without merging