Add associated constant `IDENTITY` to `Transform` and friends.
bevyengine/bevy pull request #5340
Opened 2022-07-16 16:14 UTC by devil-ira

# Objective
Since `identity` is a const fn that takes no arguments it seems logical to make it an associated constant.
This is also more in line with types from glam (eg. `Quat::IDENTITY`).

## Migration Guide

The method `identity()` on `Transform`, `GlobalTransform` and `TransformBundle` has been deprecated.
Use the associated constant `IDENTITY` instead.

2022-07-16 16:45 UTC, alice-i-cecile approved these changes
Nice use of deprecation :)

2022-08-01 17:56 UTC, mockersf commented
while marking as deprecated is nice, at this stage of Bevy I would prefer to break directly

2022-08-28 07:42 UTC, Weibye requested changes
Looks good, no need for the deprecation.

2022-08-28 07:42 UTC, Weibye commented on crates/bevy_transform/src/components/transform.rs
> +        Transform::IDENTITY
This can just be removed. Let's break things and move fast, and have less stuff to maintain.

2022-08-28 07:42 UTC, Weibye commented on crates/bevy_transform/src/lib.rs
> +        TransformBundle::IDENTITY
Same here

2022-08-28 11:45 UTC, Weibye approved these changes
Looks good!

2022-08-28 13:39 UTC, mockersf approved these changes

2022-08-30 21:58 UTC, mockersf commented
bors r+

2022-08-30 22:28 UTC, closed without merging