Document `gamepad.rs`
bevyengine/bevy pull request #5548
Opened 2022-08-02 03:23 UTC by KDecay

# Objective

- Fixes #5544

## Solution

- Document everything in the `gamepad.rs` file.
- Add a doc example for mocking gamepad input.

---

## Changelog

- Added and updated the documentation inside of the `gamepad.rs` file.

2022-08-02 13:47 UTC, alice-i-cecile commented on crates/bevy_input/src/gamepad.rs
> +/// ## Usage
This section should link to `Gamepads`, as the primary way to figure out which gamepads to access.

2022-08-02 13:47 UTC, alice-i-cecile commented on crates/bevy_input/src/gamepad.rs
> +    /// # Examples
I don't think this doc test adds value for the reader :)

2022-08-02 13:48 UTC, alice-i-cecile commented on crates/bevy_input/src/gamepad.rs
> +/// A type of a [`GamepadEvent`].
```suggestion
/// The data contained in a [`GamepadEvent`] or [`GamepadEventRaw`].
```

2022-08-02 13:49 UTC, alice-i-cecile commented on crates/bevy_input/src/gamepad.rs
> +/// because otherwise the [`GamepadSettings`] wouldn't be respected and the [`Input<GamepadButton>`],
```suggestion
/// because otherwise the [`GamepadSettings`] won't be respected and the [`Input<GamepadButton>`],
```

2022-08-02 13:49 UTC, alice-i-cecile commented on crates/bevy_input/src/gamepad.rs
> +/// When mocking gamepad input you have to use [`GamepadEventRaw`]s instead of [`GamepadEvent`]s
```suggestion
/// When mocking gamepad input you have to use [`GamepadEventRaw`]s instead of [`GamepadEvent`]s.
```

2022-08-02 13:50 UTC, alice-i-cecile commented on crates/bevy_input/src/gamepad.rs
> +    /// # Examples
I don't think this doc test adds value; the one above is much more useful.

2022-08-02 13:51 UTC, alice-i-cecile commented on crates/bevy_input/src/gamepad.rs
> +/// A raw event of a [`Gamepad`].
We should have an example of input mocking here.

2022-08-02 13:51 UTC, alice-i-cecile commented on crates/bevy_input/src/gamepad.rs
> +/// This is used to determine which button has changed its value when receiving a
This is also stored in `Input<GamepadButton>`.

2022-08-02 13:52 UTC, alice-i-cecile commented on crates/bevy_input/src/gamepad.rs
> +/// This is used to determine which axis has changed its value when receiving a
This should mention `Axis`, which is the primary API for this.

2022-08-02 13:54 UTC, alice-i-cecile requested changes
Some modest feedback. This is a solid improvement over the current absence of docs already.

2022-08-03 13:37 UTC, KDecay commented
@alice-i-cecile Great points. Thank you! 

Regarding your request to add another example to the `GamepadEventRaw`:
I moved the example from the `GamepadEvent` to the `GamepadEventRaw` and linked to it in the docs of the `GamepadEvent`. Let me know if that's what you were after or if you wanted an additional example.

2022-08-03 13:44 UTC, alice-i-cecile approved these changes

2022-08-05 02:11 UTC, cart commented
bors r+

2022-08-05 02:39 UTC, closed without merging