bevy_pbr: Add DebugLinesPlugin and DebugNormalsPlugin
bevyengine/bevy pull request #5734
Opened 2022-08-18 23:19 UTC by superdump

# Objective

- Visualise vertex normals

## Solution

- Add `DebugLinesPlugin` which adds a `DebugLines` resource which can be used to draw arbitrary lines with customisable colour
- Add `DebugNormalsPlugin` which enables drawing lines to visualise vertex normals, leveraging `DebugLinesPlugin`

---

## Changelog

- Added `DebugLinesPlugin` which adds a `DebugLines` resource which can be used to draw arbitrary lines with customizable color
- Added `DebugNormalsPlugin` which enables drawing lines to visualize vertex normals, leveraging `DebugLinesPlugin`

2022-08-19 01:04 UTC, IceSentry commented
So, while I really want something like this and I even already had something locally. I never made a PR because it was covered by the not yet merged primitive shapes RFC. I'm also not sure if this needs to live in bevy_pbr, we really need some sort of debug module.

As for the api, I generally like the idea of building a line with a resource, but I would prefer if the color was passed as the argument of draw_line. It's also a bit inconsistent with most other bevy apis. I would have expected that it would just be spawning some sort of LineBundle, personally I still prefer this style of api though.

2022-08-20 01:13 UTC, Aceeri requested changes

2022-08-20 01:13 UTC, Aceeri commented on crates/bevy_pbr/src/debug_lines.rs
> +}
```suggestion
    let mesh_normals_to_draw = if debug_normal_settings.global {
        &debug_normals
    } else {
        &no_debug_normals
    };

    for (transform, mesh) in &mesh_normals_to_draw {
        if let Some(mesh) = meshes.get(mesh) {
            draw_mesh_normals(&transform.affine(), mesh, scale, debug_lines);
        }
    }
}
```

2022-08-20 01:13 UTC, Aceeri commented on crates/bevy_pbr/src/debug_lines.rs
> +    pub scale: f32,
```suggestion
    /// Draw mesh normals on every mesh.
    pub global: bool,
    /// Color to use for drawing normals.
    pub color: Color,
    /// How far out the line will extrude to display the normal.
    pub scale: f32,
```

2022-08-20 01:13 UTC, Aceeri commented on crates/bevy_pbr/src/debug_lines.rs
> +    pub scale: f32,
was mainly just confused about the `global` one until I read the code more.

2023-11-05 14:13 UTC, superdump commented
@devil-ira do we have support for visualising normals with the gizmos plugin? If not, should I update this PR to make use of our line drawing functionality to do it? :)

2023-11-05 14:41 UTC, devil-ira commented
No, but I do have some local code that does it more efficiently than this, buuut.. it's 5 months old and way more complicated.

If you want something to use now you could update this PR to be a part of bevy_gizmos and get it merged pretty quickly.

I'll clean up my code at-some-point:tm: and PR it after as a performance boost if need be.

2024-10-05 02:43 UTC, richchurcher commented
Backlog cleanup: lack of activity, also note cart's #6529 as a partial alternative.

2024-10-05 02:43 UTC, closed without merging