Add test plugin group
bevyengine/bevy pull request #5932
Opened 2022-09-09 21:20 UTC by anchpop

# Objective

Work towards closing #5931

## Solution

- Add a `TestPlugins` group that adds `MinimalPlugins`, `AssetPlugin`, `ScenePlugin`, `WindowPlugin`, `GilrsPlugin`, `TransformPlugin`, `HierarchyPlugin`, `DiagnosticsPlugin`, and `InputPlugin`.
- Added an example for how to use it. The example gets run in CI, which should make sure that no future change ever breaks any of the plugins in Github Actions

## Limitations

- `bevy_rapier` will not work as it depends on `RenderPlugin`, but this is fixed in #5933.
- While this is usable, `LogPlugin` cannot be added until #4934 is resolved

---

## Changelog

### Added

`TestPlugins` group that adds plugins suitable for use in automated tests.

2022-09-09 21:32 UTC, alice-i-cecile approved these changes
This is a good idea, and I agree with this selection.

2022-09-09 21:35 UTC, mockersf commented
I would rather have a feature that would enable only what is interesting in CI than a plugin group. The feature would help reducing compile time.

2022-09-09 23:59 UTC, alice-i-cecile requested changes
The example should live in the root level `tests` directory, which will avoid the shenanigans :) We should try and publicize that better though; perhaps we can add a note to the examples README?

2022-09-10 14:48 UTC, alice-i-cecile commented on tests/automated_tests.rs
> +fn main() {
The entire `main` function shouldn't be necessary here.

2022-09-10 14:49 UTC, alice-i-cecile commented
@mockersf I want your opinion on the organization here. I think it's *interesting* that we're linking to this from the examples README / including it in the cargo.toml. Unsure if it's the right choice!

2022-09-17 20:34 UTC, Shatur commented
When I test something on CI I add only plugins I need. So I wouldn't add a specific plugin group.

2022-09-18 15:35 UTC, alice-i-cecile commented
Closing out; I don't think this is a reliable enough solution to include at the engine level.

2022-09-18 15:35 UTC, closed without merging