[Merged by Bors] - update camera projection if viewport changed
bevyengine/bevy pull request #5945
Opened 2022-09-11 09:02 UTC by jakobhellermann

fixes https://github.com/bevyengine/bevy/issues/5944

Uses the second solution:
> 2. keep track of the old viewport in the computed_state, and if camera.viewport != camera.computed_state.old_viewport, then update the projection. This is more reliable, but needs to store two UVec2s more in the camera (probably not a big deal).

2022-09-11 09:14 UTC, devil-ira reviewed
The computation here only cares about the size of te viewport not the position. Then it's only one extra `Uvec2` :)

2022-09-11 09:14 UTC, devil-ira commented on crates/bevy_render/src/camera/camera.rs
>              || added_cameras.contains(&entity)
The extra query and paramset in this system are unnecessary.
You mind cleaning it up a bit? :)
```suggestion
            || camera.is_added()
```

2022-09-15 22:01 UTC, superdump requested changes

2022-09-15 22:01 UTC, superdump commented on crates/bevy_render/src/camera/camera.rs
> +                .map(|viewport| (viewport.physical_position, viewport.physical_size));
I guess this value could be calculated once and used for both the logic and this assignment?

2022-09-28 04:08 UTC, superdump commented on crates/bevy_render/src/camera/camera.rs
> +                .map(|viewport| (viewport.physical_position, viewport.physical_size));
Ping @jakobhellermann

2022-10-28 19:23 UTC, devil-ira approved these changes

2022-10-28 19:56 UTC, cart commented
bors r+

2022-10-28 20:16 UTC, closed without merging