Enable some features when generating documentation on docs.rs
bevyengine/bevy pull request #6001
Opened 2022-09-17 16:51 UTC by GuillaumeGomez

While looking at some examples, I realized that it needed some features to be enabled because I couldn't find the related docs I built locally. It doesn't solve this issue unfortunately but at least when people will look on docs.rs, they will be able to find these items.

2022-09-17 16:55 UTC, mockersf commented
Some of the features you added are already present in the default feature set:
https://github.com/bevyengine/bevy/blob/e96b21a24a7fe17a64e52b7bba81e00145ea1756/Cargo.toml#L27-L40

Doesn't docs.rs use those? Otherwise https://docs.rs/bevy/latest/bevy/animation/struct.AnimationClip.html shouldn't be present as it's behind the `animation` feature

2022-09-17 19:16 UTC, Nilirad commented
Hmm, maybe we should enable all features?

2022-09-17 21:20 UTC, GuillaumeGomez commented
I don't know which ones are for internal use (ie bevy development) and which ones are to be used by users. If you have a list of features that shouldn't appear in the docs, I will update the PR.

> Some of the features you added are already present in the default feature set:

Indeed, using `default` would be better in this case.

> Doesn't docs.rs use those? Otherwise https://docs.rs/bevy/latest/bevy/animation/struct.AnimationClip.html shouldn't be present as it's behind the `animation` feature

The `animation` feature is enabled by default, hence why it's documented there.

2022-11-09 22:41 UTC, GuillaumeGomez commented
I cleaned up the list of features by using `default` directly.

> Hmm, maybe we should enable all features?

Why not. Just to be sure: do all features provide code too which would appear in the documentation? But if this is the best solution, there is an even simpler way for docs.rs to do that. :)

2023-01-11 16:28 UTC, alice-i-cecile requested changes
I would rather enable all features or stick to default features: we don't have any development only flags and I'd really like to avoid keeping two lists.

2023-01-11 16:29 UTC, GuillaumeGomez commented
Makes things simpler for me. :)

2023-01-11 16:32 UTC, GuillaumeGomez commented
I updated it so that all features are enabled when building on docs.rs. Btw, you can find more information about it here: https://docs.rs/about/metadata

2023-01-11 16:53 UTC, mockersf commented
I still don't understand the point of this?

Bevy pretty much doesn't have any public items that are behind features not already enabled by default. What does it change for docs.rs which already uses the default set of features?

2023-01-11 17:01 UTC, GuillaumeGomez commented
I honestly don't remember what I was missing in the documentation that forced me to render them locally. Should have precised it in my first comment, my bad. Looking at default features list, `serialize` isn't listed. Is it something end users can use?

2023-01-11 17:44 UTC, alice-i-cecile commented
Yes, it is. I've been bitten before by the lack of `Serialize` in the docs (and the fact that it's not a default feature).

2023-01-11 18:02 UTC, GuillaumeGomez commented
Then I guess it answers @mockersf's concern. :)

2023-01-11 18:14 UTC, mockersf commented
Then is it really a good idea to have things on docs.rs that users won't find when they try to use them? I think docs.rs can't yet automatically mark those things as "hey it's behind a feature that you need to enable"

> We shouldn't change it to be one, just remarking on its use to end users.

Why? If it's useful it should be in the default feature set I think.

2023-01-11 18:21 UTC, GuillaumeGomez commented
It's easier to find that a feature is needed rather than finding that a feature exists if it's not in the documentation.

As a sidenote, we are currently writing an RFC for the "cfg_doc" feature, so wouldn't hurt to have it in any case.

2023-01-11 20:59 UTC, alice-i-cecile commented
> Why? If it's useful it should be in the default feature set I think.

Serde leads to a large increase in compile times :( Maybe it should be on by default, but it's not a straightforward decision.

2023-01-11 21:08 UTC, GuillaumeGomez commented
A big poll to get people's opinion on this could help maybe? Personally I'm very happy serde isn't enabled by default as I don't use it. Don't know how common it is though.

2023-01-11 21:09 UTC, mockersf commented
serde is still enabled in the default features. the serialise feature wasn't done in all sub crates, and bevy_gltf has a mandatory dependency anyway

2024-05-12 21:28 UTC, mockersf commented
done in https://github.com/bevyengine/bevy/pull/12366

2024-05-12 21:28 UTC, closed without merging