remove mandatory mesh attributes
bevyengine/bevy pull request #6127
Opened 2022-09-29 18:37 UTC by IceSentry

# Objective

- It's possible to create a mesh without positions or normals, but currently bevy forces these attributes to be present on any mesh.

## Solution

- Don't assume these attributes are present and add a shader defs for each attributes
- I updated 2d and 3d meshes to use the same logic.

---

## Changelog

- Meshes don't require any attributes

# Notes
I didn't update the pbr.wgsl shader because I'm not sure how to handle it. It doesn't really make sense to use it without positions or normals.

2022-09-29 20:30 UTC, devil-ira approved these changes
LGTM.
It would be nice to have warnings when a material is used with a mesh that is missing the required attributes.
Perhaps the `Material` trait could be extended to optionally specify these, in a future PR.

2022-09-29 20:37 UTC, IceSentry commented
> Perhaps the Material trait could be extended to optionally specify these, in a future PR.

Yeah, that could work, I like the idea

2022-10-04 13:10 UTC, alice-i-cecile requested changes
I like these changes a lot: users would regularly stumble on this. Can you add a test to verify that this continues to work?

Code looks good, so once we have automated testing I'm comfortable merging this (yay for slowly learning rendering).

2022-10-10 17:47 UTC, IceSentry commented
@alice-i-cecile I tried writing a test, but it requires pretty much an entire `App` with the entire render pipeline setup to be able to call `MeshPipeline::specialize()` and it seems a bit overkill here.

I think rendering in general would need a bit more testing infrastructure before we can easily test things like this.

2022-10-10 17:57 UTC, alice-i-cecile approved these changes

2022-10-10 17:57 UTC, alice-i-cecile commented
Alright, that makes sense.

bors r+

2022-10-10 18:14 UTC, closed without merging