Add warning about broken rotations to `Transform::look_at()` docs
bevyengine/bevy pull request #6136
Opened 2022-10-01 20:01 UTC by devil-ira

Add the following note to `Transform::look_at()` and `Transform::looking_at()`: "Produces a broken rotation if the resulting forward direction is parralel with `up`."

2022-10-17 15:57 UTC, alice-i-cecile requested changes
I don't think this is the right fix. IMO we should fix the underlying math instead; this is a nasty bug.

Nit: "parallel" is the spelling :)

2022-10-17 17:33 UTC, devil-ira commented
No math to fix I'm afraid. There' is just no way to create a rotation from two parallel vectors.
I rewrote the doc to make that clearer. Maybe this is a good spot for a debug assertion?

> Nit: "parallel" is the spelling :)

Gah! I've made this mistake way to many times the last few weeks. Heck, I wrote it that way again typing the above sentence, haha

2022-10-17 18:07 UTC, Carter0 reviewed
Is this because of the Gimbal Locking problem?

https://en.wikipedia.org/wiki/Gimbal_lock#:~:text=Gimbal%20lock%20is%20the%20loss,a%20degenerate%20two%2Ddimensional%20space.

2022-10-17 18:08 UTC, alice-i-cecile commented
Ugh, right. Can we return an `Option` or a `Result` then?

2022-10-17 18:47 UTC, devil-ira commented
> Is this because of the Gimbal Locking problem?

It's similar. We need two direction vectors and them being parallel effectively removes one, like the axes in gimbal lock being parallel effectively removes one axis.

> Ugh, right. Can we return an Option or a Result then?

If you don't mind I add 62 instances of `.unwrap()` to the examples, haha

2022-10-17 19:35 UTC, alice-i-cecile commented
Hmm, right lol. Can we make a fallible variant which returns a Result then, and then point to it in these docs?

2023-01-19 15:15 UTC, rodolphito commented
Could use [Vec3A::any_orthonormal_vector](https://docs.rs/glam/0.22.0/glam/f32/struct.Vec3A.html#method.any_orthonormal_vector) to generate an up direction if `up==forward`. Might be preferable to panicking, otherwise its totally possible for a game to crash just because you stand above an entity that looks at you for example. I'd rather a random up be picked than get a crash.

2023-03-15 11:22 UTC, MatrixDev commented
> No math to fix I'm afraid. There' is just no way to create a rotation from two parallel vectors.

Unity somehow can calculate rotation so the must be a solution. Here is an example:

```csharp
transform.position = new Vector3(0.0f, 20.0f, 0.0f);
transform.LookAt(Vector3.zero, Vector3.up);
```

And result:
```csharp
position = (0.00, 20.00, 0.00)
rotation = (0.70711, 0.00000, 0.00000, 0.70711)
```

2023-03-15 13:13 UTC, devil-ira commented
Unity returns a partially randomized rotation instead.
See #7817 for an alternative PR that does that.

2023-03-15 16:53 UTC, alice-i-cecile commented
I prefer #7817: reducing mysterious footguns is better than documenting them.

2023-03-15 17:04 UTC, closed without merging