Immediate Execution of `Commands` on a `&mut World`
bevyengine/bevy pull request #6186
Opened 2022-10-06 17:36 UTC by Zeenobit

# Objective

Fixed #6184 

## Solution

This PR adds an `Execute` trait which is implemented for `&mut World` and `&mut App`. It allows the user to do this:

```rust
let mut world = World::default();
let _ = world.execute(|_world, mut commands| {
    /* ... */
});
```

2022-10-06 22:44 UTC, mockersf commented
As you mention in your doc comment, this is a very inefficient way to execute a command when you have a world available.

If this is only to be used for test, I would rather it being not available outside of tests

2022-10-07 00:13 UTC, Zeenobit commented
> As you mention in your doc comment, this is a very inefficient way to execute a command when you have a world available.
> 
> If this is only to be used for test, I would rather it being not available outside of tests

I considered doing this initially. There is a couple of problems with this:

1. We can't just gate it behind `#[cfg(test)]`, as it would also be useful for examples. So ideally it should be locked a feature of its own, but that's just extra build complexity for questionable benefit.
2. I've found this to be useful for debug UI code, such as with egui, where I want to have a button which executes a bunch of commands when I have `&mut World` access. So it's also useful for general diagnostics at runtime.

For these reasons, I decided keeping it available but with a warning in the comments is probably the best option.

Also, `Execute` is not imported with preludes. So that's an extra layer of "protection".

2022-10-07 01:28 UTC, alice-i-cecile commented on crates/bevy_ecs/src/system/commands/mod.rs
> +    /// This is not an efficient method of executing commands. However, it can be a convenient tool for
This should explain why it's not efficient, and the more efficient alternatives.

2022-10-07 01:30 UTC, alice-i-cecile commented
> If this is only to be used for test, I would rather it being not available outside of tests

This came up before in my other PRs for testing utilities. I think that the trait (that's not in the prelude) is a reasonable approach. I would also support the creation of a `bevy_testing` crate to stick this sort of thing in, which would improve discoverability.

2022-10-07 03:40 UTC, Zeenobit commented
> This came up before in my other PRs for testing utilities. I think that the trait (that's not in the prelude) is a reasonable approach. I would also support the creation of a `bevy_testing` crate to stick this sort of thing in, which would improve discoverability.

I like this idea, but I would suggest naming it some more generic like `bevy_diagnostics`. My rationale is that a lot of stuff like this that's useful for testing would also be useful for stuff like cheats, debug tools, or automation. If we name it `bevy_testing`, it'd imply it's *only* useful for testing.

2022-10-07 13:14 UTC, alice-i-cecile commented
Well, we *have* `bevy_diagnostic`. @mockersf, I'd be okay with testing utilities going in there!

2022-10-10 18:59 UTC, Zeenobit commented
Let me know if we want to move the entire implementation into a separate file `execute.rs` under `bevy_diagnostic`.

2022-10-10 19:25 UTC, alice-i-cecile commented
Yes please :)

2022-10-10 21:27 UTC, alice-i-cecile requested changes
Awesome. Can you add an example for this? Maybe in the root tests directory? I would suggest you link it from the Commands docs but we can't, because circular dependencies.

2022-10-10 22:02 UTC, Zeenobit commented
> Awesome. Can you add an example for this? Maybe in the root tests directory? I would suggest you link it from the Commands docs but we can't, because circular dependencies.

I added an example under `how_to_test_commands.rs`. It's hard to come up with a good use case for using a custom command without really explaining a system which might need it. I figured navigation might the best example, but let me know if you have better ideas. And for all regular commands, most of them are accessible through `&mut World` anyways.

Also, I'm not sure if it was just me, but an issue I discovered while testing:

`world.spawn(())` seems to panic with "index out of bounds: the len is 0 but the index is 0". But `commands.spawn(())` seems fine.

2022-10-10 22:03 UTC, alice-i-cecile commented on crates/bevy_diagnostic/src/execute.rs
> +    ///     commands.spawn(()).id()
This should use `spawn_empty` instead.

2022-10-10 22:04 UTC, alice-i-cecile commented on crates/bevy_diagnostic/src/execute.rs
> +/// Extension trait used to execute some [`Commands`] immediately on a [`World`].
```suggestion
/// Extension trait used to execute [`Commands`] immediately on a [`World`].
```

2022-10-10 22:05 UTC, Zeenobit commented on crates/bevy_diagnostic/src/execute.rs
> +    ///     commands.spawn(()).id()
Ah that explains a lot! Thanks!

2022-10-10 22:37 UTC, alice-i-cecile approved these changes

2022-12-13 00:15 UTC, closed without merging

2023-01-20 18:16 UTC, Zeenobit commented
Today I realized I accidentally deleted the repository for this. 😢 
I'll open a new PR in future.