Impl Reflect for PathBuf and OsString
bevyengine/bevy pull request #6193
Opened 2022-10-07 17:50 UTC by Shatur

# Objective

`Reflect` impl is missing for `PathBuf` and `OsString`. Closes #6166.

## Solution

Add implementations.

---

## Changelog

### Added

`Reflect` impls for `PathBuf` and `OsString`.

2022-10-07 21:27 UTC, Shatur commented
@alice-i-cecile I added implementation for `OsString` only on platforms that can serialize it [as in serde](
https://github.com/serde-rs/serde/blob/3ffb86fc70efd3d329519e2dddfa306cc04f167c/serde/src/de/impls.rs#L1732).

2022-10-07 22:14 UTC, alice-i-cecile commented
Great, thanks for the context there. Can you add that as a comment?

2022-10-07 22:19 UTC, Shatur commented
Done!

2022-10-07 23:19 UTC, alice-i-cecile approved these changes

2022-10-08 09:22 UTC, tguichaoua requested changes
I think `feature = "std"` is used in `serde` because it's a `no_std` crate. It's not necessary here.

2022-10-08 09:22 UTC, tguichaoua commented on crates/bevy_reflect/src/impls/std.rs
> +#[cfg(all(feature = "std", any(unix, windows)))]
```suggestion
#[cfg(any(unix, windows))]
```

2022-10-08 09:22 UTC, tguichaoua commented on crates/bevy_reflect/src/impls/std.rs
> +#[cfg(all(feature = "std", any(unix, windows)))]
```suggestion
#[cfg(any(unix, windows))]
```

2022-10-08 12:06 UTC, Shatur commented
Of course, thanks, fixed.

2022-10-08 12:39 UTC, tguichaoua approved these changes

2022-10-08 17:00 UTC, MrGVSV approved these changes

2022-10-08 17:02 UTC, alice-i-cecile commented
bors r+

2022-10-08 17:19 UTC, closed without merging