Add From<String> for AssetPath<'a>
bevyengine/bevy pull request #6337
Opened 2022-10-22 08:03 UTC by Ian-Yy

# Objective
Fixes #6291 

## Solution
Implement `From<String>` for `AssetPath<'a>`

2022-10-22 08:12 UTC, harudagondi requested changes

2022-10-22 08:12 UTC, harudagondi commented on crates/bevy_asset/src/path.rs
> +}
This will stack overflow, as calling `asset_path.into()` will call `AssetPath::from(asset_path)`, which will call this trait method again. You should manually create the `AssetPath` struct, and do not make any calls to `from` and `into`.

2022-10-22 08:17 UTC, harudagondi requested changes

2022-10-22 08:17 UTC, harudagondi commented on crates/bevy_asset/src/path.rs
> +}
Alternatively...

```suggestion
impl<'a> From<String> for AssetPath<'a> {
    fn from(asset_path: String) -> Self {
        asset_path.as_str().into()
    }
}
```

2022-10-22 08:18 UTC, harudagondi commented on crates/bevy_asset/src/path.rs
> +}
Alternatively...
```suggestion
impl<'a> From<String> for AssetPath<'a> {
    fn from(asset_path: String) -> Self {
        asset_path.as_str().into()
    }
}
```
As there is already existing logic for `&str`.

2022-10-22 08:24 UTC, Ian-Yy commented on crates/bevy_asset/src/path.rs
> +}
Sorry. I overlooked this. I tried the solution with `as_str()` but it would not compile due to 
> cannot return value referencing function parameter `asset_path`
> returns a value referencing data owned by the current
So, I think the solution will be to create the AssetPath struct again?

2022-10-22 08:25 UTC, harudagondi commented on crates/bevy_asset/src/path.rs
> +}
If that's the case then yes.

2022-10-22 11:30 UTC, harudagondi approved these changes
It's sad that the solution is just copying pasting from `&str` with the only difference being that this returns owned values. I'm not blocking on this, but perhaps implementing `ToOwned` would be viable here?

Approving this =)

2022-10-22 17:02 UTC, mockersf approved these changes

2022-10-23 10:37 UTC, Ian-Yy commented
> It's sad that the solution is just copying pasting from `&str` with the only difference being that this returns owned values. I'm not blocking on this, but perhaps implementing `ToOwned` would be viable here?
> 
> Approving this =)

Yea. I agree with you. But since we are passing in an owned String, any variable created would not live long enough to return. 
https://stackoverflow.com/questions/32682876/is-there-any-way-to-return-a-reference-to-a-variable-created-in-a-function

Do you have some reference as to how `ToOwned` will help and its implementation?

2022-10-23 10:43 UTC, harudagondi commented
> Do you have some reference as to how `ToOwned` will help and its implementation?

Essentially both `&str` and `String` implementations are basically the same except one returns `Cow::Borrowed` fields and the other returns `Cow::Owned`. Looking at the docs once more, `AssetPath` actually implements `Clone`.

Maybe `asset_path.as_str().into().clone()` would suffice?

2022-10-23 10:57 UTC, Ian-Yy commented
I tried implementing using `asset_path.as_str().into().clone()` as below
![image](https://user-images.githubusercontent.com/23068019/197388151-b03739b4-7e8f-4927-8199-989d4c26a500.png)

And got the following error which I think is the same as `asset_path.as_str().into()`
> cannot return value referencing function parameter `asset_path`
> returns a value referencing data owned by the current function rustc[E0515](https://doc.rust-lang.org/error-index.html#E0515)

2022-10-23 11:19 UTC, harudagondi commented
Hmm. What if we go through the `PathBuf` route? According to the impl, converting from `String` to `PathBuf` shouldn't allocate memory, which is nice.

2022-10-23 12:38 UTC, Ian-Yy commented
That is possible but we will lose the label of `AssetPath` as it's assigned a `None` to it.

2022-10-24 14:13 UTC, alice-i-cecile commented
bors r+

2022-10-24 14:33 UTC, closed without merging