[Merged by Bors] - refactor: move internals from `entity_ref` to `World`, add `SAFETY` comments
bevyengine/bevy pull request #6402
Opened 2022-10-29 09:45 UTC by jakobhellermann

# Objective

There are some utility functions for actually working with `Storages` inside `entity_ref.rs` that are used both for `EntityRef/EntityMut` and `World`, with a `// TODO: move to Storages`.
This PR moves them to private methods on `World`, because that's the safest API boundary. On `Storages` you would need to ensure that you pass `Components` from the same world.

## Solution

- move get_component[_with_type], get_ticks[_with_type], get_component_and_ticks[_with_type] to `World` (still pub(crate))
- replace `pub use entity_ref::*;` with `pub use entity_ref::{EntityRef, EntityMut}` and qualified `entity_ref::get_mut[_by_id]` in `world.rs`
- add safety comments to a bunch of methods

2022-10-29 22:23 UTC, alice-i-cecile commented
I agree with the code reorg. Lemme take a look at the safety comments...

2022-10-29 22:31 UTC, alice-i-cecile requested changes
Okay, so the safety docs have some problems 😂 They're pretty much all repeated, and I didn't call them out in each location to reduce spam.

Not your fault by any means (these docs are much better than we had), but eh, I'd like to clean them up while we're here.

2022-10-29 22:31 UTC, alice-i-cecile commented on crates/bevy_ecs/src/storage/mod.rs
> +    /// - `component_id` must be valid
We're passing in a `type_id` here, so I don't think this applies.

2022-10-29 22:31 UTC, alice-i-cecile commented on crates/bevy_ecs/src/storage/mod.rs
> +    /// - `entity_location` must be within bounds of the given archetype and `entity` must exist inside
A specific archetype isn't given, so this comment is unclear.

2022-10-29 22:31 UTC, alice-i-cecile commented on crates/bevy_ecs/src/storage/mod.rs
> +    /// - `entity_location` must be within bounds of the given archetype and `entity` must exist inside
Ditto for "given archetype". This seems to be a problem on pretty much every method here :)

2022-10-29 22:31 UTC, alice-i-cecile commented on crates/bevy_ecs/src/storage/mod.rs
> +                // SAFETY: archetypes only store valid table_rows and the stored component type is T
It's not clear what `T` refers to in the context of this function.

2022-10-29 22:31 UTC, alice-i-cecile commented on crates/bevy_ecs/src/storage/mod.rs
> +    /// - `component_id` must be valid
I'd like a bit more advice here on what it means for a component id to be valid. Probably best suited to living on the `ComponentId` docs though.

2022-10-29 22:31 UTC, alice-i-cecile commented on crates/bevy_ecs/src/storage/mod.rs
> +                // SAFETY: archetypes only store valid table_rows and the stored component type is T
T is not defined here.

2022-11-14 01:55 UTC, james7132 commented on crates/bevy_ecs/src/world/entity_ref.rs
> +                    &self.world.archetypes,
Almost all of these are using borrows from `World`. Wouldn't it make more sense to move these to `World` than `Storages`?

2022-11-14 01:56 UTC, james7132 commented on crates/bevy_ecs/src/storage/mod.rs
> +    pub unsafe fn get_component_and_ticks_with_type(
These were `pub(crate)` before, why are they now just `pub`?

2022-11-15 22:33 UTC, james7132 commented on crates/bevy_ecs/src/world/entity_ref.rs
> +                    &self.world.archetypes,
If it cannot be safely used without them, it's best to put it on the interface where it's most cleanly used and has fewer safety invariants.

2022-11-15 22:35 UTC, james7132 commented on crates/bevy_ecs/src/storage/mod.rs
> +    pub unsafe fn get_component_and_ticks_with_type(
I'd err on the side of caution here. Unless we have a solid external use case, having more `pub`, particularly for items that mutably change the state of the `World`, is just asking for public facing unsoundness.

2022-12-09 21:52 UTC, james7132 requested changes

2022-12-09 21:52 UTC, james7132 commented on crates/bevy_ecs/src/world/entity_ref.rs
> +        self.world.components().get_info(component_id)?;
```suggestion
```

This is redundant with the above.

2022-12-09 21:52 UTC, james7132 commented on crates/bevy_ecs/src/world/mod.rs
> +unsafe fn fetch_table(
Any reason why these couldn't be in the block above?

2022-12-17 13:05 UTC, james7132 approved these changes

2023-01-11 03:14 UTC, alice-i-cecile commented on crates/bevy_ecs/src/world/mod.rs
> +    unsafe fn fetch_table(
This needs safety comments.

2023-01-11 03:17 UTC, alice-i-cecile requested changes
Two concerns, but once those are fixed up I'm happy to merge this. It's better organized, and the safety comments are much better.

2023-01-11 03:17 UTC, alice-i-cecile commented on crates/bevy_ecs/src/world/entity_ref.rs
> +pub(crate) unsafe fn take_component<'a>(
The PR description suggests that this is a method on Storages (which I like better), but here it's a freestanding function.

2023-01-13 16:30 UTC, alice-i-cecile approved these changes
LGTM now once the PR description matches where the methods were moved, one way or another.

2023-01-13 16:50 UTC, alice-i-cecile commented
bors r+

2023-01-13 17:04 UTC, closed without merging