Fix `clippy::iter_with_drain`
bevyengine/bevy pull request #6485
Opened 2022-11-05 14:48 UTC by TimJentzsch

# Objective

Fixes #6483.

- Fix the [`clippy::iter_with_drain`](https://rust-lang.github.io/rust-clippy/master/index.html#iter_with_drain) warnings
- From the docs: "`.into_iter()` is simpler with better performance"

## Solution

- Replace `.drain(..)` for `Vec` with `.into_iter()`

2022-11-05 16:09 UTC, alice-i-cecile approved these changes

2022-11-05 17:14 UTC, 2ne1ugly commented on crates/bevy_ecs/src/schedule/stage.rs
> +        for system in systems.into_iter() {
```suggestion
        for system in systems {
```

2022-11-05 17:14 UTC, 2ne1ugly commented on crates/bevy_pbr/src/material.rs
> +    for (handle, material) in queued_assets.into_iter() {
```suggestion
    for (handle, material) in queued_assets {
```

2022-11-05 17:14 UTC, 2ne1ugly commented on crates/bevy_render/src/render_asset.rs
> +    for (handle, extracted_asset) in queued_assets.into_iter() {
```suggestion
    for (handle, extracted_asset) in queued_assets {
```

2022-11-05 17:15 UTC, 2ne1ugly commented on crates/bevy_sprite/src/mesh2d/material.rs
> +    for (handle, material) in queued_assets.into_iter() {
```suggestion
    for (handle, material) in queued_assets {
```

2022-11-05 17:15 UTC, 2ne1ugly requested changes
Minor but I think we can get rid of few `into_iter()`s

2022-11-05 22:37 UTC, james7132 approved these changes

2022-11-06 01:41 UTC, alice-i-cecile commented
bors r+

2022-11-06 01:58 UTC, closed without merging