Use 64 bit for world and system tick index
bevyengine/bevy pull request #6651
Opened 2022-11-16 21:04 UTC by zakarumych

# Objective

- Use strongly typed ticks with 64 bit integer value within.
- Avoid tick counter overflow
- Continue using 32 bit tick id in components. Keep existing system that prevents component age to overflow 32 bit.

---

## Changelog

- Tick values are now strongly typed as `Tick` and `SmallTick`.
- `Tick` now contains `NonZeroU64` and never overflow in any reasonable time.
- `SmallTick` are used to store tick index when component addition and last modification. It contains `u32` with lower 32 bits of `Tick`s 64 bit value.
- `World` now uses `TickCounter` that implements tick incrementing and necessary bookkeeping.

## Migration Guide

- Custom `System` implementations have to switch to strongly typed `Tick` values and remove few methods.

## Pick one

This is alternative to #6327 where components get their ticks grown to 64 bit as well.
And #6327 doesn't introduce strongly typed ticks. Can be implemented though.

2022-11-20 10:59 UTC, james7132 requested changes
Only a cursory scan. Have not done a full review of the updated logic just yet.

You do not need `#[inline(always)]` for most of these functions at this size. They're almost always guaranteed to inline even in debug mode.

2022-11-20 10:59 UTC, james7132 commented on crates/bevy_ecs/macros/src/lib.rs
> +                    change_tick: Tick,
```suggestion
                    change_tick: #path::change_detection::Tick,
```

2022-11-20 10:59 UTC, james7132 commented on crates/bevy_ecs/src/change_detection.rs
> +///
```suggestion
```

2022-11-20 10:59 UTC, james7132 commented on crates/bevy_ecs/src/change_detection.rs
> +    #[inline(always)]
```suggestion
```

2022-11-20 10:59 UTC, james7132 commented on crates/bevy_ecs/src/change_detection.rs
> +    #[inline(always)]
```suggestion
```

2022-11-20 10:59 UTC, james7132 commented on crates/bevy_ecs/src/change_detection.rs
> +    #[inline(always)]
```suggestion
```

2022-11-20 10:59 UTC, james7132 commented on crates/bevy_ecs/src/change_detection.rs
> +    #[inline(always)]
```suggestion
```

2022-11-20 10:59 UTC, james7132 commented on crates/bevy_ecs/src/change_detection.rs
> +pub struct SmallTick(pub u32);
```suggestion
pub struct SmallTick(u32);
```

2022-11-20 10:59 UTC, james7132 commented on crates/bevy_ecs/src/change_detection.rs
> +#[derive(Clone, Copy, Debug)]
```suggestion
#[derive(Clone, Copy, Debug, Default)]
```

2022-11-20 10:59 UTC, james7132 commented on crates/bevy_ecs/src/change_detection.rs
> +}
```suggestion
```

2022-11-20 10:59 UTC, james7132 commented on crates/bevy_ecs/src/change_detection.rs
> +}
```suggestion
```

2022-11-20 10:59 UTC, james7132 commented on crates/bevy_ecs/src/change_detection.rs
> +// #[allow(clippy::useless_conversion)]
```suggestion
```

2022-11-20 10:59 UTC, james7132 commented on crates/bevy_ecs/src/change_detection.rs
> +        // `TICK_BASE_VALUE` is nonzero
```suggestion
        // SAFETY: `TICK_BASE_VALUE` is nonzero
```

2022-11-23 03:44 UTC, james7132 commented
#6547 has been merged. Can you rebase? I'll run a set of microbenchmarks for comparison.

2024-10-06 00:56 UTC, richchurcher commented
Backlog cleanup: closing this and alternate approach #6327 due to inactivity and no clear consensus.

2024-10-06 00:56 UTC, closed without merging