UI Image Rotation
bevyengine/bevy pull request #6688
Opened 2022-11-18 23:58 UTC by ickshonpe

# Objective

Enable 90-degree rotations of `UiImage`s. 

## Solution

Add a bool field `rotate` to `UiImage` and shift the uv-coords to the left in prepare_uinodes if it is set to true.
Then, by composition with flip_x and flip_y, you can rotate the image by 90, 180, and 270 degrees.

---

## Changelog
* added `rotate` field to `UiImage`
* changed `update_image_calculated_size_system` to swap width and height if rotating the image.
* added `rotate` field to `ExtractedUiSprite`
* changed `prepare_uninodes` to shift the texture's UV coordinates left if rotating the image.
* added an example "image_symmetries.rs" to the ui examples

2022-11-19 10:48 UTC, DasLixou commented
Wouldn’t be enums cool? Like 180 degrees rotation = rotate and flip_x, or whatever. It’s a bit confusing but with an enum and bits in a u8 you could store everything from normal over rotate 90 180 270 to flip_x and flip_y readable and easy AND only use 8 bits?

2022-11-19 12:13 UTC, alice-i-cecile requested changes
Yep, I agree with @DasLixou's request for an enum :) I think mentally I would model this as a four-valued enum, with flipping x and y layered on top.

2022-11-19 12:26 UTC, ickshonpe commented
> Wouldn’t be enums cool? Like 180 degrees rotation = rotate and flip_x, or whatever. It’s a bit confusing but with an enum and bits in a u8 you could store everything from normal over rotate 90 180 270 to flip_x and flip_y readable and easy AND only use 8 bits?

Yes that was my original plan, but I just can't think of a decent name for the enum or its variants :cry:

2022-11-19 12:53 UTC, DasLixou commented
> > Wouldn’t be enums cool? Like 180 degrees rotation = rotate and flip_x, or whatever. It’s a bit confusing but with an enum and bits in a u8 you could store everything from normal over rotate 90 180 270 to flip_x and flip_y readable and easy AND only use 8 bits?
> 
> Yes that was my original plan, but I just can't think of a good name for the enum or its variants 😢

`ImageModifier`

```
FlipHorizontally = 100
Rotate90 = 001
Rotate180 = FlipHorizontally | FlipVertically
```
Something in this way?

2022-11-19 12:56 UTC, DasLixou commented
Or `UVModifier` because that’s what you said

> and shift the uv-coords to the left in prepare_uinodes if it is set to true.

2022-11-19 14:53 UTC, DasLixou reviewed
That seems better but i would still make it using bits. FlipRotate90 sounds a little bit scary. `ImageOrientation::Rotate90 | ImageOrientation::FlipX` would be better in my eyes. then you could also leave your old if statements but use bit flags. so 

```rust
        if extracted_uinode.orientation & ImageOrientation::Rotate90 != 0 {
            uvs = [uvs[1], uvs[2], uvs[3], uvs[0]];
        }
        if extracted_uinode.orientation & ImageOrientation::FlipX != 0 {
            uvs = [uvs[1], uvs[0], uvs[3], uvs[2]];
        }
        if extracted_uinode.orientation & ImageOrientation::FlipY != 0 {
            uvs = [uvs[3], uvs[2], uvs[1], uvs[0]];
        }
```

and then make combinations in the enum:

```rust
Rotate180 = FlipX | FlipY
```

But it would be slower because we would change uvs 3 times.. idk its your appinion, just my suggestion :) :+1:

2022-11-19 15:23 UTC, ickshonpe commented
>. FlipRotate90 sounds a little bit scary. `ImageOrientation::Rotate90 | ImageOrientation::FlipX` would be better in my eyes.

That was the first thing I considered too but the problem is that bitwise operations are commutative.
That is ImageOrientation::Rotate90 | ImageOrientation::FlipX == ImageOrientation::FlipX | ImageOrientation::Rotate90,
but a rotation followed by a reflection isn't equal to a reflection followed by a rotation:

![rs](https://user-images.githubusercontent.com/27962798/202857900-faa1d7b7-94cf-4a5f-8ee3-3e0e0740ff7b.jpg)

2022-11-19 15:29 UTC, DasLixou commented
> > . FlipRotate90 sounds a little bit scary. `ImageOrientation::Rotate90 | ImageOrientation::FlipX` would be better in my eyes.
> 
> This was the first thing I considered too, but the problem is that bitwise operations are commutative. That is `ImageOrientation::Rotate90 | ImageOrientation::FlipX == ImageOrientation::FlipX | ImageOrientation::Rotate90`, but a rotation followed by a reflection isn't equal to a reflection followed by a rotation:
> 
> ![rs](https://user-images.githubusercontent.com/27962798/202857900-faa1d7b7-94cf-4a5f-8ee3-3e0e0740ff7b.jpg)

yeah but with the old system with booleans it wasn't either

2022-11-19 15:39 UTC, alice-i-cecile commented
I think we can clarify the API by talking about which way the image is "pointing". Instead of `ImageOrientation::Rotate270`, we can simply have `Rotation::PointingLeft`.

I agree with your point about commutativity, but I really think that keeping these as separate fields will be more reliable in practice. Just clearly document that we flip first, then rotate.

2022-11-19 15:52 UTC, DasLixou commented
> I think we can clarify the API by talking about which way the image is "pointing". Instead of `ImageOrientation::Rotate270`, we can simply have `Orientation::PointingLeft`.
> 
> I agree with your point about commutativity, but I really think that keeping these as separate fields will be more reliable in practice. Just clearly document that we flip first, then rotate.

that sounds reasonable

2022-11-19 17:45 UTC, mockersf commented
> I think we can clarify the API by talking about which way the image is "pointing". Instead of `ImageOrientation::Rotate270`, we can simply have `Orientation::PointingLeft`.

As this is in UI context, maybe `LeftToRight` and `RightToLeft`?

2022-11-22 09:38 UTC, inodentry commented
Flipping on the Y axis is not the same as a 180° rotation!

![Y axis flip vs. 180 degree rotation](https://user-images.githubusercontent.com/40234599/203279209-f57a4a72-3f67-4bf0-8097-0415d754a401.png)

Both operations should be supported and *represented independently*! You can't emulate one with the other.

Having everything in one big enum is confusing and IMO leads to bad UX.

2022-11-22 09:46 UTC, inodentry commented
Well, IMO, using the enum variants directly has confusing and unergonomic usability (all the `FlipRotate*` stuff is unintuitive). You have to think about how your desired flip and rotation combine in order to pick the correct enum variant. I don't think "PointingLeft"/"PointingRight" would make things any better, it seems even more confusing to me.

I think we should just expect (and teach) users to use the methods to produce their desired effect:
```rust
ImageOrientation::default().rotate_ccw().flip_y()
```
This way of using the API seems much easier to reason about. You can produce the correct value without much cognitive overhead. That's what we should show in examples and teach to users.

2022-11-26 11:11 UTC, ickshonpe commented
> Well, IMO, using the enum variants directly has confusing and unergonomic usability. You have to think about how your desired flip and rotation combine in order to pick the correct enum variant. I don't think "PointingLeft"/"PointingRight" would make things any better, it seems even more confusing to me. It adds the confusion of "what does it mean for my image to point a certain way?".
> 
> I think we should just expect (and teach) users to use the methods to produce their desired effect:
> 
> ```rust
> ImageOrientation::default().rotate_ccw().flip_y()
> ```
> 
> This way of using the API seems much easier to reason about. You can produce the correct value without much cognitive overhead. That's what we should show in examples and teach to users.
> 
> I don't think there is a way to make directly using the enum variants themselves intuitive. They are fine as they are.

Yes, that's exactly how I intended the API to be used. I should have explained myself better. 

I think the orientation should be just one value with 8 variants. It only represents one distinct concept, the order of the image's UVs when it is rendered. 

Also with a representation like

```rust
struct UiImage {
  texture: Handle<Image>,
  direction: Direction, 
  flip_x: bool,
}
```
methods like flip_y() would have to be implemented on the whole UiImage struct, rather than just the enum. 
And with both flip_x and flip_y values and a direction enum you have redundant information. Neither of which seems very pleasant. 

I replaced counter-clockwise and clockwise with left and right and Rotate90 / Rotate270 with RotatedLeft and RotatedRight. These seem much better, I especially disliked Rotate270. 

I don't think there is a more intuitive and concise way to describe a half-turn than Rotate180 though.

2022-11-26 11:33 UTC, DasLixou approved these changes
I like it! 👍 
I don’t know if it needs any tests, but you may include one that calls multiple Orientation functions and then asserts them. Just to make sure when somebody messes around there nobody messes things up?

Also you might wanna make functions like `rotate_left` and so `const` :)

2022-11-26 12:30 UTC, ickshonpe commented
> I like it! 👍 I don’t know if it needs any tests, but you may include one that calls multiple Orientation functions and then asserts them. Just to make sure when somebody messes around there nobody messes things up?
> 
> Also you might wanna make functions like `rotate_left` and so `const` :)

Yep, good points, made both changes.

2022-11-26 12:32 UTC, DasLixou commented
It should now be time for @alice-i-cecile to review it and then add Final Review to it.

2022-12-08 14:58 UTC, mockersf commented
I would prefer to keep something similar to [`Sprite`](https://docs.rs/bevy/latest/bevy/sprite/struct.Sprite.html), with `flip_x` and `flip_y` bools, and rotation being handled by the `Transform`

2022-12-08 15:04 UTC, DasLixou commented
> I would prefer to keep something similar to [`Sprite`](https://docs.rs/bevy/latest/bevy/sprite/struct.Sprite.html), with `flip_x` and `flip_y` bools, and rotation being handled by the `Transform`



> I would prefer to keep something similar to [`Sprite`](https://docs.rs/bevy/latest/bevy/sprite/struct.Sprite.html), with `flip_x` and `flip_y` bools, and rotation being handled by the `Transform`

hmm 🤔 that would also be possible.. but i dont know how it behaves with Pivot Points or smth like that.. with that you could also argue why even use flip_x when you could rotate the sprite in the other directions for 180 degrees...

2022-12-08 15:11 UTC, mockersf commented
> why even use flip_x when you could rotate the sprite in the other directions for 180 degrees...

Because rotating by 180° is not the same as flipping? It could be done by settings the scale on x as -1.0, but that's not natural, while handling rotation with the existing rotation part of a transform

2022-12-08 15:53 UTC, DasLixou commented
> > why even use flip_x when you could rotate the sprite in the other directions for 180 degrees...
> 
> Because rotating by 180° is not the same as flipping on x? It could be done by settings the scale on x as -1.0, but that's not natural, while handling rotation with the existing rotation part of a transform is

Rotating a sprite with 180 degrees around the y axis (the axis that goes up) would have the same effect, wouldn't it?

2022-12-08 16:11 UTC, mockersf commented
Ha right, I really avoid thinking about rotating on other axes than z on 2d/ui.

But same that for scale, thinking about scale / rotation on y is not the natural thing you're looking for when trying to flip an image. Rotation feels much more natural when looking to rotate.

2022-12-09 15:00 UTC, inodentry commented
Hmm, I am not sure the Transform can be used for rotating UI images? Doesn't everything that is part of a UI hierarchy have its transforms managed by Bevy internals (based on layout calculations)?

2022-12-09 16:07 UTC, mockersf commented
Layout only updates the translation, you can update other parts of the transform if you need to.

2022-12-09 16:19 UTC, ickshonpe commented
> Layout only updates the translation, you can update other parts of the transform if you need to.

Only if the nodes have no children.

We could rotate the quad coordinates in the prepare function or something, but the extra work doesn't really make any sense unless it's that you want to allow arbitrary rotations, not just 90 degrees.

2022-12-09 16:52 UTC, mockersf commented
> Only if the nodes have no children. ImageBundles maybe shouldn't have any children, but there is nothing stopping people from spawning them at the moment.

What do you mean?

This renders the same in Bevy and in HTML: https://jsfiddle.net/y06uoL81/
<img width="1392" alt="Screenshot 2022-12-09 at 17 48 48" src="https://user-images.githubusercontent.com/8672791/206751484-ae74710c-253b-4546-b247-532cc6579b9f.png">

<details><summary>Bevy code</summary>
<p>

```rust
use std::f32::consts::FRAC_PI_4;

use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup)
        .run();
}

fn setup(mut commands: Commands) {
    commands.spawn(Camera2dBundle::default());
    commands
        .spawn(NodeBundle {
            style: Style {
                size: Size::new(Val::Px(80.0), Val::Px(80.0)),
                ..default()
            },
            background_color: BackgroundColor(Color::PINK),
            transform: Transform::from_rotation(Quat::from_rotation_z(FRAC_PI_4)),
            ..default()
        })
        .with_children(|parent| {
            parent.spawn(NodeBundle {
                style: Style {
                    size: Size::new(Val::Px(40.0), Val::Px(40.0)),
                    ..default()
                },
                background_color: BackgroundColor(Color::ALICE_BLUE),
                ..default()
            });
        });
}
```

</p>
</details>

That's actually a good point, all UI nodes can be rotated, not just images.

2022-12-09 18:19 UTC, ickshonpe commented
Ah, we're talking about different things.

This PR doesn't just do image rotation, it also adjusts the layout. So if you create an ImageBundle with a 50 wide by 100 high image and then you rotate it by 90 degrees the image's width and height are swapped and the layout will be changed depending on the style settings etc.

That won't happen if you change the rotation of the transform, it will rotate the UI element but it won't change the layout to fit its new orientation.

2023-01-10 10:25 UTC, inodentry commented
I agree with this PR. I think there should be a way to flip and rotate-by-90° UI images in a way that also affects the layout. This could be important for correctly laying out the content for some UIs.

Rotating via the Transform is a separate use case (I can see it being used for eye-candy/animations and such), where you want all the other UI/layout to stay in place.

2023-02-20 22:57 UTC, omwda requested changes
I'm finding the Orientation values to be a little too verbose/confusing. I think we should be using cardinal naming to keep things simple and consistent.

![UntitledUI-rotation](https://user-images.githubusercontent.com/6396199/220209060-ea57b7d6-a308-430a-b581-4201a938403c.png)

Following this, Orientation becomes:
```
Identity = North
RotatedLeft = East
Rotated180 = South
RotatedRight = West
FlippedX = FlippedNorth
FlippedXRotatedLeft = FlippedEast
FlippedXRoated180 = FlippedSouth
FlippedXRotatedRight = FlippedWest
```

2023-02-21 00:16 UTC, alice-i-cecile commented
Cardinal naming is much clearer to me too: good suggestion.

2023-02-21 21:18 UTC, ickshonpe commented
Cardinal naming is clear if you have an image orientated `North` but if your image is orientated `South` then the directions get reversed and it isn't very intuitive anymore. This thing has been blocked over the enum names forever though, and like Inodentry said the correct way to use the API is to use the functions not the enums anyway, so I don't care anymore, if the people really want to have cardinal directions lets go with that :ok_hand:

2023-02-21 23:22 UTC, alice-i-cecile approved these changes

2023-02-21 23:23 UTC, alice-i-cecile commented
@inodentry @mockersf I'd like to move this PR forward. Are both of you on board with this feature existing + content enough with this as an initial API?

2023-02-22 19:48 UTC, inodentry commented
I really don't like the "cardinal direction" names. They require you to think about an alternate concept (a compass) that has nothing to do with the images you are working with, to understand the analogy / what they mean.

The old names are relative to the original image, and therefore it feels much easier for me to understand what that means. I know my image's original orientation and what that looks like. When you say that something is flipped, or rotated, I can imagine what that looks like. The only source of confusion might be if I don't immediately know the direction of rotation (clockwise or anticlockwise).

Again, this is why I would personally only use the methods in practice, and recommend other people do so too. The names of the enum variants don't matter as much IMO, but I am a person who has now put a lot of thought into this problem. 😆 Someone who encounters the API for the first time, might very well not get the memo, and think they are supposed to use the enum variants directly. (Though a mention in the docs to direct them to using the methods, would be nice.)

Therefore, I think we *should* care that they are understandable. And IMO naming the operations after what is being done to the image, is easier to understand, than naming them after an analogy to a different concept.

All that said, I would also love for this PR to move forward. I want this functionality in Bevy. And, at this point, I think bikeshedding the enum variant names is counterproductive. We could discuss them indefinitely. So, I'm inclined to just say, go ahead. :)

2023-02-22 22:13 UTC, ickshonpe commented
I could add a const identity function, identical to `Orientation::North` and `Orientation::default()`. It's not great having several  ways of expressing the same thing, but it might be more intuitive to some users:

```rust
Orientation::identity().rotate_left()
```
makes immediate sense to me, whereas with:
```
Orientation::North.rotate_left()
```
you have to remember that North is the identity, and it's by no means obvious. East is a more common choice I think in most mathematics books. 

From a gamedev point of view too, when I think of sprites the first thing that comes to me is a 2d platform character facing to the right.

2023-02-22 22:14 UTC, inodentry commented
Yes exactly, the "cardinal directions" IMO make things more confusing.

Also, yes, an identity function makes a lot of sense. Good call. I think it would really improve things. :)

2023-02-22 22:42 UTC, alice-i-cecile approved these changes

2023-02-22 23:30 UTC, mockersf commented
I'm very much not convinced by this feature
* it doesn't exist in the two UI library I have a light knowledge of, CSS or Flutter. Bevy currently behaves as CSS
* using direction, and `North` as the default, is very much not natural
* if we want something to rotate things and move the layout around them, why limit it to only images? does that mean we expect users to put image nodes with transparent images to rotate items in a hierarchy and update the layout around them?

2023-02-23 10:43 UTC, inodentry commented
This is a good starting point IMO.

Bevy currently completely lacks any way to rotate images in UI in a way that also affects layout (i.e not by Transform). This is an important use case to support for some practical applications.

I understand that the API is not perfect and is controversial. I would much rather have *something*, *anything*, than nitpick this forever.

@mockersf I understand your arguments. And what exactly is wrong with merging this in its current form, and then continuing to improve and generalize the API later in subsequent PRs? Does it really need to be perfect on the first try?

Regarding your last point, there is nothing stopping us from implementing something more general in the future and removing this.

I agree on the cardinal directions. I don't like them either. The earlier version of the PR had better names, and my detailed reasoning for that is in my previous comment.

Bevy UI has always been clunky and hacky, and we should all be striving to make it less so, over time. This shouldn't get in the way of adding useful features.

Regarding your first point, Bevy currently behaves roughly like CSS, but deviates in many ways. I don't see why something not being exactly like another framework should be an argument against its inclusion in Bevy.

2023-02-23 13:12 UTC, mockersf commented
> Bevy currently completely lacks any way to rotate images in UI in a way that also affects layout (i.e not by Transform). This is an important use case to support for some practical applications.

Is it? I find it hard to believe it could be when it's not supported by CSS, Flutter or SwiftUI (which I also checked just now). And there hasn't been a lot of users asking for it yet.

I can see the need for a way to rotate things impacting layout, but doing it only if the node is an image doesn't make sense for me.

2023-02-23 22:01 UTC, omwda commented
> I really don't like the "cardinal direction" names. They require you to think about an alternate concept (a compass) that has nothing to do with the images you are working with, to understand the analogy / what they mean.
> 
> The old names are relative to the original image, and therefore it feels much easier for me to understand what that means. I know my image's original orientation and what that looks like. When you say that something is flipped, or rotated, I can imagine what that looks like. The only source of confusion might be if I don't immediately know the direction of rotation (clockwise or anticlockwise).
> 
> Again, this is why I would personally only use the methods in practice, and recommend other people do so too. The names of the enum variants don't matter as much IMO, but I am a person who has now put a lot of thought into this problem. 😆 Someone who encounters the API for the first time, might very well not get the memo, and think they are supposed to use the enum variants directly. (Though a mention in the docs to direct them to using the methods, would be nice.)
> 
> Therefore, I think we _should_ care that they are understandable. And IMO naming the operations after what is being done to the image, is easier to understand, than naming them after an analogy to a different concept.
> 
> All that said, I would also love for this PR to move forward. I want this functionality in Bevy. And, at this point, I think bikeshedding the enum variant names is counterproductive. We could discuss them indefinitely. So, I'm inclined to just say, go ahead. :)

Sure, those are all totally valid points and I agree that there are plenty of reasons not to use cardinality :)

My main issue with the original names is that they were inconsistent, and were trying to represent the current state of an image after one transformation. But as flipping and rotating aren't commutative, these names become harder to reason with chained transforms. I suggested cardinality as it's the enum labels themselves become more readable and are easier to reason about with chained transforms as they're agnostic to the specific transforms themselves, but rather the clockwise state of the box. As the enum values themselves won't be part of the public api, I figured getter methods like `identity()` should do the job of communicating that stuff.

But at the end of the day, either works for me. If users start getting confused about the naming, it's trivial to switch it back.

2023-09-14 12:35 UTC, nerdachse commented
> This is a good starting point IMO.
> 
> Bevy currently completely lacks any way to rotate images in UI in a way that also affects layout (i.e not by Transform). This is an important use case to support for some practical applications.
> 
> I understand that the API is not perfect and is controversial. I would much rather have _something_, _anything_, than nitpick this forever.
> 
> @mockersf I understand your arguments. And what exactly is wrong with merging this in its current form, and then continuing to improve and generalize the API later in subsequent PRs? Does it really need to be perfect on the first try?
> 
> Regarding your last point, there is nothing stopping us from implementing something more general in the future and removing this.
> 
> I agree on the cardinal directions. I don't like them either. The earlier version of the PR had better names, and my detailed reasoning for that is in my previous comment.
> 
> Bevy UI has always been clunky and hacky, and we should all be striving to make it less so, over time. This shouldn't get in the way of adding useful features, and refining them later.
> 
> Regarding your first point, Bevy currently behaves roughly like CSS, but deviates in many ways. I don't see why something not being exactly like another framework should be an argument against its inclusion in Bevy.

I agree so much with this. Instead of having something now, we have nothing because the something is not perfect.

I agree with @mockersf that not only images should be "orientable" but I also see that there are a lot of small wins in open PRs that just rot because it's not the perfect API.

It's also not as if the individual PRs are huge. There is a net weight of 300 lines here. Sure, if we would just mindlessly merge anything we would enter maintenance hell rather quick. But I don't see this happening.

2023-09-15 08:55 UTC, ickshonpe commented
@nerdachse 

I kind of came around to understanding mockersf's pov in the end and I've made a generalization of this #9341 that works for all content, not just images but text and hopefully any other widget's content in the future. 

But I haven't closed this PR because, as you and others said, I think this is better to have than nothing at all and it is much, much simpler than #9341. If no other solution is ready, I think this is worth including in 0.12.

I haven't rebased #9341 or this on main because rendering has been undergoing a lot of changes lately. I don't plan on updating either until after things have stabilized a bit. 

#9341 could still do with a look over if you or anyone else wants to do a preliminary review though, I'm not that happy with its name `UiContentTransform` and I'm interested if people think it is a good idea or have any criticisms. The API probably won't change very much, but the implementation is going to need to be completely rewritten.

2024-08-21 23:59 UTC, TrialDragon commented
@ickshonpe Do you have any intention to coming back to this PR? Asking in case it should be marked as `S-Adopt-Me`.

2024-08-23 21:23 UTC, ickshonpe commented
> @ickshonpe Do you have any intention to coming back to this PR? Asking in case it should be marked as `S-Adopt-Me`.

I'll update it, but I think it's better to leave until after the UI text section changes are merged and the texture slicing bugs are fixed. This PR was written before texture slicing was added, so I'd need to add support for it.

2024-10-20 02:30 UTC, richchurcher commented
Backlog cleanup: @ickshonpe , I realise you've returned recently to this PR but it's considered blocked based on the text revamp. Given we have this and #9341, do you want me to close this out and perhaps create an issue to track the overall problem/discussion, or do you still intend to resurrect this one?

2024-10-20 02:35 UTC, alice-i-cecile commented
Text revamp is merged, so this is no longer blocked :) A cohesive design on what to do here would be good though.

2024-10-20 10:59 UTC, ickshonpe commented
Yeah this is okay but limited, the other options are the more general https://github.com/bevyengine/bevy/pull/9341 (but I'm not sure now about that one now maybe text needs a different approach) or an api closer to `object-fit` from CSS (that would also support non-axis-aligned transformations).

2024-11-23 20:17 UTC, richchurcher commented
@ickshonpe should I transfer this to a linked issue for further design? What do you reckon?

2025-01-05 23:32 UTC, BenjaminBrienen commented
@ickshonpe are you interested in this, still? Otherwise, I can put it up for adoption.

2025-06-09 13:51 UTC, NthTensor commented
Closing as adopted by https://github.com/bevyengine/bevy/pull/19340.

2025-06-09 13:51 UTC, closed without merging