Allow iterating over with EntityRef over the entire World
bevyengine/bevy pull request #6843
Opened 2022-12-04 04:32 UTC by james7132

# Objective
Partially addresses #5504. Allow users to get an `Iterator<Item = EntityRef<'a>>` over all entities in the `World`.

## Solution
Change `World::iter_entities` to return an iteraotr of `EntityRef` instead of `Entity`.

This requires adding `Entities::get_unchecked` which gets the location of an entity without checking it's generation or bounds checking.

Not sure how to tackle making an `Iterator<Item = EntityMut<'_>>` without being horribly unsound. Might need to wait for `LendingIterator` to stabilize so we can ensure only one of them is valid at a given time.

---

## Changelog
Changed: `World::iter_entities` now returns an iterator of `EntityRef` instead of `Entity`.
Changed: `DynamicSceneBuilder::extract_entities` now takes an iterator of `EntityRef` instead of `Entity`.
Changed: `DynamicSceneBuilder::extract_entity` now takes an `EntityRef` instead of `Entity`.

## Migration Guide
TODO

2022-12-04 04:53 UTC, alice-i-cecile commented
> Not sure how to tackle making an Iterator<Item = EntityMut<'_>> without being horribly unsound

Can you steal the strategy from `Query::get_multiple_mut`?

2022-12-04 06:06 UTC, james7132 commented
> Can you steal the strategy from `Query::get_multiple_mut`?

I don't think so, since `EntityMut` may invalidate the underlying metadata stores we're using to build the iterator to begin with.

2022-12-04 14:41 UTC, alice-i-cecile commented on crates/bevy_ecs/src/entity/mod.rs
> +    /// Gets the location of an entity without checking the validity of it's index nor it's generation.
```suggestion
    /// Gets the location of an entity without checking the validity of its index nor its generation.
```

2022-12-04 14:45 UTC, alice-i-cecile requested changes
Interesting: this makes the `iter_entities` APIs dramatically more powerful, as you can immediately get read-only access to all entities in the world without having to do another lookup step.

I agree with these changes, and the safety strategy appears to be correct. The `EntityMut` changes are much harder and need more careful review, so IMO those should be left for their own PR.

## Blocking

The modified scene APIs are much harder to use and understand now, and don't take advantage of the added power. These should be reverted.

2022-12-05 03:16 UTC, alice-i-cecile approved these changes

2022-12-05 09:59 UTC, james7132 commented
Don't merge just yet. I have one small optimization to make.

2022-12-05 19:53 UTC, james7132 commented
Realized that the full location information of entities was already available from `Archetype`. The implementation is a bit messier, but it avoids querying `Entities` and avoids the use of unsafe entirely. Should also be forward compatible with #6681 looking forward since the table row and table ID are also available in Archetype.

2022-12-05 20:16 UTC, devil-ira approved these changes

2022-12-05 21:28 UTC, mockersf approved these changes

2022-12-05 22:34 UTC, cart commented
bors r+

2022-12-05 22:48 UTC, closed without merging