Improve change detection behavior for transform propagation
bevyengine/bevy pull request #6870
Opened 2022-12-06 08:31 UTC by james7132

# Objective
Fix #4647. If any child is changed, or even reordered, `Changed<Children>` is true, which causes transform propagation to propagate changes to all siblings of a changed child, even if they don't need to be.

## Solution
As `Parent` and `Children` are updated in tandem in hierarchy commands after #4800. `Changed<Parent>` is true on the child when `Changed<Children>` is true on the parent. However, unlike checking children, checking `Changed<Parent>` is only localized to the current entity and will not force propagation to the siblings.

Also took the opportunity to change propagation to use `Query::iter_many` instead of repeated `Query::get` calls. Should cut a bit of the overhead out of propagation. This means we won't panic when there isn't a `Parent` on the child, just skip over it.

2022-12-06 12:54 UTC, devil-ira approved these changes
Neat!

2022-12-06 15:51 UTC, alice-i-cecile commented
Neat! Do we have any benchmarks for this? I'd love to see the impact of this change in a large scene, with varying percentages of the entities moving.

2022-12-06 22:48 UTC, alice-i-cecile commented
Ah perfect, that's exactly what I was hoping for: I just didn't remember if we'd merged it.

2022-12-07 01:59 UTC, james7132 commented
On second thought, we actually don't have anything to test the case where we're reparenting transforms, only those that mutate `Transform`. Not sure how to better test this.

2022-12-07 03:56 UTC, alice-i-cecile commented
Hmm. It's good to check those still for regressions.

I'm trying to think about use cases where we're reparenting really aggressively. Maybe a snap-together builder game?

Overall I think that reparenting will be an extremely rare operation in practice, and we shouldn't be focused on optimizing the perf there other than incidentally.

2022-12-07 14:26 UTC, JoJoJet approved these changes
Seems like a clear improvement.

2022-12-10 11:04 UTC, SkiFire13 commented on crates/bevy_transform/src/systems.rs
>              // SAFETY: This call cannot create aliased mutable references.
This safety comment should be updated since it says "The above assertion ensures that ...", but the assertion is no longer there.

2023-01-04 04:10 UTC, JoJoJet requested changes

2023-01-04 07:45 UTC, SkiFire13 commented on crates/bevy_transform/src/systems.rs
>              // SAFETY: This call cannot create aliased mutable references.
This looks solved to me, but I can't mark it as such.

2023-01-05 11:51 UTC, alice-i-cecile commented on crates/bevy_transform/src/systems.rs
> +/// is not malformed and must remain as a tree or a forest. An entity must not have more than one parent.
I think that "at most one" is more correct here, since that's the actual safety requirement.

2023-01-16 01:10 UTC, james7132 commented on crates/bevy_transform/src/systems.rs
>  ///
Should be resolved now.

2023-01-16 04:19 UTC, JoJoJet approved these changes

2023-01-16 15:15 UTC, alice-i-cecile approved these changes
bors r+

2023-01-16 18:13 UTC, james7132 commented
bors retry

2023-01-17 22:26 UTC, james7132 commented
bors r+

2023-01-17 22:41 UTC, closed without merging