Added examples for async client/server files
bevyengine/bevy pull request #6892
Opened 2022-12-08 22:31 UTC by vikingSec

# Objective

I've been playing around with using raw sockets to create an asynchronous client/server methodology with Bevy. The [async_source_external_thread](ttps://github.com/bevyengine/bevy/blob/main/examples/async_tasks/external_source_external_thread.rs) example was good, but there were a few quirks that I implemented to make it work with clients/servers.

No worries if you don't find this example useful! I learned a ton from the experience and plan on implementing it into some projects in the future.

## Solution

One of the primary problems was figuring out a queue'ing/polling model. Using crossbeam_channel was a huge unlock for me, and that allowed me to essentially create a bridge between the incoming packets (whose data are pushed to the channel) and the Bevy app (which polls the Events API) by creating a system that (asynchronously) pulls from the channel (which is registered as a resource) and writes to the Events stream.

---

## Changelog

Added two files: async_client.rs and async_server.rs

2022-12-10 00:33 UTC, james7132 requested changes
Just basic style checks for now. No comment on the content yet.

2022-12-10 00:33 UTC, james7132 commented on examples/async_tasks/async_client.rs
> +/*
These should be module level comments (i.e. `//!`) instead of C-style multiline comments.

2022-12-10 00:33 UTC, james7132 commented on examples/async_tasks/async_client.rs
> +
Please run `cargo fmt --all` to reformat this code. This will not pass CI.

2024-10-15 06:06 UTC, richchurcher commented
Backlog cleanup: closing due to inactivity. Interesting idea, perhaps worth expanding on in future.

2024-10-15 06:06 UTC, closed without merging