assets.get can take any kind of handle
bevyengine/bevy pull request #6948
Opened 2022-12-13 23:58 UTC by mockersf

# Objective

- `assets.get` can take an `Handle<T>` or an `HandleId`

## Solution

- it's using the value as a `HandleId` anyway, so just expose it as needing the trait

2022-12-14 00:49 UTC, MrGVSV approved these changes

2022-12-14 16:56 UTC, HoNile requested changes
Good but if get change I think get_mut should do the same, and I guess contains too.

2022-12-14 17:55 UTC, devil-ira commented
I'm not sure about this. This removes a type check that prevents a `Handle<Mesh>` from being passed into `Assets<Image>::get` for example.

Then again, a lot of the other methods already take `Into<HandleId>` :(

2022-12-14 19:47 UTC, IceSentry commented
Yeah, I'm with ira on that one, the typecheck seems valuable here.

2022-12-17 02:24 UTC, james7132 commented
Doesn't HandleId carry type/asset path information in it already? If we pass a `Handle<Mesh>` into a `Assets<Image>` it will always fail. Though, I guess that's a silent failure that should be caught at compile time, if possible.

2023-01-02 16:33 UTC, infmagic2047 commented
It was actually changed from `Into<HandleId>` to `Handle<T>` in #4794 for the typecheck :smile:

2023-01-03 08:17 UTC, closed without merging