MAX_DIRECTIONAL_LIGHTS must be defined to have the Lights struct
bevyengine/bevy pull request #6997
Opened 2022-12-21 11:15 UTC by mockersf

# Objective

- Fixes #6996 
- Do not fail shader compilation when `MAX_DIRECTIONAL_LIGHTS` is not defined

## Solution

- `Lights` struct is only available if `MAX_DIRECTIONAL_LIGHTS` is defined as it can't be properly sized without

2022-12-21 17:16 UTC, IceSentry commented
When running the post_processing example I get
```
2022-12-21T17:16:06.229004Z ERROR bevy_render::render_resource::pipeline_cache: failed to process shader:
error: unknown type: 'Lights'
   ┌─ wgsl:68:22
   │
68 │ var<uniform> lights: Lights;
   │                      ^^^^^^ unknown type
```

2022-12-21 18:22 UTC, mockersf commented
oh right that example was already crashing... changed to not have the `directional_lights` field then, so the struct is still present.
the `Lights` struct is used as a binding, not sure what to replace it with when `MAX_DIRECTIONAL_LIGHTS` is not available

2022-12-21 18:22 UTC, aevyrie commented
This also fixes #6799, turns out my issue was a duplicate.

2022-12-21 18:34 UTC, IceSentry commented
> not sure what to replace it with when MAX_DIRECTIONAL_LIGHTS is not available

Maybe just hardcode it to 0?

Just tested the latest commit and it works correctly for the post_processing example

2022-12-21 18:47 UTC, IceSentry approved these changes

2023-01-26 21:29 UTC, Elabajaba commented
This needs to be updated now that cascaded shadow maps has landed, if we're not going to get https://github.com/bevyengine/bevy/pull/5703 in before next release.

Getting failures on both shader_prepass and post_processing now.

```
ERROR bevy_render::render_resource::pipeline_cache: failed to process shader:
error: expected expression, found '#'
   ┌─ wgsl:38:41
   │
38 │     cascades: array<DirectionalCascade, #{MAX_CASCADES_PER_LIGHT}>,
   │                                         ^ expected expression

                                  ^ expected expression
```

2023-01-27 05:02 UTC, superdump requested changes
Does this work? It’s not obvious to me that it would but if it does, ok I guess. :) As was mentioned, the cascade also need fixing, could you do that too, please?

2023-01-27 05:02 UTC, superdump commented on crates/bevy_pbr/src/render/mesh_view_types.wgsl
> +    #ifdef MAX_DIRECTIONAL_LIGHTS
```suggestion
#ifdef MAX_DIRECTIONAL_LIGHTS
```

2023-01-27 05:02 UTC, superdump commented on crates/bevy_pbr/src/render/mesh_view_types.wgsl
> +    #endif
```suggestion
#endif
```

2023-01-27 05:41 UTC, Elabajaba commented
Made a PR to fix the issue with MAX_CASCADES_PER_LIGHT being undefined sometimes so it doesn't need to be added to this one. https://github.com/bevyengine/bevy/pull/7380

2023-01-30 04:03 UTC, superdump commented
I feel like this approach will only work if the binding isn't used. Because we comment out a member of the struct, we change its data layout. So if anything is bound, it will be misinterpreted. Same for #7380. I'm not sure how to solve it at this moment. I feel like the shader failing to compile is an indication that the use of the import should be fixed.

2023-01-30 04:46 UTC, superdump commented
I implemented what I think is a better fix in #7419

2023-01-30 23:36 UTC, closed without merging