Improve safety for `CommandQueue` internals
bevyengine/bevy pull request #7039
Opened 2022-12-27 17:41 UTC by JoJoJet

# Objective

- Safety comments for the `CommandQueue` type are quite sparse and very imprecise. Sometimes, they are right for the wrong reasons.

## Solution

- Document previously-implicit safety invariants.
- Rewrite safety comments to actually reflect the specific invariants of each operation.
- Use `OwningPtr` instead of raw pointers, to encode an invariant in the type system instead of via comments.
- Use typed pointer methods when possible to increase reliability.

2023-01-07 18:43 UTC, james7132 requested changes

2023-01-07 18:53 UTC, JoJoJet commented on crates/bevy_ecs/src/system/commands/command_queue.rs
> +            // SAFETY: Due to the call to `.reserve()` above, the buffer must be
Good point.

2023-01-07 18:53 UTC, JoJoJet commented on crates/bevy_ptr/src/lib.rs
> +    /// Must point to an aligned and fully-initialized value of type `T`.
Aren't you adding this in #7117?

2023-01-07 18:53 UTC, JoJoJet commented on crates/bevy_ecs/src/system/commands/command_queue.rs
> +    /// where `T` is some specific type that was used to produce this metadata.
The function has no requirements about alignment, so there's no need to mention it.

2023-01-08 22:31 UTC, alice-i-cecile approved these changes
This is a dramatic improvement in clarity.

2023-01-09 03:21 UTC, JoJoJet commented on crates/bevy_ecs/src/system/commands/command_queue.rs
> +        // so we'll just use a dangling pointer, which is always valid for zero-sized types.
```suggestion
        // so we'll just use a dangling pointer, which is valid for zero-sized types.
```

2023-01-18 23:12 UTC, james7132 approved these changes

2023-01-18 23:12 UTC, james7132 commented on crates/bevy_ptr/src/lib.rs
> +impl<'a> OwningPtr<'a, Unaligned> {
```suggestion

impl<'a> OwningPtr<'a, Unaligned> {
```

2023-01-19 03:04 UTC, alice-i-cecile commented
bors r+

2023-01-19 03:20 UTC, closed without merging