Add to bevy feature ```bevy_sprite``` in iOS example
bevyengine/bevy pull request #7042
Opened 2022-12-27 22:44 UTC by silvestrpredko

# Objective

I am new to Bevy. And during my development, I noticed that the `iOS` example doesn't work.
Example panics with next message: ```panicked at 'Resource requested by bevy_ui::widget::text::text_system does not exist: bevy_asset::assets::Assets```.

I have asked for help in a `discord` iOS chat and there I receive a recommendation that it is possible that some bevy features missing.

## Solution

So, I added a ```bevy_sprite``` and it fixes the problem :)

2022-12-27 23:17 UTC, alice-i-cecile approved these changes

2022-12-27 23:17 UTC, alice-i-cecile commented
Thanks for testing and the fix!

2022-12-28 00:02 UTC, mockersf requested changes
I don't think there's a reason anymore to just enable select features on iOS.

Could you enable all default features using
```
bevy = { path = "../../" }
```

2022-12-28 14:13 UTC, alice-i-cecile commented
Awesome, if this works can you update the PR description and title?

bors try

2022-12-28 14:41 UTC, mockersf approved these changes

2022-12-28 16:47 UTC, alice-i-cecile commented
bors r+

2022-12-28 16:47 UTC, alice-i-cecile commented
bors r-

2022-12-28 16:47 UTC, alice-i-cecile commented
Waiting a bit so @silvestrpredko has a chance to update the PR title :)

2022-12-28 17:00 UTC, silvestrpredko commented
> Waiting a bit so @silvestrpredko has a chance to update the PR title :)

Done, sorry for the delay. I miss updating a PR title.

2022-12-28 17:09 UTC, mockersf commented
bors r+

2022-12-28 17:20 UTC, closed without merging