Expose SystemMeta field accessors (#5497)
bevyengine/bevy pull request #7119
Opened 2023-01-07 09:58 UTC by WinstonHartnett

Adds user-facing immutable and unsafe mutable accessors to `SystemMeta` (see #5497).

2023-01-07 11:10 UTC, mockersf requested changes
the safety comments should give an indication on how to use them safely

2023-01-08 05:34 UTC, alice-i-cecile commented on crates/bevy_ecs/src/system/function_system.rs
> +    /// Set this system's last change tick.
Needs links and warnings.

2023-01-08 05:34 UTC, alice-i-cecile commented on crates/bevy_ecs/src/system/function_system.rs
> +    /// Returns this system's last change tick.
Needs links.

2023-01-08 05:36 UTC, alice-i-cecile commented on crates/bevy_ecs/src/system/function_system.rs
> +    pub fn component_access_set(&self) -> &FilteredAccessSet<ComponentId> {
These should all be `const`, along with the other methods on this type.

2023-01-08 05:37 UTC, alice-i-cecile requested changes
Wildly unsafe, but I agree that this should exist for advanced users to actually impl SystemParam manually. Needs more warnings, links and more helpful safety comments though.

2023-01-23 00:48 UTC, james7132 requested changes

2023-01-23 00:48 UTC, james7132 commented on crates/bevy_ecs/src/system/function_system.rs
> +    /// Returns the system's component access set.
```suggestion
    /// Fetches the system's component access set.
```

2023-01-23 00:48 UTC, james7132 commented on crates/bevy_ecs/src/system/function_system.rs
> +    /// Returns a mutable reference to the system's component access set.
```suggestion
    /// Fetches a mutable reference to the system's component access set.
```

2023-01-23 00:48 UTC, james7132 commented on crates/bevy_ecs/src/system/function_system.rs
> +    /// This allows unsafe modifications to the component access set that can violate Bevy's scheduling soundness.
This isn't documenting the actual safety invariant. Editing the component access set needs to accurately reflect the actual mutable and immutable accesses the system (or parameter) fetches from the World.

2023-01-23 00:48 UTC, james7132 commented on crates/bevy_ecs/src/system/function_system.rs
> +    /// This allows unsafe modifications to the archetype component access set that can violate Bevy's scheduling soundness.
This also must exactly reflect the safety invariants of using this.

2023-01-23 00:48 UTC, james7132 commented on crates/bevy_ecs/src/system/function_system.rs
> +    pub unsafe fn component_access_set_mut(&mut self) -> &mut FilteredAccessSet<ComponentId> {
The `pub(crate)` on the fields should be removed and the `bevy_ecs` uses of the access sets should use these accessors.

2023-12-15 17:13 UTC, mscofield0 commented on crates/bevy_ecs/src/system/function_system.rs
>  pub struct SystemMeta {
When this gets rebased, please also make the spans public too.

2024-10-20 02:48 UTC, closed without merging

2024-10-20 02:48 UTC, richchurcher commented
Backlog cleanup: closing due to inactivity, noting existing tracking issue #5497.