Added docs for ``.apply()``in basic usage of ``systemState``
bevyengine/bevy pull request #7138
Opened 2023-01-09 09:36 UTC by zeroacez

# Objective

Fixes #5940 

## Solution

Added the suggested comment.

2023-01-09 18:37 UTC, alice-i-cecile commented on crates/bevy_ecs/src/system/function_system.rs
> +/// // You need to manually call .apply(world) on the SystemState, to apply them.
```suggestion
/// // You need to manually call `.apply(world)` on the [`SystemState`] to apply them.
```

2023-01-09 18:37 UTC, alice-i-cecile commented on crates/bevy_ecs/src/system/function_system.rs
> +/// // If you are using Commands, you can choose when you want to apply them to the world.
```suggestion
/// // If you are using [`Commands`], you can choose when you want to apply them to the world.
```

2023-01-09 18:38 UTC, alice-i-cecile requested changes
Once those links are added and working this LGTM :)

2023-01-10 01:09 UTC, james7132 approved these changes
LGTM sans Alice's comments.

2023-01-10 15:36 UTC, alice-i-cecile commented
bors r+

2023-01-10 16:17 UTC, alice-i-cecile commented
bors retry

2023-01-10 17:24 UTC, alice-i-cecile commented
bors r+

2023-01-10 17:40 UTC, closed without merging