Expose propagate_transforms system
bevyengine/bevy pull request #7145
Opened 2023-01-10 03:53 UTC by lewiszlw

# Objective

- I tried to create a fork of bevy_rapier to track latest bevy main branch. But bevy_rapier depends on bevy internal `propagate_transforms` system (see https://github.com/dimforge/bevy_rapier/blob/master/src/plugin/plugin.rs#L64).
- `propagate_transforms` system was changed to private in https://github.com/bevyengine/bevy/pull/4775.

I don't know if it's reasonable that making `propagate_transforms` public. I also created an issue to bevy_rapier https://github.com/dimforge/bevy_rapier/issues/307 to see how offical team will solve this issue.

## Solution

- make `propagate_transforms` system public.

2023-01-10 04:05 UTC, james7132 commented
You need to use both `sync_simple_transforms` and `propagate_transforns` for a full propagation. I don't like the idea of exposing them individually, and without the system labels. Could we make the plugin non-unique and allow it to be added with different system labels?

2023-01-10 04:16 UTC, alice-i-cecile commented
Won't work unfortunately, since you can't yet control when plugin systems run.

2023-01-10 07:36 UTC, lewiszlw commented
> Could we make the plugin non-unique and allow it to be added with different system labels?

I'm trying to store stages in plugin like this,
```
pub struct TransformPlugin {
    stages: Vec<Box<dyn StageLabel>>
}
impl Default for TransformPlugin {
    fn default() -> Self {
        Self { stages: vec![Box::new(StartupStage::PostStartup), Box::new(CoreStage::PostUpdate)] }
    }
}

impl Plugin for TransformPlugin {
    fn build(&self, app: &mut App) {
        ...
        for stage in self.stages {
            app.add_system_to_stage(stage, systems::propagate_transforms.label(TransformSystem::TransformPropagate))
        }
    }

    fn is_unique(&self) -> bool {
        false
    }
}
```
There are two problems
1. Don't satisfy `Plugin`  trait bound
2. Can't pass `Box<dyn StageLabel>` to `add_system_to_stage ` method as param is `impl StageLabel`

What's your thought to allow plugin to be added with different system labels? @james7132

2023-01-10 08:38 UTC, mockersf commented
> You need to use both `sync_simple_transforms` and `propagate_transforns` for a full propagation. I don't like the idea of exposing them individually, and without the system labels.

Could we expose a single system that would run both? Not used in Bevy, just for external consumption for the case when someone wants to run global transform propagation when they want

2023-01-10 17:05 UTC, james7132 commented
> Could we expose a single system that would run both? Not used in Bevy, just for external consumption for the case when someone wants to run global transform propagation when they want

We could just have a function that returns a SystemSet. That'd allow users to do what they want with it (add it to their own stages, label them however they wish, etc).

2023-01-10 17:50 UTC, mockersf commented
> > Could we expose a single system that would run both? Not used in Bevy, just for external consumption for the case when someone wants to run global transform propagation when they want
> 
> We could just have a function that returns a SystemSet. That'd allow users to do what they want with it (add it to their own stages, label them however they wish, etc).

Sounds good! @lewiszlw could you add this function as public, and mention it in the docs or comments of `propagate_transforms` and `sync_simple_transforms`, and the docs of `GlobalTransform` (https://dev-docs.bevyengine.org/bevy/prelude/struct.GlobalTransform.html)?

2023-01-11 03:07 UTC, lewiszlw commented
> Sounds good! @lewiszlw could you add this function as public, and mention it in the docs or comments of propagate_transforms and sync_simple_transforms, and the docs of GlobalTransform (https://dev-docs.bevyengine.org/bevy/prelude/struct.GlobalTransform.html)?

Sure. I'm not very good at English, feel free to correct doc.

2023-01-11 03:28 UTC, alice-i-cecile commented on crates/bevy_transform/src/components/global_transform.rs
> +/// for complete transform propagation
```suggestion
/// to control when transforms are propagated from parents to children.
```

2023-01-11 03:28 UTC, alice-i-cecile commented on crates/bevy_transform/src/components/global_transform.rs
> +/// Third party plugin should use [`transform_propagate_system_set`](crate::transform_propagate_system_set)
```suggestion
/// Third party plugins should use [`transform_propagate_system_set`](crate::transform_propagate_system_set)
```

2023-01-11 03:29 UTC, alice-i-cecile commented on crates/bevy_transform/src/systems.rs
> +/// for complete transform propagation
```suggestion
/// to propagate transforms correctly.
```

2023-01-11 03:29 UTC, alice-i-cecile commented on crates/bevy_transform/src/systems.rs
> +/// for complete transform propagation
```suggestion
/// to propagate transforms correctly.
```

2023-01-11 03:29 UTC, alice-i-cecile commented on crates/bevy_transform/src/systems.rs
> +/// Third party plugin should use [`transform_propagate_system_set`](crate::transform_propagate_system_set)
```suggestion
/// Third party plugins should use [`transform_propagate_system_set`](crate::transform_propagate_system_set)
```

2023-01-11 03:29 UTC, alice-i-cecile commented on crates/bevy_transform/src/systems.rs
> +/// Third party plugin should use [`transform_propagate_system_set`](crate::transform_propagate_system_set)
```suggestion
/// Third party plugins should use [`transform_propagate_system_set`](crate::transform_propagate_system_set)
```

2023-01-11 03:29 UTC, alice-i-cecile requested changes
Small corrections for the docs, then this looks good to me.

2023-01-11 04:47 UTC, alice-i-cecile approved these changes

2023-01-11 18:38 UTC, james7132 approved these changes

2023-01-11 18:39 UTC, mockersf approved these changes

2023-01-11 20:59 UTC, alice-i-cecile commented
bors r+

2023-01-11 21:28 UTC, closed without merging