Merge Draw function and RenderCommand
bevyengine/bevy pull request #7172
Opened 2023-01-12 15:06 UTC by kurtkuehnert

# Objective

Currently, you can choose between `Draw` and `RenderCommand`. 
Recently we have merged PhaseItem and EntityPhaseItem. 
This PR does the same for `Draw` and `RenderCommand`. 
Are there use cases that are not covered by the RenderCommand abstraction?

- This PR is built on top of #7016.
- Draw functions can only be implemented using the RenderCommand trait.
- Hides most of the implementation specifics.

## Solution

Todo

## Changelog
Todo

## Migration Guide
Todo

2023-01-13 10:03 UTC, kurtkuehnert commented
I have updated the documentation and rebased it onto main. This PR should now be ready for review.

2023-01-13 16:03 UTC, james7132 requested changes
Please fix the CI issues. Not sure if this fully compiles or not.

2023-01-13 22:17 UTC, kurtkuehnert commented on crates/bevy_render/src/render_phase/mod.rs
> +        let render_commands = world.resource::<RenderCommands<P>>();
I am not too familiar with the ECS internals, but could we move the `RenderCommandState::prepare` logic out of the render graph? Maybe into the actual `RenderStage::Prepare`?

It seems like the only thing inside the `RenderCommandState::render` method that requires a mutable reference to self is the line: `let param = self.state.get(world);`. 
This seems linked to #7084. But there the line: `let param = self.state.get_manual(world);`, still requires a mutable reference to self. Would it be possible to change that or is `SystemState` fundamentally different from `QueryState` in this regard?

Given that we could make the render method immutable and run the prepare method before the render graph, then we could eliminate the need for the RwLock, right?

2023-01-13 22:35 UTC, kurtkuehnert commented on crates/bevy_render/src/render_phase/render_command.rs
> +        self.internal.read().get_id::<C>()
Good idea. If we figure out a way to remove the RwLock, then we can get rid of `RendeCommandsInternal` entirely.

2023-03-09 13:24 UTC, kurtkuehnert commented on crates/bevy_render/src/render_phase/draw.rs
> -    /// [`SRes::into_inner`]: bevy_ecs::system::lifetimeless::SRes::into_inner
This should not be removed.

2024-08-24 13:56 UTC, closed without merging