Add example for `Camera::viewport_to_world`
bevyengine/bevy pull request #7179
Opened 2023-01-13 15:01 UTC by devil-ira

I'll add a 2d example in a separate PR. Preferably after #6557 is merged.

2023-01-13 18:18 UTC, mockersf requested changes
could you add an example description at the tope of the example in comments?

2023-03-14 04:49 UTC, rparrett commented on examples/3d/3d_viewport_to_world.rs
> +    transform.translation = point + Vec3::Y * 0.5;
I'm wondering if this section might be somewhat magical for new users.

- `Vec3::ZERO, Vec3::Y` duplicates the position / normal of the `Plane` we built in `setup`. 
- `Vec3::Y * 0.5` duplicates the offset we defined for the cube in `setup`.

I played around with this a smidge, and I think

`intersect_plane(ground.translation, ground.up())` reads well.

Querying for `Aabb` and placing the cube based on its midpoint feels sort of messy. Maybe a `CUBE_HEIGHT` constant or something would be clearer for the example?

Or possibly just some comments would help.

2023-04-06 13:16 UTC, rparrett commented on examples/README.md
> +[3D Viewport To World](../examples/3d/3d_viewport_to_world.rs) | Use the cursor to move a cube through the scene
This description is no longer accurate.

2023-04-06 13:35 UTC, rparrett approved these changes

2023-09-09 15:01 UTC, devil-ira commented
I've added an example for 2D as well.

2023-09-09 15:33 UTC, rparrett commented on examples/3d/3d_viewport_to_world.rs
> +            })),
```suggestion
            mesh: meshes.add(Mesh::from(shape::Plane::from_size(20.))),
```

or

```rust
            mesh: meshes.add(Mesh::from(shape::Plane {
                size: 20.0,
                ..default()
            })),
```

2023-09-09 15:43 UTC, rparrett approved these changes

2023-09-09 20:34 UTC, mockersf approved these changes

2023-09-11 19:16 UTC, merged