Make Msaa a component not a resource.
bevyengine/bevy pull request #7215
Opened 2023-01-15 17:26 UTC by A-Walrus

This way it can be configured per camera.

# Objective
Make `Msaa` a component so that it can be configured per camera
Fixes #7194 
## Solution

- Change `Msaa` to a component, which is included in the camera bundles, and gets extracted in the `extract_cameras` system.
- Add `Msaa` component to camera queries, instead of getting it as a resource.
- Migrate the `Msaa` related examples to new system.

---

## Changelog

### Changed
Msaa is now a component and not a resource, to allow per-camera configuration.

## Migration Guide

In order to access `Msaa` options, use a query for the `Msaa` component which is now part of the camera bundles, instead of using a `Res(Mut)<Msaa>`.
If using a camera without a bundle, make sure to add the `Msaa` component yourself!

2023-01-15 18:00 UTC, DasLixou requested changes
When the `Camera3dBundle` already has msaa field, why do we need to insert it again? Also: is there a way to make the msaa field in the bundle an option? I don’t think everyone want it. A way to disable it by just saying:
```rust
        msaa: None,
        ..default()
    }
```
would be quite handy

2023-01-15 18:15 UTC, alice-i-cecile commented
> Also: is there a way to make the msaa field in the bundle an option

Unfortunately no, see #2157.

2023-01-15 18:19 UTC, DasLixou commented
> > Also: is there a way to make the msaa field in the bundle an option
> 
> Unfortunately no, see #2157.

That’s sad. So I see two options:
* Let the msaa be in the bundle and cleanup the examples
* Remove the msaa field and let the example as it is

2023-01-15 18:23 UTC, A-Walrus commented
> When the `Camera3dBundle` already has msaa field, why do we need to insert it again?

My bad, it was unnecessary, cleaned up now.

2023-01-15 18:27 UTC, MinerSebas commented
You disable MSAA, by setting samples to 1.
The best course of action would probably be to merge #6954, which makes it more clear how to disable it.

2023-01-15 18:29 UTC, DasLixou commented
> You disable MSAA, by setting samples to 1.
> The best course of action would probably be to merge #6954, which makes it more clear how to disable it.

Like it 👍 . Yep. Then my request can be marked as resolved

2023-01-16 05:53 UTC, IceSentry commented on crates/bevy_core_pipeline/src/core_2d/camera_2d.rs
> +            msaa: Msaa { samples: 1 },
This should use the default value

2023-01-16 05:53 UTC, IceSentry commented on crates/bevy_core_pipeline/src/core_2d/camera_2d.rs
> +            msaa: Msaa { samples: 1 },
```suggestion
            msaa: Msaa::default(),
```

2023-01-16 05:54 UTC, IceSentry commented on crates/bevy_core_pipeline/src/core_3d/camera_3d.rs
> +            msaa: Msaa { samples: 1 },
```suggestion
            msaa: Msaa::default(),
```

2023-01-16 05:56 UTC, IceSentry commented on examples/3d/msaa.rs
> +        msaa: Msaa::default(),
This is the default value, but I think this should show the full struct like the original example

```suggestion
        msaa: Msaa { sample: 4 },
```

2023-01-16 05:56 UTC, IceSentry requested changes
Couple of nits.

The implementation looks good, I'm not entirely sure this is necessary, but I'll approve it once my comments are resolved.

2023-01-16 10:50 UTC, nicopap commented
Note that this change opens up a new footgun, if the user has two different sampling rates for MSAA on the same target, it will panic, here is a minimal reproducible example:

```rust
use bevy::{core_pipeline::clear_color::ClearColorConfig, prelude::*, render::view::RenderLayers};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_startup_system(startup)
        .run();
}

fn startup(mut commands: Commands, asset_server: Res<AssetServer>) {
    commands.spawn(Camera2dBundle {
        msaa: Msaa { samples: 4 },
        camera_2d: Camera2d {
            clear_color: ClearColorConfig::Custom(Color::WHITE),
        },
        ..default()
    });
    commands.spawn((
        Camera2dBundle {
            msaa: Msaa { samples: 1 },
            camera_2d: Camera2d {
                clear_color: ClearColorConfig::None,
            },
            camera: Camera {
                order: 1,
                ..default()
            },
            ..default()
        },
        RenderLayers::layer(1),
    ));

    commands.spawn((SpriteBundle {
        texture: asset_server.load("branding/icon.png"),
        transform: Transform::from_scale(Vec3::splat(2.0)),
        ..default()
    },));
    commands.spawn((
        SpriteBundle {
            texture: asset_server.load("branding/icon.png"),
            ..default()
        },
        RenderLayers::layer(1),
    ));
}
```

2023-01-18 10:00 UTC, A-Walrus commented
@nicopap I added a check that detects and warns when multiple cameras have different `Msaa`s on the same target. Also added a note in the doc comment about the footgun.

2023-01-18 11:15 UTC, robtfm commented
> if the user has two different sampling rates for MSAA on the same target, it will panic

this is a good point, and makes me think the `Camera` entity is the wrong place for the MSAA component. 

I was about to suggest it should be on the `RenderTarget` instead, but actually there's nothing to stop people making multiple `RenderTarget`s with the same underlying target image or window so it's the same problem. so actually it should be on the `Window` and the `Image` themselves.

`Image` already has this info, (`image.texture_descriptor.sample_count`), so i guess we should use that instead of the resource when looking up msaa for a camera with a `RenderTarget::Image` target. For windows, perhaps we should wait until we have #5589 before making any changes.

2023-01-18 11:19 UTC, closed without merging