Implement texture tiling
bevyengine/bevy pull request #7406
Opened 2023-01-29 06:18 UTC by Augigogigi

# Objective

This PR attempts to implement a simpler way to tile textures.

## Solution

I set the default image sampler to always use `wgpu::AddressMode::Repeat` so all that is needed to tile textures is to change the mesh UVs, which I added a function to make easier to do. There is also a `TextureTilingSettings` struct that stores the intended tiling mode for calculating the new UVs.

---

## Migration Guide

- You have to add `.init_resource::<TextureTilingSettings>()` to the app, this should be easily removeable but I don't know how

2023-01-29 06:59 UTC, Augigogigi commented
Before this is merged can someone remove the need for `.init_resource::<TextureTilingSettings>()`? When that is gone there are no breaking changes.

2023-01-29 07:52 UTC, Augigogigi commented
> Before this is merged can someone remove the need for `.init_resource::<TextureTilingSettings>()`? When that is gone there are no breaking changes.

fixed.

2023-01-29 07:55 UTC, Augigogigi commented
There still might be a possible issue with having everything be `wgpu::AddressMode::Repeat` but I haven't encountered one.

2023-01-30 04:24 UTC, Augigogigi commented
As far as I can see, this is only tiling the base color texture (not roughness or anything else.) I will look into why.

2023-01-30 11:47 UTC, Augigogigi commented
no longer a breaking change.

2023-01-30 12:00 UTC, Augigogigi commented
unless this is gonna be merged soon it should have C-Examples too.

2023-01-30 12:20 UTC, Augigogigi commented on examples/3d/texture.rs
> +}
doesn't work in my project, my textures look like this now
![image](https://user-images.githubusercontent.com/50384127/215475221-8a33c4bb-e32d-4f19-b8af-12df377aa516.png)

2023-01-30 12:24 UTC, robtfm commented on examples/3d/texture.rs
> +}
ah right, i guess it only works for x/y quads... maybe with something to choose which position components to use as well

2023-01-30 12:44 UTC, robtfm commented on examples/3d/texture.rs
> +}
actually i'd probably just add a comment noting that for planes you want to use position[0] and position[2].

2023-01-30 14:56 UTC, Augigogigi commented on examples/3d/texture.rs
> +}
```	let mut attributes = mesh.attributes_mut().collect::<HashMap<_,_>>();
	if let (
		Some(VertexAttributeValues::Float32x2(uvs)),
		Some(VertexAttributeValues::Float32x3(positions)),
		Some(VertexAttributeValues::Float32x3(normals)),
	) = (
		attributes.remove(&Mesh::ATTRIBUTE_UV_0.id),
		attributes.remove(&Mesh::ATTRIBUTE_POSITION.id),
		attributes.remove(&Mesh::ATTRIBUTE_NORMAL.id),
	) {
		for ((position, uv), normal) in positions.iter().zip(uvs).zip(normals) {
			let x = normal[0];
			let y = normal[1];
			let z = normal[2];

			if x > y && x > z {
				uv[0] = position[1] / texture_world_space_size.0;
				uv[1] = -position[2] / texture_world_space_size.1;
			} else if y > x && y > z {
				uv[0] = position[0] / texture_world_space_size.0;
				uv[1] = -position[2] / texture_world_space_size.1;
			} else {
				uv[0] = position[0] / texture_world_space_size.0;
				uv[1] = -position[1] / texture_world_space_size.1;
			}
		}
	}```
This code almost works, the plane looks fine and the cube has just *one* face that is messed up. Any idea on how to fix?

2023-01-30 14:57 UTC, Augigogigi commented on examples/3d/texture.rs
> +}
![image](https://user-images.githubusercontent.com/50384127/215511991-5e4600ac-e137-4b8a-b348-1c6182a58642.png)

2023-01-30 15:03 UTC, Augigogigi commented on examples/3d/texture.rs
> +}
![image](https://user-images.githubusercontent.com/50384127/215513681-c80c2d39-0767-4788-a708-4606dad36666.png)
two faces*

2023-01-30 19:39 UTC, robtfm commented on examples/3d/texture.rs
> +}
to make that work you'd need to look at abs(x), abs(y) etc to see which axis the normal is on, then multiply positions by the sign of the dominant axis to correctly reflect the positions. but ... i think we are getting beyond what we want from the example - a generic world-space-scaling uv function seems pretty tricky, especially when we consider moving beyond axis-aligned planes to more complex geometry.

i think probably we should rename this function to `update_quad_uvs...`, leave a note regarding what to do for planes, and suggest using the simple scaling function for more complex geometry.

2023-01-31 07:25 UTC, Augigogigi commented on examples/3d/texture.rs
> +}
![image](https://user-images.githubusercontent.com/50384127/215693643-50d56198-ffbb-4950-a3a6-ad5f22a537ad.png)
changing it to use position[2] always seems to work fine for any quad so i just set it to do that

2023-01-31 07:31 UTC, Augigogigi commented on examples/3d/texture.rs
> +}
actually now for some reason the example no longer works, probably something to do with angles or the fact that the texture isn't a square

2023-01-31 07:41 UTC, Augigogigi commented on examples/3d/texture.rs
> +}
> a generic world-space-scaling uv function seems pretty tricky
i think its almost required to write one for planes unless we go back to the 4-arg function, so i can do that and just leave a note that the world-space one is just for planes.

2023-02-03 01:17 UTC, robtfm commented
honestly i think the world uvs function is more confusing now, it is called "plane_uvs" but we use it with `Quad`s not `Plane`s, and it is not generic for any planar mesh, it will fail if the normals point down or left or backwards.

the built in primitive `Quad`s always have x/y-plane positions so using 0 and 1 works. built in primitive `Plane`s always have x/z positions so using 0 and 2 will work. other types of mesh will need custom logic specific to the vertex positions of the mesh.

can we please go back to the simple function for quads with a comment about using positions 0 and 2 for planes?

2023-02-03 09:41 UTC, Augigogigi commented
> can we please go back to the simple function for quads with a comment about using positions 0 and 2 for planes?

done

2023-02-03 11:59 UTC, robtfm requested changes

2023-02-03 11:59 UTC, robtfm commented on examples/3d/texture.rs
> +// Update a planes's UVs so that the applied texture tiles with the calculated number of tiles,
```suggestion
// Update a quad's UVs so that the applied texture tiles with the calculated number of tiles,
```

2023-02-03 11:59 UTC, robtfm commented on examples/3d/texture.rs
> +    update_plane_uvs_for_world_space_texture_size(&mut blue_tiled_texture_mesh, (1.0, 0.25));
```suggestion
    update_quad_uvs_for_world_space_texture_size(&mut blue_tiled_texture_mesh, (1.0, 0.25));
```

2024-01-25 17:42 UTC, closed without merging