feat: improve `initialize_bundle` error message
bevyengine/bevy pull request #7464
Opened 2023-02-01 22:13 UTC by SDesya74

# Objective

This PR improves message that caused by duplicate components in bundle.

## Solution

Show names of duplicate components.

The solution is not very elegant, in my opinion, I will be happy to listen to suggestions for improving it

2023-02-01 22:21 UTC, alice-i-cecile reviewed
This is a much nicer error message. Can you check to see if it regressed performance by running benchmarks before and after? This is very hot code, and we've both added another & to its signature and introduced a branch.

2023-02-02 01:29 UTC, alice-i-cecile commented
> Will it be enough just to call cargo bench in the benches folder and compare the reports received, or do I need to perform some additional actions?

That should be just fine, but I'll defer to @james7132 for a final decision.

2023-02-02 13:48 UTC, SDesya74 commented
[criterion-before-changes.zip](https://github.com/bevyengine/bevy/files/10569498/criterion-before-changes.zip)
[criterion-after-changes.zip](https://github.com/bevyengine/bevy/files/10569500/criterion-after-changes.zip)
<img width="791" alt="Screenshot_20230202_044350" src="https://user-images.githubusercontent.com/41489405/216341839-7c3e8101-dac1-449c-ab07-25ca38be4282.png">
<img width="760" alt="Screenshot_20230202_044100" src="https://user-images.githubusercontent.com/41489405/216341847-20d16b9d-7539-47af-8e9e-1a37989820eb.png">

I'm not sure exactly where to look for the difference, so I'm giving both reports in their entirety

2023-02-02 15:19 UTC, alice-i-cecile commented
Interesting: seems to have improved performance slightly. That's very surprising to me, I'll dig in further.

2023-02-02 15:36 UTC, SDesya74 commented
Could I somehow screw up in running benchmarks to get such a result? This obviously should not be faster, the condition is absolutely the same as in the previous implementation.

2023-02-02 15:36 UTC, SDesya74 commented
Could I somehow screw up in running benchmarks to get such a result? This obviously should not be faster, the condition is absolutely the same as in the previous implementation.

2023-02-02 16:04 UTC, alice-i-cecile commented
Benchmarks are noisy: it's possible that you had different processes open. The other thing that I've seen happen is accidentally swapping before / after. Double-check that you're benchmarking in at least release mode too? Also TBH micro-optimization can be very surprising.

Good choice of key benchmark to examine though.

2023-02-02 16:38 UTC, SDesya74 commented
I ran the benchmarks a few more times, each time there were shifts in both directions within a couple of percent, without even changing the code, so this is probably noise.

So far, I have not been able to achieve any significant change in speed in either direction.

2023-02-02 16:38 UTC, SDesya74 commented
I ran the benchmarks a few more times, each time there were shifts in both directions within a couple of percent, without even changing the code, so this is probably noise.

So far, I have not been able to achieve any significant change in speed in either direction.

2023-02-02 16:46 UTC, alice-i-cecile approved these changes
Great, I'm content if there's no measurable regressions.

2023-02-03 05:49 UTC, james7132 requested changes

2023-02-03 05:49 UTC, james7132 commented on crates/bevy_ecs/src/bundle.rs
> +                components.get_info_unchecked(id).name()
```suggestion
                unsafe { components.get_info_unchecked(id).name(); }
```

2023-02-03 05:49 UTC, james7132 commented on crates/bevy_ecs/src/bundle.rs
> +        let mut seen = HashSet::new();
```suggestion
        // TODO: Replace with `Vec::partition_dedup` once https://github.com/rust-lang/rust/issues/54279 is stabilized
        let mut seen = HashSet::new();
```

2023-02-03 05:58 UTC, james7132 commented
The benchmark results also look to be within the margin of error, which makes sense since this is strictly during bundle initialization and only if there is a duplicate component, so it shouldn't be on the happy nor hot path.

2023-02-05 16:03 UTC, SDesya74 commented on crates/bevy_ecs/src/bundle.rs
> +                components.get_info_unchecked(id).name()
I committed this without a semicolon

2023-02-15 04:59 UTC, james7132 approved these changes

2023-02-15 22:44 UTC, mockersf approved these changes

2023-02-15 22:56 UTC, james7132 commented
bors r+

2023-02-15 23:12 UTC, closed without merging