Add LCH(ab) color space to `bevy_render::color::Color`
bevyengine/bevy pull request #7483
Opened 2023-02-03 08:26 UTC by ldubos

# Objective

- Fixes #766

## Solution

- Add a new `Lcha` member to `bevy_render::color::Color` enum

---

## Changelog

- Add a new `Lcha` member to `bevy_render::color::Color` enum
- Add `bevy_render::color::LchRepresentation` struct

2023-02-03 16:58 UTC, alice-i-cecile commented on crates/bevy_render/src/color/colorspace.rs
> +pub struct LchRepresentation;
Doc strings please. Links to reference materials would be particularly useful.

2023-02-03 16:59 UTC, alice-i-cecile commented on crates/bevy_render/src/color/colorspace.rs
> +    const CIE_EPSILON: f32 = 216.0 / 24389.0;
All of these magic numbers need to be sourced. A single good reference is fine, but ideal would be specific callouts.

2023-02-03 17:00 UTC, alice-i-cecile requested changes
Well-made and tested, but needs more documentation and references :)

2023-02-03 17:33 UTC, alice-i-cecile approved these changes
Thanks :)

2023-02-03 17:34 UTC, alice-i-cecile commented
@iMplode-nZ, care to review?

2023-02-03 22:30 UTC, mockersf approved these changes

2023-02-06 17:03 UTC, alice-i-cecile commented
bors r+

2023-02-06 17:51 UTC, alice-i-cecile commented
bors retry

2023-02-06 18:07 UTC, closed without merging