Refactor globals struct into own shader
bevyengine/bevy pull request #7512
Opened 2023-02-05 15:55 UTC by torsteingrindvik

fixes #6799 

# Objective

We should be able to use the `Globals` shader struct definition without being required to define unrelated shader defs.

## Solution

Refactor globals into a standalone shader without any required defs.

2023-02-05 16:12 UTC, torsteingrindvik commented
As a note: This change does not introduce any change in the engine itself since `mesh_view_types` includes the new importable shader.
But from a third-party plugin's perspective they may now directly import the new shader.

2023-02-05 18:17 UTC, IceSentry commented
I don't think this is the right direction. If you are using the default Globals struct you _need_ to use it through the mesh view bindings. If you just want the struct definition, but bind the data yourself then you are probably doing something different and should probably just define your own struct.

I'm not sure I understand when this would be useful.

2023-02-05 21:43 UTC, IceSentry commented
Oh, also, if the goal is to import only the global struct I think #5703 is a much better solution for granular imports

2023-02-05 22:27 UTC, torsteingrindvik commented
@IceSentry the use case is a third party plugin that has its own shader(s). Like you say I bind it myself.

I think it's reasonable to expect other users to want to reuse the data found in `Globals` too, and allowing the definition import makes it quite frictionless since I don't need to keep my own local definition up to date and I can just bind it via the render world resource which is already there.

I haven't look at #5703 yet.

2023-02-07 12:21 UTC, superdump commented
I think I agree with @torsteingrindvik - custom code should be able to reuse bindings and data from core. You don't have to use `mesh_view_bindings` to want to use the `Globals` uniform buffer. Same for `View`. Indeed, I would like a PR that separates out `View` into a shader import that is shared across bevy_pbr, bevy_sprite and anywhere else it is used. I think this would be a good place for the `Globals` too.

2023-02-07 21:18 UTC, torsteingrindvik commented
I tried doing the refactor to include `View`, don't have time to test it right now but I'll polish this tomorrow.

2023-02-08 17:36 UTC, torsteingrindvik commented
After the changes I tried some examples which all work, it also works for my plugin.

Waiting on review.

2023-02-11 14:49 UTC, torsteingrindvik commented
Adding 0.10 since I'd like to know if this should be in or closed before 0.10 so I know what to do with the linked issue.

2023-02-11 15:20 UTC, superdump requested changes
Minor changes but looks good. Have you tested everything continues to work correctly? So each of the renderers using View (pbr, sprite, mesh2d, ui) and something using the Globals (I think maybe there's a shader material example using the time for animation.)

2023-02-11 15:20 UTC, superdump commented on crates/bevy_sprite/src/render/sprite.wgsl
> +#import bevy_render::view
```suggestion
#import bevy_render::view

```

2023-02-11 15:20 UTC, superdump commented on crates/bevy_render/src/globals.wgsl
> +    _wasm_padding: f32
Not from your PR but:
```suggestion
    _webgl2_padding: f32
```

2023-02-11 16:48 UTC, torsteingrindvik commented
@superdump 
Applied your suggestions, and tried:

- many_sprites
- ui
- animate_shader
- pbr

all of which work well.

2023-02-11 17:37 UTC, superdump approved these changes
I just tested the mesh2d example as well and it works fine.

@robtfm has approved the PR on Discord noting that they want this to be merged regardless of their shader import / view bind group slot efforts. Noting this as it removes the possible controversiality raised by @IceSentry .

2023-02-11 17:54 UTC, alice-i-cecile approved these changes

2023-02-11 17:55 UTC, superdump commented
bors r+

2023-02-11 18:10 UTC, closed without merging