improve TextStyle document
bevyengine/bevy pull request #7578
Opened 2023-02-09 14:11 UTC by ErickMVdO

# Objective

This PR just adds a comment to improve the documentation of `font_size` field of [TextStyle](https://docs.rs/bevy/latest/bevy/prelude/struct.TextStyle.html#), informing the user that he can be surprising when using a custom scaling.

Fixes #7273.

Co-authored-by: Caio <caiocesar31951910@hotmail.com>

2023-02-09 19:57 UTC, alice-i-cecile approved these changes

2023-02-09 19:58 UTC, alice-i-cecile requested changes
Apologies, the text itself is fine (but could be clearer about the nature of the surprise), but I missed that you weren't using doc comment formatting :)

2023-02-09 19:58 UTC, alice-i-cecile commented on crates/bevy_text/src/text.rs
> +    // The size of the font in pixels. Note that this value may surprise users who have a custom scale factor set.
```suggestion
    /// The size of the font in pixels. 
    ///
    ///Note that this value may surprise users who have a custom scale factor set.
```

This needs to use doc comments, and splitting it into lines like this gives better hints / layout in IDEs.

2023-02-09 22:30 UTC, mockersf commented on crates/bevy_text/src/text.rs
> +    // The size of the font in pixels. Note that this value may surprise users who have a custom scale factor set.
you should describe how it interacts with scale factor: is it multiplied by it or does it ignore it?

2023-02-25 16:32 UTC, alice-i-cecile commented on crates/bevy_text/src/text.rs
> +    ///Note that this value may surprise users who have a custom scale factor set.
```suggestion
    /// Note that this value may surprise users who have a custom scale factor set.
```

2023-02-25 22:06 UTC, alice-i-cecile commented
> you should describe how it interacts with a custom scale factor: is it multiplied by it or does it ignore it?

Seconding this comment: I'd prefer to see this fixed before merging.

2023-08-03 08:14 UTC, closed without merging