add len, is_empty, iter method on SparseSets, make SparseSets inspect…
bevyengine/bevy pull request #7638
Opened 2023-02-12 03:36 UTC by shuoli84

…able like Table. Rename clear to clear_entities to clarify that metadata keeps, only value cleared

# Objective

- Provide some inspectability for SparseSets. 

## Solution

- `Tables` has these three methods, len, is_empty and iter too. Add these methods to `SparseSets`, so user can print the shape of storage.

---

## Changelog

> This section is optional. If this was a trivial fix, or has no externally-visible impact, you can delete this section.

- Add `len`, `is_empty`, `iter` methods on SparseSets.
- Rename `clear` to `clear_entities` to clarify its purpose.
- Add `new_for_test` on `ComponentInfo` to make test code easy.
- Add test case covering new methods.

## Migration Guide

> This section is optional. If there are no breaking changes, you can delete this section.

- Simply adding new functionality is not a breaking change.

2023-02-12 03:38 UTC, alice-i-cecile commented
Can you delete the Migration Guide section to help our automated tooling out? :) It'll get added to the list otherwise.

2023-02-12 03:40 UTC, alice-i-cecile approved these changes
Simple and useful. Adds more docs!

2023-02-12 03:40 UTC, alice-i-cecile commented on crates/bevy_ecs/src/storage/sparse_set.rs
> +    /// Create an Iterator for each [`ComponentId`] and [`SparseSet`]
It would be nice to explain that these two are paired in some form.

2023-02-12 03:40 UTC, alice-i-cecile commented on crates/bevy_ecs/src/storage/table.rs
> +    /// Returns true if this collection contains no [`Table`]
```suggestion
    /// Returns true if this collection contains no [`Table`]s
```

2023-02-12 03:41 UTC, alice-i-cecile commented on crates/bevy_ecs/src/storage/sparse_set.rs
> +    /// Returns true if this collection contains no SparseSet
```suggestion
    /// Returns true if this collection contains no [`SparseSet`]s
```

2023-02-12 03:41 UTC, alice-i-cecile commented on crates/bevy_ecs/src/storage/sparse_set.rs
> +    /// Returns the number of SparseSet this collection contains
```suggestion
    /// Returns the number of [`SparseSet`]s this collection contains
```

2023-02-12 03:41 UTC, alice-i-cecile commented on crates/bevy_ecs/src/component.rs
> +    /// Create a new ComponentInfo for test purpose
```suggestion
    /// Create a new [`ComponentInfo`] for use in tests
```

2023-02-12 03:42 UTC, alice-i-cecile commented
Comments on the docs are just nits, but do help clean things up a bit.

2023-02-13 01:32 UTC, alice-i-cecile approved these changes

2023-02-15 04:44 UTC, james7132 requested changes

2023-02-15 04:44 UTC, james7132 commented on crates/bevy_ecs/src/component.rs
> +    pub(crate) fn new_for_test(id: ComponentId, descriptor: ComponentDescriptor) -> Self {
This does the same thing as `new`. It might be better just to make it `pub(crate)` and eschew the `#[cfg(test)]`.

2023-02-15 04:44 UTC, james7132 commented on crates/bevy_ecs/src/storage/sparse_set.rs
> +    pub fn clear_entities(&mut self) {
I don't think this is publicly usable. You can't get a `&mut Storages` of any kind, cannot publicly construct `SparseSets`, and cannot get a `&mut SparseSets` from `Storages` either. We might want to make this `pub(crate)`. The same is true for the rest of the `&mut self` functions on `SparseSets`.

2023-02-15 06:53 UTC, james7132 approved these changes

2023-02-15 06:53 UTC, james7132 commented on crates/bevy_ecs/src/storage/sparse_set.rs
> +    /// Returns the number of [`SparseSet`]s this collection contains.
```suggestion
    /// Returns the number of [`ComponentSparseSet`]s this collection contains.
```

2023-02-15 06:53 UTC, james7132 commented on crates/bevy_ecs/src/storage/sparse_set.rs
> +    /// Returns true if this collection contains no [`SparseSet`]s.
```suggestion
    /// Returns true if this collection contains no [`ComponentSparseSet`]s.
```

2023-02-15 06:53 UTC, james7132 commented on crates/bevy_ecs/src/storage/sparse_set.rs
> +    /// An Iterator visiting all ([`ComponentId`], [`SparseSet`]) pairs.
```suggestion
    /// An Iterator visiting all ([`ComponentId`], [`ComponentSparseSet`]) pairs.
```

2023-02-15 06:53 UTC, james7132 commented on crates/bevy_ecs/src/storage/sparse_set.rs
> +    /// Clear entities stored in each [`SparseSet`]
```suggestion
    /// Clear entities stored in each [`ComponentSparseSet`]
```

2023-02-15 22:34 UTC, mockersf approved these changes

2023-02-15 23:51 UTC, alice-i-cecile commented
bors r+

2023-02-16 00:06 UTC, closed without merging