`CalculatedSize`'s size should not be Val
bevyengine/bevy pull request #7641
Opened 2023-02-12 11:30 UTC by ickshonpe

# Objective

`CalculatedSize` shouldn't be `Val`, it only ever stores the size in pixels of widgets. It's really confusing.

## Solution

Change the `size` field of `CalculatedSize` to a Vec2.

2023-02-12 12:07 UTC, ickshonpe commented
I think I might be getting somewhere with the text layout bugs finally. All this weird and broken stuff needs to go first.

2023-02-12 12:19 UTC, ickshonpe commented
I think I might be getting somewhere with fixing the remaining text widget problems. Need to remove all this unnecessary complexity first.

2023-02-12 19:45 UTC, alice-i-cecile requested changes
I think this needs a critical clarifying doc comment, then this LGTM.

2023-02-12 19:45 UTC, alice-i-cecile commented on crates/bevy_ui/src/ui_node.rs
>      /// The size of the node
```suggestion
    /// The size of the node in logical pixels
```

2023-02-12 21:22 UTC, mockersf approved these changes

2023-02-12 23:00 UTC, alice-i-cecile approved these changes

2023-02-13 18:16 UTC, alice-i-cecile commented
bors r+

2023-02-13 18:43 UTC, closed without merging