Create `get_resource_or_init` in `World`
bevyengine/bevy pull request #7669
Opened 2023-02-14 00:55 UTC by myreprise1

# Objective

At the moment all references to `World::get_resource_or_insert_with` are called on the resource's `default`, so a I added a small function which does that for you. This should save *some* typing.

---

## Changelog

- Added `World::get_resource_or_init`.

2023-02-14 01:14 UTC, alice-i-cecile requested changes

2023-02-14 01:14 UTC, alice-i-cecile commented on crates/bevy_ecs/src/world/mod.rs
> +        self.get_resource_or_insert_with(R::default)
IMO this should use the `FromWorld` trait, for consistency with the other init_resource methods.

2023-02-20 01:32 UTC, james7132 commented
I'm not convinced this delivers that much more than what the existing APIs provide, and the `World` API surface is already super crowded.

2023-04-22 20:45 UTC, alice-i-cecile commented
Closing out until we see a clearer need. Agreed that the `World` methods are already extremely crowded.

2023-04-22 20:45 UTC, closed without merging