Simplify generics for the `SystemParamFunction` trait
bevyengine/bevy pull request #7675
Opened 2023-02-14 16:06 UTC by JoJoJet

# Objective

The `SystemParamFunction` (and `ExclusiveSystemParamFunction`) trait is very cumbersome to use, due to it requiring four generic type parameters. These are currently all used as marker parameters to satisfy rust's trait coherence rules.

### Example (before)

```rust
pub fn pipe<AIn, Shared, BOut, A, AParam, AMarker, B, BParam, BMarker>(
    mut system_a: A,
    mut system_b: B,
) -> impl FnMut(In<AIn>, ParamSet<(AParam, BParam)>) -> BOut
where
    A: SystemParamFunction<AIn, Shared, AParam, AMarker>,
    B: SystemParamFunction<Shared, BOut, BParam, BMarker>,
    AParam: SystemParam,
    BParam: SystemParam,
```

## Solution

Turn the `In`, `Out`, and `Param` generics into associated types. Merge the marker types together to retain coherence.

### Example (after)

```rust
pub fn pipe<A, B, AMarker, BMarker>(
    mut system_a: A,
    mut system_b: B,
) -> impl FnMut(In<A::In>, ParamSet<(A::Param, B::Param)>) -> B::Out
where
    A: SystemParamFunction<AMarker>,
    B: SystemParamFunction<BMarker, In = A::Out>,
```

---

## Changelog

+ Simplified the `SystemParamFunction` and `ExclusiveSystemParamFunction` traits.

## Migration Guide

For users of the `SystemParamFunction` trait, the generic type parameters `In`, `Out`, and `Param` have been turned into associated types. The same has been done with the `ExclusiveSystemParamFunction` trait.

2023-02-14 17:25 UTC, alice-i-cecile requested changes
Much nicer. I think this is both clearer and less cumbersome.

More docs please though while we're here?

2023-02-14 17:25 UTC, alice-i-cecile commented on crates/bevy_ecs/src/system/exclusive_function_system.rs
> +    type In;
Docs on these associated types would be very nice while we're here.

2023-02-14 17:25 UTC, alice-i-cecile commented on crates/bevy_ecs/src/system/function_system.rs
> +    type In;
Docs here too.

2023-02-14 17:25 UTC, alice-i-cecile commented on crates/bevy_ecs/src/system/function_system.rs
> +    fn run(&mut self, input: Self::In, param_value: SystemParamItem<Self::Param>) -> Self::Out;
Also on run in both cases :)

2023-02-14 17:39 UTC, alice-i-cecile approved these changes

2023-02-15 18:19 UTC, james7132 approved these changes

2023-02-15 19:40 UTC, alice-i-cecile commented
bors r+

2023-02-15 20:10 UTC, closed without merging