[Merged by Bors] - expose ambiguities of `ScheduleGraph`
bevyengine/bevy pull request #7716
Opened 2023-02-16 21:36 UTC by jakobhellermann

# Objective

- other tools (bevy_mod_debugdump) would like to have access to the ambiguities so that they can do their own reporting/visualization

## Solution

- store `conflicting_systems` in `ScheduleGraph` after calling `build_schedule`

The solution isn't very pretty and as pointed out it https://github.com/bevyengine/bevy/pull/7522, there may be a better way of exposing this, but this is the quick and dirty way if we want to have this functionality exposed in 0.10.

2023-02-16 21:38 UTC, james7132 requested changes

2023-02-16 21:38 UTC, james7132 commented on crates/bevy_ecs/src/schedule/schedule.rs
> +    pub conflicting_systems: Vec<(NodeId, NodeId, Vec<ComponentId>)>,
Does this field need to be public if the accessor is as well?

2023-02-16 23:07 UTC, mockersf commented on crates/bevy_ecs/src/schedule/schedule.rs
> +
is this needed in this PR?

2023-02-17 00:01 UTC, alice-i-cecile approved these changes
bors r+

2023-02-17 00:54 UTC, closed without merging