Add len, iter on Bundles, add an example to show how to inspect a world
bevyengine/bevy pull request #7758
Opened 2023-02-20 04:18 UTC by shuoli84

# Objective

- Improve world inspectability. 

## Solution

- Add len, iter to `Bundles`, so user can get how many bundles registered in world with `world.bundles().len()`.
- Add an example to show how to inspect `World`.

The output for example like:
```bash

***************
World shape:
  component: 2
  bundle: 2
  archetype: 3
  entity: 1
World detail:
  bundles:
    BundleId(0): [ComponentId(0)]
    BundleId(1): [ComponentId(1)]
  archetypes:
    ArchetypeId(0): components:[] entity count: 0
    ArchetypeId(1): components:[ComponentId(0)] entity count: 0
    ArchetypeId(2): components:[ComponentId(0), ComponentId(1)] entity count: 1
***************
World shape:
  component: 2
  bundle: 2
  archetype: 3
  entity: 0
World detail:
  bundles:
    BundleId(0): [ComponentId(0)]
    BundleId(1): [ComponentId(1)]
  archetypes:
    ArchetypeId(0): components:[] entity count: 0
    ArchetypeId(1): components:[ComponentId(0)] entity count: 0
    ArchetypeId(2): components:[ComponentId(0), ComponentId(1)] entity count: 0

```

2023-02-20 04:21 UTC, alice-i-cecile commented
Neat, this is useful. FYI, you should use "Draft mode" for WIP PRs: it filters them more usefully for reviewers.

2023-02-21 04:05 UTC, shuoli84 commented
```bash

***************
World shape:
  component: 2
  bundle: 3
  archetype: 3
  entity: 0
  schedules: 1
    label: Bar kind:MultiThreaded
    hierachy:
    Set(0)(Some("Set1")) -> System(0)(Some("world_diagnostic::first_system"))
    Set(1)(Some("Set2")) -> System(2)(Some("world_diagnostic::empty_system"))
    Set(1)(Some("Set2")) -> System(1)(Some("world_diagnostic::second_system"))
    Set(2)(Some("BaseSet1")) -> System(0)(Some("world_diagnostic::first_system"))
    Set(3)(Some("BaseSet2")) -> System(2)(Some("world_diagnostic::empty_system"))
    Set(3)(Some("BaseSet2")) -> System(1)(Some("world_diagnostic::second_system"))
    Set(4)(Some("SystemTypeSet(\"world_diagnostic::empty_system\")")) -> System(0)(Some("world_diagnostic::first_system"))
    Set(5)(Some("SystemTypeSet(\"world_diagnostic::first_system\")")) -> System(1)(Some("world_diagnostic::second_system"))
    Set(6)(Some("SystemTypeSet(\"world_diagnostic::second_system\")")) -> System(2)(Some("world_diagnostic::empty_system"))
    dependency:
    System(1)(Some("world_diagnostic::second_system")) -> Set(6)(Some("SystemTypeSet(\"world_diagnostic::second_system\")"))
World detail:
  bundles:
    BundleId(0): [ComponentId(1)]
    BundleId(1): [ComponentId(2)]
  archetypes:
    ArchetypeId(0): components:[] entity count: 0
    ArchetypeId(1): components:[ComponentId(1)] entity count: 0
    ArchetypeId(2): components:[ComponentId(1), ComponentId(2)] entity count: 0

```

2023-02-21 15:05 UTC, shuoli84 commented
Added more details, I think it is ready to collect some ideas. 

```bash

world:
  summary:
    component: 3
    bundle: 5
    archetype: 4
    entity: 2
    resource: 2
    resource(non send): 0
    table: 3
    sparse set: 1
  detail:
    bundles:
      BundleId(0): ["ComponentId(3)(world_diagnostic::HitPoint)"]
      BundleId(1): ["ComponentId(3)(world_diagnostic::HitPoint)", "ComponentId(2)(world_diagnostic::Counter)", "ComponentId(4)(world_diagnostic::HighlightFlag)"]
      BundleId(2): ["ComponentId(2)(world_diagnostic::Counter)"]
    components:
      ComponentId(0)(bevy_ecs::schedule::schedule::Schedules) Table send_sync
      ComponentId(1)(world_diagnostic::GameState) Table send_sync
      ComponentId(2)(world_diagnostic::Counter) Table send_sync
      ComponentId(3)(world_diagnostic::HitPoint) Table send_sync
      ComponentId(4)(world_diagnostic::HighlightFlag) SparseSet send_sync
    archetypes:
      ArchetypeId(0): components:[] table:TableId(0) entity:0
      ArchetypeId(1): components:["ComponentId(3)(world_diagnostic::HitPoint)"] table:TableId(1) entity:0
      **ArchetypeId(2): components:["ComponentId(2)(world_diagnostic::Counter)", "ComponentId(3)(world_diagnostic::HitPoint)", "ComponentId(4)(world_diagnostic::HighlightFlag)"] table:TableId(2) entity:1
      ArchetypeId(3): components:["ComponentId(2)(world_diagnostic::Counter)", "ComponentId(3)(world_diagnostic::HitPoint)"] table:TableId(2) entity:1**  // notice these two archetype share same table
    tables:
      [0] entities: 0
      [1] entities: 0
      [2] entities: 2
    resources:
      ComponentId(0)(bevy_ecs::schedule::schedule::Schedules)
      ComponentId(1)(world_diagnostic::GameState)
    sparse_set:
      ComponentId(4)(world_diagnostic::HighlightFlag) entity:1
Schedule:
  schedules: 1
    label: Bar kind:MultiThreaded
  hierachy:
    nodes:
      Set(8)(SystemTypeSet("world_diagnostic::second_system"))
      Set(7)(SystemTypeSet("world_diagnostic::first_system"))
      Set(6)(SystemTypeSet("world_diagnostic::sync_counter"))
      System(2)(world_diagnostic::sync_counter)
      Set(5)(SystemTypeSet("world_diagnostic::increase_game_state_count"))
      Set(4)(SystemTypeSet("world_diagnostic::empty_system"))
      Set(3)(BaseSet2)
      Set(2)(BaseSet1)
      Set(1)(Set2)
      System(4)(world_diagnostic::second_system)
      System(3)(world_diagnostic::first_system)
      Set(0)(Set1)
      System(1)(world_diagnostic::increase_game_state_count)
      System(0)(world_diagnostic::empty_system)
    edges:
      Set(0)(Set1) -> System(1)(world_diagnostic::increase_game_state_count)
      Set(0)(Set1) -> System(0)(world_diagnostic::empty_system)
      Set(1)(Set2) -> System(4)(world_diagnostic::second_system)
      Set(1)(Set2) -> System(3)(world_diagnostic::first_system)
      Set(2)(BaseSet1) -> System(0)(world_diagnostic::empty_system)
      Set(3)(BaseSet2) -> System(4)(world_diagnostic::second_system)
      Set(3)(BaseSet2) -> System(3)(world_diagnostic::first_system)
      Set(4)(SystemTypeSet("world_diagnostic::empty_system")) -> System(0)(world_diagnostic::empty_system)
      Set(5)(SystemTypeSet("world_diagnostic::increase_game_state_count")) -> System(1)(world_diagnostic::increase_game_state_count)
      Set(6)(SystemTypeSet("world_diagnostic::sync_counter")) -> System(2)(world_diagnostic::sync_counter)
      Set(7)(SystemTypeSet("world_diagnostic::first_system")) -> System(3)(world_diagnostic::first_system)
      Set(8)(SystemTypeSet("world_diagnostic::second_system")) -> System(4)(world_diagnostic::second_system)
    topsorted:
      Set(8)(SystemTypeSet("world_diagnostic::second_system"))
      Set(7)(SystemTypeSet("world_diagnostic::first_system"))
      Set(6)(SystemTypeSet("world_diagnostic::sync_counter"))
      System(2)(world_diagnostic::sync_counter)
      Set(5)(SystemTypeSet("world_diagnostic::increase_game_state_count"))
      Set(4)(SystemTypeSet("world_diagnostic::empty_system"))
      Set(3)(BaseSet2)
      Set(2)(BaseSet1)
      Set(1)(Set2)
      System(4)(world_diagnostic::second_system)
      System(3)(world_diagnostic::first_system)
      Set(0)(Set1)
      System(1)(world_diagnostic::increase_game_state_count)
      System(0)(world_diagnostic::empty_system)
  dependency:
    nodes:
      Set(0)(Set1)
      Set(1)(Set2)
      Set(2)(BaseSet1)
      Set(3)(BaseSet2)
      System(0)(world_diagnostic::empty_system)
      Set(4)(SystemTypeSet("world_diagnostic::empty_system"))
      System(1)(world_diagnostic::increase_game_state_count)
      Set(5)(SystemTypeSet("world_diagnostic::increase_game_state_count"))
      Set(6)(SystemTypeSet("world_diagnostic::sync_counter"))
      System(2)(world_diagnostic::sync_counter)
      System(3)(world_diagnostic::first_system)
      Set(7)(SystemTypeSet("world_diagnostic::first_system"))
      Set(8)(SystemTypeSet("world_diagnostic::second_system"))
      System(4)(world_diagnostic::second_system)
    edges:
      System(1)(world_diagnostic::increase_game_state_count) -> Set(6)(SystemTypeSet("world_diagnostic::sync_counter"))
      System(3)(world_diagnostic::first_system) -> Set(8)(SystemTypeSet("world_diagnostic::second_system"))
    topsorted:
      System(4)(world_diagnostic::second_system)
      Set(7)(SystemTypeSet("world_diagnostic::first_system"))
      System(3)(world_diagnostic::first_system)
      Set(8)(SystemTypeSet("world_diagnostic::second_system"))
      System(2)(world_diagnostic::sync_counter)
      Set(5)(SystemTypeSet("world_diagnostic::increase_game_state_count"))
      System(1)(world_diagnostic::increase_game_state_count)
      Set(6)(SystemTypeSet("world_diagnostic::sync_counter"))
      Set(4)(SystemTypeSet("world_diagnostic::empty_system"))
      System(0)(world_diagnostic::empty_system)
      Set(3)(BaseSet2)
      Set(2)(BaseSet1)
      Set(1)(Set2)
      Set(0)(Set1)
  **dependency flatten:** // it is pretty clear what flatten means here.
    nodes:
      System(0)(world_diagnostic::empty_system)
      System(3)(world_diagnostic::first_system)
      System(4)(world_diagnostic::second_system)
      System(1)(world_diagnostic::increase_game_state_count)
      System(2)(world_diagnostic::sync_counter)
    edges:
      System(1)(world_diagnostic::increase_game_state_count) -> System(2)(world_diagnostic::sync_counter)
      System(3)(world_diagnostic::first_system) -> System(4)(world_diagnostic::second_system)
    topsorted:
      System(0)(world_diagnostic::empty_system)
      System(3)(world_diagnostic::first_system)
      System(4)(world_diagnostic::second_system)
      System(1)(world_diagnostic::increase_game_state_count)
      System(2)(world_diagnostic::sync_counter)

```

2023-04-22 20:34 UTC, alice-i-cecile commented on crates/bevy_ecs/examples/world_diagnostic.rs
> +fn diagnose_dag(
Non-blocking: I think this may make more sense as a method on `Dag`.

2023-04-22 20:34 UTC, alice-i-cecile commented on crates/bevy_ecs/examples/world_diagnostic.rs
> +fn component_display(component_id: ComponentId, world: &World) -> String {
This definitely makes more sense as a method on `ComponentId`.

2023-04-22 20:35 UTC, alice-i-cecile commented on crates/bevy_ecs/examples/world_diagnostic.rs
> +fn diagnostic_world(world: &World) -> Result<String, std::fmt::Error> {
This is very useful: I'd prefer to see this as a method on `World`.

2023-04-22 20:36 UTC, alice-i-cecile requested changes
Very useful stuff, but I think that these should all be methods on the corresponding types. Only being present in examples will substantially reduce how useful and discoverable these methods are.

2025-01-20 23:59 UTC, closed without merging