Added UI text wrapping example
bevyengine/bevy pull request #7761
Opened 2023-02-20 13:40 UTC by ickshonpe

# Objective

An example demonstrating more text layout options, text wrapping and `LineBreakOn`.

2023-02-20 15:31 UTC, alice-i-cecile requested changes
Looks great? Do you have PRs open to fix the remaining text wrap bugs? Could you link them here?

2023-02-20 15:31 UTC, alice-i-cecile commented on examples/ui/text_wrap.rs
> +use bevy::prelude::*;
Needs simple module level docs :)

2023-02-20 20:32 UTC, ickshonpe commented
> Looks great? Do you have PRs open to fix the remaining text wrap bugs? Could you link them here?

I've got one big patch for it I'm just cleaning up now, it's a horrible mess internally but the output looks great and, as far as I can tell, it fixes all remaining text layout bugs. I'll put in a PR tonight or tomorrow morning. It will need a lot more work and some other people's input, it makes a lot of changes and I don't really know what I'm doing.

2023-02-21 09:55 UTC, omwda requested changes
All looks good, pointed out a couple of typos that were freaking the CI. No text-wrapping behavior worked on my environment (Metal), but that's an Issue for another day.

2023-02-21 09:55 UTC, omwda commented on Cargo.toml
> +[package.metadata.example.text_wraap]
Little typo here throwing the CI, should be `[package.metadata.example.textwrap]`

2023-02-21 09:55 UTC, omwda commented on examples/ui/text_wrap.rs
> +        ..Default::default()
Other minor typo, `..default()` isn't necessary here as you've filled all the fields.

2023-02-21 18:04 UTC, ickshonpe commented
> All looks good, pointed out a couple of typos that were freaking the CI. Should also have an entry in the `examples/README.md`. No text-wrapping behavior worked on my environment (Metal), but that's an Issue for another day.

The no text-wrapping is expected as text-wrapping isn't working correctly in bevy main atm. I made this originally as a test case for finding bugs in the text implementation.

2023-02-21 18:05 UTC, ickshonpe commented
> > Looks great? Do you have PRs open to fix the remaining text wrap bugs? Could you link them here?

#7761

2023-02-21 19:33 UTC, alice-i-cecile commented
I think you meant to link https://github.com/bevyengine/bevy/pull/7779 :)

2023-02-21 19:38 UTC, ickshonpe commented
That would be be good guess.

2023-03-07 08:47 UTC, doup commented
I'm not sure about this example:
- I like it as debugging example as it helps review that the node height is correct after the line breaks are applied; specially interesting when mixed with the `Space*` cases.
- I don't like for an user, as it mixes two concepts: text wrapping and flex layout.

Otherwise, it looks great. :-)

2023-03-07 11:08 UTC, ickshonpe commented
> I'm not sure about this example:
> 
> * I like it as debugging example as it helps review that the node size is correct after the line breaks are applied; specially interesting when mixed with the `Space*` cases.
> * But I don't like it for an user, as it mixes two concepts: text wrapping and flex layout.
> 
> Otherwise, it looks great. :-)

Yep it's more of a debugging example, if you look at this in Bevy 0.9 it's a horrible mess. The space cases are especially important to get right.

Maybe there should be a separate examples section for debugging examples full of sanity checks and edge cases like this.

2023-03-07 13:19 UTC, alice-i-cecile commented
> Maybe there should be a separate examples section for debugging examples full of sanity checks and edge cases like this.

Yeah, `stress_tests` serves a similar role. `torture_tests` is probably a bit too off-color, but I'd support the creation of a similar folder, either specific to UI or in general.

2023-03-07 19:42 UTC, doup commented
Maybe just append `_debug` to the example name and state it in the example description. Like `text_debug` does?

![image](https://user-images.githubusercontent.com/188612/223534942-8d5788fe-3e52-4811-ae20-712a78b668d8.png)

2023-03-07 20:28 UTC, ickshonpe commented
> Maybe just append `_debug` to the example name and state it in the example description. Like `text_debug` does?
> 
> ![image](https://user-images.githubusercontent.com/188612/223534942-8d5788fe-3e52-4811-ae20-712a78b668d8.png)

Yep, I like that idea.

2023-03-08 11:45 UTC, ickshonpe commented
Another important use case with this example is using it to make sure that the text systems respond correctly to window resizing, which is one of the places where the previous attempts to fix text wrapping tended to fail.

2023-03-09 09:14 UTC, doup commented
I'm trying to tweak this example to use `gap/padding` for extra style points… but it breaks when width is not explicitly set. HTML/CSS correctly handles text overflow. Note that width is calculated from flex basis/shrink/grow.

I'm not sure if this is related to #7779; it might be a bug on its own.

Commit with gaps: https://github.com/doup/bevy/commit/fc0e0085c629b0caa18ad384dba9d0f3b92928aa

## Current: col width < text width

![image](https://user-images.githubusercontent.com/188612/223973773-51412351-95f8-4a70-ba76-7242f13ebb8b.png)

## With `gap`: col width > text width

Works fine 👏 (because text width is smaller than column width)
![image](https://user-images.githubusercontent.com/188612/223971174-1f963f2f-2cbe-46a3-8ea6-727d0cac4d7c.png)

## With `gap`: col width < text width

On window resize, text doesn't overflow. Column width should be smaller.
![image](https://user-images.githubusercontent.com/188612/223971771-7998b4a4-f556-4ae7-8f3e-fe8a519256b1.png)

## Sanity check with HTML/CSS

HTML example, text-overflow is handled correctly:
https://gist.github.com/doup/78710118d8e54fd89b89d587798f6452

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/188612/223972902-e35719d6-dfd5-419d-8148-6d20f200643a.png">

cc @nicoburns

2023-03-09 10:35 UTC, ickshonpe commented
I'll work on #7779 later today, 
In Bevy UI main text only wraps when you set the size width constraints of the Style component of the Text Node to `Val::Px` values. This is the function that calculates the text constraints for the text widget:

```
pub fn text_constraint(min_size: Val, size: Val, max_size: Val, scale_factor: f64) -> f32 {
    // Needs support for percentages
    match (min_size, size, max_size) {
        (_, _, Val::Px(max)) => scale_value(max, scale_factor),
        (Val::Px(min), _, _) => scale_value(min, scale_factor),
        (Val::Undefined, Val::Px(size), Val::Undefined) | (Val::Auto, Val::Px(size), Val::Auto) => {
            scale_value(size, scale_factor)
        }
        _ => f32::MAX,
    }
}
```

As can see, there's no support for percentages at all. 

The aim of this example is to include as many of the broken and unimplemented features and edge cases as possible, so we know what we've still got to fix. So anything extra you can think of to add to it is great.

2023-03-09 11:28 UTC, nicoburns commented
@doup I think this might be due to `overflow: hidden` not being handled properly (indeed Taffy currently doesn't allow you to set `overflow` at all). I think the workaround at the moment would be to set `min-width: 0` on the columns. But probably we ought to support overflow?

See https://github.com/w3c/csswg-drafts/issues/1865.

2023-03-10 08:41 UTC, doup commented
I don't understand why, but `min-width: 0` works. I've created an issue; we can follow there and stop spamming this PR.  ^_^U Btw, I've found another issue, I'll create the ticket now.

2023-04-22 20:31 UTC, alice-i-cecile approved these changes

2023-04-23 11:46 UTC, nicoburns approved these changes
I echo other comments that combining text layout with flex alignment makes this a little confusing. I'd prefer if this was just text layout options. But this generally seems fine.

2023-04-24 14:47 UTC, merged