impl `Reflect` for `std::collections::HashMap` instead of only `bevy::utils::HashMap`
bevyengine/bevy pull request #7782
Opened 2023-02-21 21:19 UTC by 13ros27

# Objective

Implement `Reflect` for `std::collections::HashMap<K, V, S>` as well as `hashbrown::HashMap<K, V, S>` rather than just for `hashbrown::HashMap<K, V, RandomState>`. Fixes #7739.

## Solution

Rather than implementing on `HashMap<K, V>` I instead implemented most of the related traits on `HashMap<K, V, S> where S: BuildHasher + Send + Sync + 'static` and then `FromReflect` also needs the extra bound `S: Default` because it needs to use `with_capacity_and_hasher` so needs to be able to generate a default hasher.

As the API of `hashbrown::HashMap` is identical to `collections::HashMap` making them both work just required creating an `impl_reflect_for_hashmap` macro like the `impl_reflect_for_veclike` above and then applying this to both HashMaps.

---

## Changelog

`std::collections::HashMap` can now be reflected. Also more `State` generics than just `RandomState` can now be reflected for both `hashbrown::HashMap` and `collections::HashMap`

2023-02-21 21:52 UTC, PROMETHIA-27 requested changes
If I'm not mistaken, bevy_utils::hashbrown::HashMap and the std one are the same type. Can you just implement on std with the appropriate bounds and cover both?

2023-02-21 21:58 UTC, 13ros27 commented
If I remove the explicit `hashbrown` impl and just leave the `collections` one it starts erroring in `bevy_input/src/gamepad` with 'the trait `Reflect` is not implemented for `bevy_utils::hashbrown::HashMap<GamepadButton, ButtonAxisSettings>`'. From what I can tell although `hashbrown` is used in rust now (since 1.36) bevy still imports `hashbrown` and re-exports that from `bevy_utils`.

2023-02-21 22:00 UTC, PROMETHIA-27 commented
I think we should probably stop using hashbrown directly then, I thought all utils was doing was swapping out the hasher, not the entire type.

2023-02-22 01:35 UTC, MrGVSV commented
> I think we should probably stop using hashbrown directly then, I thought all utils was doing was swapping out the hasher, not the entire type.

This can probably be done in a separate PR. I think this should at least solve the immediate issue of not being able to use the standard library `HashMap` with `Reflect`.

2023-02-22 01:35 UTC, MrGVSV approved these changes

2023-02-22 03:12 UTC, james7132 commented
> I think we should probably stop using hashbrown directly then, I thought all utils was doing was swapping out the hasher, not the entire type.

Currently impossible, we're using the unstable/unexposed entry API of hashbrown for performance reasons.

2023-02-27 07:15 UTC, james7132 approved these changes
Generally LGTM. The PR has quite a bit a noise due to the increased indentation, but seems to be identical sans being generic over the HashMap state type and the macro to support both hashbrown and std.

2023-02-27 13:45 UTC, PROMETHIA-27 approved these changes
LGTM

2023-02-27 21:04 UTC, james7132 commented
bors r+

2023-02-27 21:37 UTC, james7132 commented
bors retry

2023-02-27 21:54 UTC, closed without merging