Expanded the doc comment for the `padding` field of `Style`.
bevyengine/bevy pull request #7785
Opened 2023-02-22 12:30 UTC by ickshonpe

# Objective

Add a comment explaining that percentage padding is calculated based on the width of the parent node.

2023-02-22 13:41 UTC, nicoburns requested changes
This change looks good, but:

- I think it would be good to explicitly write out that this applies to even top/bottom padding
- It would be good to add the same note to margin and border

2023-02-22 15:37 UTC, ickshonpe commented
I thought borders were implemented in Bevy but not rendered and just ended up as empty space, but that doesn't seem the case like in this example:
```
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup)
        .run();
}

fn setup(mut commands: Commands) {
    commands.spawn(Camera2dBundle::default());
    let root = commands.spawn(NodeBundle {
        style: Style {
            flex_direction: FlexDirection::Column,
            flex_basis: Val::Percent(100.0),
            margin: UiRect::all(Val::Px(25.0)),
            flex_wrap: FlexWrap::Wrap,
            justify_content: JustifyContent::FlexStart,
            align_items: AlignItems::FlexStart,
            align_content: AlignContent::FlexStart,
            ..Default::default()
        },
        background_color: BackgroundColor(Color::BLACK),
        ..Default::default()
    }).id();

    for i in 0 .. 10 {
        let b = commands.spawn(NodeBundle {
            style: Style {
                size: Size::all(Val::Px(100.)),
                border: UiRect::all(Val::Px(25.0)),
                ..Default::default()
            },
            background_color: BackgroundColor(Color::BLUE),
            ..Default::default()
        }).id();

        let r = commands.spawn(NodeBundle {
            style: Style {
                size: Size::all(Val::Px(100.)),
                border: UiRect::all(Val::Percent(25.0)),
                ..Default::default()
            },
            background_color: BackgroundColor(Color::RED),
            ..Default::default()
        }).id();

        let y = commands.spawn(NodeBundle {
            style: Style {
                size: Size::all(Val::Px(100.)),
                ..Default::default()
            },
            background_color: BackgroundColor(Color::YELLOW),
            ..Default::default()
        }).id();

        let g = commands.spawn(NodeBundle {
            style: Style {
                size: Size::all(Val::Px(100.)),
                border: UiRect::all(Val::Px(250.0)),
                ..Default::default()
            },
            background_color: BackgroundColor(Color::GREEN),
            ..Default::default()
        }).id();

        let p = commands.spawn(NodeBundle {
            style: Style {
                size: Size::all(Val::Px(100.)),
                border: UiRect::top(Val::Percent(250.0)),
                ..Default::default()
            },
            background_color: BackgroundColor(Color::PURPLE),
            ..Default::default()
        }).id();
        
        let c = commands.spawn(NodeBundle {
            style: Style {
                size: Size::all(Val::Px(100.)),
                border: UiRect::all(Val::Percent(250.0)),
                ..Default::default()
            },
            background_color: BackgroundColor(Color::CYAN),
            ..Default::default()
        }).id();

        commands.entity(root).push_children(&[b, r, y, g, p, c]);    
    }
}
```

Draws the squares in a regular tessellated pattern, even though each one has a different border. Or am I missing something?

2023-02-23 10:01 UTC, ickshonpe commented
Improved the examples a bit but they aren't great.
It might nice to have the option to generate test layouts without having to go through the `flex_node_system` machinery.

The documentation for borders, I'm not sure I know how borders work. I had thought borders followed mostly the same rules as margins, except for having no automatic determination and being drawn.  As the rendering isn't implemented, they aren't useful anyway at the moment? 

Should we just have a comment saying "not implemented yet, don't use"? Or even remove the field until the implementation is ready.

2023-02-23 11:30 UTC, nicoburns commented
> Should we just have a comment saying "not implemented yet, don't use"? Or even remove the field until the implementation is ready.

IMO it ought to be removed entirely if borders aren't actually drawn. Looks like there's already an issue for actual border support https://github.com/bevyengine/bevy/issues/5924

2023-02-23 11:54 UTC, ickshonpe commented
I could implement basic solid coloured border support myself just quickly, but I'm not quite sure where to get the border geometry. 
Is it just that the node size is increased by the size of the border, and you just go inwards from each edge by the border value?

2023-02-23 12:07 UTC, nicoburns commented
> Is it just that the node size is increased by the size of the border, and you just go inwards from each edge by the border value?

You go inwards from each edge by the border value (in CSS varies depending on the `box-sizing` property. We assume `box-sizing: border-box` which is basically what "everyone" on the web uses too (it's not the default for historical reasons but the vast majority of websites are using a CSS reset which sets border-box) See: https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing

Percentage borders are not a thing on web (they are a taffy/bevy proprietary extension). They are resolved against the computed width of the *parent* node by analogy with padding/margin.

2023-02-23 12:47 UTC, ickshonpe commented
Ah, I think I understand borders after hacking out this implementation.

What I was missing is that the size of the node *only* needs to be expanded by the dimensions of the border if there are constraints that stop the layout algorithm from placing the border within the existing node boundary.

2023-02-23 16:11 UTC, nicoburns commented
> What I was missing is that the size of the node only needs to be expanded by the size of the border if there are constraints that prevent the layout algorithm from placing the border within the existing node boundary.

I believe this is correct, but that even if it does "need" to be expanded, a node won't necessarily be expanded just to accommodate a border. It's also entirely possible that the border is just clipped. An example would a node with a fixed width which is smaller than the size needed to accommodate the border.

2023-02-23 16:16 UTC, nicoburns approved these changes

2023-02-25 16:37 UTC, alice-i-cecile approved these changes
Very helpful.

bors r+

2023-02-25 16:53 UTC, closed without merging