Enable `many_buttons` to run without `bevy_text`
bevyengine/bevy pull request #8116
Opened 2023-03-17 11:19 UTC by ickshonpe

# Objective

`many_buttons` isn't a good benchmark in all cases as it draws so much text. Enable it to run with the `bevy_text` feature disabled.

## Solution

Gate all the text specific code with `#[cfg(feature = "bevy_text")]`.

---

## Changelog

* `many_buttons` can now be run with the `bevy_text` feature disabled. Use
```cargo run --example many_buttons --no-default-features --features bevy_ui,bevy_sprite,bevy_render,bevy_core_pipeline,bevy_asset,bevy_winit```

2023-03-17 15:57 UTC, mockersf commented
Rather than rely on features, several other `many_*` examples accept command line parameters to change their behaviour.

Very simple flag like in https://github.com/bevyengine/bevy/blob/52b91ac15b50ed2d1e2ed29ff987ed55af07298c/examples/stress_tests/many_cubes.rs#L52-L53

2023-03-17 16:32 UTC, ickshonpe commented
> accept command line parameters

I see, that is much simpler. Changed.

2023-03-17 18:39 UTC, mockersf approved these changes

2023-03-17 18:43 UTC, james7132 requested changes

2023-03-17 18:43 UTC, james7132 commented on examples/stress_tests/many_buttons.rs
> +    if std::env::args().nth(1).as_deref() != Some("no-text") {
This extracts the flag for every button, Could we move this outside of this function and the spawning loop?

2023-03-18 22:58 UTC, mockersf approved these changes

2023-03-18 23:20 UTC, merged