Improve UI `update_clipping_system` comments
bevyengine/bevy pull request #8147
Opened 2023-03-21 07:24 UTC by doup

# Objective

- Improve `update_clipping_system` comments

## Solution

- Add extra comments
- Reorder `CalculatedClip` updating `match` so it's reads `(old, new)` vs previous `(new, old)`
- Remove `clone` on children iteration

2023-03-21 09:56 UTC, ickshonpe requested changes
Looks good, just got a few suggestions for some other improvements.

2023-03-21 09:56 UTC, ickshonpe commented on crates/bevy_ui/src/update.rs
> +    match (old_clip, clip) {
`(old_clip, clip)` is an improvement but I think the semantics would be even clearer if you renamed `clip` as well so it's 

```suggestion
    match (old_clip, new_clip) {
```

2023-03-21 09:56 UTC, ickshonpe commented on crates/bevy_ui/src/update.rs
>      }
I was going to suggest to use `set_if_neq` but then I checked and we never actually query for changes in `CalculatedClip` so the neq gate is unnecessary: 

```suggestion
        (Some(mut old_clip), Some(clip)) =>  *old_clip = CalculatedClip { clip },
    }
```

2023-03-21 09:56 UTC, ickshonpe commented on crates/bevy_ui/src/update.rs
>              let node_center = global_transform.translation().truncate();
There is a helper function for this now:
```suggestion
            let node_clip = node.logical_rect(global_transform);
```

2023-03-21 10:19 UTC, ickshonpe requested changes

2023-03-21 10:19 UTC, ickshonpe commented on crates/bevy_ui/src/update.rs
>      clip: Option<Rect>,
This parameter could be renamed to make clear that the clipping `Rect` is inherited from the node's parent:

```suggestion
   maybe_inherited_clip: Option<Rect>,
```

2023-03-21 10:19 UTC, ickshonpe commented on crates/bevy_ui/src/update.rs
> +    let (node, global_transform, style, old_clip) = node_query.get_mut(entity).unwrap();
I think `maybe_calculated_clip` is better than `old_clip`, makes it clearer it's an optional smart pointer to the component.

```suggestion
    let (node, global_transform, style, maybe_calculated_clip) = node_query.get_mut(entity).unwrap();
```

2023-03-21 10:19 UTC, ickshonpe commented on crates/bevy_ui/src/update.rs
>              commands.entity(entity).insert(CalculatedClip { clip });
```suggestion
        (None, Some(inherited_clip)) => {
            commands.entity(entity).insert(CalculatedClip { clip: inherited_clip });
```

2023-03-21 10:19 UTC, ickshonpe commented on crates/bevy_ui/src/update.rs
> +        (Some(mut old_clip), Some(clip)) => {
```suggestion
        (Some(mut calculated_clip), Some(inherited_clip)) => {
```

2023-03-21 10:30 UTC, ickshonpe commented
#8095 that is very related needs some reviews, be grateful if you have a few minutes spare to look at it.

2023-03-22 07:16 UTC, doup commented
Thanks for the comments! I was going to review them, but suddenly I'm getting a segfault out of nowhere. So frustrating. The good thing is that I can learn how this kind of stuff is debugged.

Anyway, sure I can check #8095. Btw, I want to review more UI PRs (mostly yours and nico's), but first I want to finish reading the UI related code. I did few reviews last couple of weeks but I realized I was lacking understanding. ^_^

2023-03-22 20:08 UTC, doup commented
@ickshonpe I've applied most of the suggestions. I think I'm going to skip https://github.com/bevyengine/bevy/pull/8147#discussion_r1143108441 I prefer not to touch that part. In any case, I've asked about it in #8095, we can follow there.

2023-03-22 23:34 UTC, mockersf approved these changes

2023-03-24 00:46 UTC, ickshonpe approved these changes

2023-03-28 20:17 UTC, james7132 approved these changes

2023-03-28 20:42 UTC, merged