Constrain values in uniform buffers to `ShaderSize`.
bevyengine/bevy pull request #8352
Opened 2023-04-10 23:29 UTC by konsolas

# Objective

Fixes #8351 

## Solution

- Replace ShaderType with ShaderSize in relevant files.

---

## Changelog

- Values written to uniform buffers are checked to ensure they are fixed-size at compile time.

## Migration Guide

- If you `#[derive(ShaderType)]`, no changes are needed because this derive automatically implements `ShaderSize` on acceptable types.
- If you explicitly use `ShaderType` as a trait bound, this should be changed to `ShaderSize` if the type will be written to a uniform buffer, as appropriate.

2023-04-10 23:52 UTC, james7132 approved these changes

2023-04-11 07:05 UTC, superdump commented
I need to check whether this will work with the hacky approaches to trailing pseudo-variable length arrays - where an array is fixed size but you fill fewer than the maximum number of elements and then start the next dynamic offset binding as soon as possible after the last valid element.

2023-04-12 20:40 UTC, konsolas commented
> I need to check whether this will work with the hacky approaches to trailing pseudo-variable length arrays - where an array is fixed size but you fill fewer than the maximum number of elements and then start the next dynamic offset binding as soon as possible after the last valid element.

Is it currently possible to do this with bevy's DynamicUniformBuffer? It seems like the dynamic offset is not controllable by client code.

If this 'hacky' approach is only possible by using lower-level (wgpu) APIs, it shouldn't be affected by a change to a bevy abstraction over these APIs.

2024-08-16 23:01 UTC, tychedelia requested changes
I think this makes sense but we should probably use the same logic for all the buffer types too which are currently `T: ShaderType`. Will approve after merge conflicts.

2026-03-30 15:51 UTC, NthTensor commented
This PR appears to have gone stale. Nominating to close.

2026-05-21 11:14 UTC, closed without merging