Make setup of Opaque3dPrepass and AlphaMask3dPrepass phase items consistent with others
bevyengine/bevy pull request #8408
Opened 2023-04-16 21:41 UTC by Sixmorphugus

# Objective

When browsing the bevy source code to try and learn about `bevy_core_pipeline`, I noticed that the DrawFunctions resources, `sort_phase_system`s and texture preparation for the `Opaque3d` and `AlphaMask3d` phase items are all set up in `bevy_core_pipeline`, while the `Opaque3dPrepass` and `AlphaMask3dPrepass` phase items are only *declared* in `bevy_core_pipeline`, and actually registered properly with the renderer in `bevy_pbr`.

This means that, if I am trying to make crate that replaces `bevy_pbr`, I need to make sure I manually fix this unfinished setup the same way that `bevy_pbr` does. Worse, it means that if I try to use the `PrepassNode` `bevy_core_pipeline` adds *without* fixing this, the engine will simply crash because the `DrawFunctions<T>` resources cannot be accessed.

The only advantage I can think of for bevy doing it this way is an ambiguous performance save due to the prepass render phases not being present unless you are using prepass materials with PBR.

## Solution

I have moved the registration of `DrawFunctions<T>`, `sort_phase_system::<T>`, camera RenderPhase extraction, and texture preparation for prepass's phase items into `bevy_core_pipeline` alongside the equivalent code that sets up the `Opaque3d`, `AlphaMask3d` and `Transparent3d` phase items.

Am open to tweaking this to improve the performance impact of prepass things being around if the app doesn't use them if needed.

I've tested that the `shader_prepass` example still works with this change.

2023-04-16 21:49 UTC, Sixmorphugus commented
Fixing unused imports rn

2023-04-21 06:55 UTC, nicopap requested changes
Actually, `apply_normal_mapping` is used in `pbr_prepass.wgsl` at line 98, you should update that file to use the new argument list.

The reason it compiles is that the `shader_prepass.rs` example doesn't have a normal map, so the `#ifdef` removes the code from the file, and there is no opportunity to create a shader compilation error since the code is never compiled.

2023-04-21 09:10 UTC, Sixmorphugus commented
> Actually, `apply_normal_mapping` is used in `pbr_prepass.wgsl` at line 98, you should update that file to use the new argument list.
> 
> The reason it compiles is that the `shader_prepass.rs` example doesn't have a normal map, so the `#ifdef` removes the code from the file, and there is no opportunity to create a shader compilation error since the code is never compiled.

I'm not sure what you mean, I've pulled changes just now and the argument list hasn't changed.

2023-04-21 09:24 UTC, nicopap commented
I mistook this PR for #8106 :sweat_smile: How embarrassing. Everything is good

2023-04-21 09:24 UTC, nicopap approved these changes

2023-06-11 19:39 UTC, IceSentry approved these changes
LGTM, sorry for not reviewing this sooner.

2023-06-12 19:40 UTC, merged