Prevent Zero Duration with Runtime Check in Timer
bevyengine/bevy pull request #8591
Opened 2023-05-11 05:41 UTC by Connor-McMillin

# Objective

- Fixes #8477 

## Solution

- Create a new `NonZeroDuration` struct which ensures duration is never zero by panicing at runtime when it encounters a zero duration 

---

2023-05-30 22:49 UTC, alice-i-cecile commented on crates/bevy_time/src/timer.rs
> +    pub fn new(duration: Duration) -> Self {
This needs doc strings, and a #Panics section.

2023-05-30 22:50 UTC, alice-i-cecile commented on crates/bevy_time/src/timer.rs
> +/// and removes the need for repeated runtime checks for zero duration in `tick()`
`tick` should have a doc link so we can tell when this comment is outdated.

2023-05-30 22:53 UTC, alice-i-cecile commented on crates/bevy_time/src/timer.rs
> +    fn fail_me() {
```suggestion
    fn zero_duration_nonzero_duration_panics() {
```

2023-05-30 22:54 UTC, alice-i-cecile requested changes
I really like this solution, and the code changes look great. Just a few things to clean up.

2023-05-31 23:50 UTC, alice-i-cecile commented on crates/bevy_time/src/timer.rs
> +/// Ensures that `duration` is never zero when being used in Timer. This simplifies edge cases
```suggestion
/// A new-typed [`Duration`] that is never [`Duration::ZERO`].
///
/// Interally, this snsures that `duration` is never zero when being used in [`Timer`]. This simplifies edge cases
```

2023-05-31 23:52 UTC, alice-i-cecile requested changes
Slightly better docs explaining the meat of "what is a NonZeroDuration" better for users who run into this. Then, LGTM!

Sorry for missing this in the last pass.

2023-06-01 15:12 UTC, Connor-McMillin commented
Awesome, thanks! I just accepted that doc change

2023-06-01 16:27 UTC, alice-i-cecile approved these changes

2023-06-01 17:03 UTC, MrGVSV commented on crates/bevy_time/src/timer.rs
> +/// and removes the need for repeated runtime checks for zero duration in [Timer::tick](Timer::tick)
Would this work?
```suggestion
/// and removes the need for repeated runtime checks for zero duration in [`Timer::tick`]
```

2023-06-01 17:03 UTC, MrGVSV commented on crates/bevy_time/src/timer.rs
> +#[reflect(Default)]
Nit: We could also register `PartialEq` and `ReflectFromReflect`

2023-06-01 17:03 UTC, MrGVSV commented on crates/bevy_time/src/timer.rs
> +impl NonZeroDuration {
I think this impl should have a `get` or `value` or some other method for accessing the inner duration (similar to the NonZero*** types)

2023-06-01 17:08 UTC, MrGVSV commented on crates/bevy_time/src/timer.rs
>      /// Creates a new timer with a given duration.
This doc comment should also include a `Panics` section as well

2023-06-01 17:13 UTC, MrGVSV commented on crates/bevy_time/src/timer.rs
> +    pub fn new(duration: Duration) -> Self {
I think that makes sense. Then we only panic in the places where it needs to be unwrapped, like in `Timer`

2023-06-02 02:26 UTC, Gingeh commented
I think that (if possible) we shouldn't impl `Default` for `NonZeroDuration` as there isn't really an 'obvious' value to use.

2026-05-22 08:20 UTC, closed without merging