Add FromReflect where Reflect is used
bevyengine/bevy pull request #8776
Opened 2023-06-07 17:43 UTC by raffaeleragni

# Objective

Discovered that PointLight did not implement FromReflect. Adding FromReflect where Reflect is used. I overreached and applied this rule everywhere there was a Reflect without a FromReflect, except from where the compiler wouldn't allow me.

Based from question: https://github.com/bevyengine/bevy/discussions/8774

## Solution

- Adding FromReflect where Reflect was already derived

## Notes

First PR I do in this ecosystem, so not sure if this is the usual approach, that is, to touch many files at once.

2023-06-07 18:55 UTC, MrGVSV requested changes
Thanks for doing this!

One thing I think needs to be added are `ReflectFromReflect` registrations for all of these types. This is added the same way as `ReflectComponent` and other type data:

```rust
#[derive(Reflect, FromReflect)]
#[reflect(FromReflect)]
struct MyType;
```

2023-06-07 18:55 UTC, MrGVSV commented on crates/bevy_reflect/src/lib.rs
> +        #[derive(Hash, PartialEq, Reflect, FromReflect)]
This doesn't need `FromReflect` since it's a test (and sometimes deriving `FromReflect` could break the robustness of the test).

2023-06-07 18:55 UTC, MrGVSV commented on crates/bevy_reflect/src/lib.rs
> +        #[derive(Clone, Hash, PartialEq, Reflect, FromReflect)]
Same here, this should be removed.

2023-06-07 19:38 UTC, raffaeleragni commented on crates/bevy_reflect/src/lib.rs
> +        #[derive(Clone, Hash, PartialEq, Reflect, FromReflect)]
ok changed both back

2023-06-07 20:04 UTC, raffaeleragni commented
Now also added the ReflectFromReflect

2023-06-07 21:03 UTC, raffaeleragni commented
Now it seems to error, unclear why tho.

2023-06-07 21:28 UTC, raffaeleragni commented
Ok, should be fixed now.

2023-06-08 07:15 UTC, MrGVSV approved these changes
LGTM! Glad to see `FromReflect` in more places 😄

2023-06-08 21:06 UTC, raffaeleragni commented
How do we know that these are all the needed ones?
All I could do was finding them via search, but it's a long list.

A couple of ones also could not derive FromReflect, anything to do with those?

2023-06-09 05:21 UTC, MrGVSV commented
> How do we know that these are all the needed ones? All I could do was finding them via search, but it's a long list.
> 
> A couple of ones also could not derive FromReflect, anything to do with those?

Hm, I'm not sure. We should get a couple more reviews to make sure we're not being overzealous in certain places or possibly even breaking/missing something.

2023-06-09 05:23 UTC, MrGVSV commented
Also, I should make it clear that this PR would be a temporary solution until #6056 is merged (which, honestly, could come before or after 0.11).

2023-06-09 06:12 UTC, raffaeleragni commented
Sure, all I need right now is that some components are not deriving FromReflect, not necessarily ReflectFromReflect, because it's blocking something I am writing. If that comes first I can still continue either way.

2023-06-19 16:04 UTC, alice-i-cecile approved these changes

2023-06-19 16:43 UTC, merged