Add documentation to note that `FrameTimeDiagnosticsPlugin` must be added after `DiagnosticsPlugin`
bevyengine/bevy pull request #8785
Opened 2023-06-08 01:42 UTC by opstic

# Objective

- `FrameTimeDiagnosticsPlugin` does not currently have docs to explain that it must be added after `DiagnosticsPlugin`

## Solution

- Add documentation for it

2023-06-08 01:47 UTC, alice-i-cecile commented on crates/bevy_diagnostic/src/frame_time_diagnostics_plugin.rs
> +/// Must be added after [`DiagnosticsPlugin`]
```suggestion
///
/// # Warning
///
/// Must be added after [`DiagnosticsPlugin`] or a panic will occur due to missing resources.
```

2023-06-08 01:48 UTC, alice-i-cecile requested changes
Formatting / style nit + more clarity on why the panic occurs, then LGTM.

2023-06-08 12:09 UTC, alice-i-cecile approved these changes

2023-06-08 22:19 UTC, mockersf commented
If we add this doc for `FrameTimeDiagnosticsPlugin`, it should be added to all the other diagnostics plugins:
- `AssetCountDiagnosticsPlugin`
- `EntityCountDiagnosticsPlugin`
- `SystemInformationDiagnosticsPlugin`

2023-06-10 10:05 UTC, mockersf approved these changes

2023-06-10 22:55 UTC, mockersf commented
see https://github.com/bevyengine/bevy/pull/8783#issuecomment-1585842232

2023-06-11 03:13 UTC, alice-i-cecile approved these changes

2023-06-11 16:11 UTC, opstic commented
Closing in favor of #8819

2023-06-11 16:11 UTC, closed without merging