Added Has<T> WorldQuery type
bevyengine/bevy pull request #8844
Opened 2023-06-14 19:27 UTC by wainwrightmark

# Objective

- Fixes #7811 

## Solution

- I added `Has<T>` (and `HasFetch<T>` ) and implemented `WorldQuery`, `ReadonlyWorldQuery`, and `ArchetypeFilter` it
- I also added documentation with an example and a unit test

I believe I've done everything right but this is my first contribution and I'm not an ECS expert so someone who is should probably check my implementation. I based it on what `Or<With<T>,>`,  would do. The only difference is that `Has` does not update component access - adding `Has` to a query should never affect whether or not it is disjoint with another query *I think*.

---

## Changelog

## Added
- Added `Has<T>`  WorldQuery to find out whether or not an entity has a particular component.

2023-06-15 01:21 UTC, alice-i-cecile commented on crates/bevy_ecs/src/query/fetch.rs
> +/// Returns whether each entity has component `T`.
```suggestion
/// Returns a bool that describes if the entity has component `T`.
```

2023-06-15 01:24 UTC, alice-i-cecile requested changes
Nice! I've often wanted this.

Can we have a couple more tests to verify that the accesses are set up correctly? We should be able to do  Have + &mut in two queries in the same system.

Perhaps as a doc test: this is a nice property to teach about.

2023-06-15 13:47 UTC, alice-i-cecile commented on crates/bevy_ecs/src/query/fetch.rs
> +/// fn alphabet_entity_system(mut alphas: Query<(&mut Alpha, Has<Beta>)>, mut betas: Query<(&mut Beta, Has<Alpha>)>) {
```suggestion
/// // Unlike `Option<&T>`, `Has<T>` is compatible with `&mut T` 
/// // as it does not actually access any data.
/// fn alphabet_entity_system(mut alphas: Query<(&mut Alpha, Has<Beta>)>, mut betas: Query<(&mut Beta, Has<Alpha>)>) {
```

2023-06-15 16:29 UTC, wainwrightmark commented on crates/bevy_ecs/src/query/fetch.rs
> +        _fetch.matches = _table.has_column(*_state);
Thanks

2023-06-15 20:42 UTC, JoJoJet approved these changes

2023-06-15 20:42 UTC, JoJoJet commented on crates/bevy_ecs/src/query/fetch.rs
> +/// Returns a bool that describes if the entity has component `T`.
```suggestion
/// Returns a bool that describes if an entity has the component `T`.
```

2023-06-15 21:04 UTC, Aceeri approved these changes

2023-06-15 23:07 UTC, alice-i-cecile commented
@wainwrightmark can you try out the suggestion from James and report back? Once that's done (success or failure), I'm happy to merge this and ship it for 0.11 :)

2023-06-16 08:46 UTC, wainwrightmark commented
Replacing `HasFetch<T>` with `bool` worked great!

2023-06-19 05:36 UTC, wainwrightmark commented
I realize I have made a mistake in making `Has<T>` and `ArcheTypeFilter` - it's technically true in a sense but completely unhelpful as you should never be using it in a filter position. I've reverted this.

2023-06-19 13:56 UTC, alice-i-cecile approved these changes

2023-06-19 14:20 UTC, merged