Fix black spots appearing due to NANs when SSAO is enabled
bevyengine/bevy pull request #8926
Opened 2023-06-22 05:47 UTC by Elabajaba

# Objective

Fixes https://github.com/bevyengine/bevy/issues/8925

## Solution

Clamp the bad values.

2023-06-22 06:26 UTC, Elabajaba commented on crates/bevy_pbr/src/render/pbr_lighting.wgsl
> +    LoH = clamp(saturate(dot(L, H)), 0.0, 1.0);
[Filament docs](https://google.github.io/filament/Filament.md.html#materialsystem/standardmodelsummary) and the [khronos GLTF sample viewer](https://github.com/KhronosGroup/glTF-Sample-Viewer/blob/47a191931461a6f2e14de48d6da0f0eb6ec2d147/source/Renderer/shaders/pbr.frag#L202) both seem to clamp all of these, so I just added clamps to them to be safe.

2023-06-22 06:27 UTC, Elabajaba commented on crates/bevy_pbr/src/render/pbr_functions.wgsl
> +    let NdotV = clamp(dot(in.N, in.V), 0.0001, 1.0);
This is the important clamp to fix the black spots.

2023-06-22 06:44 UTC, Elabajaba commented
Another option that fixes it is to wrap `prepass_normal()` here https://github.com/bevyengine/bevy/blob/bb59509d44d2979e4b91bd0f998c047f16b89dd0/crates/bevy_pbr/src/render/pbr.wgsl#L121 with `normalize()`

2023-06-22 14:04 UTC, JMS55 commented on crates/bevy_pbr/src/render/pbr_lighting.wgsl
> +    NoH = clamp(saturate(dot(N, H)), 0.0, 1.0);
Saturate already clamps between [0, 1]. Adding another clamp does nothing here.

2023-06-22 20:41 UTC, Elabajaba commented on crates/bevy_pbr/src/render/pbr_lighting.wgsl
> +    LoH = clamp(saturate(dot(L, H)), 0.0, 1.0);
Removed as they're redundant

2023-06-22 20:51 UTC, Elabajaba commented
I changed it to just normalize the `prepass_normal()` return value to avoid any potential loss of data from clamping.

We do this for `apply_normal_mapping()` when the prepass normals aren't used here https://github.com/bevyengine/bevy/blob/c6170d48f91357b5ed8ebb167b33d3cfa9688a6d/crates/bevy_pbr/src/render/pbr_functions.wgsl#L107

2023-06-23 02:09 UTC, JMS55 approved these changes

2023-06-23 02:45 UTC, alice-i-cecile approved these changes

2023-06-23 13:54 UTC, superdump requested changes
As mentioned on Discord, I think this solution is probably not the best choice.

The prepass normals are stored in an Rgb10a2Unorm texture. That means the values must be in the range [0,1] in the texture. I’m not certain but I think any values outside of that range would be clamped to that range.

Clamping is a problem because it changes the direction of the normal, which is undesirable for lighting. Normalising is probably a better choice.

Mikktspace says that when using normal mapping, you are not supposed to normalise the vertex normal, nor the interpolated vertex normal in order to obtain an exact inverse of the normal map baking process. You only normalise the normal-mapped normal which is the one used for lighting. This is done at the end of apply_normal_mapping.

So, the problem here is that mikktspace would potentially allow normals that don’t fit in Rgb10a2Unorm, and would be clamped, and then perhaps also that the world normal is not normalised.

I think then maybe the best thing to do is to go against the mikktspace recommendations and normalise the world normal before writing to the texture. I’m not certain of this but I’d say until we have clarity on what to do, this is possibly a bit controversial.

On the other hand, it is better than stuff doesn’t look broken so maybe we should add a FIXME comment to this, merge it, and continue figuring out how best to address it.

2023-06-23 18:37 UTC, Elabajaba commented
@superdump sorry, I forgot to update the PR description.

I removed all the clamps, and this just normalizes the `prepass_normal()` call.

2023-06-26 18:00 UTC, IceSentry commented
> We do this for apply_normal_mapping() when the prepass normals aren't used here

Unless something else changed, the prepass already calls `apply_normal_mapping()` so the results should already be normalized. If they aren't it might mean there's a missing shader def in the prepass or something.

2023-06-26 18:53 UTC, IceSentry commented
Also, I think this shouldn't be done in `prepass_normals()` but should be done at the callsite. The normal texture can be generated by a custom material and normalizing there might not be what user expects. So I'd just do it directly in pbr.wgsl.

2023-06-26 19:34 UTC, IceSentry commented
It was pointed out on discord that this happens because of precision issues even if the normals are normalized in the prepass. So it makes sense to do it like this. So you can ignore my comments.

2023-06-27 18:53 UTC, IceSentry approved these changes

2023-06-27 20:33 UTC, alice-i-cecile commented
@superdump are you okay if we merge this?

2023-07-01 19:42 UTC, fintelia commented
The `saturate` method is defined as: 
> Returns `clamp(e, 0.0, 1.0)`. [Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

So it doesn't seem to make much sense to do `clamp(saturate(...), 0.0, 1.0)`...

2023-07-01 19:43 UTC, fintelia approved these changes

2023-07-01 21:28 UTC, superdump approved these changes
After some more discussions on discord and here, I’m fine with this solution.

2023-07-01 21:53 UTC, merged