Prevent setting parent as itself
bevyengine/bevy pull request #8980
Opened 2023-06-28 04:55 UTC by lewiszlw

# Objective

- Fixes https://github.com/bevyengine/bevy/issues/8979.

## Solution

- Panic when parent and child are same entity.

2023-06-28 05:11 UTC, farend-east commented
The fix must also apply to `InsertChildren` `PushChildren` and `ReplaceChildren`

2023-06-28 06:18 UTC, lewiszlw commented
> The fix must also apply to `InsertChildren` `PushChildren` and `ReplaceChildren`

Added!

2023-06-28 06:46 UTC, nicopap commented
This doesn't solve the problem for the `EntityMut` methods. Those methods are called in the functions you modified, so you can just move the check to the `EntityMut` methods.

In this `impl` block:

```rust
impl<'w> BuildWorldChildren for EntityMut<'w> {
```

With regard to `EntityCommand` implementations, Adding a panic in the `commands` methods would be ideal, so that the panic occurs, the backtrace shows exactly what code caused the issue.

Add the panic in the relevant functions in this `impl` block:

```rust
impl<'w, 's, 'a> BuildChildren for EntityCommands<'w, 's, 'a> {
```

The current change only solves the issue for parents inserted through commands, and has poor backtraces.

2023-06-28 10:46 UTC, nicopap commented
> We still need the same logic for EntityCommands as this is where the user will mainly call from commands.

Technically, the commands then later will call the `EntityMut` methods with the same parameters, so it will panic. But I think they should be added to `EntityCommands` regardless.

I would strongly advise to add the check in the `EntityCommands` extension methods. Have you ever hit the "couldn't despawn entity, it is already despawned" error? It's so annoying, and it's basically impossible to know what code caused it.

This is because the panic is located in a different system than the one that triggered the despawn.

Pushing the panic in the `EntityCommands` extension methods will make the panic run within the system that tries to add the parent as child, as a result, the system will be included in the backtrace. With this, it's trivial for the bevy user to find where the error happens and fix it. Without it, it can become a struggle to figure out how to avoid the panic.

2023-06-28 10:52 UTC, lewiszlw commented
> I would strongly advise to add the check in the EntityCommands extension methods. Have you ever hit the "couldn't despawn entity, it is already despawned" error? It's so annoying, and it's basically impossible to know what code caused it.

make sense.

2023-06-29 12:53 UTC, alice-i-cecile approved these changes
I don't love adding more ways for commands to panic, but I think that surfacing the error early when the command is initialized is ultimately a nicer UX.

2023-06-29 20:39 UTC, mockersf requested changes
Some of those panics are added not in the commands execution, but in the command creation, so while we could still return a result.

If we want to panic in those methods, a panic section should be added to their docs

2023-07-03 09:05 UTC, lewiszlw commented
Added panics doc

2023-08-03 14:36 UTC, nicopap approved these changes

2023-08-07 23:24 UTC, merged