Optional UI rendering
bevyengine/bevy pull request #8997
Opened 2023-06-29 11:53 UTC by ickshonpe

# Objective

Make UI rendering optional.

Quite a few people have been experimenting with using Bevy UI for layout and interaction but replacing the rendering with `bevy_prototype_lyon` or whatever. It's awkward to do though as there is no way to disable the existing UI rendering requiring users to create their own custom node bundles and components. Also, you can't replace the UI's shader and a number of other things.

This PR makes the setup and initialization of UI rendering for the RenderApp optional. Then you can do whatever you want by replacing `build_ui_render` with your own function. For instance, one that loads a custom shader.

The UI layout and interaction components are still updated as normal.

## Solution

Add a field `disable_ui_rendering` to `UiPlugin.
Only call `build_ui_render` and initialize the `UiPipeline` if `disable_ui_rendering` is false.

I thought about implementing a "bevy_ui_render" feature but suspect everything is too tightly coupled atm and it would be very fragile similar to the problems with "bevy_text" but worse.

---

## Changelog

  `UiPlugin`
  * Added a bool field `disable_ui_rendering`.
  * Only calls `build_ui_render` and initializes the `UiPipeline` if `disable_ui_rendering` is false.

## Migration Guide

`UiPlugin` has a new field `disable_ui_rendering`. If set to true, UI rendering won't be added to the `RenderApp` and the UI will not be shown.

2023-06-29 12:47 UTC, alice-i-cecile approved these changes
> I thought about implementing a "bevy_ui_render" feature but suspect everything is too tightly coupled atm and it would be very fragile. Similar to the struggles with the "bevy_text" feature but worse.

I would prefer this solution, especially in the long run, but the struggles are entirely plausible. We *should* work towards decoupling things here though.

2023-06-29 13:36 UTC, ickshonpe commented
> > I thought about implementing a "bevy_ui_render" feature but suspect everything is too tightly coupled atm and it would be very fragile. Similar to the struggles with the "bevy_text" feature but worse.
> 
> I would prefer this solution, especially in the long run, but the struggles are entirely plausible. We _should_ work towards decoupling things here though.

Definitely agree. My preference I think would be to move the UI renderer into its own crate.

2023-06-30 09:10 UTC, nicoburns commented
> Similar to the struggles with the "bevy_text" feature but worse.

This could be fixed by running tests without the `bevy_text` feature on CI (which can be done by running `cargo test` in the `bevy_ui` crate dir rather than just from the root).

2024-09-14 07:47 UTC, janhohenheim requested changes

2024-09-14 07:47 UTC, janhohenheim commented on crates/bevy_ui/src/lib.rs
> +    pub disable_ui_rendering: bool,
I think having a boolean in the negative is a bit weird, semantically. Could you change this to `ui_rendering: bool` with a default of `true`?

2024-09-14 07:47 UTC, janhohenheim commented on crates/bevy_ui/src/lib.rs
> +        if !self.disable_ui_rendering {
Nit: I'd prefer this as an early return

2024-10-19 15:35 UTC, pablo-lua approved these changes

2024-10-19 16:23 UTC, alice-i-cecile commented
@ickshonpe just waiting on merge conflicts now :)

2024-10-19 23:14 UTC, merged