Add the required features for TonyMcMapface tonemapping to bevy_pbr
bevyengine/bevy pull request #9073
Opened 2023-07-08 19:51 UTC by Elabajaba

# Objective

People keep running into issues with their materials being pink in 3rd party bevy libraries because we switched to TonyMcMapface for tonemapping, and they didn't realize they needed to include the `ktx2`, `tonemapping_luts`, and  `zstd` features for it to work properly.

## Solution

Add `ktx2`, `tonemapping_luts`, and  `zstd` to the `bevy_pbr` feature.

## Changelog

The `bevy_pbr` feature now includes the `ktx2`, `tonemapping_luts`, and  `zstd` features.

## Migration Guide

TODO

2023-07-09 00:40 UTC, superdump commented
Should be bevy_core_pipeline I think as tonemapping is used for both 2D and 3D, the node is in bevy_core_pipeline, and it is added into both core pipelines there.

2023-07-09 03:57 UTC, cart commented
Agreed!

2023-07-09 04:07 UTC, Elabajaba commented
There's a few open questions from discord as to whether we even want to do this or not.

1. This would mean that you could no longer use `bevy_pbr` (or `bevy_core_pipeline`) without the `ktx2`, `tonemapping_luts`, and  `zstd` features. Do we want to make those features a required part of the renderer?
2. Would doing that break anything we care about?

2023-07-13 07:43 UTC, nicopap commented
I think an alternative is the following:

Have two feature flags for bevy_pbr:

1. `bevy_pbr_minimal` basically equals to `bevy_pbr` feature today, doesn't add the new dependencies. With this feature, Reinhard luminance should be used as default tonemapper (conditionally, more on this later)
2. `bevy_pbr` this would add the required dependencies for TonnyMcMapface, and set TonnyMcMapface as default tonemapper  **unconditionally**.

What happens if both features are enabled? Well, `bevy_pbr` prevails, it is strictly additive over `bevy_pbr_minimal`. The required dependencies for TonnyMcMapface are set and it itself is set as default

This allows 3rd party plugin crates to depend on `bevy_pbr_minimal` and users to pick between `bevy_pbr_minimal`  and `bevy_pbr` at their discretion.

2023-07-13 20:24 UTC, cart commented
Yeah _requiring_ those features for bevy_pbr does seem overly restrictive. I don't love having a separate "minimal" configuration. Seems like one more concept to contend with (and bucket of features to ensure work well together).

We could also just leave features as-is, detect when rendering with a fallback lut texture, and print an error message (with a pointer to the `tonemapping_luts`  + `ktx2` features and maybe a callout that they can change to reinhard). This _is_ an error case.

2023-07-18 16:06 UTC, rs017991 requested changes
However this shakes out, please update [cargo_features.md](https://github.com/bevyengine/bevy/blob/a30da0001ea3479fda32ac286e1a6647c791e5c1/docs/cargo_features.md) to make the interdependencies clear.

(Ref. #9179 for a newcomer's perspective on the surprising consequences given the current wording)

2023-10-27 04:09 UTC, JMS55 commented
Closed in favor of https://github.com/bevyengine/bevy/pull/10253

2023-10-27 04:09 UTC, closed without merging