Add `GltfLoader::new`.
bevyengine/bevy pull request #9120
Opened 2023-07-11 21:15 UTC by pcwalton

# Objective

In my application, I'm manually wrapping the built-in Bevy loaders with a wrapper loader that stores some metadata before calling into the inner Bevy loader. This worked for the glTF loader in Bevy 0.10, but in Bevy 0.11 it became impossible to do this because the glTF loader became unconstructible outside Bevy due to the new private fields within it. It's now in fact impossible to get a reference to a GltfLoader at all from outside Bevy, because the only way to construct a GltfLoader is to add the GltfPlugin to an App, and the GltfPlugin only hands out references to its GltfLoader to the asset server, which provides no public access to the loaders it manages.

## Solution

This commit fixes the problem by adding a public `new` method to allow manual construction of a glTF loader.

2023-07-11 21:22 UTC, james7132 approved these changes

2023-07-11 21:25 UTC, mockersf commented
instead of adding a `new` method, I see no good reason to not make the field public

2023-07-11 23:39 UTC, pcwalton commented
This should be ready to merge, I think.

2023-07-12 00:28 UTC, mockersf requested changes
Instead of adding a new method, could you make the fields of `GltfLoader` public?

2023-07-13 23:37 UTC, cart approved these changes

2023-07-14 00:18 UTC, merged