Make Sprite and Anchor Copy
bevyengine/bevy pull request #9327
Opened 2023-08-01 16:17 UTC by nicopap

# Objective

In `bevy_sprite`, the `Anchor` and `Sprite` types are not `Copy`. It makes interacting with them more difficult than necessary.

## Solution

Derive `Copy` on them. The rust API guidelines are that you should derive `Copy` when possible. <https://rust-lang.github.io/api-guidelines/interoperability.html#types-eagerly-implement-common-traits-c-common-traits>
Regardless, `Anchor` is a very small `enum` which warrants `Copy`, while `Sprite` is also a very small struct.

---

## Changelog

- In `bevy_sprite`, `Sprite` and `Anchor` are now `Copy`.

2023-08-01 16:35 UTC, alice-i-cecile commented
Definitely agree on Anchor, not totally sold on Sprite 🤔

2023-08-01 16:44 UTC, nicopap commented
The one objection I can see for Sprite is that it might in the future hold a `Handle<Image>`. I find it unlikely.

Otherwise it's a 68 bytes struct where each field themselves are `Copy`. `GlobalTransform` is 64 bytes for comparison.

2023-08-03 00:12 UTC, alice-i-cecile approved these changes

2023-08-03 07:43 UTC, james7132 requested changes
> Definitely agree on Anchor, not totally sold on Sprite 🤔

I'm going to mirror this concern. Adding Copy changes the semantics of the type, and any changes to revert this is going to be a very painful breaking change. @cart has mentioned multiple times that types should be Copy within the codebase if and only if you can treat the type as values (i.e. Vec2, Transform), and I don't think Sprites logically meet this criteria.

2023-08-11 20:46 UTC, cart approved these changes
Yeah I agree that Sprite should not be copy. I removed that derive.

2023-08-11 21:22 UTC, merged