Don't panic when applying an `Insert` command
bevyengine/bevy pull request #9379
Opened 2023-08-07 01:34 UTC by SludgePhD

# Objective

- Fixes https://github.com/bevyengine/bevy/issues/7118

## Solution

- Remove the delayed panic caused by `EntityCommands::insert`, by ignoring the command if its entity has been despawned
- Make all builtin commands behave consistently when acting on an entity that has since been despawned

---

## Changelog

- The `Insert` command now no longer panics when its entity no longer exists.

2023-08-07 02:28 UTC, alice-i-cecile requested changes
I think we should at least warn here: this is pretty important potential bug.

My preferred solution though is to create a class of `try_verb` commands though, which fail silently.

2023-08-07 05:49 UTC, killercup reviewed
I would at least make it log an error, so that you can still see when this is happening.

2023-08-09 20:32 UTC, SludgePhD commented
If we log an error or warning here, we'd basically be indicating that any occurrence of this situation is a bug that should be resolved, and I'm not convinced that that is correct.

I'm currently running into this panic because I am despawning entities in the `PostUpdate` schedule, and the `bevy_sprite::calculate_bounds_2d` system is trying to `insert` the `Aabb` component there as well.

The panic of course does not happen reliably, because the entity is only rarely despawned on the same frame as the `bevy_sprite::calculate_bounds_2d` system inserts the `Aabb`.

From what I can tell, most people running into this panic end up in a similar situation, where the correct resolution is to simply ignore the `insert` and despawn the entity. It does not really sound like treating this as a bug would be the right thing to do.

Perhaps the "bug" would be that bevy's internals need to use `.try_insert` instead of `.insert` pretty much everywhere, but then this strikes me as poor API design: the non-prefixed, shortest method name should ideally be the correct one to use, but here it causes nondeterministic bugs.

2023-09-10 19:32 UTC, JMS55 commented
This would also fix https://github.com/bevyengine/bevy/issues/9721

2023-10-10 19:40 UTC, alice-i-cecile commented
This was added as opt-in behavior in #9844.

2023-10-10 19:40 UTC, closed without merging

2023-10-10 20:08 UTC, SludgePhD commented
Were bevy's internal systems ever fixed to use it?

2023-10-10 23:00 UTC, alice-i-cecile commented
No, I would appreciate issues for the places where this is the correct choice :) Or a single issue might be fine and the implementor can track them down.

We just ran into one over in https://github.com/bevyengine/bevy/issues/9721, and I suspect that there's more to fix.