Expose `animation_clip` paths
bevyengine/bevy pull request #9392
Opened 2023-08-09 04:38 UTC by jfaz1

Need this for a custom `AnimationPlayer` that I tick in `FixedUpdate`

# Objective

- Need access to an animation clip's `paths` from outside the module

## Solution

- Add a getter method to return a reference to `paths`

2023-08-09 14:15 UTC, tguichaoua requested changes

2023-08-10 05:39 UTC, tguichaoua requested changes

2023-08-10 05:39 UTC, tguichaoua commented on crates/bevy_animation/src/lib.rs
> +    /// The [`EntityPath`] map.
```suggestion
    /// The bone ids mapped by their [`EntityPath`].
```

2023-08-10 06:29 UTC, tguichaoua approved these changes
LGTM

2023-08-11 13:12 UTC, alice-i-cecile approved these changes

2023-08-11 21:03 UTC, mockersf approved these changes

2023-08-11 21:21 UTC, merged