Add missing documentation to `bevy_time`
bevyengine/bevy pull request #9428
Opened 2023-08-12 21:43 UTC by JoJoJet

# Objective

* Add documentation to undocumented items in `bevy_ecs`.
* Add a warning for undocumented items.

2023-08-12 21:54 UTC, alice-i-cecile approved these changes

2023-08-12 21:55 UTC, alice-i-cecile commented
Progress towards https://github.com/bevyengine/bevy/issues/3492

2023-08-12 23:50 UTC, Selene-Amanita commented
Not introduced by this PR but can be fixed by it, wrong backticks in https://docs.rs/bevy/0.11.0/bevy/time/fixed_timestep/struct.FixedTime.html#method.expend:
```[`Err(FixedUpdateError`)]```

2023-08-13 00:22 UTC, Selene-Amanita reviewed
The doc on this page is great: https://docs.rs/bevy_time/0.11.0/bevy_time/fixed_timestep/index.html but [FixedTime](https://docs.rs/bevy_time/0.11.0/bevy_time/fixed_timestep/struct.FixedTime.html) and [run_fixed_update_schedule](https://docs.rs/bevy_time/0.11.0/bevy_time/fixed_timestep/fn.run_fixed_update_schedule.html) don't link back to it. Since [FixedUpdate](https://docs.rs/bevy/0.11.0/bevy/app/struct.FixedUpdate.html) links to `run_fixed_update_schedule`, I think it would be great to link back to the central doc on fixed time, people (me at least) don't always think to check module documentation.

2023-08-13 00:22 UTC, Selene-Amanita commented on crates/bevy_time/src/lib.rs
>  pub enum TimeUpdateStrategy {
Does this affect `FixedTime`? Should it be mentioned here?

From my understanding `FixedTime` is updated from `Time`, maybe mentioning that briefly here and/or in https://docs.rs/bevy_time/0.11.0/bevy_time/fixed_timestep/index.html would be useful?

2023-08-13 00:22 UTC, Selene-Amanita commented on crates/bevy_time/src/lib.rs
> +    /// [`Time`] will be updated to the specified [`Instant`] value.
```suggestion
    /// [`Time`] will be updated to the specified [`Instant`] value each frame.
```

(If I understood correctly)

2023-08-13 01:18 UTC, JoJoJet commented on crates/bevy_time/src/lib.rs
> +    /// [`Time`] will be automatically updated according to the length of the previous frame.
Hmm, looks like I was wrong about it using the length of the previous frame. It's updated using an `Instant` sent from the render world.

2023-08-13 02:42 UTC, JoJoJet commented
Thank you for the review. I believe I have addressed your points.

2023-08-13 13:01 UTC, Selene-Amanita requested changes
Besides a small typo looks good to me!

2023-08-13 16:23 UTC, Selene-Amanita approved these changes

2023-08-14 17:45 UTC, GuillaumeGomez commented
To help you with missing docs, you can add `#![deny(missing_docs)]`. :)

2023-08-14 22:44 UTC, alice-i-cecile commented
@GuillaumeGomez a warn equivalent was added in `lib.rs` :) Like we discussed in the linked issue, `warn` is less intrusive for development, but still blocks CI.

2023-08-15 08:32 UTC, GuillaumeGomez commented
Nice! There is also `rustdoc::missing_doc_code_examples` which could be helpful but I think it's nightly only. Bevy docs is really lacking examples. ^^'

2023-08-15 22:22 UTC, merged