Add removal_detection example
bevyengine/bevy pull request #945
Opened 2020-11-29 00:14 UTC by lukors

This PR adds an example that shows how you can know when a component has been removed, so you can react to it.

2020-11-29 00:41 UTC, amberkowalski requested changes
Code looks good, only issue is where in the changelog you placed the change.

2020-11-29 00:41 UTC, amberkowalski commented on CHANGELOG.md
> +- [Add removal_detection example][945]
This should probably be in `Added`

2020-11-29 00:47 UTC, lukors commented
Ah, thanks!

I didn't see the headings because there were no newlines before them, so my markdown syntax highlighting didn't highlight them.

I added newlines before and after the headings in the changelog for the upcoming version so it matches the changelogs for the previous versions.

And I moved the change to `Added`. :)

2020-11-29 00:49 UTC, amberkowalski approved these changes

2020-11-30 21:02 UTC, cart commented
Well done! The comments are clear and helpfully walk the user through each step.

2020-11-30 21:25 UTC, merged