TextureAtlasBuilder padding
bevyengine/bevy pull request #9494
Opened 2023-08-19 08:16 UTC by ickshonpe

# Objective

`TextureAtlas` supports pregenerated padded texture atlases, but `TextureAtlasBuilder` can't add padding when it creates a new atlas.

fixes #8150

## Solution

Add a method `padding` to `TextureAtlasBuilder` that sets the amount of padding to add.

When queueing the textures to be copied, add the padding value to the size of each source texture. Then when copying the source texture to the output atlas texture subtract the same padding value from the target rect.

---

## Changelog
`TextureAtlasBuilder`
* Added support for building texture atlases with padding.
* Adds a `padding` method to `TextureAtlasBuilder` that can be used to set an amount of padding to add between the sprites of the generated texture atlas.

2023-08-19 16:53 UTC, alice-i-cecile requested changes
LGTM once we clarify the docs: the field docs are great, but aren't publicly exposed so it's helpful to repeat them.

2023-08-19 16:53 UTC, alice-i-cecile commented on crates/bevy_sprite/src/texture_atlas_builder.rs
> +    /// Sets the amount of padding in pixels to add between the textures in the texture atlas.
```suggestion
    /// Sets the amount of padding in pixels to add between the textures in the texture atlas.
    ///
    /// The `x` value provide will be added to the right edge, while the `y` value will be added to the bottom edge.
```

2023-08-21 08:44 UTC, ickshonpe commented
Might also be good to expand the texture atlas builder example in another PR.
We could generate atlases with and without padding and render the textures with and without anti-aliasing to demonstrate how different approaches can deal with bleeding issues etc.

2023-08-21 14:47 UTC, alice-i-cecile approved these changes

2023-09-07 17:52 UTC, rparrett approved these changes

2023-09-08 15:22 UTC, merged