Add panicking helpers for getting components from `Query`
bevyengine/bevy pull request #9659
Opened 2023-08-31 17:58 UTC by Shatur

# Objective

- Currently we don't have panicking alternative for getting components from `Query`. Partially addresses #9443.

## Solution

- Add these functions.

---

## Changelog

### Added

- `Query::component` and `Query::component_mut` to get specific component from query and panic on error.

2023-08-31 19:04 UTC, alice-i-cecile requested changes
The "See also" section of the docs should point to the non-panicking equivalents, and vice versa :)

2023-08-31 20:26 UTC, Shatur commented
> The "See also" section of the docs should point to the non-panicking equivalents, and vice versa :)

Currently we points from mut functions to non-mut equivalents. I can add pointing to non-panicking equivalents, but it will be 2 2 functions (mut and non-mut one). So should I point to 3 other functions?
Or should I only cross-reference panicking and non-panicking equivalents?
Please, advice :)

2023-08-31 22:45 UTC, alice-i-cecile commented
I would point to the adjacent functions in the panicking/mutability grid :) So each should reference two other methods.

2023-09-02 09:31 UTC, Shatur commented
@alice-i-cecile makes sense, done!

2023-09-03 00:57 UTC, alice-i-cecile approved these changes

2023-09-03 00:59 UTC, alice-i-cecile commented
@Shatur, thinking about this a bit more, this should also exist on `QueryState`, and we should call the corresponding method from `Query`.

2023-09-03 07:07 UTC, Shatur commented
@alice-i-cecile hm... I don't see `get_component` in `QueryState`. Should I open a separate issue to add them or add `(get_)component(_mut)`?

2023-09-03 13:27 UTC, alice-i-cecile commented
Separate issue to add them then please :)

2023-09-03 13:38 UTC, Shatur commented
@alice-i-cecile done: #9683

2023-09-03 14:39 UTC, JoJoJet approved these changes

2023-09-04 11:41 UTC, Selene-Amanita approved these changes

2023-09-04 12:51 UTC, merged