Improve `SpatialBundle` docs
bevyengine/bevy pull request #9673
Opened 2023-09-02 13:44 UTC by Nilirad

# Objective

This PR aims to fix a handful of problems with the `SpatialBundle` docs:

The docs describe the role of the single components of the bundle, overshadowing the purpose of `SpatialBundle` itself. Also, those items may be added, removed or changed over time, as it happened with #9497, requiring a higher maintenance effort, which will often result in errors, as it happened.

## Solution

Just describe the role of `SpatialBundle` and of the transform and visibility concepts, without mentioning the specific component types. Since the bundle has public fields, the reader can easily click them and read the documentation if they need to know more. I removed the mention of numbers of components since they were four, now they are five, and who knows how many they will be in the future. In this process, I removed the bullet points, which are no longer needed, and were contextually wrong in the first place, since they were meant to list the components, but ended up describing use-cases and requirements for hierarchies.

2023-09-02 18:32 UTC, alice-i-cecile commented on crates/bevy_render/src/spatial_bundle.rs
> +/// to work correctly.
```suggestion
/// to be rendered correctly.
```

2023-09-02 18:32 UTC, alice-i-cecile commented on crates/bevy_render/src/spatial_bundle.rs
> +/// Hierarchies of entities must contain
```suggestion
/// Parent-child hierarchies of entities must contain
```

2023-09-02 18:33 UTC, alice-i-cecile commented on crates/bevy_render/src/spatial_bundle.rs
> +/// It consists of transform components,
I think this whole paragraph is unhelpful and prone to getting outdated.

2023-09-02 18:33 UTC, alice-i-cecile requested changes
I agree with the intent here, but I think we can clean it up further.

2023-09-02 22:54 UTC, JoJoJet approved these changes

2023-09-02 23:44 UTC, alice-i-cecile approved these changes

2023-09-03 00:02 UTC, merged

2023-09-03 07:04 UTC, bzm3r commented
Something that is a little confusing to me: why is `visibility` part of the `SpatialBundle`?

2023-09-03 07:27 UTC, Nilirad commented
> why is visibility part of the SpatialBundle? That's the only part of the doc explanation that makes me scratch my head: position, rotation, scale and visibility...one of those is not quite like the others.

I believe it's because the purpose this bundle is actually for rendering. Therefore, visibility has a fundamental role in answering the question "where should this be drawn?"

> It may also be worthwhile to leave a tiny bit of info about what kind of scale scale is

That detail would be better suited for Transform.scale