Provide getters for fields of ReflectFromPtr
bevyengine/bevy pull request #9748
Opened 2023-09-10 15:41 UTC by nicopap

# Objective

The reasoning is similar to #8687.

I'm building a dynamic query. Currently, I store the ReflectFromPtr in my dynamic `Fetch` type.

[See relevant code](https://github.com/nicopap/bevy_mod_dynamic_query/blob/97ba68ae1e13f15cabfac1dcd58c2483396dfd3f/src/fetches.rs#L14-L17)

However, `ReflectFromPtr` is:

- 16 bytes for TypeId
- 8 bytes for the non-mutable function pointer
- 8 bytes for the mutable function pointer

It's a lot, it adds 32 bytes to my base `Fetch` which is only `ComponendId` (8 bytes) for a total of 40 bytes.

I only need one function per fetch, reducing the total dynamic fetch size to 16 bytes.

Since I'm querying the components by the ComponendId associated with the function pointer I'm using, I don't need the TypeId, it's a redundant check.

In fact, I've difficulties coming up with situations where checking the TypeId beforehand is relevant. So to me, if ReflectFromPtr makes sense as a public API, exposing the function pointers also makes sense.

## Solution

- Make the fields public through methods.

---

## Changelog

- Add `get_to_reflect` and `get_to_reflect_mut` methods to `ReflectFromPtr` to access the underlying function pointers

2023-09-10 17:20 UTC, alice-i-cecile requested changes
I think this reasoning makes sense. `get_to_reflect` is pretty awful as a name, but I don't have any really strong alternatives. `get_reflect_conversion` and `get_reflect_mut_conversion` maybe?

I'd really like to either see those safety comments duplicated on the fields themselves, or `#[inline]` annotations + using these methods internally.

2023-09-10 17:26 UTC, nicopap commented
I agree the name is pretty poor.

I think the field should be renamed to `from_ptr[_mut]` (which matches the struct name) and the method follow the rust convention of re-using the field name. What do you think? It might be awkward to have a `from_ptr` method that returns something instead of accepting a `Ptr` though.

2023-09-11 12:44 UTC, alice-i-cecile commented
I think I'm happy enough with that rename :) @MrGVSV may have other opinions, but we can paint that bike shed when we get to it.

2023-09-12 14:03 UTC, alice-i-cecile approved these changes

2023-09-12 20:18 UTC, MrGVSV approved these changes
I agree `from_ptr[_mut]` isn't the _best_ but I think it's pretty good. Especially for an API that's more catered to advanced usages anyways.

2023-09-18 08:17 UTC, nicopap commented
@alice-i-cecile I forgot to update some doc examples and CI didn't pass. It should be fixed now.

2023-09-18 14:03 UTC, merged

2023-09-18 15:55 UTC, nicopap commented on crates/bevy_reflect/src/type_registry.rs
> +                // SAFETY: same as above, but foor `as_reflect_mut`, `from_ptr_mut` and `deref_mut`.
Oh noes `foor`, that's what I get for hurried changes.