Add Explicit Ordering for `DefaultPlugins` Systems
bevyengine/bevy pull request #9828
Opened 2023-09-17 06:39 UTC by bushrat011899

# Objective

- Fixes #9511

## Solution

- Added `before` and `after` statements as required to remove system order ambiguity.

## Notes

This PR is a bit on the rough side of things and probably serves better as a reference point for the kind of work required to properly resolve #9511. A number of system ambiguities were between areas of Bevy that previously didn't need to reference each other. In those instances, I chose to add the crate and resolve the ambiguity directly. A better approach would probably be to add some better sets for sharing between these crates.

Also, I had some troubles on my machine actually diagnosing the original ambiguity errors using the `nondeterministic_system_order` example. I ended up working around this issue by explicitly configuring all the schedules run by `Main` separately:

```rust
// ...
.edit_schedule(Main, |schedule| {
    schedule.set_build_settings(ScheduleBuildSettings {
        ambiguity_detection: LogLevel::Error,
        ..default()
    });
})
.edit_schedule(PreStartup, |schedule| {
    schedule.set_build_settings(ScheduleBuildSettings {
        ambiguity_detection: LogLevel::Error,
        ..default()
    });
})
.edit_schedule(Startup, |schedule| {
    schedule.set_build_settings(ScheduleBuildSettings {
        ambiguity_detection: LogLevel::Error,
        ..default()
    });
})
// ... etc.
```

If this is merged, I do think the CI tests should be updated to include ambiguity detection to prevent regression.

2023-09-17 16:09 UTC, alice-i-cecile requested changes
We should avoid adding new dependencies between crates just for ambiguity resolution. Instead, I think we should add a plugin to `DefaultPlugins`, whose only job is to resolve these ambiguities using public labels.

2023-09-17 19:47 UTC, NiklasEi commented
Instead of ordering everything, some systems could also be added to ambiguity sets to allow for more parallelism. E.g. the animation system might be OK with running in parallel to layout systems.

2023-09-22 05:32 UTC, hymm commented
FYI I have a couple PR's that will affect ambiguitites.

* https://github.com/bevyengine/bevy/pull/9895 adds ignoring ambiguities by type and ignores ambiguities on Assets<T>
* https://github.com/bevyengine/bevy/pull/9822 auto adds apply_buffers systems to the schedule and ignores ambiguities on those auto added sync points

2023-11-06 17:34 UTC, alice-i-cecile commented
Closing in favor of https://github.com/bevyengine/bevy/pull/10411<3

2023-11-06 17:34 UTC, closed without merging