docs: Update input_toggle_active example
bevyengine/bevy pull request #9913
Opened 2023-09-24 11:02 UTC by ottah

# Objective

- Update incomplete example for `bevy::input::common_conditions::input_toggle_active`.

## Solution

- Update example.

2023-09-25 19:57 UTC, mockersf commented
this example is actually not using `input_toggle_active`, could you remove it from the imports? and it should show how to use `input_just_pressed` for that case instead of checking it in system

2023-09-30 18:48 UTC, mockersf approved these changes

2023-10-02 00:25 UTC, james7132 requested changes
This is an example intended to show how to use `input_toggle_active`. Doesn't removing it defeat the purpose of the example?

2023-10-02 00:41 UTC, mockersf commented
It's just removing the import, the condition was actually never used in the condition. From my understanding, this specific example is more "you can't use that condition if you need to move the state to your own resource/state/whatever"

2023-10-02 22:17 UTC, rparrett approved these changes

2023-10-28 06:17 UTC, james7132 approved these changes

2023-10-28 06:36 UTC, merged